### ISSUE TITLE
The extension seems to fail registering its commands.

### ISSUE THREAD

**Issue by smallkirby** [microsoft/vscode-cpptools#9291]
### Environment

- OS and version: Linux x64 5.13.0-40-generic
- VS Code: 1.67.0
- C/C++ extension: v1.9.8
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

Bug Summary:

The extension seems to fail register its commands.

After successful installation of the extension, no suggestions or auto-completions doesn't appear on C file editor. If I execute the command `C/C++: Change Configuration Provider` in a command palette, the error dialog appears saying that `Command 'C/C++: Change Configuration Provider...' resulted in an error (command 'C_Cpp.ConfigurationProviderSelect' not found)`.

`Show Running Extensions` command shows that the extension is running.

### Other Extensions

I disabled all the extensions other than this extension, but the problem still occurs.

### Additional Information

I uninstalled the extension, and re-installed it. Also, I switched to Pre-Release Version and back to Release Version. None of these worked for me.

No `c_cpp_properties.json` file in a testing environment.

**Comment by michelleangela** [comment]
@smallkirby 
Could you try installing the extension by manually downloading and installing the VSIX package from https://github.com/microsoft/vscode-cpptools/releases/tag/v1.9.8?

Do you have any `C_Cpp.*` settings configured, such as `C_Cpp.intelliSenseEngine`?

**Comment by smallkirby** [comment]
Ah, you are right.
I checked my user-level vscode config (`$HOME/.config/Code/config.json`) and I found the line saying that `"C_Cpp.intelliSenseEngine": "Disabled"`.
I haven't known that any `C_Cpp` commands fail when this config is disabled.

Thank you for your cooperation and sorry for my disturbance, now I can close this issue.

**Comment by michelleangela** [comment]
@smallkirby 
It's actually a known issue (see https://github.com/microsoft/vscode-cpptools/issues/9272) that commands fail when `C_Cpp.intelliSenseEngine` is "Disabled". 

However, some of the `C_Cpp` commands like `C/C++: Change Configuration Provider` are used to configure IntelliSense. Therefore if users are using commands to configure IntelliSense, then it's expected that `C_Cpp.intelliSenseEngine` would not be "Disabled". 

The commands used for the debugging features in the C++ extension should still work though when `C_Cpp.intelliSenseEngine` is "Disabled, hence that part is a bug (https://github.com/microsoft/vscode-cpptools/issues/9272).
