### ISSUE TITLE
Support trailing return type properly for highlighting

### ISSUE THREAD

**Issue by gracicot** [microsoft/vscode-cpptools#9292]
Bug type: Language Service

**Describe the bug**
- OS and Version: MacOS 11.5
- VS Code Version: 1.67
- C/C++ Extension Version: v1.10.0

Trailing return types are wrongly identified as being a variable dereferenced with the arrow symbol.

**Steps to reproduce**

1. Create a new cpp file
2. Paste the following content:
```cpp
#include <string>

auto test() noexcept -> std::string;
std::string test() noexcept;
```
4. Wait for highlighting to appear
5. See highlight being wrong at line 3

The `noexcept` is wrongly given the attribute `variable.other.object.access.cpp` and the `std` namespace the `variable.other.property.cpp`. 

Consider this other example:

```cpp
struct T {
    auto test1() noexcept -> void;
    auto test2() const -> void;
    void test3() noexcept;
};
```

All line but line 2 are correct. The `noexcept` here is wrongly attributed `keyword.operator.noexcept.cpp`.

**Expected behavior**

In all cases demonstrated above, it all `noexcept` should be `storage.modifier.specifier.functional.post-parameters.noexcept.cpp`, and the `std` namespace always `entity.name.scope-resolution.cpp`

**Screenshots**

Here's a screenshot of the problems it can cause with themes:

<img width="282" alt="Screen Shot 2022-05-10 at 9 56 29 AM" src="https://user-images.githubusercontent.com/2906673/167645834-c7d01441-cf93-4ae1-a20b-2754781e1c33.png">

**Comment by sean-mcmanus** [comment]
Our extension doesn't provide lexical colorization -- it's from VS Code, which gets it from the Better C/C++ Syntax extension. You should look into filing a bug at https://github.com/jeff-hykin/better-cpp-syntax/issues .

**Comment by gracicot** [comment]
For the records, it seems the issue exists there: jeff-hykin/better-cpp-syntax#405
