### ISSUE TITLE
Stuck and Crash in render thread

### ISSUE THREAD

**Issue by variantf** [microsoft/vscode-cpptools#9296]
Bug type: Language Service

**Describe the bug**
- OS and Version: Both Win11 and MacOS
- VS Code Version: 1.67.1
- C/C++ Extension Version: v1.9.8
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: Linux Redhat 8.5

**Steps to reproduce**

1. open a pariticular .cpp file
2. The whole vs code window stucked

**Expected behavior**

Should be able to view file content

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

![167985312-5bad6a32-8de0-45a7-ad6c-91da85610435](https://user-images.githubusercontent.com/2265407/167993187-5f318644-b655-4402-9fd1-106cca26fb5e.png)
![167985352-eead8d09-d786-4be6-8d92-49ba2a3a1694](https://user-images.githubusercontent.com/2265407/167993206-7fd2a30c-d3f5-4192-9bc7-6977696948ae.png)

**Additional context**

**Comment by variantf** [comment]
Since it's stuck whole vs  code suddenly. there's no log printed. sorry

**Comment by variantf** [comment]
#https://github.com/microsoft/vscode/issues/149314

**Comment by sean-mcmanus** [comment]
Does the issue still repro with 1.10.1 (pre-release) of the C/C++ extension?

The bug only repros with certain files? Can you provide a repro?

Can you set C_Cpp.loggingLevel to "Debug" and look at the logging in the C/C++ window to see what the last logs are to hopefully determine what our extension is doing?

**Comment by variantf** [comment]
@sean-mcmanus Here's some findings:

it works find with 1.68.0 insiders and 1.10.1 pre-release. but not working with 1.67 vscode + 1.10.1 pre-release

this issue can only occur on specific C++ files inside a large project. if I put the C++ file outside, it works fine.

so maybe we can close ticket for a while a I'll reopen if there's still issue after relase version bump to 1.68 + 1.10.1 ?
