### ISSUE TITLE
vcFormat won't work with UTF-8 characters > 1 byte

### ISSUE THREAD

**Issue by heroboy** [microsoft/vscode-cpptools#9297]
Bug type: Language Service

**Describe the bug**
- OS and Version: windows 10
- VS Code Version: 1.67.1
- C/C++ Extension Version: v1.9.8
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: windows 10
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Maybe vcformat not  correctly count the number of  characters or bytes of Chinese characters.
This cause vcformat insert a space in wrong position, when it is after the Chinese characters in the same line.
https://github.com/microsoft/vscode-cpptools/issues/7703

**Steps to reproduce**
1. Set the format to "vc-format"
2. create a cpp file:
`m_pServerSite->WriteScoreByUserID(pi.userid, &us, "逃跑预扣分",&m_GameGuid);`
（note: there is no space before the "&m_GameGuid", and the formatter want to insert a space）
  save it as utf-8 or gbk(My windows encoding) encoding.
3. format the document .
4. And the formatter insert the space look like:
`m_pServerSite->WriteScoreByUserID(pi.userid, &us, "逃跑预 扣分",&m_GameGuid);`
   Every time format the document, a more space will be inserted.

**Expected behavior**
The space should be insert in the correct position.

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
A simplified repro is `"逃"&` and a non-repro would be `"i"&`.

**Comment by sean-mcmanus** [comment]
@RaulPerez1 @michelleangela `逃+逃` and `/*逃*/i+i;` are simpler repros -- the triggering condition is a UTF-8 character > 1 byte on the left side of code in which an edit is made -- the reason is because that code is computing columns in "logical" offsets when our code that handles it expects physical/byte offsets.

A previously fixed issue was https://github.com/microsoft/vscode-cpptools/issues/7704, but in that case the UTF-8 characters were not on the left side of an edit.

**Comment by sean-mcmanus** [comment]
Until we can fix this, you may want to downgrade to version 1.6.0 (which doesn't repro this bug), or switch C_Cpp.formatting to "clangFormat" to avoid generating garbage code.

**Comment by sean-mcmanus** [comment]
Fixed with 1.10.4 (pre-release). That version should be very similar to our final 1.10.5 release next week, maybe with an additional bug fix.

**Comment by sean-mcmanus** [comment]
FYI, the remaining case is with 4-byte UTF-8 characters (3-byte UTF-8 characters seem okay).

**Comment by sean-mcmanus** [comment]
The 4-byte UTF-8 character issue got fixed with 1.10.5.
