### ISSUE TITLE
takes a lot of CPU just when I type code

### ISSUE THREAD

**Issue by Iamwangli** [microsoft/vscode-cpptools#9298]
Issue Type: <b>Bug</b>

when I type code, my ubuntu 20.04 LTS show this tools takes a lot of CPU

Extension version: 1.9.8
VS Code version: Code 1.67.1 (da15b6fd3ef856477bf6f4fb29ba1b7af717770d, 2022-05-06T12:39:22.915Z)
OS version: Linux x64 5.13.0-41-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|23.35GB (1.70GB free)|
|Process Argv|--unity-launch --crash-reporter-id 3128cb2d-eb9c-4154-a258-d50bc2c4d82f|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebugcf:30475217
vsclangdc:30486549

```

</details>

**Comment by Iamwangli** [comment]
It's caused by Cpptools.

**Comment by sean-mcmanus** [comment]
What is "a lot"? That might be "by design". We need more info. The CPU usage is only when you're typing? Does it go away when you stop typing and/or when the flame icon disappears? Does it repro with C_Cpp.intelliSenseEngine set to "Tag Parser" (we recommend using the setting "Default")?

**Comment by Iamwangli** [comment]
@sean-mcmanus Yes, It caused by cpptools. when I type the code, cpptools start to used my CPU, one core 100%. when I stop typing, cpptools stops too.

**Comment by Iamwangli** [comment]
@sean-mcmanus the setting of my c_cpp_properties.json shown as follow:
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/include",
                "/usr/local/include",
                "/usr/local/include/vtk-9.0",
                "/usr/local/include/pcl-1.12"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "clang-x64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}

**Comment by sean-mcmanus** [comment]
I repro high CPU usage when I hold down a key with a "large" file, but it doesn't repro with a small file -- when I attach a debugger and break into it I see it processing the didChange event and rebuilding the "line mapping" -- is that what you're seeing? Instructions for attaching a debugger are at https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv . The page at https://github.com/microsoft/vscode-cpptools/wiki/Troubleshooting-Performance-Issues may also help.

**Comment by Iamwangli** [comment]
@sean-mcmanus Thanks, I'll try it.
