### ISSUE TITLE
Unable to start debugging. Program path '...' is missing or invalid.

### ISSUE THREAD

**Issue by moisesguimaraes** [microsoft/vscode-cpptools#93]
I'm getting the following error when trying to run the debugger. I'm on a OS X El Capitain and here is my configuration:

{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "client",
            "type": "cppdbg",
            "request": "launch",
            "launchOptionType": "Local",
            "targetArchitecture": "x64",
            "program": "${workspaceRoot}/examples/client/client",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${workspaceRoot}",
            "environment": [],
            "externalConsole": false
        }
    ]
}

**Comment by moisesguimaraes** [comment]
running the same string from '...' in the command line works as expected.

**Comment by pieandcakes** [comment]
@moisesguimaraes Thank you for reporting this issue. Can you tell me which folder you opened in Visual Studio Code and if your executable is called "client"? 

for example, when I open my project, I'm opening the folder /Users/piel/src/testproject and my program is called a.out, then my program parameter would just be ${workspaceRoot}/a.out .

**Comment by moisesguimaraes** [comment]
Hi @pieandcakes ,
Yes, my executable is called 'client'.

```
moisesguimaraes@phyrexia: ~/workspaces/wolfssl/wolfssl$ code .
moisesguimaraes@phyrexia: ~/workspaces/wolfssl/wolfssl$ ls -l examples/client/client
-rwxr-xr-x  1 moisesguimaraes  staff   6,2K 18 Jul 22:03 examples/client/client
```

Thanks for your help.

**Comment by pieandcakes** [comment]
@moisesguimaraes When you chose to open the folder in VSCode, did you open ~/workspaces/wolfssl/wolfssl/ or did you open ~/workspaces/wolfssl/wolfssl/examples/client/ ? I'm wondering why it can't find the executable for debugging.

**Comment by moisesguimaraes** [comment]
~/workspaces/wolfssl/wolfssl/

**Comment by pieandcakes** [comment]
@moisesguimaraes I'm wondering if its an issue with your version of GDB. Do you have it signed and are you able to debug your executable with GDB? Signing instructions are in the README.md that is located under ~/.vscode/extensions/<extension name>.  

We released an update (0.8.1) that now supports debugging with lldb if you want to give that a shot instead. You will need to delete the launch.json file in your ${workspaceRoot}/.vscode folder.

**Comment by delmyers** [comment]
@moisesguimaraes, I just want to follow up quickly to see if your issue has been resolved. As Pierson indicated, we have a new release that now debugs on Mac using a build of lldb rather than gdb. Are you able to debug if you update your copy of the C++ tools?

**Comment by jpotyka** [comment]
Hello, i get the same error but i use the following setup:

Visual Studio Code:
Version 1.4.0
Commit 6276dcb0ae497766056b4c09ea75be1d76a8b679
Datum 2016-08-04T16:49:32.489Z
Shell 0.37.6
Renderer 49.0.2623.75
Node 5.10.0

C/C++ Extension:
0.8.1

OS:
Kali GNU/Linux 2.0 (sana) 64-Bit

**Comment by pieandcakes** [comment]
If this is still an issue, please comment/reopen. I haven't been able to duplicate this.

**Comment by Grohden** [comment]
I don't know if it's the same problem, but I had a similar problem in Windows, there were two environment variables pointing to gdb, one was from minGW and the other was from Haskell, I do not know why VSCode got it from haskell (when I typed `where gdb` on powershell the return was the mingw path) but when I deleted the haskell variable and restarted the VSCode, it worked.
Probably it was because i was using mingw32-make from haskell to compile and the mingw gdb..
