### ISSUE TITLE
issue with spaces in path

### ISSUE THREAD

**Issue by imba-tjd** [microsoft/vscode-cpptools#930]
My OS: Windows LTSB 2015 x64
VS Code Version: 1.14.2
Extension Version: 0.12.1

When the workspace name or file name contains a space, I will receive an error. But if the space only exist in a folder name in workspace, this error won't appear.
I thought this would be easy to discover because the default name of a folder is *New folder*……
You may need to create a new workspace to reproduce it because extension has cache.

![image](https://user-images.githubusercontent.com/24759802/28751130-320fe822-7532-11e7-904f-d648e35295c4.png)

---
Well, I don't know why but now I can't reproduce this problem……
So if administrators don't reproduce it either, please close this issue.

**Comment by bobbrow** [comment]
Works fine for me.  Closing...
