### ISSUE TITLE
CPPTools continually generating  core files

### ISSUE THREAD

**Issue by dalepenn** [microsoft/vscode-cpptools#9301]
Bug type: Language Service

System Configuration (from About Window): 

Version: 1.67.0
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Date: 2022-05-04T12:08:42.978Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Linux x64 4.18.0-305.12.1.el8_4.x86_64

Extensions Installed
CPPTools (ms_vscode.cpptools) v1.10.1
CMake Tools (ms_vscode.cmake-tools) v1.11.18
SVN (johnstoncode.svn-scm) v2.15.5

Extensions were downloaded as VSIX files and installed (development system is isolated).
The CPPTools file is : ms-vcode.cpptools-1.10.1@linux-x64.vsix, and was downloaded on May 12, 2022

Workspace is a single project with many components.

When CPPTools is enabled, if make a CPP file active in the edit window, I get a continuous series of core files in the workspace directory. When queried with the file command, the come from execution cpptools. The stack dump going through intellisense code into msvs::start_process_impl then aborting. The only way to stop the core file generation is to disable CPPTools.
The core file generation persists even if the other extensions are disabled

Attached is one of the core files generated (I think, the issue page is not clear if I succeeded). If something else is needed, I will try and get it.

Dale Pennington

**Comment by dalepenn** [comment]
OK, I tried to upload core.zip (zipped up RHEL8 Core file), but when I try I seem to get a "is not included in the list" in the box for selecting files to upload. So I do not think it is excepting the .ZIP even thought that is supposed to be a supported extension.

**Comment by dalepenn** [comment]
SInce I could not get the Core file to download, I went back to get additional data.
First I created a new Workspace with only 1 file, a simple hello_world.cpp file. The cpptools generating cores still happened.

From the core file, I got this from the Unix 'file' command : 
core.218069: ELF 64-bit LSB core file, x86-64, version 1 (SYSV), SVR4-style, from '/home/dpennington/.vscode/extensions/ms-vscode.cpptools-1.10.1/bin/cpptools', real uid: 29347, effective uid: 29347, real gid: 1000, effective gid: 1000, execfn: '/home/dpennington/.vscode/extensions/ms-vscode.cpptools-1.10.1/bin/cpptools', platform: 'x86_64'

I then ran the gdb command with the following command line : 
gdb /home/dpennington/.vscode/extensions/ms-vscode.cpptools-1.10.1/bin/cpptools core.218069

I ran the backtrace (where command), and here is what I got : 

Core was generated by `/home/dpennington/.vscode/extensions/ms-vscode.cpptools-1.10.1/bin/cpptools'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f4043a2937f in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: yum debuginfo-install glibc-2.28-151.el8.x86_64 libgcc-8.4.1-1.el8.x86_64
(gdb) where
#0  0x00007f4043a2937f in raise () from /lib64/libc.so.6
#1  0x00007f4043a13db5 in abort () from /lib64/libc.so.6
#2  0x00000000010d31bf in msvc::start_process_impl(msvc::process_t&, msvc::basic_zstring_view<char>, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const*, unsigned long, bool, bool, bool, bool, bool) ()
#3  0x00000000010d3292 in msvc::start_process(msvc::process_t&, msvc::basic_zstring_view<char>, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::basic_string_view<char, std::char_traits<char> >, std::basic_string_view<char, std::char_traits<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool (*)(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&), std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const*, unsigned long, bool, bool, bool, bool) ()
#4  0x00000000010b213a in msvc::channel_manager_t::start_server(msvc::basic_zstring_view<char>, std::basic_string_view<char, std::char_traits<char> >, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, std::shared_ptr<msvc::pipe_channel_t>&, std::chrono::duration<long, std::ratio<1l, 1000l> >, unsigned long) ()
#5  0x000000000084159e in intellisense_client::start_channel() ()
#6  0x00000000008417e5 in intellisense_client::create_server() ()
#7  0x0000000000841f37 in intellisense_client::init() ()
#8  0x0000000000841e47 in intellisense_client::create(char const*, char const*, compilation_args&&, unsigned long, bool) ()
#9  0x0000000000864952 in create_sync_work(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, unsigned long, std::shared_ptr<browse_engine> const&, std::shared_ptr<compilation_args_provider> const&, bool, bool, bool) ()
#10 0x0000000000866f7f in create_async_work(char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*, unsigned long, std::shared_ptr<browse_engine> const&, std::shared_ptr<compilation_args_provider> const&, bool) ()
#11 0x000000000086e660 in std::_Function_handler<void (), intellisense_client_factory::create_async(char const*, char const*, char const*, std::shared_ptr<browse_engine> const&, std::shared_ptr<compilation_args_provider> const&, bool, std::function<void (std::vector<std::shared_ptr<intellisense_client>, std::allocator<std::shared_ptr<intellisense_client> > >)>&&, std::function<void ()>&&)::$_4>::_M_invoke(std::_Any_data const&) ()
#12 0x0000000000899912 in std::_Function_handler<void (), msvc::thread_pool::enqueue(std::function<void ()>&&, std::future<void>*)::$_2>::_M_invoke(std::_Any_data const&) ()
#13 0x00000000008986a0 in msvc::thread_pool::do_work(unsigned long) ()
#14 0x00000000010d5a3a in msvc::thread_helper_t::thread_entry(void*) ()
#15 0x00007f4043dbf14a in start_thread () from /lib64/libpthread.so.0
#16 0x00007f4043aeedc3 in clone () from /lib64/libc.so.6

Again, if there is anything else I can get to help with debugging this, just let me know.

**Comment by sean-mcmanus** [comment]
Yeah, we just needed that call stack and not the full core dump file -- this is a known regression crash (which also repros on Mac) starting with 1.10.1 (possibly with 1.10.0 too) -- you should downgrade to the non-pre-release 1.9.8 if it's an issue for you until we're able to release a pre-release version with a fix.

**Comment by sean-mcmanus** [comment]
@Colengms I'm guessing it's related to the fix for https://github.com/microsoft/vscode-cpptools/issues/9261 .

**Comment by dalepenn** [comment]
Thanks for the info, I shall try that

Dale

**Comment by sean-mcmanus** [comment]
We just published 1.10.2 with the fix.
