### ISSUE TITLE
Problem with Hello world Programm #include <iostream> is marked as wrong

### ISSUE THREAD

**Issue by X4ndras** [microsoft/vscode-cpptools#9305]
![image](https://user-images.githubusercontent.com/81412931/168213824-cd1258a8-accb-4e97-bedd-057914b624ad.png)
in this image you can see that #include is marked as wrong this problem only appears if im using the vs code c++ extention (C/C++ IntelliSense, debugging, and code browsing.)

Here is the error message:
![image](https://user-images.githubusercontent.com/81412931/168213986-b66ef117-5dee-4a26-8d66-e0f32767bd77.png)

I dont know how I can fix this it would be nice if anybody could help me.
Thanks.

**Comment by michelleangela** [comment]
@Dynastray 
If the extension can't find the paths of [system includes](https://code.visualstudio.com/docs/cpp/customize-default-settings-cpp#_system-includes), it could mean that the compiler path was not found or the extension failed to get the system include paths from the compiler.

Could you run the command `C/C++: Log Diagnostics` and copy and paste the log output to the issue? The log will show the [IntelliSense configuration](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference) and what include paths the extension is using.

Could you also share the logs from the language server (see instructions https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)? This will show the extension querying the compiler path and if it was able to get the system includes.

**Comment by Dynastray** [comment]
C++ Log Diagnostics
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find Log: No such file or directory
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find Diagnostics: No such file or directory

**Comment by Dynastray** [comment]
@michelleangela did you mean this with logging
`loggingLevel: Debug
cpptools/didChangeCppProperties
Es wird versucht, Standardwerte vom C++-Compiler in der Eigenschaft "compilerPath" abzurufen: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Es wird versucht, Standardwerte vom C-Compiler in der Eigenschaft "compilerPath" abzurufen: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
  Ordner: C:/MSYS64/MINGW64/ werden indiziert.
  Ordner: E:/@CODINGGAMEENGINE/!PROJECTS/PYTHONPROJECTS/RANDOMPROJECTS/ werden indiziert.
cpptools/didChangeCppProperties
Es wird versucht, Standardwerte vom C++-Compiler in der Eigenschaft "compilerPath" abzurufen: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Es wird versucht, Standardwerte vom C-Compiler in der Eigenschaft "compilerPath" abzurufen: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
  Ordner: C:/MSYS64/MINGW64/ werden indiziert.
  Ordner: E:/@CODINGGAMEENGINE/!PROJECTS/C#PROJECTS/ werden indiziert.
cpptools/didChangeCppProperties
Es wird versucht, Standardwerte vom C-Compiler in der Eigenschaft "compilerPath" abzurufen: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Codesuchdienst initialisiert.
Es wird versucht, Standardwerte vom C++-Compiler in der Eigenschaft "compilerPath" abzurufen: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
  Ordner: C:/MSYS64/MINGW64/ werden indiziert.
  Ordner: E:/@CODINGGAMEENGINE/!PROJECTS/C++PROJECTS/ werden indiziert.
Dateien werden ermittelt...
  Ordner wird verarbeitet (rekursiv): C:/MSYS64/MINGW64/
textDocument/didOpen: E:\@CodingGameEngine\!Projects\C++Projects\test.cpp
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: E:\@CodingGameEngine\!Projects\C++Projects\test.cpp
cpptools/resumeParsing
cpptools/getDocumentSymbols: E:\@CodingGameEngine\!Projects\C++Projects\test.cpp (id: 2)
cpptools/getCodeActions: E:\@CodingGameEngine\!Projects\C++Projects\test.cpp (id: 3)
cpptools/getDocumentSymbols
cpptools/getFoldingRanges: E:\@CodingGameEngine\!Projects\C++Projects\test.cpp (id: 4)
cpptools/getSemanticTokens: E:\@CodingGameEngine\!Projects\C++Projects\test.cpp (id: 5)
Nach Syntaxfehlern wird gesucht: E:\@CodingGameEngine\!Projects\C++Projects\test.cpp
  Ordner wird verarbeitet (rekursiv): E:/@CODINGGAMEENGINE/!PROJECTS/PYTHONPROJECTS/RANDOMPROJECTS/
  Ordner wird verarbeitet (rekursiv): C:/MSYS64/MINGW64/
  Ordner wird verarbeitet (rekursiv): E:/@CODINGGAMEENGINE/!PROJECTS/C#PROJECTS/
  Ordner wird verarbeitet (rekursiv): C:/MSYS64/MINGW64/
  Ordner wird verarbeitet (rekursiv): E:/@CODINGGAMEENGINE/!PROJECTS/C++PROJECTS/
  Dateiermittlung: 106685 Datei(en) verarbeitet
  0 Datei(en) aus Datenbank entfernt
Die Ermittlung von Dateien ist abgeschlossen.
Der Cache für die Includevervollständigung wird aufgefüllt.
Verbleibende Dateien werden analysiert...
  Analyse: 0 Datei(en) verarbeitet
Die Analyse verbleibender Dateien ist abgeschlossen.
Kompilierungsargumente für "E:\@CodingGameEngine\!Projects\C++Projects\test.cpp" werden gesendet.
  Includes: C:\MSYS64\MINGW64\INCLUDE\C++\11.3.0
  Includes: C:\MSYS64\MINGW64\INCLUDE\C++\11.3.0\X86_64-W64-MINGW32
  Includes: C:\MSYS64\MINGW64\INCLUDE
  Includes: C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\11.3.0\INCLUDE
  Define-Anweisung: _DEBUG
  Define-Anweisung: UNICODE
  Define-Anweisung: _UNICODE
  stdver: ms_c++17
  intelliSenseMode: windows-msvc-x64
Nach Syntaxfehlern wird gesucht: E:\@CodingGameEngine\!Projects\C++Projects\test.cpp
IntelliSense-Update für Dateien in dieser Übersetzungseinheit wird in die Warteschlange eingereiht: E:\@CodingGameEngine\!Projects\C++Projects\test.cpp
cpptools/finishUpdateSquiggles
Anzahl von Fehlerwellenlinien: 1
IntelliSense-Zeit aktualisieren (Sek.): 6.113
cpptools/getCodeActions: E:\@CodingGameEngine\!Projects\C++Projects\test.cpp (id: 6)
cpptools/getFoldingRanges: E:\@CodingGameEngine\!Projects\C++Projects\test.cpp (id: 7)`

**Comment by sean-mcmanus** [comment]
The C/C++: Log Diagnostics command should be run from the VS Code Command Palette.

**Comment by Dynastray** [comment]
@sean-mcmanus 
```
-------- Diagnostics - 17.5.2022, 06:09:31
Version: 1.10.2
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.
```

**Comment by sean-mcmanus** [comment]
@Dynastray The command needs to be run after opening the source file -- otherwise it says "No active translation units".

**Comment by Dynastray** [comment]
```
-------- Diagnostics - 25.5.2022, 22:29:24
Version: 1.10.3
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
No active translation units.
```

**Comment by Colengms** [comment]
Hi @Dynastray .  Is it possible there is an error in the path to cl.exe? `C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe` ?  It looks like it may be failing to locate cl.exe, and is instead falling back to MinGW.  Or, do you perhaps have some `C_cpp.*` settings set in VS Code, that might be adding the MinGW path `C:/MSYS64/MINGW64/`?

cl.exe is MSVC.  MinGW is GCC based.  Somehow these 2 compilers have been mixed in your configuration.  Since you are specifying cl.exe in a `compilerPath` setting in your configuration, perhaps it's not found and we are falling back to a version of MinGW detected on your system?

**Comment by Dynastray** [comment]
![image](https://user-images.githubusercontent.com/81412931/176207539-ab91821e-b4f0-441c-b04c-b3c08c4379a7.png)

**Comment by Dynastray** [comment]
Editing C_Cpp default Compiler path to "C_Cpp.default.compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe" did't helped still getting red lines every where around

**Comment by Dynastray** [comment]
@sean-mcmanus `-------- Diagnostics - 28.6.2022, 16:45:12
Version: 1.11.0
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.19041.0",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe",
    "compilerPathIsExplicit": true,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ E:\@CodingGameEngine\!Projects\C++Projects\test.cpp ]:
    E:\@CodingGameEngine\!Projects\C++Projects\test.cpp
Translation Unit Configurations:
[ E:\@CodingGameEngine\!Projects\C++Projects\test.cpp ]:
    Process ID: 31324
    Memory Usage: 44 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
    Includes:
        C:\MSYS64\MINGW64\INCLUDE\C++\11.3.0
        C:\MSYS64\MINGW64\INCLUDE
        C:\MSYS64\MINGW64\INCLUDE\C++\11.3.0\X86_64-W64-MINGW32
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\11.3.0\INCLUDE
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 44 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 142453

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: C:/msys64/mingw64/include/c++/11.3.0/bits/string_view.tcc
    Alternative: "C:/msys64/mingw64/include/c++/11.3.0/experimental"
Using: C:/msys64/mingw64/include/c++/11.3.0/cctype
    Alternative: "C:/msys64/mingw64/include/c++/11.3.0/tr1"
Using: C:/msys64/mingw64/include/c++/11.3.0/cmath
    Alternative: "C:/msys64/mingw64/include/c++/11.3.0/ext"
Using: C:/msys64/mingw64/include/limits.h
    Alternative: "C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/11.3.0/include-fixed"
    Alternative: "C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/11.3.0/install-tools/include"
Using: C:/msys64/mingw64/include/c++/11.3.0/math.h
    Alternative: "C:/msys64/mingw64/include"
Using: C:/msys64/mingw64/include/stddef.h
    Alternative: "C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/11.3.0/include"
Using: C:/msys64/mingw64/include/stdint.h
    Alternative: "C:/msys64/mingw64/include/isl"
Using: C:/msys64/mingw64/include/stdio.h
    Alternative: "C:/msys64/mingw64/lib/gcc/x86_64-w64-mingw32/11.3.0/include/ssp"
Using: C:/msys64/mingw64/include/c++/11.3.0/string
    Alternative: "C:/msys64/mingw64/include/c++/11.3.0/debug"
Using: C:/msys64/mingw64/include/time.h
    Alternative: "C:/msys64/mingw64/include/sys"
Using: C:/msys64/mingw64/include/c++/11.3.0/type_traits
    Alternative: "C:/msys64/mingw64/include/c++/11.3.0/tr2"` is it this what you ment?

**Comment by sean-mcmanus** [comment]
Are you trying to configure for mingw or cl.exe?

**Comment by Dynastray** [comment]
@sean-mcmanus 
I would prefer to use mingw but if you recomend to use cl its fine for me to configure for cl

**Comment by sean-mcmanus** [comment]
Can you try to change your compilerPath from cl.exe to the mingw gcc compiler and remove the mingw includes from the systemIncludePath setting?

**Comment by Dynastray** [comment]
Well thanks, that worked for me now the errors are gone thank you very much
