### ISSUE TITLE
Useless Include File Parsing Order

### ISSUE THREAD

**Issue by JonTBeckett** [microsoft/vscode-cpptools#9307]
Bug type: Language Service

This could be considered expected behavior but it is problematic behavior none-the-less. 

The extension seems to parse include files in an include directory in alphabetical order. This causes problems when using header guards and other #ifndef patterns. See below for an example in the Steps to reproduce section.

I apologize in advance for the poor formatting. I entered this initially on my phone but plan on coming back and filling it out more fully when I am at my desk.  

- OS and Version: Windows 10 Enterprise Version 20H2
- VS Code Version: 1.67.1
- C/C++ Extension Version: v1.9.8
- Other extensions you installed (and if the issue persists after disabling them): C/C++ Themes - issue persists when disabled

**Steps to reproduce**
1. Setup a file structure like this:
.
|- include/
   |-- file1.h
   |-- file2.h
   |-- file3.h

2. Set includePath to ["${workspaceFolder}/include"]
3. Setup the content of the as seen below:

file1.h
--------
#ifndef FILE1
#define FILE1

#ifndef FILE2
#include <file2.h>
#endif

#include <file3.h>

#endif
--------

file2.h
--------
#ifndef FILE2
#define FILE2

int test(void);

#endif
--------

file3.h
--------
#ifndef FILE3
#define FILE3

#ifndef FILE2
#include <file2.h>
#endif

int x = test();

#endif
--------

**Expected behavior**
In the above Steps to reproduce, file3.h treats FILE2 as already defined because it was defined when file3.h was included in file1.h. file3.h still has access to test() according to the extension despite the extension saying that file2.h will not be included. 

I would expect the extension to be able to recognize a bit more context and not simply walk through the include directory alphabetically and interpret files  based in the order they show up in the directory.

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
The defines that are used will depend on which TU is being picked. If you run C/C++: Log Diagnostics you should be able to see which TUs are getting used, i.e. depending on which file is open first, it may re-use an existing TU if that TU includes the 2nd/3rd file opened.

**Comment by BekTek** [comment]
Thank you, @sean-mcmanus. I checked the log and there is only one TU in use. I will try to update this issue to make this more clear but for now I will ask a question here. I have a typedef in a file like file2.h described above. I then need to use that typedef in file3.h. Both file2.h and file3.h are in the only TU listed in the log. file3.h is not recognizing my typedef from file2.h. I would expect file3.h to have access to the typedefs from files in the TU. Is my expectation correct?

I apologize for the unhelpful file names and lack of specificity. I work on export controlled software so I have to sanitize these examples.

**Comment by sean-mcmanus** [comment]
Yes, if the file2.h and file3.h are in the same TU then file2.h types should be available from file3.h if it's included before file2.h in the TU. It's possible you could be hitting a bug. Are you able to repro the issue with the sample you provided?

![image](https://user-images.githubusercontent.com/19859882/168655434-3b466625-ddda-4fc6-90c3-720aa2f8d1ad.png)

You could try setting C_Cpp.intelliSenseCacheSize to 0 to see if that works around the issue.

**Comment by JonTBeckett** [comment]
I apologize for the delay in response. I was pulled off the project where I ran into this and have since left that company so I no longer have access to the code base. I've tried to reproduce it as best I can from memory but cannot. 

Thank you for the responses and looking into as best you could!
