### ISSUE TITLE
Autocomplete issue: local variable does not appear in the list

### ISSUE THREAD

**Issue by Leedehai** [microsoft/vscode-cpptools#931]
VSCode: 1.14.2
OS: macOS 10.12.6

As demonstrated below, the IntelliSense didn't recognize "start" as a local variable in the method, and "start" does not appear in the suggestion list.
<img width="570" alt="screen shot 2017-07-30 at 01 46 58" src="https://user-images.githubusercontent.com/18319900/28751956-0eeb8ca2-74c9-11e7-8d9f-327b25fa07e8.png">

My the autocomplete tool is "C_Cpp.autocomplete": "Default", which means VSCode uses the active intellisense engine, and my intellisense engine is "Default" (not "Tag Parser").

**Comment by bobbrow** [comment]
This is currently expected.  The new IntelliSense only provides member suggestions right now (e.g. stuff typed after `.`, `->`, and `::`).  Everything else is still using the old IntelliSense engine - which doesn't know about variables defined at the function scope.  We are using issue #13 to track the implementation of the remaining auto-complete functionality.
