### ISSUE TITLE
Doxygen multiple returns: only the first return is displayed.

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#9316]
### Environment

Doxygen supports multiple returns:

> \return { description of the return value }
>
>Starts a return value description for a function. The text of the paragraph has no special internal structure. All visual   enhancement commands may be used inside the paragraph. Multiple adjacent \return commands will be joined into a single paragraph. The \return description ends when a blank line or some other sectioning command is encountered. See section [\fn](https://www.doxygen.nl/manual/commands.html#cmdfn) for an example.

So in case of:

```C++
* @return true is good
* @return false is bad
```

VSCode's documentation popup displays just the first value

### Bug Summary and Steps to Reproduce

Create a documentation comment such as:

```C++
/** @brief Func
 *
 * @return true
 * @return false
 */
bool ThisIs() { ...};

### Debugger Configurations

```shell
none
```

### Debugger Logs

```shell
none
```

**Comment by sean-mcmanus** [comment]
Thanks for reporting this. I've filed a bug on VS (shared implementation) at https://developercommunity.visualstudio.com/t/C-Doxygen-comments-only-show-1-return-/10043754 .
