### ISSUE TITLE
jump function is very slow

### ISSUE THREAD

**Issue by wk89463** [microsoft/vscode-cpptools#9320]
Bug type: Language Service

question 1:
my project is very large，the cpptools IntelliSense find function def (F12)  is very slow，how can i use GNU global to find function def

question 2:
my project include many *.i file，how can i configure to ignore *.i file when i use F12 to jump function，now the result include *.i file
<img width="863" alt="企业微信截图_b10c879b-be74-4c04-9948-68a3c6e1ca5a" src="https://user-images.githubusercontent.com/54431875/168801766-c9ce50f2-eff5-41f7-bc37-3142c5756a28.png">

**Describe the bug**
- OS and Version:macOS 12.3.1
- VS Code Version:1.67.1
- C/C++ Extension Version:1.9.8
- Other extensions you installed (and if the issue persists after disabling them):C/C++ GNU global

**Comment by sean-mcmanus** [comment]
Do you want to use our C/C++ extension or the GNU global extension? Since they provide overlapping functionality, you should disable the one you don't want to use, and then file the bug on the extension that is active. Otherwise, we can't tell if the bug is from our extension or the other one.

**Comment by wk89463** [comment]
thanks, it's works

**Comment by sean-mcmanus** [comment]
I'm not sure which extension is working for you, but I'll close this issue.

**Comment by wk89463** [comment]
how can i add inactive code into code analysis，now cpptools can't find the inactive code arg.
<img width="660" alt="企业微信截图_3d5da496-832f-4256-8179-a849eb008c2a" src="https://user-images.githubusercontent.com/54431875/169226406-b51f10e9-8858-4a8a-832b-a5dbf4ad1fd2.png">

**Comment by sean-mcmanus** [comment]
I do not understand what you're asking. You're using the C/C++ extension? The inactive regions implementation is hooked into IntelliSense configuration and not code analysis configuration. You may need to add defines to the "defines" property in c_cpp_properties.json or set "compilerPath" or "compilerArgs".
