### ISSUE TITLE
Add auto-formatting support for clang-tidy fixes

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#9322]
Some clang-tidy fix types such as for readability-braces-around-statements generates fixes that need to be formatted in order to give acceptable results (otherwise, } will have no indentation). Potentially, we just run the currently configured formatting on the lines that are changed.

One workaround is to add `--format-style=` to C_Cpp.codeAnalysis.clangTidy.args if clang-format style formatting is desired. Or add FormatStyle to a .clang-tidy file. UPDATE: The workaround doesn't work.

UPDATE: I noticed with readability-else-after-return it is desirable to format the entire range, but the fix only applies it to the start/end lines...not sure if there's a way to improve that.

**Comment by sean-mcmanus** [comment]
I'm seeing `FormatStyle: file` not working in .clang-tidy with readability-braces-around-statements. I'll file a clang-tidy bug later.

**Comment by sean-mcmanus** [comment]
I've filed bug https://github.com/llvm/llvm-project/issues/55569 .

**Comment by sean-mcmanus** [comment]
They said it's by design for --export-fixes to not format.

**Comment by H-G-Hristov** [comment]
This should be optional.

**Comment by sean-mcmanus** [comment]
@H-G-Hristov Yeah, a setting to disable it sounds good. Do you have repro steps for the invalid `\"%s\" code? It may be a bug with our processing.

**Comment by Zingam** [comment]
> @H-G-Hristov Yeah, a setting to disable it sounds good. Do you have repro steps for the invalid `"%s" code? It may be a bug with our processing.

@sean-mcmanus  Sorry for the delay. I have filed some details here: https://github.com/llvm/llvm-project/issues/56669
