### ISSUE TITLE
illegal state - object is disposed

### ISSUE THREAD

**Issue by Rellotscrewdriver** [microsoft/vscode-cpptools#9323]
### Environment

- OS and version: Windows 7 x86 (6.1)
- VS Code: 1.67
- C/C++ extension: C/C++

### Bug Summary and Steps to Reproduce

Bug Summary:
This error happens when I simply run the extension, VS code always pop up saying that C/C++ failed to run 3 times, it will not restart. Looking into the extension -> Runtime status I found this(look in additional info)

Steps to reproduce:
1. install C/C++ extension on the VS code store
2. close and open VS code 

### Other Extensions
C/C++ version 1.2.0
C/C++ Extension Pack
C#
GitLens
Doxygen Docs

### Additional Information

![image](https://user-images.githubusercontent.com/50903223/169002554-92d7a7e5-af35-4bc7-91b3-4d0b9a5e9a81.png)
![image](https://user-images.githubusercontent.com/50903223/169003670-21359adc-7a76-4e7c-a62a-0a91ae52f35d.png)

**Comment by Rellotscrewdriver** [comment]
version 1.2.0

**Comment by sean-mcmanus** [comment]
1.2.0 is a year old -- can you update to the latest version 1.9.8 or 1.10.2 (pre-release)?

**Comment by Rellotscrewdriver** [comment]
Tried updating to the latest, got the same error
Tried updating to the pre-release, got the same crash but the error is not shown

**Comment by sean-mcmanus** [comment]
This seems similar to issue https://github.com/microsoft/vscode-cpptools/issues/9324 in which a dependency DLL wasn't found. Can you try running `C:\Users\<username>\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x86\bin\cpptools.exe` and see if you get an error message? It's possible you may need to update your OS or .NET SDKs with the latest available patches.

**Comment by Rellotscrewdriver** [comment]
cpptools.exe works fine. no errors encountered

**Comment by sean-mcmanus** [comment]
I'll check if anyone on our team is able to repro this...

**Comment by Rellotscrewdriver** [comment]
Hello!
today I tried the lastest version which is 1.10.4 which works successfully!! the intellisense and autocompletion are working correctly
