### ISSUE TITLE
Connection to server got closed. Server will not be restarted.

### ISSUE THREAD

**Issue by lvyin555** [microsoft/vscode-cpptools#9324]
Bug type: Language Service

**Describe the bug**
- OS and Version:Windows11
- VS Code Version:1.67.1
- C/C++ Extension Version:1.9.8
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine:
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

- Error is reported whenever VScode starts: 'Connection to server got closed. Server will not be restarted.' and cannot use features such as autocomplete and syntax highlighting

**Expected behavior**

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

**Additional context**

**Comment by jwy2008** [comment]
When I was trying to solve it, I found the following solution: https://blog.csdn.net/linchuran/article/details/115522616,
The general way is to switch to the old version and turn off the automatic update of the plugin, but this method has no effect!

**Comment by sean-mcmanus** [comment]
There is the "Install Another Version..." feature and extensions.autoUpdate. However, we don't know what could be causing the failure. You might want to check if it works when opening a simpler folder, or if `C:\Users\<username>\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\bin\cpptools.exe` is executable or if 1.10.2 (pre-release) works.

**Comment by jwy2008** [comment]
> There is the "Install Another Version..." feature and extensions.autoUpdate. However, we don't know what could be causing the failure. You might want to check if it works when opening a simpler folder, or if is executable or if 1.10.2 (pre-release) works.`C:\Users\<username>\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\bin\cpptools.exe`

Error: Code execution cannot continue because mscorree.dll was not found. Reinstalling the program may resolve the issue

**Comment by jwy2008** [comment]
> There is the "Install Another Version..." feature and extensions.autoUpdate. However, we don't know what could be causing the failure. You might want to check if it works when opening a simpler folder, or if is executable or if 1.10.2 (pre-release) works.`C:\Users\<username>\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\bin\cpptools.exe`

Error: Code execution cannot continue because `mscoree.dll` was not found. Reinstalling the program may resolve the issue

**Comment by jwy2008** [comment]
> > There is the "Install Another Version..." feature and extensions.autoUpdate. However, we don't know what could be causing the failure. You might want to check if it works when opening a simpler folder, or if is executable or if 1.10.2 (pre-release) works.`C:\Users\<username>\.vscode\extensions\ms-vscode.cpptools-1.9.8-win32-x64\bin\cpptools.exe`
> 
> Error: Code execution cannot continue because `mscoree.dll` was not found. Reinstalling the program may resolve the issue

When I looked for `mscoree.dll`, I found that many people encountered the problem of "cannot find `mscoree.dll`", some people guessed that it was a system update problem
https://answers.microsoft.com/zh-hans/windows/forum/all/%E7%94%B1%E4%BA%8E%E6%89%BE%E4%B8%8D%E5%88%B0mscor/75a4155d-2599-4e92-9dd6-6ce83b0bca3d

**Comment by jwy2008** [comment]
But when I put in the missing dll file, I still get an error:
`Connection to server got closed. Server will not be restarted.`

**Comment by jwy2008** [comment]
But this solves a problem. Before that, the button for setting the C++ compiler was displayed normally, and my C++ configuration could be imported normally, but there was still no response to the click.
<img width="73" alt="屏幕截图 2022-05-19 210413" src="https://user-images.githubusercontent.com/89643112/169300236-a3d12fc5-41f1-4a71-a0a3-79002783db73.png">

**Comment by jwy2008** [comment]
But this solves a problem, the button to set the C++ compiler can be displayed normally (it didn't even display normally before this), and I can import my C++ configuration normally, but still nothing happens when I click it:
<img width="73" alt="屏幕截图 2022-05-19 210413" src="https://user-images.githubusercontent.com/89643112/169303658-bbe7c9d0-a997-41c0-ac12-42e377f64175.png">

**Comment by jwy2008** [comment]
But this solves an issue, the button for setting the C++ compiler shows up fine (before this it didn't even show up properly) and I can import my C++ config fine
<img width="73" alt="屏幕截图 2022-05-19 210413" src="https://user-images.githubusercontent.com/89643112/169347004-6bd3ac98-aedd-405e-bd4a-36da083ef2d5.png">

**Comment by jwy2008** [comment]
@sean-mcmanus I found a solution! Open .net 3.5 (I only had 4.8 open before)

**Comment by sean-mcmanus** [comment]
What does "Open .net 3.5" mean? Do you think our extension has a bug with not including some required DLL or is it some issue with your machine's software?

**Comment by jwy2008** [comment]
@sean-mcmanus 
It's my computer that doesn't have the .NET Framework 3.5 installed, causing it to not work
