### ISSUE TITLE
Break/Continue snippets on WSL

### ISSUE THREAD

**Issue by Wakotu** [microsoft/vscode-cpptools#9332]
### Feature Request

I use version 1.9.8 of this plugin on the WSL, the auto completing  problem of `break;` and `continue;` snippet seemed not to be modified.(While the same problem in the same version of this plugin on Windows has been modified.)

**Comment by Colengms** [comment]
Hi @yqy-pong-ops .  The completion behavior of the C/C++ extension does not fundamentally differ based on the target platform.  Could you confirm that the version of the C/C++ extension installed in the remote WSL environment is the same as the version you are comparing against in your local environment?

You might consider uninstalling the extension and clearing all instances of it from your `.vscode` directories (in your user directories), then freshly reinstalling.

**Comment by sean-mcmanus** [comment]
This issue is fixed with our latest 1.10.2 (pre-release), see https://github.com/microsoft/vscode-cpptools/issues/9115 .
