### ISSUE TITLE
clang-tidy not being enabled by workspace settings

### ISSUE THREAD

**Issue by jahaniam** [microsoft/vscode-cpptools#9335]
I have a container and insider container, I have code-workspace file. 

My workspace settings I have enabled clang-tidy  as 

"C_Cpp.codeAnalysis.clangTidy.enabled": false
but it wont get enabled until I create a settings.json and explicitly enable it there.

**Comment by Colengms** [comment]
Hi @jahaniam .  I'm not able to easily reproduce this issue.  I tried adding the following to a `.code-workspace` file:

```
	"settings": {
		"C_Cpp.codeAnalysis.clangTidy.enabled": true
	}
```

And I was able to get clang-tidy warnings using the following example code, which triggers a dereference warning:

```cpp
void foo()
{
  int *i = 0;
  *i = 10;
}
```

Also, I noticed you referred to setting `enabled` to `false`.  I assume you meant to indicate you had set it to `true`?
