### ISSUE TITLE
The non-taking part of code enclosed in #if / #ifdef is not rendered inactive

### ISSUE THREAD

**Issue by xueyunquan** [microsoft/vscode-cpptools#934]
Hi,

In the current version of 0.12.1, if a code block is enclosed by `#if 0 / #endif` , it is rendered inactive, with the same color as comments.

However, if a code block is enclosed by `#if / #endif` or `#ifdef / #endif` and the testing condition is not met, it is not rendered inactive.

Please refer to the following screenshot as an example:

![image](https://user-images.githubusercontent.com/4216222/28812605-0e94a51c-76c8-11e7-96c0-3a84c33e8809.png)

On line 4 the symbol is undefined, and so the code on line 6 is inactive, and should be displayed like line 12. But it is not. By hovering the mouse point on line 6 and line 8, it is confirmed that this is only a display issue, because line 8 shows a function definition and line 6 doesn't. This implies that the parser does know which code is active and which is inactive, judging by the conditions of the preprocessing directives.

Working on a large project with lots of conditional code, like the Linux kernel, could be quite hard with the conditional code rendered incorrectly. So please fix this. Thank you.

**Comment by sean-mcmanus** [comment]
We're tracking this in https://github.com/Microsoft/vscode-cpptools/issues/230 .

A workaround is to hover over the code (with the Default IntelliSense engine) -- the inactive code won't give any hover info, but the active code will.

**Comment by xueyunquan** [comment]
@sean-mcmanus   Thank you. And sorry for missing the original issue and creating a duplicated one.

**Comment by sean-mcmanus** [comment]
@xueyunquan Inactive code colorization has been added in 0.15.0 (intelliSenseEngine needs to be "Default" though).
