### ISSUE TITLE
Clang-tidy arm-gcc error with makefile tools

### ISSUE THREAD

**Issue by KrestenHelstrup** [microsoft/vscode-cpptools#9340]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10
- VS Code Version: 1.67.2
- C/C++ Extension Version: 1.10.2
- Other extensions you installed (and if the issue persists after disabling them): Makefile Tools 0.5.0
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

All configurations/defines seems to be passed correctly from makefile tools to clang-tidy when the following is present in the configuration: "configurationProvider": "ms-vscode.makefile-tools"
However, I get the following error from clang-tidy "typedef redefinition with different types (unsigned int vs unsigned long)" from stddef.h.
The project compiles correctly with arm-gcc (arm-none-eabi-gcc) and the debug output shows that the gcc includes are found correctly by makefile tools - same goes for other defines found in the makefile. 

**Expected behavior**
clang-tidy should work as expected.

**Comment by KrestenHelstrup** [comment]
Already got a bit more information. It seems like paths like ARMGCC/lib/gcc/arm-none-eabi/4.9.3/include are correctly provided by the configuration provider - but the standard defines are wrong so things like __GNUC__ is missing.
Any ideas ?

**Comment by sean-mcmanus** [comment]
clang-tidy itself may have a problem compiling your code (have your tried manually invoking it?). Our code analysis feature will get the clang-tidy configuration from the IntelliSense configuration. It's possible the Makefile extension may not be providing us the info we need. If you set C_Cpp.loggingLevel to "Debug" you should be able to see the defines used in the C/C++ logging -- do you see certain defines missing?

**Comment by KrestenHelstrup** [comment]
Yes, with the logginglevel set to debug I see __ GNUC __ missing - among many others.
I will try to install clang-tidy to see if it works outside of Code.

**Comment by sean-mcmanus** [comment]
Does your compiler define `__GNUC__`? If you set C_Cpp.loggingLevel to "Debug" and open the source file you should see IntelliSense logging in the "C/C++" pane that lists all the defines that we get back from querying the compiler, e.g.`  define: __GNUC__=10`. There could be some command line arg that we may not be handling correctly.

**Comment by sean-mcmanus** [comment]
Oops, sorry, I just repeated myself.

**Comment by KrestenHelstrup** [comment]
I had a look in the debug output and this is what I get:

Custom configurations received:
  uri: file:///c%3A/Path/To/My/File/system_efm32g.c
  config: {
  "defines": [
    "EFM32G890F128",
    "DEBUG"
  ],
  "standard": "c11",
  "includePath": [
    "c:\\Path\\To\My\\src",
    "c:\\Path\\To\My\\Includes\\CMSIS-Include",
    "c:\\Path\\To\My\\Includes\\EnergyMicro\\inc"
  ],
  "forcedInclude": [],
  "compilerPath": "C:\\ARMTC\\ARMGCC/bin/arm-none-eabi-gcc.exe",
  "compilerArgs": [
    "-Wall",
    "-Wextra",
    "-Wno-pragmas",
    "-mcpu=cortex-m3",
    "-mthumb",
    "-mfix-cortex-m3-ldrd",
    "-fomit-frame-pointer",
    "-ffunction-sections",
    "-fdata-sections",
    "-MMD",
    "-MP",
    "-g",
    "-O0",
    "-c",
    "-o",
    "build/system_efm32g.o",
    "Path/To/File/system_efm32g.c"
  ]
}
cpptools/didChangeCustomConfiguration
Attempting to get defaults from C compiler in "compilerPath" property: 'C:\ARMTC\ARMGCC/bin/arm-none-eabi-gcc.exe'

To me this looks correct. And it looks like it tries to get defaults but I think it doesn't work as expected. If I run something like:
arm-none-eabi-gcc -dM -E MyFile.c
I get __ GNUC __ which I don't see in the debug output when it tries to run clang-tidy.

I changed some of the paths but that shouldn't matter - I hope this gives some more information.

**Comment by KrestenHelstrup** [comment]
![image](https://user-images.githubusercontent.com/74759135/170019084-9670c7b1-4473-4514-9a5f-adf417574002.png)
Intellisense also detects the __ GNUC __ define correctly.

**Comment by sean-mcmanus** [comment]
Yes, IntelliSense will have `__GNUC__` defined, but we intentionally filter out the `__GNUC__` define when running clang-tidy, because it caused the problem mentioned at https://github.com/microsoft/vscode-cpptools/issues/9091 .

Are you able to get clang-tidy to run via the command line or via generating a compile_commands.json and setting C_Cpp.codeAnalysis.clangTidy.useBuildPath to true?

Version 1.9.8 doesn't filter out the `__GNUC__` so you could also try that, but it could just lead to other errors as mentioned in #9091.

We may need to do further investigation on how to get clang-tidy to work with the arm-gcc compiler.

**Comment by KrestenHelstrup** [comment]
I'm trying to get it working via the command line. I figured that I probably need to add --extra-arg=--target=arm-none-eabi-gcc but since the configuration is supplied by ms-vscode.makefile-tools I don't know how to add extra args. Can I use a compile_commands.json without overriding everything already set by the makefile-tools ?

**Comment by sean-mcmanus** [comment]
You can use C_Cpp.codeAnalysis.clangTidy.args to add `--extra-arg=--target=arm-none-eabi-gcc` to that, you can also use C_Cpp.codeAnalysis.clangTidy.useBuildPath set to `true` to use the compile_commands.json directly without configuration from makefile tools.

**Comment by KrestenHelstrup** [comment]
I think that did the trick - thank you very much for your support.
Could you provide an example of a compile_commands.json file ?

**Comment by sean-mcmanus** [comment]
@KrestenHelstrup There's some docs at https://clang.llvm.org/docs/JSONCompilationDatabase.html .
