### ISSUE TITLE
clang-format: outdated?

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cpptools#9349]
### Feature Request

The extension appears to use clang-format - although I can't seem to find a confirmation easily. If so the clang-format appears to be outdated - current version is 14.
Is there an option to check which versions is the extension using:
clang-format, clang-tidy, etc. ?

**Comment by Colengms** [comment]
Hi @Zingam .  What version of cpptools are you using?  As new versions of clang-format and clang-tidy are released, we include them in the next release of the C/C++ extension.  Currently, version 14 is included in the pre-release version currently available on the marketplace: 1.10.2

**Comment by Zingam** [comment]
The non-prerelease version. My format was failing due to me using a newer option and I didn't see any error output. I wasn't even sure if the extension were using clang-format initially.

**Comment by Zingam** [comment]
Neither (AFAIK) Visual Studio 2022 nor cpptools make it clear which third party tool versions are included.

**Comment by sean-mcmanus** [comment]
1.9.8 uses clang 13 by default, 1.10.x uses 14 by default.

We don't currently check on or report the versions used. We'll consider that for the future, but it hasn't been a priority yet.
