### ISSUE TITLE
Setting the C++ standard for parsing

### ISSUE THREAD

**Issue by kranzj** [microsoft/vscode-cpptools#935]
Dear all,

I'm sorry if I'm just blind, but I think the options are currently lacking means to set the C++ standard of a project.

Thanks for developing VSC and the C++ extension!

**Comment by horvay** [comment]
This is by no means a proper answer, but if you need this functionality now, I believe it is possible to modify a file in the extension as specified at the bottom of this issue: #685 

In windows, the location is in the user folder `C:\Users\<user>\.vscode\extensions\ms-vscode.cpptools-0.12.1\bin`

**Comment by sean-mcmanus** [comment]
Yeah, we don't expose that as a setting yet, but you can modify the msvc.json file (near the bottom where it says c++17) as @horvay describes.

**Comment by kranzj** [comment]
Thank you for your fast answers! :+1:

**Comment by sean-mcmanus** [comment]
We added cStandard and cppStandard properties to c_cpp_properties.json in March.
