### ISSUE TITLE
Jump to definition/declaration jumps to wrong definition for preprocessor macros

### ISSUE THREAD

**Issue by prosenboim** [microsoft/vscode-cpptools#9350]
Bug type: Language Service

Using VS code 1.67.2 on Mac and connecting to remote Ubuntu 20 machine. Cpp extention v1.9.8.

With following sample code

```
#include <stdio.h>

#define DEF1    5


#define DEF2 DEF1


void main()
{
    printf("%d", DEF2);
}
```
if I point a cursor to DEF2 in `printf` line and press F12, VS code jumps to definition of DEF1. Same happens in all other places when one preprocessor definition uses another - jump to definition skips the immediate definition.

**Comment by sean-mcmanus** [comment]
Can you try 1.10.2 or 1.10.3 (pre-release)? This sounds like an issue that was already fixed in those versions.
