### ISSUE TITLE
cannot find the definition of variable and the member of a struct

### ISSUE THREAD

**Issue by niliushall** [microsoft/vscode-cpptools#9355]
Bug type: Language Service

**Describe the bug**
- OS and Version: win11, 10.0.22000, remote ubuntu20.04
- VS Code Version: 1.67.2
- C/C++ Extension Version: v1.10.3 / v1.9.8
- Other extensions you installed (and if the issue persists after disabling them): c++ intellisense
- If using SSH remote, specify OS of remote machine: ubuntu20.4
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

In the workspace, vscode can not find the definition of the variable(some can be found, some can not be found, especially in different files), and it can not identify the member of a struct though it can jump to its definition. But the code can be compiled and run normally.

The configurations as follow:
c_cpp_properties.json
```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "/usr/src/**",
                "/usr/include/**"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c11",
            "cppStandard": "c++20",
            "intelliSenseMode": "linux-gcc-x64"
        }
    ],
    "version": 4
}
```

settings.json: none.

**Screenshots**

![Snipaste_2022-05-24_15-35-03](https://user-images.githubusercontent.com/25560399/169977543-d2d04384-f367-41e6-82e8-3639654180f8.png)

![Snipaste_2022-05-24_15-52-49](https://user-images.githubusercontent.com/25560399/169979233-05b917e0-9b10-4f4e-bcdb-e3c672144c9c.png)

![Snipaste_2022-05-24_15-53-20](https://user-images.githubusercontent.com/25560399/169979253-1bd2db94-3c7c-427b-8436-b9ddb55c4509.png)

**Comment by sean-mcmanus** [comment]
Can you remove
```
"/usr/src/**",
"/usr/include/**"
```
from your includePath? Does the issue still repro after that?

If so, can you try setting C_Cpp.intelliSenseCacheSize to 0?

**Comment by niliushall** [comment]
> Can you remove
> 
> ```
> "/usr/src/**",
> "/usr/include/**"
> ```
> 
> from your includePath? Does the issue still repro after that?
> 
> If so, can you try setting C_Cpp.intelliSenseCacheSize to 0?

I have removed the configuration mentioned above, and set the intelliSenseCacheSize to 0, but the issue still repro after restarting the vscode.

**Comment by sean-mcmanus** [comment]
Is the repro for C, right?

**Comment by niliushall** [comment]
> Is the repro for C, right?

Yeah, that's right.

**Comment by sean-mcmanus** [comment]
In your 2nd screenshot, who is supposed to be defining `__USE_MISC`? Your user code? If you run C/C++: Log Diagnostics from the Command Palette do you see the `__USE_MISC` defined in the logging?

**Comment by sean-mcmanus** [comment]
For the 1st screenshot, is /usr/include/linux in your includePath or are you using `#include <linux/limits.h>`?

**Comment by sean-mcmanus** [comment]
Also, I noticed you have the "c++ intellisense" extension installed -- that extension could possibly be conflicting with our extension so you may want to disable that one.

**Comment by niliushall** [comment]
> Also, I noticed you have the "c++ intellisense" extension installed -- that extension could possibly be conflicting with our extension so you may want to disable that one.

Now, I have uninstalled the `c++ intellisense`, but the issue still repro.

**Comment by sean-mcmanus** [comment]
You should add __USE_MISC to the "defines" property if you want to get rid of the IntelliSense error.

However, it doesn't sound like your settings are property configured to build -- you should install the Makefile Tools extension and set the "configurationProvider" in c_cpp_properties.json to "ms-vscode.makefile-tools" -- that extension should configure your IntelliSense correctly so that it matches what makefile is using to build.

**Comment by niliushall** [comment]
> You should add __USE_MISC to the "defines" property if you want to get rid of the IntelliSense error.
> 
> However, it doesn't sound like your settings are property configured to build -- you should install the Makefile Tools extension and set the "configurationProvider" in c_cpp_properties.json to "ms-vscode.makefile-tools" -- that extension should configure your IntelliSense correctly so that it matches what makefile is using to build.

I found that if I delete the dir `.vscode`, all the issues disappeared. But I don't know why. Maybe there is something wrong of my configuration.
I will try to use this extension. Thank you very much!

**Comment by Zaynoel3** [comment]
Zayn90
