### ISSUE TITLE
cannot run cpptools within docker container when extensions directory is mounted to host

### ISSUE THREAD

**Issue by indirectlylit** [microsoft/vscode-cpptools#9358]
### Environment

- OS and version: macOS 12.3.1
- VS Code: 1.67.2 
- C/C++ extension: 1.10.3
- OS and version of docker image: Ubuntu 18.04

### Bug Summary and Steps to Reproduce

**Bug Summary:**

The VS Code documentation [recommends](https://code.visualstudio.com/remote/advancedcontainers/avoid-extension-reinstalls) mounting the `~/.vscode-server/extensions` directory in order to persist installed extensions across container runs.

For example: 

```bash
docker run -it --rm --volume "$HOME/docker-vscode-server:/root/.vscode-server/extensions" # ...
```

This seems to work fine when the docker host and container are both linux. However when the host is macOS and the image is Ubuntu, a popup `Couldn't start client cpptools` is shown.

This means that I cannot avoid VS Code extension reinstalls while using a dockerized ubuntu development environment on mac.

**Steps to reproduce:**

Using a mac host with an ubuntu docker image, set up a mapped volume to persist extensions to the host. Try using the C++ extension in the running container.

**Comment by Colengms** [comment]
Hi @indirectlylit .  The C/C++ extension is platform-specific, and bundles binaries needed for the target platform.  Does your mounted extensions directory contain the extension as installed for macOS?  If so, the issue would seem to be that the binaries do not match what is needed on Linux, and you might consider opening an issue in the [VS Code repo](https://github.com/microsoft/vscode/issues) requesting that they update their documentation to also address when platform-specific extensions are used.

**Comment by indirectlylit** [comment]
> Does your mounted extensions directory contain the extension as installed for macOS?

No, these extensions are correctly installed by VS Code for linux. Here's the runtime error:

```
[Error - 6:11:08 PM] Starting client failed
Launching server using command /root/.vscode-server/extensions/ms-vscode.cpptools-1.9.8-linux-x64/bin/cpptools failed.
```

If I try to run it manually from within the container I see:

```
/root/.vscode-server/extensions/ms-vscode.cpptools-1.9.8-linux-x64/bin/cpptools
zsh: permission denied: /root/.vscode-server/extensions/ms-vscode.cpptools-1.9.8-linux-x64/bin/cpptools
```

This is different from the binary on the host:

```
~/.vscode/extensions/ms-vscode.cpptools-1.9.8-darwin-x64/bin/cpptools
```

**Comment by indirectlylit** [comment]
The problem appears to be that I was using the `--volume` flag rather than the `--mount` with a named volume. Creating and mounting a named volume allows the binary to be run. I assume this is because there is some filesystem incompatibility or discrepancy between macOS and linux.

thank you!
