### ISSUE TITLE
Update Docs screenshots on tasks

### ISSUE THREAD

**Issue by elahehrashedi** [microsoft/vscode-cpptools#9359]
The drop-down for `Add debug configuration` and `Run and Debug` play button needs to be updated.
The current screenshots don't have these items:
"`recently used task`" and "`the compiler path`"

Also: update this page: https://code.visualstudio.com/docs/cpp/launch-json-reference

**Comment by sean-mcmanus** [comment]
@elahehrashedi Is this for 1.10 still or 1.11?

**Comment by browntarik** [comment]
@AlexandraKemperMS

**Comment by browntarik** [comment]
This issue is out of date with our current docs and will be closed.
