### ISSUE TITLE
C++: IntelliSense does not recognize types from literals

### ISSUE THREAD

**Issue by Ptomaine** [microsoft/vscode-cpptools#936]
Literals are not recognized as type providers.

![literals](https://user-images.githubusercontent.com/2706546/28850112-8ca9a19e-76cf-11e7-9043-79117a9b91f9.png)

**Comment by bobbrow** [comment]
Can you share some additional information about your literal and the type it describes?  I don't see this with the string literals on Windows:
![initlist](https://user-images.githubusercontent.com/12818240/28851455-687705f2-76d7-11e7-976e-08a5c079aa68.png)

**Comment by Ptomaine** [comment]
I use two libraries to work with JSON data:
        [https://github.com/nlohmann/json](https://github.com/nlohmann/json)
        [https://github.com/Tessil/ordered-map](https://github.com/Tessil/ordered-map)

and I use the following type aliases and the custom literal:
```
template<class Key, class T, class Ignore, class Allocator, class Hash = std::hash<Key>, class KeyEqual = std::equal_to<Key>>
using ordered_map = tsl::ordered_map<Key, T, Hash, KeyEqual, Allocator>;

using json_ord = nlohmann::basic_json<ordered_map>;

inline json_ord operator "" _json_ord(const char* s, std::size_t n)
{
    return json_ord::parse(s, s + n);
}
```

**Comment by bobbrow** [comment]
This works for me with the latest version of the C++ extension.

![image](https://user-images.githubusercontent.com/12818240/52227286-f3488400-2863-11e9-82b3-5be327000da0.png)

![image](https://user-images.githubusercontent.com/12818240/52227319-065b5400-2864-11e9-9e4c-db559ed821f6.png)
