### ISSUE TITLE
Where is the Select Environment dropdown?

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-cpptools#937]
Reading the following at:
https://code.visualstudio.com/docs/languages/cpp

<img width="766" alt="screen shot 2017-08-02 at 03 42 38" src="https://user-images.githubusercontent.com/738650/28854033-f30d1e2e-7734-11e7-81c8-f86d716d3972.png">

Can someone show with an image what the Select Environment dropdown looks like?
I can't find it anywhere.

**Comment by xueyunquan** [comment]
@clankill3r :
![image](https://user-images.githubusercontent.com/4216222/28855706-e8c0dd02-7770-11e7-8b69-ce5449b4d8f1.png)

And here you go:

![image](https://user-images.githubusercontent.com/4216222/28855731-1d9f8ba4-7771-11e7-8b89-118354ee8a80.png)

I hope this answers your question.

**Comment by clankill3r** [comment]
Thanks. I get it now, the "Select Environment" only shows up when a `launch.json` does not yet exist.

**Comment by bobbrow** [comment]
Other ways to make it appear:
* if you don't have a launch.json yet, click the green arrow and it will appear
![debug1](https://user-images.githubusercontent.com/12818240/28933641-b3b548ce-7832-11e7-9f1f-7580d51ba670.png)
* you can also choose it from the configuration drop-down list at any time
![debug](https://user-images.githubusercontent.com/12818240/28933659-c9860936-7832-11e7-95ae-47acc25fe6f8.png)
