### ISSUE TITLE
c/c++: edit configuration error

### ISSUE THREAD

**Issue by zgxgoo** [microsoft/vscode-cpptools#9370]
### Environment

- OS and version: mac os Big Sur
- VS Code:1 .67.2
- C/C++ extension: v1.9.8
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. In this environment...
2. With this config c/c++: edit configurations(ui/jason)
3. Do '...'
4. See error...
   命令"C/C++: 编辑配置(UI)"导致错误 (command 'C_Cpp.ConfigurationEditUI' not found)
   命令"C/C++: 编辑配置(JSON)"导致错误 (command 'C_Cpp.ConfigurationEditJSON' not found)

**Comment by zhangshouyin** [comment]
> 

want` s extensions?

**Comment by zhangshouyin** [comment]
> miss install extensions

what are the extensions?
