### ISSUE TITLE
"copy callstack" puts backslashes in linux filenames

### ISSUE THREAD

**Issue by Spongman** [microsoft/vscode-cpptools#9372]
Issue Type: <b>Bug</b>

debugging c++ code via remote-wsl to gdb on a linux guest. the "copy callstack" command places `\` backslash characters in the linux source filenames.

Extension version: 1.10.3
VS Code version: Code 1.67.2 (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:15:52.058Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2
Remote OS version: Linux x64 5.10.102.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.66GB (20.65GB free)|
|Process Argv|C:\\Users\\PiersH\\AppData\\Local\\Temp\\iisexpress\\applicationhost202252514642992.config|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (18.84GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (18.84GB free)|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: CentOS7|
|OS|Linux x64 5.10.102.1-microsoft-standard-WSL2|
|CPUs|Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz (6 x 2904)|
|Memory (System)|37.34GB (18.84GB free)|
|VM|0%|
</details>

**Comment by WardenGnaw** [comment]
The debugger is returning the correct paths:
```
<--   C (stackTrace-14): {"command":"stackTrace","arguments":{"threadId":1194,"startFrame":0,"levels":20},"type":"request","seq":14}
--> R (stackTrace-14): {"type":"response","request_seq":14,"success":true,"command":"stackTrace","body":{"stackFrames":[{"id":1000,"name":"libfoo.so!foo()","source":{"name":"foo.cpp","path":"/home/user/cpp/foo.cpp","sources":[],"checksums":[]},"line":6,"column":1,"instructionPointerReference":"0x00007ffff7fc4121","moduleId":2},{"id":1001,"name":"main()","source":{"name":"main.cpp","path":"/home/user/cpp/main.cpp","sources":[],"checksums":[]},"line":11,"column":1,"instructionPointerReference":"0x0000555555555241"}],"totalFrames":2},"seq":484}
```

but when using "copy call stack", it results in:
```
libfoo.so!foo() (\home\user\cpp\foo.cpp:6)
main() (\home\user\cpp\main.cpp:11)
```

however, hovering over the file name results in the correct pathing:
![image](https://user-images.githubusercontent.com/3953714/170797862-93121637-efdf-43c3-8309-2ed2e970e6cb.png)


You will want to open this in https://github.com/microsoft/vscode/issues

**Comment by Spongman** [comment]
any chance you can transfer it there? i don't have permissions to do that.

**Comment by WardenGnaw** [comment]
Unfortunately, I can't either. 

I suggest creating a new issue and link this issue.
