### ISSUE TITLE
Intellisense not working with emsdk/emscripten

### ISSUE THREAD

**Issue by alshamma** [microsoft/vscode-cpptools#9374]
Bug type: Language Service

**Describe the bug**
- OS and Version: macOS 12.4
- VS Code Version: 1.67.2
- C/C++ Extension Version: v1.9.8
- Other extensions you installed (and if the issue persists after disabling them):
- If using SSH remote, specify OS of remote machine: no
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**
2. Open a large C++ project
3. Generate compile_commands.json
4. Create like c_cpp_properties.json
```{
    "configurations": [
        {
            "name": "myproject debug",
            "compilerPath": "/Users/alshamma/dev/myproject/emscripten/em++",
            "compileCommands": "/Users/alshamma/dev/myproject/{more paths segments}/compile_commands.json"
        }
    ],
    "version": 4
}
```
7. Edit code in a C++ files. 
8. Intellisense does not kick in for code completion
9. Some files generate problem output: unable to find include paths
10. Go to definition can take about 15 seconds

**Expected behavior**

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
-------- Diagnostics - 5/27/2022, 4:45:30 PM
Version: 1.9.8
Current Configuration:
{
    "name": "Psweb apollo debug",
    "compilerPath": "/Users/alshamma/dev/emsdk/upstream/emscripten/em++",
    "compileCommands": "/Users/alshamma/dev/photoshop/photoshop/projects/psm/web/web_cmake/Debug_build/compile_commands.json",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "intelliSenseModeIsExplicit": false,
    "compilerArgs": [],
    "mergeConfigurations": false,
    "browse": {
        "limitSymbolsToIncludedHeaders": true
    }
}

[more is in the log with non-public information]

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
```
[{
	"resource": "/Users/alshamma/dev/photoshop/photoshop/dcx_framework/source/dcx_framework.cpp",
	"owner": "C/C++",
	"code": "1696",
	"severity": 2,
	"message": "#include errors detected. Consider updating your compile_commands.json or includePath. IntelliSense features for this translation unit (/Users/alshamma/dev/photoshop/photoshop/dcx_framework/source/dcx_framework.cpp) will be provided by the Tag Parser.",
	"source": "C/C++",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 21
},{
	"resource": "/Users/alshamma/dev/photoshop/photoshop/dcx_framework/source/dcx_framework.cpp",
	"owner": "C/C++",
	"code": "1696",
	"severity": 2,
	"message": "cannot open source file \"math.h\" (dependency of \"/Users/alshamma/dev/photoshop/photoshop/web/webunivheaders/PS_Prefix.h\")",
	"source": "C/C++",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 2,
	"endColumn": 21
},{
	"resource": "/Users/alshamma/dev/photoshop/photoshop/dcx_framework/source/dcx_framework.cpp",
	"owner": "C/C++",
	"code": "1696",
	"severity": 2,
	"message": "cannot open source file \"string\" (dependency of \"dcx_framework.h\")",
	"source": "C/C++",
	"startLineNumber": 6,
	"startColumn": 1,
	"endLineNumber": 6,
	"endColumn": 27
},{
	"resource": "/Users/alshamma/dev/photoshop/photoshop/dcx_framework/source/dcx_framework.cpp",
	"owner": "C/C++",
	"code": "1696",
	"severity": 2,
	"message": "cannot open source file \"string\"",
	"source": "C/C++",
	"startLineNumber": 7,
	"startColumn": 1,
	"endLineNumber": 7,
	"endColumn": 18
},{
	"resource": "/Users/alshamma/dev/photoshop/photoshop/dcx_framework/source/dcx_framework.cpp",
	"owner": "C/C++",
	"code": "1696",
	"severity": 2,
	"message": "cannot open source file \"algorithm\" (dependency of \"PSInlines.h\")",
	"source": "C/C++",
	"startLineNumber": 9,
	"startColumn": 1,
	"endLineNumber": 9,
	"endColumn": 23
},{
	"resource": "/Users/alshamma/dev/photoshop/photoshop/dcx_framework/source/dcx_framework.cpp",
	"owner": "C/C++",
	"code": "1696",
	"severity": 2,
	"message": "cannot open source file \"functional\" (dependency of \"UPSUtilities.h\")",
	"source": "C/C++",
	"startLineNumber": 12,
	"startColumn": 1,
	"endLineNumber": 12,
	"endColumn": 26
},{
	"resource": "/Users/alshamma/dev/photoshop/photoshop/dcx_framework/source/dcx_framework.cpp",
	"owner": "C/C++",
	"code": "1696",
	"severity": 2,
	"message": "cannot open source file \"vector\" (dependency of \"USystemFramework.h\")",
	"source": "C/C++",
	"startLineNumber": 13,
	"startColumn": 1,
	"endLineNumber": 13,
	"endColumn": 30
},{
	"resource": "/Users/alshamma/dev/photoshop/photoshop/dcx_framework/source/dcx_framework.cpp",
	"owner": "C/C++",
	"code": "1696",
	"severity": 2,
	"message": "cannot open source file \"string\" (dependency of \"ZUID.h\")",
	"source": "C/C++",
	"startLineNumber": 76,
	"startColumn": 1,
	"endLineNumber": 76,
	"endColumn": 18
},{
	"resource": "/Users/alshamma/dev/photoshop/photoshop/libapollo/application.cpp",
	"owner": "C/C++",
	"severity": 2,
	"message": "Include file not found in browse.path.",
	"source": "C/C++",
	"startLineNumber": 120,
	"startColumn": 1,
	"endLineNumber": 120,
	"endColumn": 21
}]
```

**Screenshots**

**Additional context**

**Comment by sean-mcmanus** [comment]
It sounds like we're not able to query the `/Users/alshamma/dev/myproject/emscripten/em++` compiler for system includes. Can you set C_Cpp.loggingLevel to "Debug" and open a file and look at the C/C++ pane logging to see if there's a message indicating why compiler querying is failing?

**Comment by alshamma** [comment]
I am seeing this crash
```
textDocument/hover: /Users/alshamma/dev/.../somefile.cpp (id: 9)
IntelliSense process crash detected.
IntelliSense engine is not responding. Using the Tag Parser instead.
using Tag Parser for quick info
IntelliSense process crash detected.
Checking for syntax errors: /Users/alshamma/dev/.../somefile.cpp.cpp
Update IntelliSense time (sec): 0
textDocument/hover: /Users/alshamma/dev/.../somefile.cpps.cpp (id: 10)
Resetting IntelliSense server: /Users/alshamma/dev/.../somefile.cpp.cpp
```

I also see a number of lines like 
```
  tag parsing file: /Users/alshamma/dev/.../someotherfile.hpp
    tag parsing error (this can be ignored unless symbols can't be found):
    line 26 (col. 1): error: expected a file name
```

And several more `IntelliSense process crash detected.` later in the log.

A lot of `Request canceled: 32` as well. E.g., 
```
  intelliSenseMode: linux-clang-x64
Request canceled: 32
cpptools/textEditorSelectionChange
cpptools/getCodeActions: /Users/alshamma/dev/.../somefile.cpp (id: 33)
textDocument/definition: /Users/alshamma/dev/.../somefile.cpp.cpp (id: 34)
terminating child process: 81893
terminating child process: 81894
```

**Comment by sean-mcmanus** [comment]
With the crashes, you're still using 1.9.8, right, and not 1.10.3? There's a known crash issue with older Macs like 10.12 with 1.10.3 that should be fixed with 1.10.4.

The IntelliSense crashes are certainly a bug, but in that case it is not expected to get header not found squiggles, so I'm not sure in which case those are occurring. The tag parser error messages should only effect the Outline and symbols that are found and not the header resolving. In other words, it sounds like you're hitting multiple issues. I don't see logging related to the original issue which appears to be a problem querying the compiler for system includes. If you create a simple file with something like `#include <stddef.h>` maybe the logging will be better and it won't crash?

**Comment by alshamma** [comment]
Yes, still using 1.9.8. 

I took an existing file and replaced it with
```
#include <stddef.h>

void dummy(void) {
    
}
```
I get squiggles on the include, but if I right click and go to definition it actually works. 

But, I also get this message `#include errors detected. Consider updating your compile_commands.json or includePath. IntelliSense features for this translation unit (/Users/alshamma/dev/.../application.cpp) will be provided by the Tag Parser.C/C++(1696)`

**Comment by sean-mcmanus** [comment]
Squiggles on the include mean our IntelliSense engine isn't getting the correct includePath, but the tag parser is being used for the Go to Definition of the header instead. If you run the C/C++: Log Diagnostics command you can see what include paths are being used for IntelliSense, but details on why the compiler querying isn't working would have to be found in the C/C++ logging (if it exists).

**Comment by alshamma** [comment]
I actually get four possible locations for the header file (this is a complex, multi-OS project). I wonder if that is why the squiggles. I do see all of them in the diagnostics.

**Comment by sean-mcmanus** [comment]
The reason you get 4 possible locations is that it's using the tag parser to find the definition, so it's not able to precisely determine which is the 1 real one. If IntelliSense had the correct include path, it would go to the one definition used by IntelliSense (which compiles the specific TU, versus just querying a project-wide database).

**Comment by alshamma** [comment]
Turns out I had a leftover value in the VS Code User Settings which I believe overrode the `compilerPath` in `.vscode/c_cpp_properties.json`.

Intellisense is now working for my project. Thank you!

**Comment by bobbrow** [comment]
Yes, the specific setting was `C_Cpp.default.systemIncludePath`.  We were querying the compiler and getting the correct result system include path, but it was being overridden by that setting.  This would be a good thing to report on in the `Log Diagnostics` command.
