### ISSUE TITLE
Option for tag-parser to not parse files excluded by preprocessor?

### ISSUE THREAD

**Issue by Dromantor** [microsoft/vscode-cpptools#9375]
Short version:
---------------------
- Extension version 1.10.3, 1.9.8 behaves equally.
- Cpptools is configured to `"limitSymbolsToIncludedHeaders": true`.
- Cpptools tag-parses thousands of headers that aren't included because masked by #ifdef-s, causing long running high CPU load on a single core.
- Those header files are in the same folder (most of 'em).
- Compiler is Microchip XC8, a clang derivate, which doesn't work properly with cpptools which may or may not influence all of this.
- Reproduces on a plain W11 VM with just MPLABX, XC8 and VSCode installed, so no fallback compiler available if this was the cause.
- Intellisense cache size is set to 0.
- See c_cpp_properties.json at the end.

Long version:
---------------------
It seems that the tag parser, configured to `"limitSymbolsToIncludedHeaders": true` of course, parses all files found as #include-s even when they are "excluded" by the preprocessor via #ifdef. This may not be that big of a deal with desktop app developement, but when coding microcontroller firmware you quite often have header files that have thousands of lines with stuff like this:
```
--- file: pic_chip_select.h ---
....

#ifdef _12F519
#ifdef _LEGACY_HEADERS
#include <pic12f519_legacy.h>
#undef _HEADER_NOT_FOUND
#else
#include <pic12f519.h>
#undef _HEADER_NOT_FOUND
#endif
#endif

....
```
And usually there is just a single #ifdef that matches your defines and is therefore a single file is really included. The rest is noise.
Cpptools logging looks like this for me:
```
.... more lines above ....
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f18875.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f18876.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f18877.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f19155.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f19156.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f19175.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f19176.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f19185.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f19186.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f19195.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f19196.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f19197.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f1933.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f1934.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f1936.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f1937.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f1938.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f1939.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f1946.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f1947.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f505.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f506_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f506.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f526_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f526.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f527.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f5x_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f54.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f57.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f570.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f59.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f616_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f610.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f616.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f6x_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f627.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f62xa_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f627a.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f628.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f628a.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16630_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f630.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f685_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f631.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f636.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f639.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f648a.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f676.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f677.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f684_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f684.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f685.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f687.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f688_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f688.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f689.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f690.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f707.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f716_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f716.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f7x_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f72.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f720_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f720.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f721_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f721.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\legacy\pic16f72x_legacy.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f722.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f722a.h
  tag parsing file: C:\Microchip\xc8\current\pic\include\proc\pic16f723.h
.... more lines below ....
```
There are 1566 + 189 header files in the two directories (proc + legacy) that you see in the log above. Scanning each file takes approx. 3s on average (some nearly instant, most at average, some >15s). This means cpptools sits at 100% CPU (single core) for ~88min. (calculated, not tested, but for sure >60min) scanning 99.9% useless files.

But all of this this may or may not be caused/influenced by the fact that cpptools cant deal with my compiler (Microchip XC8, clang derivate). I don't know if this changes the way includes are scanned.
(It then uses cl.exe as a fallback, which brings me to another (unrelated) point: Would be great if there was an option to disable this behaviour and just rely on the include paths and defines I set in c_cpp_properties.json, some sort of "no compiler mode". The fallback adds another bunch of useless headers on top because it uses cl.exe's include paths which are irrelevant for my project. This leads to things like autocompleting system header files that aren't even avaliable with XC8, or go to definition going to the wrong file.)

I ran another test in a newly setup VM with just MPLABX, XC8 and VSCode installed. Same behaviour, it just cannot find a fallback compiler, but this doesn't change anything about the scanning.

It does the same thing with XC16 (gcc derivate, detected correctly but no C++ support, so cl.exe fallback for just C++) but there it isn't that bad. Maybe because not all headers are in a single directory and the compiler just returns the correct one for the used device family when queried. So "just" 100-200 files found and scanned instead of almost 2k, resulting in about 10min of parsing, which is easier to ignore.

Is this perhaps by design that every file is parsed, even if excluded by the preprocessor, but no symbols are offered from them, or is this a bug? Or did I perhaps configure something wrong or miss a setting which inhibits the scanning of everything?

My c_cpp_properties.json for reference:
```
{
    "configurations": [
        {
            "name": "XC8",
            "includePath": [
                "${workspaceFolder}/*",
                "C:/Microchip/xc8/current/pic/include/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE",
                "_HAS_INT24",
                "HI_TECH_C",
                "_OMNI_CODE_",
                "__XC",
                "__XC8",
                "__XC8__",
                "__XC__",
                "__PICC__",
                "_16F1705"
            ],
            "compilerPath": "C:/Microchip/xc8/current/bin/xc8-cc.exe",
            "cStandard": "c99",
            "cppStandard": "c++03",
            "intelliSenseMode": "linux-clang-arm",
            "browse": {
                "limitSymbolsToIncludedHeaders": true
            },
            "compilerArgs": [
                "-mcpu=16F1705",
                "-O1",
                "-std=c99"
            ]
        }
    ],
    "version": 4
}
```

Reproduction steps:
- install XC8
- use above configuration, but adjust for your install path
- use following include in a C source file: `#include <xc.h>`

Another small question: On my W10 machine VSCode and cpptools debug output is in English, but on W11 the cpptools output is in German while VSCode is configured to English. Is there a setting or something to switch over cpptools to english there too? Didn't find anything.

Environment details:
- OS: W10 21H2 and W11
- VSCode: 1.67.2

**Comment by Dromantor** [comment]
Didn't have any microcontroller development for the last two months so I totally forgot about this (oops). It can stay closed if any improvement to this isn't a priority.

Just some final notes:
- The faster parsing of headers with lots of defines, as stated in release notes for v1.11.4, did not improve this. Still takes ages even though its mostly defines.
- My proposal for a solution to this, before completely forgetting about it, would have been to add a setting for paths which should not be scanned even if returned by the compiler. But if an included header wasn't found (red error squiggle) these paths would be searched for that file and than only this file is parsed. This way the original indexing function doesn't have to be modified, except for the exclusion of said paths.
- I would really love to be able to disable that damn compiler fallback if the configured compiler doesn't work with the extension. I don't want headers in the autocomplete that do not exist for my target. I'm tempted to just uninstall VS just to have cl.exe gone.

Greetings,
Andreas

**Comment by sean-mcmanus** [comment]
@Dromantor You can use C_Cpp.files.exclude. You can set compilerPath to "".

**Comment by Dromantor** [comment]
1: Not the same since the file that is included and I want to be parsed is never parsed then, so no symbols, i.e. no register names, are autocompleted at all. Could just deactivate the C++ extension then (that's what I did before) or use the vendor IDE \*shudder\*.
Also the updating intellisense flame doesn't go away at all anymore. May have to do with the excluded path (.../pic/include/proc) being a subfolder of the include path (.../pic/include/**).

2: Didn't know that with the compiler path, much thanks.
