### ISSUE TITLE
"Max Concurrent Threads" option not effective, only get two

### ISSUE THREAD

**Issue by shoffmeister** [microsoft/vscode-cpptools#9376]
Bug type: Language Service

**Describe the bug**
- OS and Version: `Linux fedora 5.17.11-300.fc36.x86_64 #1 SMP PREEMPT Wed May 25 15:04:05 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- VS Code Version: 1.67.2
- C/C++ Extension Version: 1.9.8

The extension offers a configuration option `Max Concurrent Threads`, C_Cpp.maxConcurrentThreads. Regardless of the content of that setting (`null` or `8`), the level of _observed_ concurrency appears to be `2`.

With that level of concurrency, "workspace parsing" takes a long time for a large code base - the two "cpptools" processes are quite busy, but I have eight "real" cores at disposal, of which six hence are rather under-utilized. (Leaving aside that this Tiger Lake 11800H CPU has a total 16 thread-level execution units).

The net effect is that it (probably) takes (by far) longer to parse the workspace than possible - unless there is some internal dependencies in the tooling which prevents parallelizing processing through data dependencies.

**Steps to reproduce**

* have vscode with C/C++ extension pack installed, no other config
* `git clone https://github.com/torvalds/linux.git`
* `cd linux`
* `code .`

Inspect the output of command `ps -ef | grep cpptools`

**Expected behavior**

"Many" processes are parsing the workspace files, given the documentation says:

> The maximum number of concurrent threads to use for language service processing. The value is a hint and may not always be used. The default of null (empty) uses the number of logical processors available.

and that my system is 

```
$ lscpu

Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         39 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  16
  On-line CPU(s) list:   0-15
Vendor ID:               GenuineIntel
  Model name:            11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    CPU family:          6
    Model:               141
    Thread(s) per core:  2
    Core(s) per socket:  8
    Socket(s):           1
    Stepping:            1
    CPU(s) scaling MHz:  28%
```

I do appreciate the qualification "value is a hint and may not always be used", but, seriously, I have six underutilized cores and 60 GB of memory available.

**Comment by sean-mcmanus** [comment]
This is currently "by design", although it could be somewhat improved -- you can upvote the pre-existing issue at https://github.com/microsoft/vscode-cpptools/issues/2083 . Even though that issue is marked "more votes needed", it could still be fixed from "unification" work we plan to do which would move the tag parsing work out of process like it is in VS, although the need to synchronize on the database operations to store the parsing results would limit the performance benefit.
