### ISSUE TITLE
C/C++ IntelliSense Go to Definition goes to the wrong definition

### ISSUE THREAD

**Issue by jdskdi2** [microsoft/vscode-cpptools#9380]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 pro, 19043.1706
- VS Code Version: 1.67.2
- C/C++ Extension Version: 1.9.8
- Other extensions you installed (and if the issue persists after disabling them):
 > vim, Makefile Tools ... 
- If using SSH remote, specify OS of remote machine: 
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

**Steps to reproduce**

1. git clone --recursive https://github.com/ThrowTheSwitch/CMock.git
2. Open Folder CMock
3. Open CMock\vendor\unity\examples\example_1\test\TestProductionCode.c
4. Go to definition "TEST_ASSERT_EQUAL" in 23 line
   TEST_ASSERT_EQUAL(0, FindFunction_WhichIsBroken(78));
5. It goes to "#define UNITY_LINE_TYPE" in vendor\unity\src\unity_internals.h

**Expected behavior**
It goes to "#define TEST_ASSERT_EQUAL" in vendor\unity\src\unity.h

**Code sample and logs**

- Code sample

- Configurations in `c_cpp_properties.json`
![image](https://user-images.githubusercontent.com/64671175/171110792-ddb1f201-6786-4e72-b7e3-35ec61096d0f.png)

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
-------- Diagnostics - 2022. 5. 31. 오후 3:56:28
Version: 1.9.8
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPath": "C:\\Program Files\\mingw-w64\\x86_64-8.1.0-win32-seh-rt_v6-rev0\\mingw64\\bin\\gcc.exe",
    "cppStandard": "gnu++14",
    "intelliSenseMode": "windows-gcc-x64",
    "cStandard": "c11",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [],
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\CMock\vendor\unity\examples\example_1\test\TestProductionCode.c ]:
    D:\CMock\vendor\unity\examples\example_1\test\TestProductionCode.c
    D:\CMock\vendor\unity\src\unity_internals.h *
Translation Unit Configurations:
[ D:\CMock\vendor\unity\examples\example_1\test\TestProductionCode.c ]:
    Process ID: 13912
    Memory Usage: 26 MB
    Compiler Path: C:\Program Files\mingw-w64\x86_64-8.1.0-win32-seh-rt_v6-rev0\mingw64\bin\gcc.exe
    Includes:
        C:\PROGRAM FILES\MINGW-W64\X86_64-8.1.0-WIN32-SEH-RT_V6-REV0\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE
        C:\PROGRAM FILES\MINGW-W64\X86_64-8.1.0-WIN32-SEH-RT_V6-REV0\MINGW64\LIB\GCC\X86_64-W64-MINGW32\8.1.0\INCLUDE-FIXED
        C:\PROGRAM FILES\MINGW-W64\X86_64-8.1.0-WIN32-SEH-RT_V6-REV0\MINGW64\X86_64-W64-MINGW32\INCLUDE
        D:\CMOCK\VENDOR\UNITY\EXAMPLES\EXAMPLE_1\SRC
        D:\CMOCK\VENDOR\UNITY\SRC
        D:\CMOCK\VENDOR\UNITY\EXAMPLES
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c11
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --gcc
        --gnu_version=80100
Total Memory Usage: 26 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 2811
Number of files parsed: 332

------- Potential include path issues --------
Some headers exist in multiple locations. If IntelliSense is behaving incorrectly,
try adding one of the alternate paths to the "includePath" in your configuration in
c_cpp_properties.json to override the automatic path discovery for that header.

Using: D:/CMock/vendor/unity/examples/example_1/src/ProductionCode.h
    Alternative: "D:/CMock/vendor/unity/examples/example_2/src"
    Alternative: "D:/CMock/vendor/unity/examples/example_3/src"
    Alternative: "D:/CMock/vendor/unity/examples/example_4/src"

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)

**Screenshots**

![image](https://user-images.githubusercontent.com/64671175/171111433-23b5308a-ad86-4705-8be7-7cf783f75338.png)

go to definition
![image](https://user-images.githubusercontent.com/64671175/171111508-5d8917fb-c0a1-4e7b-9165-b5645b2f1768.png)

go to reference 
![image](https://user-images.githubusercontent.com/64671175/171111642-5d65b3d6-c2dc-413d-a7a1-d5e7b24db419.png)

**Additional context**

**Comment by Colengms** [comment]
Hi @dooGitit .  I believe this issue has been addressed in v1.10.3.  I'm not able to repro with v1.10.3. Could you try selecting `Switch to Pre-Release Version` for the C/C++ extension in the extension marketplace UI in VS Code, and confirm if this issue has been addressed for you?
