### ISSUE TITLE
How to add folders for source code searching (Go-to-definition)?

### ISSUE THREAD

**Issue by semin-park** [microsoft/vscode-cpptools#9381]
I've setup c_cpp_properties.json with include paths and browse.path and it all works fine when the thing I'm looking for is defined in a .h file.

However, when I try to look for a definition that's implemented in a .c file, I'm still redirected to the .h file instead of the .c file.
Is there any configuration that I can override to get me redirected to the source code?

I'm currently doing this with the linux kernel, if that helps. Maybe it's too big? With OpenSSL I didn't have this problem 😛

**Comment by sean-mcmanus** [comment]
If Go to Def isn't going to the definition in the source file, that could be caused by a failure to parse the symbol -- when you open the source file, do you see the symbol in the Outline view?
