### ISSUE TITLE
Key word 'public' not recognized when namespace is involved in class inheritance

### ISSUE THREAD

**Issue by Leedehai** [microsoft/vscode-cpptools#939]
<img width="357" alt="screen shot 2017-08-01 at 21 55 41" src="https://user-images.githubusercontent.com/18319900/28858254-2de54b74-7704-11e7-90ca-ff3a1cabd1a2.png">
Also, class name is not recognized when namespace is involved. I feel regex matching is problematic when "::" is prefixed/suffixed.

**Comment by sean-mcmanus** [comment]
This seems like bug https://github.com/atom/language-c/issues/81 . All of the C++ syntax issues are implemented/fixed at that repository.
