### ISSUE TITLE
CompactNamespaces Not Working

### ISSUE THREAD

**Issue by garbles9100** [microsoft/vscode-cpptools#9391]
I have CompactNamespaces set to true in my .clang-format file and it seemingly is not doing what the documentation says it will do.

According to this [rule](https://clang.llvm.org/docs/ClangFormatStyleOptions.html#:~:text=FOOBAR%20pragma%3A%20keep-,CompactNamespaces,-(Boolean)),
having CompactNamespaces set to true should try to put all of the namespace declarations on the same line.

What I am seeing is that if I have put all of the namespaces on the same line then pressing Alt+Shift+F will keep them on the same line. But if the namespaces are not on the same line then pressing Alt+Shift+F formats the namespaces the way shown for CompactNamespaces set to false, putting either all or some of them on a new line.

What I expected to see was if the namespaces were on different lines then pressing Alt+Shift+F moves all of the namespaces to the same line.

My ColumnLimit is set to 0 so I do not expect them to wrap.

Here is my .clang-format file:
BasedOnStyle: LLVM
UseTab: Never
IndentWidth: 4
TabWidth: 4
BreakBeforeBraces: Custom
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
ColumnLimit: 0
CompactNamespaces: true
AccessModifierOffset: -4
NamespaceIndentation: All
FixNamespaceComments: false
SeparateDefinitionBlocks: Always
BraceWrapping:
  AfterCaseLabel: false
  AfterClass: true
  AfterControlStatement: Always
  AfterEnum: true
  AfterFunction: true
  AfterNamespace: false
  AfterObjCDeclaration: true
  AfterStruct: true
  AfterUnion: true
  AfterExternBlock: true
  BeforeCatch: true
  BeforeElse: true
  BeforeLambdaBody: true
  BeforeWhile: false
  IndentBraces: false
  SplitEmptyFunction: false
  SplitEmptyRecord: false
  SplitEmptyNamespace: false

**Comment by sean-mcmanus** [comment]
Is this a bug with clang-format itself or a bug in our extension's handling of it?

What is a repro code example? i.e.
```cpp
namespace Foo {
namespace Bar {
}
}
```
or what?

**Comment by sean-mcmanus** [comment]
Also, with C_Cpp.loggingLevel set to "Debug" do you get a clang-format failed message in the C/C++ logging pane?

**Comment by sean-mcmanus** [comment]
@garbles9100 Specifically, I get a failure due to
```
BraceWrapping:
AfterCaseLabel: false
```
in the .clang-format file.

**Comment by garbles9100** [comment]
> BasedOnStyle: LLVM
> UseTab: Never
> IndentWidth: 4
> TabWidth: 4
> BreakBeforeBraces: Custom
> AllowShortIfStatementsOnASingleLine: false
> IndentCaseLabels: false
> ColumnLimit: 0
> CompactNamespaces: true
> AccessModifierOffset: -4
> NamespaceIndentation: All
> FixNamespaceComments: false
> SeparateDefinitionBlocks: Always
> BraceWrapping:
> AfterCaseLabel: false
> AfterClass: true
> AfterControlStatement: Always
> AfterEnum: true
> AfterFunction: true
> AfterNamespace: false
> AfterObjCDeclaration: true
> AfterStruct: true
> AfterUnion: true
> AfterExternBlock: true
> BeforeCatch: true
> BeforeElse: true
> BeforeLambdaBody: true
> BeforeWhile: false
> IndentBraces: false
> SplitEmptyFunction: false
> SplitEmptyRecord: false
> SplitEmptyNamespace: false

I wonder if the lack of indentation is messing it up. It should look like this:
BasedOnStyle: LLVM
UseTab: Never
IndentWidth: 4
TabWidth: 4
BreakBeforeBraces: Custom
AllowShortIfStatementsOnASingleLine: false
IndentCaseLabels: false
ColumnLimit: 0
CompactNamespaces: true
AccessModifierOffset: -4
NamespaceIndentation: All
FixNamespaceComments: false
SeparateDefinitionBlocks: Always
BraceWrapping:
  AfterCaseLabel: false
  AfterClass: true
  AfterControlStatement: Always
  AfterEnum: true
  AfterFunction: true
  AfterNamespace: false
  AfterObjCDeclaration: true
  AfterStruct: true
  AfterUnion: true
  AfterExternBlock: true
  BeforeCatch: true
  BeforeElse: true
  BeforeLambdaBody: true
  BeforeWhile: false
  IndentBraces: false
  SplitEmptyFunction: false
  SplitEmptyRecord: false
  SplitEmptyNamespace: false

**Comment by sean-mcmanus** [comment]
Yeah, making the indentation correct fixes the failure I was seeing. The results you're getting are from clang-format itself, so it's either "by design" or a bug with clang-format. Removing the ColumnLimit: 0 fixes it, so it might be an issue with that, it says "A column limit of 0 means that there is no column limit. In this case, clang-format will respect the input’s line breaking decisions within statements unless they contradict other rules.". You could try filing a bug at https://github.com/llvm/llvm-project/issues and see what they say.

**Comment by garbles9100** [comment]
> Yeah, making the indentation correct fixes the failure I was seeing. The results you're getting are from clang-format itself, so it's either "by design" or a bug with clang-format. Removing the ColumnLimit: 0 fixes it, so it might be an issue with that, it says "A column limit of 0 means that there is no column limit. In this case, clang-format will respect the input’s line breaking decisions within statements unless they contradict other rules.". You could try filing a bug at https://github.com/llvm/llvm-project/issues and see what they say.

Okay. Thank you!
