### ISSUE TITLE
Can not parse symbols

### ISSUE THREAD

**Issue by qwetqwe** [microsoft/vscode-cpptools#9394]
Bug type: Language Service

**Describe the bug**
- OS and Version: Ubuntu 18.04
- VS Code Version:1.67.2
- C/C++ Extension Version: 1.9.8
- Other extensions you installed (and if the issue persists after disabling them): c++ extension pack
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
If I include *pb.h and <condition_variable> , IntelliSense can not parse my class. But if I remove either of them, it works, I don't know whether the issue is related with my system env
Here is my repro sample code test:
![Kazam_screenshot_00065](https://user-images.githubusercontent.com/30464144/171782107-db46b6a4-2a3b-4c86-84cc-84f5d9060e60.png)
![Kazam_screenshot_00066](https://user-images.githubusercontent.com/30464144/171782127-196f3471-445e-4966-9d5d-19e6c09a9db7.png)
![Kazam_screenshot_00067](https://user-images.githubusercontent.com/30464144/171782130-00a2587a-b21e-4f98-8079-0340758d6bd1.png)

**Expected behavior**

It can always work well

**Code sample and logs**

- Code sample
[test.zip](https://github.com/microsoft/vscode-cpptools/files/8829376/test.zip)

- Configurations in `c_cpp_properties.json`
default
- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
-------- Diagnostics - 2022/6/3 11:48:37
Version: 1.9.8
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "/usr/bin/gcc",
    "cStandard": "gnu11",
    "intelliSenseMode": "linux-gcc-x64",
    "compilerArgs": [],
    "cppStandard": "c++14",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": true,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/apollo/文档/test/dd.h ]:
    /home/apollo/文档/test/dd.h
    /home/apollo/文档/test/pointcloud.pb.h *
Translation Unit Configurations:
[ /home/apollo/文档/test/dd.h ]:
    Process ID: 26442
    Memory Usage: 73 MB
    Compiler Path: /usr/bin/gcc
    Includes:
        /usr/include/c++/7
        /usr/include/x86_64-linux-gnu/c++/7
        /usr/include/c++/7/backward
        /usr/lib/gcc/x86_64-linux-gnu/7/include
        /usr/local/include
        /usr/lib/gcc/x86_64-linux-gnu/7/include-fixed
        /usr/include/x86_64-linux-gnu
        /usr/include
    Standard Version: c++14
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=70500
        --header_only_fallback
Total Memory Usage: 73 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 17901

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
Queueing IntelliSense update for files in translation unit of: /home/apollo/文档/test/dd.h
sending 1 changes to server
cpptools/finishUpdateSquiggles
Error squiggle count: 1
Update IntelliSense time (sec): 2.252
cpptools/getFoldingRanges: /home/apollo/文档/test/dd.h (id: 374)
cpptools/textEditorSelectionChange
cpptools/getCodeActions: /home/apollo/文档/test/dd.h (id: 375)
idle loop: reparsing the active document
Checking for syntax errors: /home/apollo/文档/test/dd.h
Queueing IntelliSense update for files in translation unit of: /home/apollo/文档/test/dd.h
cpptools/finishUpdateSquiggles
Error squiggle count: 17
Update IntelliSense time (sec): 0.369
cpptools/getSemanticTokens: /home/apollo/文档/test/dd.h (id: 376)
cpptools/getFoldingRanges: /home/apollo/文档/test/dd.h (id: 377)
cpptools/getCodeActions: /home/apollo/文档/test/dd.h (id: 378)
cpptools/getDiagnostics (id: 379)
terminating child process: 6513
terminating child process: 6520
cpptools/textEditorSelectionChange
cpptools/activeDocumentChange: /home/apollo/文档/test/dd.h

**Comment by sean-mcmanus** [comment]
What do you mean by "IntelliSense can not parse my class"? What is the exact error you are seeing? Does the issue repro if you set C_Cpp.intelliSenseCacheSize to 0? Does the bug repro with 1.10.3 (pre-release)? Your sample project seems to require protobuf?

**Comment by qwetqwe** [comment]
@sean-mcmanus 
the members in class DetectionComponent can not be parsed, it can not be colorsized(always white).If I use this member ,it can not autocomplete
Does the issue repro if you set C_Cpp.intelliSenseCacheSize to 0? 
yes
Does the bug repro with 1.10.3 (pre-release)?
yes
Your sample project seems to require protobuf?
yes, I want to autocomplete api in protobuf. And I have added pb.h files in include path

**Comment by qwetqwe** [comment]
It seems there is no protobuf lib in my env.
If included header file parse failed, origin file may parse failed or not. Is it right?

**Comment by sean-mcmanus** [comment]
@qwetqwe Sorry, I'm not understanding what you're asking. IntelliSense needs to have the protobuf headers in order to compile that particular TU, otherwise, parsing errors are expected.
