### ISSUE TITLE
Sym links not followed for includes on Linux 

### ISSUE THREAD

**Issue by Jevyn** [microsoft/vscode-cpptools#94]
Due to needing different structures for different versions, I used Linux symbolic links to link to the correct header.  These links are not being followed, causing the green squiggle to appear under the header in the gui.

Example to reproduce:

Some C file contains #include "version.h"

On the OS, version.h is a sym link to version_5.h
A squiggle will appear under version.h, even if I add this directory explicitly to the includes path.

Note that the build works fine (make/gcc), this is just a gui bug.

**Comment by jgoshi** [comment]
This just got fixed (but will not make it into the upcoming release 0.9.0). It will appear in the following release (no guarantees but we try to release monthly).
