### ISSUE TITLE
Function navigation not list all functions

### ISSUE THREAD

**Issue by Grizzbear** [microsoft/vscode-cpptools#940]
- Information
Platform: windows 7
VSCode: 1.14.2
cpptools: 0.12.1
encode: GBK(Chinese characters used)

- Issue 
I can't see all of my functions in the function navigation view.  And if there is one function not showing on the function list, the rest after this one will not show. After some experiment, I found if I reapeatly use LOG(a function in my project) in a function, then this function could possibly disappear in the navigation view. It's very strange that the function would not disappear on the first LOG, nor the sencond, but after several LOGs. I can't locate the problem. Here is the defination of LOG:
```
#define LOG(...)  LOGA("I", __VA_ARGS__)
#define LOGA(flag, ...)\
do{\
sprintf(something);\
...\
}while(0)
```
This function just prints some log information.

- Tried
1. delete the .browse.vc.db; 
2. rewrite the function disappeared; 
3. reorder  functions.
4. **print English characters instead of Chinese characters in the LOG function**: this works, the function showed. 
5. change vscode default encoding to GBK/UTF-8/GB18030 and disable encoding auto-guess.

I guess it's the encoding issue. But still I can't solve this. I'm wondering how you guys parsing functions to the navigation view. Hopefully you could offer some solutions.

**Comment by Grizzbear** [comment]
- update
I figure out a way to reproduce this error. 
1. create a cpp file, and change encoding type to GBK.
2. write a funtion, just print enough Chinese characters. for example,
```
int a(){
printf("随便写点什么中文");
printf("随便写点什么中文");
printf("随便写点什么中文");
... //repeat
}
```
In my enviroment, function a() disappear when I repeat 111 times of the printf. Now I'm sure it's a encoding issue, because if I save this file with UTF-8, everything will be OK. Is it a vscode issue or a cpptool issue? If it's a vscode issue, could you offer some workaround because I have to use GBK in my work. Thanks in advance!

**Comment by sean-mcmanus** [comment]
The cpptools extension doesn't really support the GBK encoding yet. Same issue as https://github.com/Microsoft/vscode-cpptools/issues/806 .

**Comment by Grizzbear** [comment]
Thx.  So I guess I could do nothing but waiting for GBK support comming?

**Comment by sean-mcmanus** [comment]
You could try using VS 2017 Community edition. We're working on porting code from there that might get us GBK support (I think they do some conversion from GBK to another encoding).

**Comment by Grizzbear** [comment]
I'll take a try. Thanks for your reply 👍
