### ISSUE TITLE
Add debugging support for memory viewer and disassembly code (including instruction stepping).

### ISSUE THREAD

**Issue by xdante** [microsoft/vscode-cpptools#941]
Add debugging support for memory viewer and disassembly code (including instruction stepping).

**Comment by alanjmcf** [comment]
I guess a workaround for memory display, is to -exec the gdb x command in the Debug Console

e.g. to see 16 bytes in hex
`-exec x/16x 0x7fffffffc186`

![screenshot from 2018-01-27 15-08-33](https://user-images.githubusercontent.com/26221920/35473186-11705b94-0374-11e8-89a0-62b37a77d967.png)

**Comment by f3rm4rf3r** [comment]
Is this in the roadmap for this extension?

**Comment by princehektor** [comment]
@pieandcakes : Has this feature been added in the latest extension version ?

**Comment by pieandcakes** [comment]
@princehektor No, this has not been implemented.

**Comment by ci70** [comment]
Why not?

**Comment by ohoroyoi** [comment]
still not?

**Comment by gerekon** [comment]
Would be nice feature

**Comment by pieandcakes** [comment]
Duplicate of #206 (assembly) and #509 (memory)

**Comment by aneox** [comment]
Would be nice feature

**Comment by jihuacao** [comment]
-exec does not work in cppvsdbg.
