### ISSUE TITLE
Support C99 VLAs in error checker

### ISSUE THREAD

**Issue by trond-snekvik** [microsoft/vscode-cpptools#942]
The syntax checker reports an error when coming across variable length arrays in C99 code, although this is valid code.

## Reproducing:

This is [the VLA example from Wikipedia](https://en.wikipedia.org/wiki/Variable-length_array). For this piece of code, the C/C++ plugin marks the `n` in the array declaration with a red squiggly line, and reports `expression must have a constant value`.

```C
float read_and_process(int n)
{
    float vals[n];

    for (int i = 0; i < n; i++)
        vals[i] = read_val();
    return process(n, vals);
}
```

**Comment by imba-tjd** [comment]
Well, I don't have this problem. Maybe you need to give more information.
![qq 20170804214504](https://user-images.githubusercontent.com/24759802/28971534-e6929832-795e-11e7-8a42-d8a408a935dd.png)

**Comment by trond-snekvik** [comment]
Yes, that's quite odd. 

This is my version in a clean folder (made a new folder, opened it in vscode, made a new C file, pasted the code and pressed save): 
![image](https://user-images.githubusercontent.com/7857838/28972108-b715e472-792e-11e7-90c8-46994f173648.png)

I've also tried disabling all other extensions, same result.

This is the default configuration I get when I run the "Edit Configurations" command:

```
    {
            "name": "Win32",
            "includePath": [
                "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10150.0/um",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10150.0/ucrt",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10150.0/shared",
                "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10150.0/winrt",
                "${workspaceRoot}"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE"
            ],
            "intelliSenseMode": "msvc-x64",
            "browse": {
                "path": [
                    "C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/include/*",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10150.0/um",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10150.0/ucrt",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10150.0/shared",
                    "C:/Program Files (x86)/Windows Kits/10/Include/10.0.10150.0/winrt",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
```

Note that it's fetching Visual Studio 14.0 paths, and using Windows kit 10.0.10150.0. I'm on a Windows 7 x64, C/C++ plugin version is 0.12.2. This is my VSCode version output:

![image](https://user-images.githubusercontent.com/7857838/28972300-76301cec-792f-11e7-9e03-ebc09c21dfd3.png)

**Comment by imba-tjd** [comment]
That's it. Even VS 15 doesn't support VLA. If you want to use this feature, you can use MinGW-w64.

**Comment by bobbrow** [comment]
@trond-snekvik, can you open a separate issue for the Windows SDK selection?  I'd like to keep this issue focused on the C99 VLA feature.

Our IntelliSense engine is compiling for C11 and VLA is optional in that spec.  
![novla](https://user-images.githubusercontent.com/12818240/28977748-2d5ad4a8-78f8-11e7-97a5-48c3b2b39060.png)

However, I do see that VS 2017 also does not show VLA support **and** it doesn't show `__STDC_NO_VLA__` as defined, so I'm not sure which spec they are compiling against.  I'm working on finding that out, but I think the core request here is going to be that you would like to choose which spec IntelliSense compiles against (similar to C++ coders wanting to choose c++11 vs c++14 vs c++17).

**Comment by sean-mcmanus** [comment]
This bug should be fixed now, right? If not, please provide more info, such as the OS and compilerPath setting used.

**Comment by trond-snekvik** [comment]
Yes, this is now solved, thank you!
