### ISSUE TITLE
C++ debugging in mac M1 terminal for cin/cout, breakpoints do not work

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#9426]
### Discussed in https://github.com/microsoft/vscode-cpptools/discussions/9395

<div type='discussions-op-text'>

<sup>Originally posted by **prabhavagrawal7** June  2, 2022</sup>
I am a competitive programmer so I need to debug .cpp files when available, but C/C++ debugger doesn't help me out as I need terminal for cin/cout which is not available with the extension idk why?
Good thing I found an alternative codeLLDB but the thing is, sometimes it runs for the breakpoints even you didn't have provided input in terminal. 
What should I do now?</div>

Debugger logs available from discussion in https://github.com/microsoft/vscode-cpptools/discussions/9395

**Comment by michelleangela** [comment]
@prabhavagrawal7 Could you provide your macOS version?

**Comment by prabhavagrawal7** [comment]
<img width="612" alt="image" src="https://user-images.githubusercontent.com/55106161/172697300-cddfce80-d87e-42c7-aa79-b7edbe58dc63.png">

**Comment by prabhavagrawal7** [comment]
**MacOS** Monterey
**Version 12.4**
**MacBook Air (M1, 2020)**
**Chip** Apple M1
**Memory** 8 GB

**Comment by WardenGnaw** [comment]
From the logs, no breakpoints were provided by the VS Code client, the only breakpoint hit was the one the debugger uses for stopping at the entrypoint (`main`).

Can you share a gif or video of the client showing that a breakpoint was sent in the client UI and also share the engine logs. This may be a bug in VS Code.

**Comment by prabhavagrawal7** [comment]
Ig, this will help you
https://user-images.githubusercontent.com/55106161/172835637-540a7490-c380-4ebe-aa17-3335632d886e.mov

**Comment by prabhavagrawal7** [comment]
This is the code I've used
```
#include <bits/stdc++.h>
using namespace std;
#define ll long long

// ordered set
// #include <ext/pb_ds/assoc_container.hpp>
// #include <ext/pb_ds/tree_policy.hpp>
// using namespace __gnu_pbds;
// #define ordered_set tree<int, null_type, less<int>, rb_tree_tag, tree_order_statistics_node_update>

// Uncomment them for optimisations
//#pragma GCC optimize("Ofast")
//#pragma GCC target("avx,avx2,fma")

// for segment tree
// #define mid (start+end)/2
// #define lnode (node*2+1)
// #define rnode (node*2+2)
#define popcount(x) __builtin_popcount(x)
#define GET_MACRO(_1, _2, _3, _4, NAME, ...) NAME
#define range(...) GET_MACRO(__VA_ARGS__, r4, r3, r2, r1) \
(__VA_ARGS__)
#define r4(var, start, stop, step) for (ll var = start; step >= 0 ? var < stop : var > stop; var = var + step)
#define r3(var, start, stop) for (ll var = start; var < stop; var++)
#define r2(var, stop) for (ll var = 0; var < stop; var++)
#define r1(stop) for (ll start_from_0 = 0; start_from_0 < stop; start_from_0++)
#define newint(...) \
	ll __VA_ARGS__; \
	take_input(__VA_ARGS__)
#define min(...) min({__VA_ARGS__})
#define max(...) max({__VA_ARGS__})
#define give(...)           \
	{                       \
		print(__VA_ARGS__); \
		return;             \
	}
#define endl "\n"
#define FULL_INF numeric_limits<double>::infinity()
#define INF INT64_MAX
#define INT_INF INT32_MAX
#define ld long double
#define V vector
#define P pair
#define S set
#define MS multiset
#define M map
#define UM unordered_map
#define US unordered_set
#define MM multimap
#define mt make_tuple
#define mp make_pair
#define pb push_back
#define pf push_front
const ll mod = 1000000007;
// const ll mod = 998244353;
#define FAST ios_base::sync_with_stdio(0), cin.tie(0), cout.tie(0);
#define all(a) a.begin(), a.end()
#define db(x) cout << #x << " = " << x << "\n"
string db_bin(ll n)
{
	string ans;
	while (n)
	{
		ans.push_back((n & 1) + '0');
		n >>= 1;
	}
	reverse(all(ans));
	return ans;
}
#define newstring(str) \
	string str;        \
	cin >> str;
#define foreach(a, x) for (auto &&a : x)
const ld pi = acos(-1);
typedef vector<string> vs;
typedef pair<ll, ll> pii;
typedef vector<ll> vi;
typedef map<ll, ll> mii;
typedef set<ll> si;
typedef vector<vector<ll>> vvi;
template <typename... T>
void take_input(T &&...args) { ((cin >> args), ...); }
vi inputvec(ll n, ll start = 0)
{
	vi vec(n);
	range(i, start, n) cin >> vec[i];
	return vec;
}
template <typename T>
bool btn(T a, T b, T c)
{
	if ((a <= b && b <= c) || (a >= b && b >= c))
		return true;
	return false;
}
template <typename T>
ostream &operator<<(ostream &os, const V<T> &v)
{
	for (int i = 0; i < v.size(); ++i)
	{
		os << v[i];
		if (i != v.size() - 1)
			os << " ";
	}
	return os;
}
template <typename _A, typename _B>
ostream &operator<<(ostream &os, const pair<_A, _B> &p)
{
	os << "[" << p.first << ", " << p.second << "]";
	return os;
}
template <typename... T>
void print(T &&...args)
{
	((cout << args << " "), ...);
	cout << endl;
}
template <typename... T>
void printl(T &&...args) { ((cout << args << " "), ...); }
inline ld TLD(ll n) { return n; }
ll gcd(ll __m, ll __n) { return __n == 0 ? __m : gcd(__n, __m % __n); }
inline ll rs(ll n) { return (n = n % mod) >= 0 ? n : n + mod; }
ll power(ll x, ll y)
{
	ll res = 1;
	while (y)
	{
		if (y & 1LL)
			res = (res * x) % mod;
		y >>= 1;
		x = (x * x) % mod;
	}
	return res % mod;
}

/* -------------------------------------------------------------------------------------------------------------------------------------------------------- */

void func()
{
	newint(n); 
	n = n + 1; 
	print(n); 
}
int main()
{
	// Uncomment for faster I/O
	// FAST;
	newint(t);
	range(t)
	{
		func();
	}
}

```

**Comment by prabhavagrawal7** [comment]
Uploading Screen Recording 2022-06-09 at 4.57.16 PM.mov…

Here I have did the same thing, with very simple code. Hope it helps

**Comment by prabhavagrawal7** [comment]
Here I have did the same with simpler code, hope it helps

https://user-images.githubusercontent.com/55106161/172836708-c296db90-70e9-492f-ad59-9c80b2fce598.mov

**Comment by WardenGnaw** [comment]
The launch.json in the provided discussion does not use the provided task. How are you building your binary?

**Comment by prabhavagrawal7** [comment]
Oh yes, maybe I should add prelaunchtask in launch.json

**Comment by prabhavagrawal7** [comment]
After, correcting preLaunchTask, it now works fine for me. Although if it would be internal terminal, it would be a lot better experience.

**Comment by prabhavagrawal7** [comment]
@WardenGnaw Why integrated console doesn't works out in mac os? Is there any bug or some other problem?

**Comment by luisfernandomoraes** [comment]
@WardenGnaw still integrated terminal doesn't work for Mac M1?

**Comment by prabhavagrawal7** [comment]
I didn't check that, for now I am using [codeLLDB](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) extension.

**Comment by mohammadazeemwani** [comment]
> [@luisfernandomoraes](https://github.com/luisfernandomoraes) You can use [codeLLDB](https://marketplace.visualstudio.com/items?itemName=vadimcn.vscode-lldb) extension.

This is the way..
