### ISSUE TITLE
cpptools taking 100% cpu of one core when expected to be idle

### ISSUE THREAD

**Issue by indirectlylit** [microsoft/vscode-cpptools#9428]
- Bug type: Language Service
- OS and Version: macOS 12.3
- Remote SSH docker container: ARM64 system running Ubuntu 18.04
- VS Code Version:  1.67.2 
- C/C++ Extension Version: v1.10.4
- No other extensions installed

`cpptools` is taking 100% of one core of the CPU. This only seems to happen when vscode reports that it is _not_ currently parsing files: it happens when parsing is at 0% or 99%.

Reloading causes the workspace to re-parse the files, during which time the CPU load is spread across all cores. Then once the files have finished parsing a single core pegs to 100% again.

Let me know if there's anything I can investigate to help narrow the cause.

**Comment by sean-mcmanus** [comment]
When you set C_Cpp.loggingLevel to "Debug" what file is the last one logged with a "tag parsing" message? It's possible our parser is getting stuck in some parsing loop...we may have at least one existing issue like that but I don't seem to be able to locate it. You may be able to workaround that via adding the path to that file to C_Cpp.files.exclude, although you won't get symbols for that file.

If you attach a debugger to the cpptools you should be able to get a call stack -- most of the threads will be irrelevant, but you should see one bigger thread that appears to be doing parsing work: see https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv

**Comment by indirectlylit** [comment]
> When you set C_Cpp.loggingLevel to "Debug" what file is the last one logged with a "tag parsing" message? 

It is not consistent. As far as I can tell, the issue is not associated with a specific file. It also seems to be intermittent, in that it will only start happening after some usage, not immediately.

>  It's possible our parser is getting stuck in some parsing loop

This would surprise me because the issue only seems to happen when vscode reports that it is _not_ currently parsing files.

> If you attach a debugger to the cpptools you should be able to get a call stack 

I tried following the instructions given in the link but was not able to get the `(gdb) Attach` launch config to display. It says to "Create or edit .vscode/launch.json". For a remote session should that actually be `~/.vscode-server/launch.json`?

I put a file there and edited with the absolute path to `cpptools`  in `program`, and reloaded VS Code. However I don't see the launch config as expected:

![image](https://user-images.githubusercontent.com/2367265/172735422-464bb2e0-d649-426d-b4b3-cd02d1208505.png)

**Comment by sean-mcmanus** [comment]
Oh, I thought it was getting stuck at 96-99% of parsing files. If there's no database icon showing then it's not tag parsing files.

Once you have a launch.json file, there should be an "Add Configuration" button that appears in the bottom right that has a (gdb) Attach option available.

**Comment by indirectlylit** [comment]
> If you attach a debugger to the cpptools you should be able to get a call stack

Here's the stack trace of the offending thread:

```
code_store::CEncParseNode::InsertInTree(code_store::CEncParseNode*, int) (Unknown Source:0)
code_store::CEncEditScript::ProcessNodeFromTree2(code_store::CEncParseNode*) (Unknown Source:0)
code_store::CEncEditScript::ProcessTreePreOrder(code_store::CEncParseNode*, std::function<bool ()> const&) (Unknown Source:0)
code_store::CEncEditScript::ProcessTreePreOrder(code_store::CEncParseNode*, std::function<bool ()> const&) (Unknown Source:0)
code_store::CEncEditScript::ProcessTreePreOrder(code_store::CEncParseNode*, std::function<bool ()> const&) (Unknown Source:0)
code_store::CEncEditScript::Execute(std::function<bool ()> const&) (Unknown Source:0)
code_store::CEncRudeEditEngine::ComputeParseTreeEdits(std::shared_ptr<code_store::CEncParseTree> const&, std::shared_ptr<code_store::CEncParseTree> const&, std::function<bool ()> const&) (Unknown Source:0)
code_store::a_store_file_il::impl::diff_changes(code_store::an_il_scope*, unsigned long&, unsigned long&, std::deque<std::pair<code_store::a_record_id<code_store::an_item_tag>, code_store::a_code_item_kind>, std::allocator<std::pair<code_store::a_record_id<code_store::an_item_tag>, code_store::a_code_item_kind> > >&, code_store::a_store_event_listener&, std::shared_ptr<std::deque<std::shared_ptr<code_store::CEncEdit>, std::allocator<std::shared_ptr<code_store::CEncEdit> > > >&) (Unknown Source:0)
code_store::a_store_file_il::update_store(code_store::a_store_event_listener*) (Unknown Source:0)
parser::update_file_if_needed(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, bool, code_store::a_record_id<code_store::a_file_tag>&, bool) (Unknown Source:0)
browse_engine::parse_file(unsigned long, char const*, code_store::a_record_id<code_store::a_file_tag> const&, std::unordered_set<code_store::a_record_id<code_store::a_file_tag>, std::hash<code_store::a_record_id<code_store::a_file_tag> >, std::equal_to<code_store::a_record_id<code_store::a_file_tag> >, std::allocator<code_store::a_record_id<code_store::a_file_tag> > >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&, parser&, std::function<void ()>&&, std::shared_ptr<include_paths> const&, bool) (Unknown Source:0)
browse_engine::parse_root() (Unknown Source:0)
vscode::message_handler::parse_root(bool) (Unknown Source:0)
std::_Function_handler<void (), vscode::message_handler::main_loop()::$_6>::_M_invoke(std::_Any_data const&) (Unknown Source:0)
msvc::thread_helper_t::thread_entry(void*) (Unknown Source:0)
libpthread.so.0!start_thread (Unknown Source:0)
libc.so.6![Unknown/Just-In-Time compiled code] (Unknown Source:0)
```

ref thread ID 485:

| htop | vscode |
|--|--|
| ![image](https://user-images.githubusercontent.com/2367265/172948984-9cd8113f-6f16-4d11-8326-32fd9fe61c0a.png) | ![image](https://user-images.githubusercontent.com/2367265/172949082-ffa40d1d-2463-404c-aec5-6fd9a1c6d194.png) |

**Comment by sean-mcmanus** [comment]
Yeah, that is a commonly hit known issue https://github.com/microsoft/vscode-cpptools/issues/6454 . You should upvote that or add upvotes/comments to the issue in VS at https://developercommunity.visualstudio.com/t/updating-cc-intellisense-and-browsing-information-1/1263948 .

**Comment by sean-mcmanus** [comment]
@indirectlylit Also, the VS teams says they might be able to fix it in their next development cycle, although I don't know if they're schedule will change, but at least it seems to be on their radar.

**Comment by sean-mcmanus** [comment]
...and if you're interested, it's done with actual parsing, but stuck doing some diff processing during the database updating, which we just consider as "parsing" still.

**Comment by sean-mcmanus** [comment]
@indirectlylit And the current recommended workaround is to add the folders with the files with large amounts of `#defines` to C_Cpp.files.exclude. Those files should be output in the logging.

**Comment by indirectlylit** [comment]
Hi, thanks for the information.

> add the folders with the files with large amounts of #defines to C_Cpp.files.exclude. Those files should be output in the logging

I did identify a particularly enormous file which lived in an external dependency – [this 9MB cpp file](https://github.com/wolfpld/tracy/blob/master/server/TracyMicroArchitecture.cpp).

That said, the extension appears to be eagerly tag parsing far more than it needs to: I see over 5000 files parsed and only a small fraction of them are `#include`d in my code. Most of them are files made available through external dependency `CMakeLists.txt` configurations, and it would be a huge chore to manually exclude sub-directories of external dependencies.

It seems like a major performance issue to be eagerly parsing every file made available from the CMake config.

**Comment by indirectlylit** [comment]
With some aggressive use of `exclude` (e.g. most sub-directories of `/usr/include` I was able to reduce the number of files from ~5000 to under 100.

**Comment by sean-mcmanus** [comment]
Yeah, in the future we may change it to not recursively do symbol parsing on the system include paths like /usr/include by default, and/or improve it to only parse the headers that are actually used (currently, it's just filename based so it may for example pick up g++ 10 headers when only g++ 11 headers are in use).

**Comment by sean-mcmanus** [comment]
This fix is available with 1.11.2 (pre-release): https://github.com/microsoft/vscode-cpptools/releases

**Comment by indirectlylit** [comment]
thank you!

Do you happen to know whether the fix addresses just the "large file with many defines" case, or if it prunes the parsed header files to only parse those actually used?

**Comment by sean-mcmanus** [comment]
The fix was in the database diffing code for a file with large defines, not pruning of parsing headers to those actually used.

**Comment by sean-mcmanus** [comment]
Yes, files.exclude would still be useful to reduce parsing. That issue is being tracked by https://github.com/microsoft/vscode-cpptools/issues/5257.

**Comment by indirectlylit** [comment]
thank you! I'll add a note there
