### ISSUE TITLE
Auto-Completion not listing the member function in the class properly

### ISSUE THREAD

**Issue by KKyang** [microsoft/vscode-cpptools#943]
While I was using auto-completion in vscode in Ubuntu 16.04, I always have to copy the function name by myself because auto-completion never shows the function unless I nearly type the complete name of the function.

For example I have a class A with a function ``ThisIsAFunction``, and I want to use it in ``main.cpp``. I'll have to type until half (something like ``ThisIsAFunct``) or more of the function, then the plugin will pop out the candidate in the auto-completion list. Another issue is that auto-completion usually pops out lots of std functions in the list. Is it possible to make the plugin pops out the keywords in the priority of **this cpp**->**the .h corresponding to this cpp**->**the source code of this project**->**the 3rdparty lib called from the source code**->**others**?

**Comment by sean-mcmanus** [comment]
When you type less characters like "This" do you get a popup with lots of results or no popup? Is it just slow to appear? We have a 1000 result limit, so if "This" is returning >1000 results, then "ThisIsAFunction" might not appear in the list until you provide more characters. We can increase the 1000 limit to something greater like 10000 probably.

I don't understand why std functions appearing in the list is a problem. I think we sort alphabetically. Other types of sorting might have issues.

**Comment by KKyang** [comment]
When I type "This" I get lots of results in vscode, but in Visual Studio 2013, 2015, they don't return non class member answers. <s>For example, I wrote my own class ``class A`` with a function ``ThisIsAFunction``, Visual Studio should only show ''ThisIsAFunction'' when I type dot because this is the only option I get for my class instead of popping all the functions in the C++ library.</s>

![27](https://user-images.githubusercontent.com/2676255/28947331-d035553e-78e1-11e7-8fa1-56a9b31f9cfb.png)

**Update**

Sorry I give a very bad example of reproducing the problem.

The following case are the behaviors in two different IDEs.

![29](https://user-images.githubusercontent.com/2676255/28947747-3ca9c338-78e4-11e7-86e0-2d80e2298eda.png)
![28](https://user-images.githubusercontent.com/2676255/28947752-3e188010-78e4-11e7-9f04-64b0e653d026.png)

In Visual Studio 2015, when I have a member named ``classic( )``, VS only pops out ``classic( )`` for me to choose.

But in VS Code it also returns ``class`` which is not available in my ``class A``.

This may cause a problem if a library uses similar words for their member function names, VS Code will return lots of unrelated results.

**Comment by KKyang** [comment]
**Update**

I found another interesting behavior in VS Code.

![31](https://user-images.githubusercontent.com/2676255/28948223-e9cf7e16-78e6-11e7-953a-86f14bd7240a.png)

As the image above, there are three variables named ``m_thread_num``, ``m_thread_switch``, and ``m_thread_idx``. If I type ``m`` after the dot, VS Code returns the wrong result.

![32](https://user-images.githubusercontent.com/2676255/28948292-49d2fe32-78e7-11e7-8b74-5e06b1273851.png)

Even if I type the third alphabet of the variable name, no correct answer is returned.

![34](https://user-images.githubusercontent.com/2676255/28948317-731ed09a-78e7-11e7-8784-22cba2e80ad4.png)

But if I type ``a.m`` then stop typing and move the cursor to somewhere else. Next I switch the cursor back to this line to continue typing ``_`` after ``a.m``, VS Code gives the correct answer.

**Comment by bobbrow** [comment]
It looks like you are using the "Tag Parser" IntelliSense engine.  If you add `"C_Cpp.intelliSenseEngine": "Default"` to your settings.json file, member list completions will work as you expect.

That last case though is not something I've encountered before.

**Comment by sean-mcmanus** [comment]
The bug where a.m and a.classic don't give results has been fixed for our next release. Thanks for reporting that. You can also try changing your intelliSenseEngine setting to Default too (which uses a different implementation that also doesn't have the bug).

**Comment by bobbrow** [comment]
We released 0.12.3 which has a fix for this.
