### ISSUE TITLE
Custom Workspace Include Paths

### ISSUE THREAD

**Issue by hutiwephy** [microsoft/vscode-cpptools#9430]
## The issue
Currently if I set the ```C_Cpp.default.includePath``` property inside the workspace settings it won't allow the ```${default}``` option to add all include paths defined on the User settings and since I´m using custom locations for headers and libraries I can only specify it on the User settings due to it's unique setup, and it's not practical to use the ```.vscode/c_cpp_properties.json``` ha I would like to only have to use one file that is not hidden from the user on certain platforms

### The setup
```
C:\
  |- mingw
       |- frameworks
       |       |- i686-w64-mingw32      => win32 includes and libraries
       |       |- x86_64-w64-mingw32  => win64 includes and libraries
       |
       |- mingw  => TDM-GCC multilib win32 and win64
       |- mingw32  => mingw w64 -> i686-8.1.0-release-posix-dwarf-rt_v6-rev0
       |- mingw64  => mingw w64 -> x86_64-8.1.0-release-posix-seh-rt_v6-rev0
```

### The User settings
```
...
    "C_Cpp.default.compilerArgs": [
        "-I\"C:/mingw/frameworks/i686-w64-mingw32/include\"",
        "-I\"C:/mingw/frameworks/x86_64-w64-mingw32/include\"",
        "-L\"C:/mingw/frameworks/i686-w64-mingw32/lib\"",
        "-L\"C:/mingw/frameworks/x86_64-w64-mingw32/lib\""
    ],
    "C_Cpp.default.includePath": [
        "${workspaceFolder}/*",
        "${workspaceFolder}/headers/**",
        "C:/mingw/frameworks/i686-w64-mingw32/include/**",
        "C:/mingw/frameworks/x86_64-w64-mingw32/include/**"
    ],
...
```

### The Workspace settings
```
...
	"settings": {
		...
		 "C_Cpp.default.includePath": [
		      "${default}",
		      "${workspaceFolder}/**",
		      "${workspaceFolder}/**/headers/**",
		      "${workspaceFolder}/headers/**"
		 ],
                 ...
	},
...
```

## What I wanted
A property or the capability to add the includes on the user settings to the workspace settings with a ```${default}``` like solution on the workspace file

PS: can the ```miDebuggerPath``` property from the Debug configurations also be defined on the User settings instead of having to add the bin folder to the PATH variable

**Comment by sean-mcmanus** [comment]
Yeah, the current implementation only processes the ${default} in the c_cpp_properties.json and not in the settings themselves to bring in defaults from the higher level setting scopes. Adding that ability might be relatively easy to do in our open source TypeScript.
