### ISSUE TITLE
A single string with spaces in compilerArgs is no longer supported with 1.10.5

### ISSUE THREAD

**Issue by YOYO-UIAT** [microsoft/vscode-cpptools#9432]
Bug type: Language Service

**Describe the bug**
- OS and Version: Windows 10 20H2
- VS Code Version: 1.67.1
- C/C++ Extension Version: 1.10.5
- Other extensions you installed (and if the issue persists after disabling them): I disabled all other cpp extensions, and the issue still persists

I opened a folder. The folder does not have `c_cpp_properties.json`, so it's using `C_Cpp.default.compilerPath` as the compiler. Lately I set the `C_Cpp.default.compilerPath` to `C:\\msys64\\mingw64\\bin\\g++.exe`, but it told me `Unable to resolve configuration with compilerPath`. The MinGW compiler is able to be used in the console.

The error output: 

```
[2022/6/11 13:23:47] 无法使用 compilerPath“C:\msys64\mingw64\bin\g++.exe”解析配置。 请改用“D:\usr\bin\gcc”。
```

In the past I used C/C++ extension version 1.9.8(or maybe 1.9.7?), and the compiler was resolved successfully. But after I upgraded the  C/C++ extension, it doesn't work anymore.

**Code sample and logs**

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette:

```
-------- Diagnostics - 2022/6/11 13:31:20
Version: 1.10.5
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "compilerArgs": [
        "-std=c++14 -O2 -D_GLIBCXX_DEBUG -D_GLIBCXX_DEBUG_PEDANTIC -Wall -Wextra -Wformat=2 -Wfloat-equal -Wcast-qual -Wcast-align -Wl,--stack=1234567890 -fno-ms-extensions -Wno-misleading-indentation -Wshadow -Dzyz"
    ],
    "cStandard": "c17",
    "cppStandard": "c++14",
    "intelliSenseMode": "gcc-x64",
    "mergeConfigurations": false,
    "compilerPath": "C:\\msys64\\mingw64\\bin\\g++.exe",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\洛谷\P5068_Ynoi2015_我回来了.cpp ]:
    D:\洛谷\P5068_Ynoi2015_我回来了.cpp
Translation Unit Configurations:
[ D:\洛谷\P5068_Ynoi2015_我回来了.cpp ]:
    Process ID: 8000
    Memory Usage: 13 MB
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: c++14
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=103000
Total Memory Usage: 13 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 1477

```

**Comment by XKTZ** [comment]
I faced similar problems. The vscode says "unable to resolve configuration with compiler path ... (my g++.exe)" and it says using my gcc path instead. I just solve this problem by using the older version of c/c++ plugin.

**Comment by YOYO-UIAT** [comment]
@XKTZ I'll try the older version. Thanks.

**Comment by sean-mcmanus** [comment]
compilerArgs is expected to be an array of arguments and not a string separated by spaces. It works if you use:
```json
            "compilerArgs": [
                "-std=c++14",
                "-O2",
                "-D_GLIBCXX_DEBUG",
                "-D_GLIBCXX_DEBUG_PEDANTIC",
                "-Wall",
                "-Wextra",
                "-Wformat=2",
                "-Wfloat-equal",
                "-Wcast-qual",
                "-Wcast-align",
                "-Wl,--stack=1234567890",
                "-fno-ms-extensions",
                "-Wno-misleading-indentation -Wshadow",
                "-Dzyz"],
```

**Comment by sean-mcmanus** [comment]
Setting `"C_Cpp.legacyCompilerArgsBehavior": true` is another workaround, although you'll get a deprecation warning in your settings (and the setting won't appear in auto-complete) -- that setting should probably not be deprecated yet?

**Comment by sean-mcmanus** [comment]
We're considering this a "by design" breaking change -- see https://github.com/microsoft/vscode-cpptools/issues/9432#issuecomment-1154350836 for the recommended fix and https://github.com/microsoft/vscode-cpptools/issues/9432#issuecomment-1154360612 for the non-recommended workaround.

**Comment by YOYO-UIAT** [comment]
Thanks very much.

**Comment by YOYO-UIAT** [comment]
Thanks a lot.
