### ISSUE TITLE
can i change go to definition(now is F12) key?

### ISSUE THREAD

**Issue by wk89463** [microsoft/vscode-cpptools#9445]
### Feature Request

can i change go to definition(now is F12) key? F12 is used by other software and it can't be changed，so can i change go to definition(now is F12) key? such as F11

**Comment by Colengms** [comment]
Hi @wk89463 .  As @Wastus described, this is changeable via a setting in VS Code.  Since the ability to change this shortcut exists, and because this isn't specific to the C/C++ Extension, I'll close this issue.
