### ISSUE TITLE
Unable to start preLaunchTask when "C_Cpp.intelliSenseEngine": "Disabled"

### ISSUE THREAD

**Issue by fonqL** [microsoft/vscode-cpptools#9446]
### Environment

- OS and version: Windows 10
- VS Code: 1.65.0
- C/C++ extension: 1.10.5
- GDB / LLDB version: gdb 11.2

### Bug Summary and Steps to Reproduce

Bug Summary:

I'm using clangd for code completion and also expect to use C/C++ for debug, so I enable the C/C++ plugin and disable the C/C++ intellisense engine. After pressing F5 vscode reports an error says the .exe program doesn't exist. But my preLaunchTask works well and generates .exe when I either disable C/C++ plugin or enable the "C_Cpp.intelliSenseEngine". 
Disable clangd or reboot system can't solve the problem. 
Also, if I set preLaunchTask with a non-existent task, it also report .exe doesn't exist instead of reporting "Could not find the task ...".
Why? and what should I do?

Steps to reproduce:
1. Config launch.json and tasks.json, and set preLaunchTask to build task.
2. Enable C/C++ and set "C_Cpp.intelliSenseEngine": "Disabled"
3. Press F5
4. vscode reports an error says the .exe program doesn't exist.

### Debugger Configurations

```shell
launch.json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb)launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "D:\\MinGW\\bin\\gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "build"
        }
    ]
}

tasks.json
{
    "version": "2.0.0",
    "tasks": [
        {
            "type": "process",
            "label": "build",
            "command": "g++",
            "args": [
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "-m64",
                "-Wall",
                "-Wextra",
                "-Wshadow",
                "-std=c++14",
                "-static-libgcc",
                "-fexec-charset=GBK",
                "-DFread",
                "-Wunreachable-code"
            ],
            "presentation": {
                "echo": false,
                "reveal": "silent",
                "showReuseMessage": false,
                "focus": false,
                "clear": true
            },
            "options": {},
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "compiler: D:\\MinGW\\bin\\g++.exe",
            "problemMatcher": []
        },
        {
            "label": "run",
            "type": "shell",
            "command": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "presentation": {
                "focus": true,
                "echo": false,
                "showReuseMessage": false,
                "clear": true
            },
            "group": {
                "kind": "test",
                "isDefault": true
            }
        }
    ]
}
```

### Debugger Logs

```shell
None
```

**Comment by fufufuqqq** [comment]
![image](https://user-images.githubusercontent.com/75968297/173589757-6dab8c33-0490-4ba2-a4b6-7c101b663d79.png)

**Comment by sean-mcmanus** [comment]
@fufufuqqq Do you know if this used to work in a previous version, such as 1.9.8? (We could also check this ourselves).

@elahehrashedi Do you know if this is related to your build task changes and/or do you have time to investigate this? If not, I could potentially look into, but I have multiple other issues in flight.

**Comment by bobbrow** [comment]
I've never seen a task with `"type": "process"` before.  @fufufuqqq which extension provides the implementation for that task?  Should it be `"type": "cppbuild"` instead?

cc: @elahehrashedi

**Comment by sean-mcmanus** [comment]
@bobbrow We do handle the "cppdbg" debugger type, so it's possible we skipping something required for that to work when intelliSenseEngine is Disabled.

**Comment by elahehrashedi** [comment]
This is a regression.
1. When the IntelliSense is disabled, the Vs Code will fail to run a `cppbuild` preLaunch task, so we run that build task before the launch starts. 
2. But if the task is not `cppbuild` Vs Code can resolve the preLaunch tasks before launch starts.

**Comment by sean-mcmanus** [comment]
Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.10.6 .

**Comment by fufufuqqq** [comment]
> I've never seen a task with `"type": "process"` before. @fufufuqqq which extension provides the implementation for that task? Should it be `"type": "cppbuild"` instead?
> 
> cc: @elahehrashedi

https://code.visualstudio.com/docs/editor/tasks#_custom-tasks
Here it says "type" can either be "shell" or "process".

**Comment by Trass3r** [comment]
>     2. But if the task is not a `cppbuild` type, Vs Code should be able to resolve the preLaunch tasks before launch starts.

No it did affect standard vscode tasks too.
Now it finally works again, thanks. I was already puzzled why it stopped working.

**Comment by bobbrow** [comment]
> https://code.visualstudio.com/docs/editor/tasks#_custom-tasks
> Here it says "type" can either be "shell" or "process".

Thanks.  It appears the documentation doesn't account for extension-provided "types" which are also valid, but it's good to know that the "process" type belongs to "VS Code"
