### ISSUE TITLE
strange include header bug

### ISSUE THREAD

**Issue by CHChang810716** [microsoft/vscode-cpptools#945]
When using the standard library provied by MinGW-w64 and the intelliSenseEngine set to "Default", the header "regex.h" compiled fail. 

OS: win7 64bit
VScode version: 1.14.2

The include path is configured by the output of command:
```
g++ -E -x c++ - -v 
```

![image](https://user-images.githubusercontent.com/8450899/28937243-d8fda150-78bc-11e7-9630-2bf5c09a570c.png)

**Comment by sean-mcmanus** [comment]
I'm not able to repro the problem with 0.17.7, although regex.h does repro another bug: https://github.com/Microsoft/vscode-cpptools/issues/2352 . My source file includes `<regex>` and my compilerPath is set to the mingw-w64 compiler. Let me now if you're still hitting a bug.

![image](https://user-images.githubusercontent.com/19859882/43620664-c1d8944a-9688-11e8-8968-682d3e1e3b1f.png)
