### ISSUE TITLE
Error squiggles and colorization not working

### ISSUE THREAD

**Issue by voylin** [microsoft/vscode-cpptools#9452]
Bug type: Language Service

**Describe the bug**
- OS and Version: Arch Linux LTS 5.15.46-1
- VS Code Version: 1.68.0-1
- C/C++ Extension Version: 1.10.6
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

The issue is that intellisense is not working. When I type I get the code completion pop-up, but whenever I type something wrong, there are no error squiggles. Another issue is that the colors are also not working properly. By example std::string, std is in green, string is in white and I have this issue with my own made classes as well. Tried over multiple projects, re-installed multiple times, whole system update, deleting everything, but I just can't find how to fix this.

**Steps to reproduce**

1. Make any new cpp file and add any type of text with as many mistakes as you'd like as it won't work anyway.

**Expected behavior**
I expect the error squiggles to appear and that the color for types and classes is correct.

**Code sample and logs**
- Code sample
`#include <iostream>

int test() {
  std::string test = 32;
  return "hello"
}
`
- Configurations in `c_cpp_properties.json`
`{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**",
                "./"
            ],
            "defines": [],
            "compilerPath": "/usr/bin/gcc",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "linux-gcc-x64",
            "mergeConfigurations": false,
            "browse": {
                "path": [
                    "${workspaceFolder}/**",
                    "./"
                ],
                "limitSymbolsToIncludedHeaders": true
            }
        }
    ],
    "version": 4
}`

- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)
`idle loop: reparsing the active document
Checking for syntax errors: /home/voylin/Documents/Programming/cpp_vulkan_engine/test.cpp
Queueing IntelliSense update for files in translation unit of: /storage/Documents/Programming/cpp_vulkan_engine/test.cpp
sending 1 changes to server
sending 1 changes to server
cpptools/finishUpdateSquiggles
Error squiggle count: 3
Update IntelliSense time (sec): 0.253
textDocument/hover: /home/voylin/Documents/Programming/cpp_vulkan_engine/test.cpp (id: 496)`

**Screenshots**
![Screenshot from 2022-06-15 14-34-54](https://user-images.githubusercontent.com/56970759/173747715-08922e0f-e1af-4d13-a2b7-ab7442c39ba1.png)

**Comment by sean-mcmanus** [comment]
I don't understand. Is there a symlink on the workspace folder path? If so, it's a duplicate of https://github.com/microsoft/vscode-cpptools/issues/4573 .

**Comment by voylin** [comment]
> I don't understand. Is there a symlink on the workspace folder path? If so, it's a duplicate of #4573 .

Yes, look identical to issue #4573, so I will close this issue. I hope this gets solved someday.
