### ISSUE TITLE
Incorrect syntax highlighting for `unsigned int` in C. 

### ISSUE THREAD

**Issue by james-parky** [microsoft/vscode-cpptools#9466]
Bug type: Language Service

**Describe the bug**
When using this extension as a syntax highlighter for C code, the lexer incorrectly assumes that `unsigned int` is a variable of type `unsigned` with identifier `int`, rather than one typename. 

**Steps to reproduce**
Simply typing `unsigned int` will show the `unsigned` as a type, and `int` as a variable identifier. 

**Expected behavior**
This should be recognised as one typename. 

**Screenshots**
<img width="422" alt="Screenshot 2022-06-17 at 13 56 08" src="https://user-images.githubusercontent.com/72101291/174302597-0c89f9ee-d7e9-4232-8f88-63fcd4cd7503.png">

**Comment by sean-mcmanus** [comment]
The repro appears to require a switch statement, i.e. a full example is
```c

#include <stdio.h>
#include <stdarg.h>

int func()
{
    char *args;
    int c;
    switch(c)
    {
    case 'i':
        printf("%i", va_arg(args, unsigned int)); break;
    }
}
```

The issue repros without our C/C++ extension installed and from VS Code which gets lexical colorization from https://github.com/jeff-hykin/better-cpp-syntax/issues , so you should report it there.

**Comment by sean-mcmanus** [comment]
Also, seems like a duplicate of https://github.com/jeff-hykin/better-cpp-syntax/issues/580
