### ISSUE TITLE
"cannot open source file x" wording could be improved

### ISSUE THREAD

**Issue by Tyriar** [microsoft/vscode-cpptools#947]
I read "open source" as in "OSS". Why not just make it "cannot open file x"?

**Comment by bobbrow** [comment]
We use the same error messages as Visual Studio.  The message is "cannot open %s file %s", so it is attempting to provide more detailed information.  Given the context of the error, I don't find it confusing.  I can't think of a reason why a compiler would try to "open source" a file on your behalf.
