### ISSUE TITLE
debugging files in protected folders MacOS

### ISSUE THREAD

**Issue by Hunam6** [microsoft/vscode-cpptools#9474]
### Environment

- OS and version: MacOS Montery 12.4 M1
- VS Code: 1.68.1
- C/C++ extension: 1.10.7
- GDB / LLDB version: lldb-1316.0.9.46 Apple Swift version 5.6.1 (swiftlang-5.6.0.323.66 clang-1316.0.20.12)

### Bug Summary and Steps to Reproduce

Bug Summary:
This is the pretty much the exact same issue as https://github.com/microsoft/vscode-cpptools/issues/5282 bug it isn't resolved.

Steps to reproduce:
1. Try to debug a C file located in the `~/Documents` folder.
<img width="39" alt="Screenshot 2022-06-19 at 16 20 10" src="https://user-images.githubusercontent.com/38606542/174485653-a9f81bae-9cd9-497c-bafc-f0132da29f9f.png">

2. Asks for permission every time
<img width="645" alt="Screenshot 2022-06-19 at 16 20 51" src="https://user-images.githubusercontent.com/38606542/174485675-052af34d-6dcc-4aca-82c2-d218e10c3982.png">

3. Granting full disk access to either VSCode or the "main" file doesn't work.

### Debugger Configurations

```shell
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: clang build active file",
            "command": "/usr/bin/clang",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}/${fileBasenameNoExtension}"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

### Debugger Logs

```shell
Loaded '/usr/lib/system/libsystem_pthread.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_symptoms.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libsystem_trace.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libunwind.dylib'. Symbols loaded.
Loaded '/usr/lib/system/libxpc.dylib'. Symbols loaded.
Loaded '/usr/lib/libc++abi.dylib'. Symbols loaded.
Loaded '/usr/lib/libobjc.A.dylib'. Symbols loaded.
Loaded '/usr/lib/liboah.dylib'. Symbols loaded.
Loaded '/usr/lib/libc++.1.dylib'. Symbols loaded.
hello
The program '/Users/hunam/Documents/dev/learn-c/main' has exited with code 0 (0x00000000).
```

**Comment by WardenGnaw** [comment]
It looks like macOS has hardened their default folders more and it will now require `Full Disk Access`.

You can workaround this by giving your terminal access in `Security & Privacy` -> `Privacy` -> `Full Disk Access` and click on the checkbox for Terminal.

**Comment by Hunam6** [comment]
Mhh this won't be fixed then?

**Comment by WardenGnaw** [comment]
If `terminal` did not work, you may have to allow your app (`main`) full disk access.

This is still an external issue due to macOS's security system Gatekeeper.

You could completely disable the system with `sudo spctl --master-enable`, but I do not recommend that. 

If Documents is giving you issues, I would recommend placing your workspace root in a non-protected folder.
