### ISSUE TITLE
Problems matcher can not show the correct file path.

### ISSUE THREAD

**Issue by PickaxeHit** [microsoft/vscode-cpptools#9489]
### Environment

- OS and version:Windows 11 Build 25140 x64
- VS Code:v1.68.1
- C/C++ extension:v1.10.7
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

Bug Summary:
I'm using `Espressif IDF` extension.

When I click on a problem in Problems tab, it shows VSCode cannot find the file.
The path in the tab looks like /:/.../myfile.c
but the correct one is C:/.../myfile.c

Steps to reproduce:
1. an ESP-IDF project with its own error (which is not a common error. Only by analysising the terminal outputs, it can find the error)
2. Use the `build` button to build the project, the subprocess will start in Terminal tab. And the termial outputs the correct file path.
3. Return to Problems tab, click one problem in it. VSCode cannot find the file and want to add this file to the wrong path `/:/.../myfile.c`

### Other Extensions

Chinese (Simplified) (简体中文) Language Pack for Visual Studio Code
Espressif IDF

### Additional Information

![image](https://user-images.githubusercontent.com/95094338/174963051-8eb019c3-7d71-46fa-82cc-acd38cca9a1a.png)
(the termial outputs)
![image](https://user-images.githubusercontent.com/95094338/174963308-8b998f2b-42d1-4f57-953d-b6c1dcfc6e57.png)
(wrong file path in Problems tab)
![image](https://user-images.githubusercontent.com/95094338/174963471-7e254387-3705-489f-bbf7-c76f9565b325.png)
(it can show the common error correctly)

All of my settings are default.

**Comment by Pickaxe-Hit** [comment]
![image](https://user-images.githubusercontent.com/95094338/174964243-5ed7d0ef-f494-44ae-bb82-7f655ba9deb3.png)
the things happened when i clicked the error in Problems tab.

**Comment by Pickaxe-Hit** [comment]
> Our extension only ships the $gcc problemMatcher and it's working for me in a similar scenario.
> 
> ![image](https://user-images.githubusercontent.com/19859882/175104128-e4cded47-d294-4092-a36b-d7aff9988eea.png)
> 
> Your screenshot appears to not show the "gcc" problemMatcher source, which implies that you're using a different problemMatcher, maybe one from the Espressif IDF extension, so it would be a bug with their version of the problemMatch and not a bug with ours.
> 
> I do see some C/C++ source errors which are from our extension, but we need more info if you believe those errors are a bug with our extension.

Thanks for your reply. I am not sure who caused the problem,i have tried to change the version of them(vscode,cpptools and espressif idf), but it didn't work. so I am trying to change the windows version. Could you tell me how to change the problem matcher(to use cpptools)?

**Comment by sean-mcmanus** [comment]
The problem matcher would be defined either in your tasks.json or the problems could be generated by the other extension themselves. With our extension, you'd have to have the $gcc defined in the tasks.json problemMatcher property.
