### ISSUE TITLE
the disappear of the #include directive green squiggle

### ISSUE THREAD

**Issue by sigmarising** [microsoft/vscode-cpptools#949]
VScode version: 1.14.2
C_Cpp_tool version: 0.12.2
windows version: windows 10 1703

These days I update the cpp extension and there appears a bug. There is no such `c_cpp_properties.json` 
 but the #include directive green squiggle still doesn't appear.

This picture shows that the disappear of the green squiggle:

![default](https://user-images.githubusercontent.com/25470568/28991575-5665101a-79bc-11e7-9d85-90a326fb5601.png)

This picture show that I don't add the file  `c_cpp_properties.json`  :

![2](https://user-images.githubusercontent.com/25470568/28991618-ce3c53a0-79bc-11e7-9bc1-7ba0f72af89a.png)

I don't know how to fix it.

**Comment by sean-mcmanus** [comment]
If there's no c_cpp_properties.json we use a default. You can do an C/Cpp: Edit Configuration command to generate the file. If no green squiggles appear, it sounds like our extension may have crashed or is stuck. What are the Microsoft.VSCode.CPP.* processes doing?

**Comment by sigmarising** [comment]
I add the `c_cpp_properties.json` file and add my root of the header,  but no more things happens. The intellisence engine still can not match the key words in the header files.

This problem don't happen in the older version of this extension.

![3](https://user-images.githubusercontent.com/25470568/28991912-2ef36526-79c2-11e7-90f7-3235ee6128b5.png)

![4](https://user-images.githubusercontent.com/25470568/28991920-42a57e7e-79c2-11e7-8358-33f2d581e884.png)

**Comment by sean-mcmanus** [comment]
Do you remember what your earlier version was or approximately what month it was from? Are you saying there should be squiggles or is Go to Definition just failing? Can you try changing the databaseFilename in your c_cpp_properties.json to "${workspaceRoot}/.vscode/vc.db" to regenerate the symbol database?

**Comment by sigmarising** [comment]
The earlier version I used was the 0.12.1.

I find that when I change the setting  from `"C_Cpp.intelliSenseEngine": "Tag Parser",` to `"C_Cpp.intelliSenseEngine": "Default",`, the red squiggles appears under the include sentences. 

I try to add the include path to `c_cpp_properties.json`, the function Go to define works, but the red squiggles are still here(I think they should disappear).

![default](https://user-images.githubusercontent.com/25470568/28994432-96164f0a-7a00-11e7-9ee6-943fd64557a7.png)

Then I add the `"${workspaceRoot}/.vscode/vc.db"` , nothing happens.

![2](https://user-images.githubusercontent.com/25470568/28994512-337fb1cc-7a02-11e7-8b02-3fbadeec77d8.png)

It seems that if I set  `"C_Cpp.intelliSenseEngine": "Tag Parser",` then all squiggles go away; and `"C_Cpp.intelliSenseEngine": "Default",` makes so many squiggles.

**Comment by sigmarising** [comment]
Today I create a new project, but no matter how I change my setting `"C_Cpp.intelliSenseEngine":`, both the squiggles display and the Go to Define crashed. 😢

**Comment by sean-mcmanus** [comment]
With the Default intelliSenseEngine, you need to set your includePath setting correctly (it is not recursive). See https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md . If you're getting red squiggles for the header files, that means your intelliSenseEngineFallback is set to Disabled (you might want to change it to Enabled). You should view your Problems window to see help on which include files are not able to be found. If you can help provide a repro or call stack of the Go to Definition crash that would be great.

**Comment by sigmarising** [comment]
Ops! 

Today I open my Visual Studio Code Setting, I suddenly find a new line `"C_Cpp.intelliSenseEngineFallback": "Disabled",` add to my user's setting. I am sure that I didn't add this setting by myself, it seems that this setting was added automatically.

Then I delete this setting from user's setting and add the include file in `c_cpp_properties.json`(both `includePath` and `browse.path`). With the `"C_Cpp.intelliSenseEngine": "Tag Parser",`, the include file squiggles and Go to Define function works well. 

![image](https://user-images.githubusercontent.com/25470568/29102986-8b3db702-7cef-11e7-8de2-641b9ca61bb8.png)

I change the setting to `"C_Cpp.intelliSenseEngine": "Default",`, Go the Define function works but the green squiggles appear under every `#include' sentences. It seems that the engine cannot search the  subdirectory in the path I add.

![image](https://user-images.githubusercontent.com/25470568/29103101-37fbbb7e-7cf0-11e7-9c28-6da51fd7db78.png)

![image](https://user-images.githubusercontent.com/25470568/29103111-405ffff0-7cf0-11e7-81f8-db1f5774a901.png)

![image](https://user-images.githubusercontent.com/25470568/29103188-ae043c24-7cf0-11e7-9fe8-3f63a2560074.png)

I am sorry that I don't know how to get the *repro or call stack of the Go to Definition crash* file 😂. I am willing to provide these if you can teach me how to get them 😄.

**Comment by sean-mcmanus** [comment]
Our code never changes the intelliSenseEngineFallback setting to "Disabled" automatically. Maybe another extension you have installed changed the setting? There is also a Code Action (lightbulb) and a "Toggle IntelliSense Engine Fallback on Include Errors" command that will change the setting. Yesterday, we did change the default intelliSenseEngine setting to "Default" for some people. The green squiggles with the intelliSenseEngine is because the includePath setting is not recursive, and that's the setting used by the "Default" intelliSenseEngine. See https://github.com/Microsoft/vscode-cpptools/blob/master/Documentation/LanguageServer/FAQ.md .

**Comment by sigmarising** [comment]
Maybe the Code Action change the setting(I did use this before). 

And thanks a lot for @sean-mcmanus to answer my question. 😄
