### ISSUE TITLE
vs code c++ debugging using internal debugger in m1

### ISSUE THREAD

**Issue by prabhavagrawal7** [microsoft/vscode-cpptools#9493]
### Feature Request
Machine Config
OS :- macos monterey
Machine :- Macbook air m1 
I was a linux user back then, so I used to debug c++ applications in integrated terminal as it really comes in handy but in mac os we have to do it with external terminal. If possible, please add this feature :)

**Comment by WardenGnaw** [comment]
Duplicate of https://github.com/microsoft/vscode-cpptools/issues/6715

lldb does not support tty redirection so we are unable to use integrated terminal with VS Code.
