### ISSUE TITLE
Intellisense: Types in namespace appear in global namespace.

### ISSUE THREAD

**Issue by HildarTheDorf** [microsoft/vscode-cpptools#95]
Types within nested namespaces also appear in the global namespace. In the case of some standard lib types they don't appear in `std::` at all.

To reproduce:

`#include <memory>` then type `std::unique_`
Expected behavior: `unique_ptr` is suggested
Actual behavior: `unique_ptr` is not suggested. It is however suggested when just typing `unique_` without the `std:`: qualifier.

`namespace Foo { namespace Bar { struct Baz; } }`
Expected behavior: Baz is not suggested unless `Foo::Bar::` is typed first
Actual behavior: Baz is suggested without namespace.

Happening on ubuntu 16.04, VSCode 1.3.0, C/C++ extension 0.7.1

**Comment by sridmad** [comment]
#13  covers enabling accurate auto completion
