### ISSUE TITLE
Display (customizable) pretty names in inlay hints

### ISSUE THREAD

**Issue by PoetaKodu** [microsoft/vscode-cpptools#9508]
### Feature Request

I want to be able to use custom names for the inlay type hint. Some types are pretty long, for example: `std::filesystem::path`. I'm pretty much always using an alias `fs = std::filesystem`. It would be nice to be able to map the types to custom names:

- `std::filesystem::path`, display name: `fs::path`
- `std::chrono::high_resolution_clock`, display name: `hr_clock`
- `std::string`, display name: `str`
- `const char*`, display name: `cstr`
- ... or whatever the user wants.

Argument names from the standard library with a reserved naming convention (`_Name`, `__name`) could also be prettified. Right now it looks like this:
![image](https://user-images.githubusercontent.com/6839845/175818742-0b97f1ab-fd56-41c8-8799-7ca186f66aca.png)
![image](https://user-images.githubusercontent.com/6839845/175818818-a90dc7da-6ecb-4e5e-bc96-77ec6a4ebf19.png)

Cheers.

**Comment by PoetaKodu** [comment]
> The name aliases is just for the "auto" types, right?

Yes.

**Comment by sean-mcmanus** [comment]
The "_" at the start are auto-hidden by default with 1.11.2 (pre-release), and there's a setting to add them back if you want): https://github.com/microsoft/vscode-cpptools/releases
