### ISSUE TITLE
include a file from a subdirectory

### ISSUE THREAD

**Issue by clankill3r** [microsoft/vscode-cpptools#951]
(Note,  Im using `"C_Cpp.intelliSenseEngine": "Default",` but I had problems as well with "Tag Parser".)

I want to include a file using: `#include <GLFW\glfw3.h>`
But it keeps saying (with that green underline):

> Cannot open source file "GLFW\glfw3.h"

In my `c_cpp_properties.json` in `includePath` I have both:
```
"/Volumes/DATA/learn_opengl/Include",
"/Volumes/DATA/learn_opengl/Include/GLFW"
```

This works fine however: `#include <glfw3.h>`, but an include that contains the GLFW folder as in `#include <GLFW\glfw3.h>` never seems to work.

Is this a bug?

**Comment by clankill3r** [comment]
Turns out it is the backslash...

**Comment by sean-mcmanus** [comment]
Yeah, I've made that mistake too. It would be nice if we gave a better warning/error message.
