### ISSUE TITLE
namespace "std" has no member "thread"

### ISSUE THREAD

**Issue by PikaMeow** [microsoft/vscode-cpptools#952]
When I use the std::thread in my code, there will be an error like this:
![_0 un xqx 2 qx22cruy442](https://user-images.githubusercontent.com/11624776/29011209-bf15b422-7b63-11e7-920b-8a46b1a72348.png)

But I can click "go to the declaration" on it, and jump to file "thread" and see the class definiton of thread:
![_2 1o 8d xkl3 ajco pbd4](https://user-images.githubusercontent.com/11624776/29011253-19c46bac-7b64-11e7-9af4-b58b646a093a.png)

I use cygwin environment on Windows, here is my include_path in `c_cpp_properties.json`:
```
"includePath": [
        "C:\\cygwin64\\usr\\include",
        "C:\\cygwin64\\lib\\gcc\\x86_64-pc-cygwin\\5.4.0\\include",
        "C:\\cygwin64\\lib\\gcc\\x86_64-pc-cygwin\\5.4.0\\include\\c++",
        "C:\\cygwin64\\lib\\gcc\\x86_64-pc-cygwin\\5.4.0\\include\\c++\\x86_64-pc-cygwin",
        "${workspaceRoot}"
    ]
```

When I build with `-std=c++11`, I can run the program normally, I just can't eliminate the warning.
Did I miss some path? Or should I add some macro definition in the `.json` file?

**Comment by bobbrow** [comment]
what does gcc report as the default include path when you run `gcc -v -E -x c++ -`?  You should copy whatever gcc tells you into your `includePath` for best results.

**Comment by bobbrow** [comment]
Also, please make sure you set the `"intelliSenseMode"` to `"clang-x64"` in the **c_cpp_properties.json** file if you haven't already.

**Comment by bobbrow** [comment]
Let us know if the suggestions above were unable to help you resolve your issue.

**Comment by alitoufighi** [comment]
![mutex](https://user-images.githubusercontent.com/30089812/49546953-b65d2100-f8f6-11e8-8a85-4d7348e29da5.jpg)

![properties](https://user-images.githubusercontent.com/30089812/49547085-076d1500-f8f7-11e8-80b5-a8924c5730ca.png)

I think this is a relevant issue. Above are my error with using `mutex` and my c_cpp_properties.json file. I added everything I saw on the Internet in it but still not working.

**Comment by sean-mcmanus** [comment]
@alitoufighi The "no type named" message doesn't come from our extension. Do you have another one installed?

**Comment by wrgallo** [comment]
VSCode Extensions > C/C++ > Extension Settings > C_CPP: Intelli Sense Engine > Set to "Tag Parser"

This solved the problem for me.

**Comment by bobbrow** [comment]
Using the "Tag Parser" engine will disable IntelliSense squiggles and remove semantic matches in the autocomplete list.  It's not recommended unless you are using a specialized compiler that is incompatible with MSVC or GCC/Clang.

As this issue is quite dated, the information is old.  You should use `compilerPath` in your configuration in `c_cpp_properties.json` to tell the extension where the system headers are.  It is not recommended to add the system include paths directly to `includePath` anymore.

**Comment by bobbrow** [comment]
If you are having issues with red squiggles or getting the extension configured at all, please open a new issue and we'd be happy to help you troubleshoot it.
