### ISSUE TITLE
debug loaded wrong .so

### ISSUE THREAD

**Issue by yyfcc17** [microsoft/vscode-cpptools#9525]
### Environment

- OS and version: macos
- VS Code: latest
- C/C++ extension: latest
- OS and version of remote machine (if applicable):
- GDB / LLDB version: GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. prepare a c++ project
2. make dir build, and build release version
3. make dir build-debug, build debug version
4. debug using executable in build-debug, but $cwd set to build
5. it will load .so in build not build-debug, so some break points will not be captured.
6. after you make clean in build dir, then run debug, it then will load the correct .so, and breakpoints will work

in my project, i found this bug, my vscode and extensions are all updated.

### Debugger Configurations

```shell
-
```

### Debugger Logs

```shell
-
```

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.
