### ISSUE TITLE
IntelliSense stuck at 'loading...' .A crash of the IntelliSense process was detected.

### ISSUE THREAD

**Issue by li0o** [microsoft/vscode-cpptools#9526]
Bug type: Language Service 

### **Describe the bug**
- OS and Version: Windows 11_22000.739
- VS Code Version: 1.69.0-insider (user setup)
- C/C++ Extension Version: v1.10.7
- Other extensions (and the issue persists after disabling them): PlatformIO IDE v2.5.0
- Single project 

**Steps to reproduce**

1. New PIO project (STM32_Arduino)
2. Open './src./main.cpp'
3. '#include <Arduino.h>'
4. '#include <HardwareSerial.h>'
5. Click 'Arduino.h' Go to Definition(F12)
6. Back
7. Click 'HardwareSerial.h' Go to Definition(F12)
8. Back
9. Click 'Arduino.h' Go to Definition(F12)
10. Back
11. Click 'HardwareSerial.h' Go to Definition(F12)
12. Back
13. Click 'Arduino.h' Go to Definition(F12)
14. Back ..........
99. ..................    (Multiple attempts) 
100. See 'Loading...'

**Code sample and logs**

- Code sample
`#include <Arduino.h>`
`#include <HardwareSerial.h>`
`HardwareSerial URT1(USART1);`
`void setup() {}`
`void loop() {}`

- Configurations in `c_cpp_properties.json`
[c_cpp_properties.zip](https://github.com/microsoft/vscode-cpptools/files/9020011/c_cpp_properties.zip)

- Logs from running `C/C++: Log Diagnostics` from the VS Code command palette
[C++ Log Diagnostics.log](https://github.com/microsoft/vscode-cpptools/files/9020062/C%2B%2B.Log.Diagnostics.log)

- Logs from [the language server logging]
[C++ Log.log](https://github.com/microsoft/vscode-cpptools/files/9020061/C%2B%2B.Log.log)

**Screenshots**
![gif](https://user-images.githubusercontent.com/51149934/176684209-40f75f75-a9c6-4127-b101-a87edc8767cf.gif)

**Comment by sean-mcmanus** [comment]
@li0o I'm unable to locate "STM32_Arduino" -- how do I get that project?

**Comment by li0o** [comment]
> @li0o I'm unable to locate "STM32_Arduino" -- how do I get that project?

@sean-mcmanus 
This is the project I am using.
Board: STM32F103xx
Framework: Arduino
<img width="450" alt="2022-07-02 145935" src="https://user-images.githubusercontent.com/51149934/176990359-a41d1148-8022-4fd8-9935-c24e7b933054.png">

**Comment by sean-mcmanus** [comment]
The root bug appears to be that the headers are not getting associated with the main.cpp. Can you try running the C/C++: Reset IntelliSense Database command and wait for the database icon to go away (finish parsing)? You want to make sure "--header_only_fallback" doesn't appear in the logging when you do a go to def on a header (ideally our extension should check for this and remap the header to the source file).

**Comment by li0o** [comment]
> The root bug appears to be that the headers are not getting associated with the main.cpp. Can you try running the C/C++: Reset IntelliSense Database command and wait for the database icon to go away (finish parsing)? You want to make sure "--header_only_fallback" doesn't appear in the logging when you do a go to def on a header (ideally our extension should check for this and remap the header to the source file).

@sean-mcmanus 
I'm a C++ beginner and don't really understand what you're saying. But the problem seems to have disappeared after I rolled back 'C/C++ Extension' to v1.1.3. The problem started with v1.2.0.
I repackaged Log and Project and there seems to be no problem except for crashes.
[Project.zip](https://github.com/microsoft/vscode-cpptools/files/9052104/Project.zip)
[c++.log](https://github.com/microsoft/vscode-cpptools/files/9052105/c%2B%2B.log)

**Comment by sean-mcmanus** [comment]
I mean to run "C/C++: Reset IntelliSense Database" from the VS Code View->Command Palette menu item.

Also, when you run "C/C++: Log Diagnostics" you want to see:

Translation Unit Mappings:
[ C:\Users\user\Documents\PlatformIO\Projects\projectName\src\main.cpp ]:
    C:\Users\user\Documents\PlatformIO\Projects\projectName\src\main.cpp
    C:\Users\user\.platformio\packages\framework-arduinoststm32\cores\arduino\HardwareSerial.h *

Your previous logging showed HardwareSerial.h having a different mapping separate from main.cpp. The incorrect mapping could be triggering the crash.

v.1.1.3 is over a year old and not recommended, although if necessary, you could use that as a workaround.

**Comment by li0o** [comment]
> I mean to run "C/C++: Reset IntelliSense Database" from the VS Code View->Command Palette menu item.
> 
> Also, when you run "C/C++: Log Diagnostics" you want to see:
> 
> Translation Unit Mappings: [ C:\Users\user\Documents\PlatformIO\Projects\projectName\src\main.cpp ]: C:\Users\user\Documents\PlatformIO\Projects\projectName\src\main.cpp C:\Users\user.platformio\packages\framework-arduinoststm32\cores\arduino\HardwareSerial.h *
> 
> Your previous logging showed HardwareSerial.h having a different mapping separate from main.cpp. The incorrect mapping could be triggering the crash.
> 
> v.1.1.3 is over a year old and not recommended, although if necessary, you could use that as a workaround.

@sean-mcmanus 

Okay.

The "Reset IntelliSense Database" did not solve my problem.

I've created various STM32+Arduino projects and still get "Translation Unit Mappings: [main.cpp]". but ESP32+Arduino has no problem.
It seems that the problem lies in PlatformIO or my coding method, and I can't solve it yet, so I can only leave the version at v1.1.3 for now.

Thank you for your reply.
