### ISSUE TITLE
Debugger stops working when hit first breakpoint

### ISSUE THREAD

**Issue by unterumarmung** [microsoft/vscode-cpptools#9547]
### Environment

- OS and version: Windows 10 21H2
- VS Code:
```
Version: 1.68.1 (user setup)
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-06-14T12:49:10.067Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT ia32 10.0.19044
```
- C/C++ extension: 
Currently, I reproduce the bug with `v1.11.0` pre-release version. I switched to it from the latest release version - I had a hope that it was fixed in pre-release version. I didn't write down what the latest release version was.
- OS and version of remote machine (if applicable): Ubuntu 20.04.3 LTS
- GDB / LLDB version: `GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2`

### Bug Summary and Steps to Reproduce

Bug Summary:

Unfortunately, I couldn't came up with minimal reproducible example.
When I start debugging LLVM Flang, debugger successfully hit the first breakpoint and then it stops working because:
```
Stopping due to fatal error: AggregateException: One or more errors occurred. (Cannot access a disposed object.
Object name: 'Microsoft.MIDebugEngine.VariableInformation'.)
```
Also, variables and watch values are being infinitely loaded:
![image](https://user-images.githubusercontent.com/39276703/177576589-abf6d170-d100-4c9f-bf70-0db4c860b11e.png)
![image](https://user-images.githubusercontent.com/39276703/177576629-37b008ca-b676-46e2-bda2-d131bd4771bb.png)

Steps to reproduce:
1. Clone and build the trunk of llvm project: https://github.com/llvm/llvm-project
```
$ cmake -B build -DLLVM_ENABLE_ASSERTIONS=ON -DBUILD_SHARED_LIBS=ON -DLLVM_TARGETS_TO_BUILD='X86;AMDGPU' -DLLVM_APPEND_VC_REV=OFF -DCMAKE_BUILD_TYPE=Debug -DLLVM_PARALLEL_LINK_JOBS=1 -DLLVM_ENABLE_PROJECTS='clang;flang' llvm
$ make -C build -j10 all
```
This should be done on Ubuntu machine. Also, this may take a while..
2. Set a breakpoint here: https://github.com/llvm/llvm-project/blob/3b7c3a654c9175f41ac871a937cbcae73dfb3c5d/flang/lib/Optimizer/Transforms/AbstractResult.cpp#L214
3. Add any watch value that depends on a local variable like `context->getImpl()`. Though, It may not be necessary.
4. Run debugger with the launch file attached below
5. See the error showed earlier

### Debugger Configurations

```shell
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/build/bin/flang-new",
            "args": [
                "-fc1",
                "-emit-llvm",
                "${workspaceFolder}/flang/test/Fir/abstract-results.fir",
                "-o",
                "-"
            ],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Set Disassembly Flavor to Intel",
                    "text": "-gdb-set disassembly-flavor intel",
                    "ignoreFailures": true
                }
            ]
        }
    ]
}
```

### Debugger Logs

Debug logs are very bloated, so I attach just a small piece of them:

```shell
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (254572) ->(gdb)\n"},"seq":2686}
1: (254572) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (254572) 1117: elapsed time 5\n"},"seq":2688}
1: (254572) 1117: elapsed time 5
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (254572) Send Event AD7BreakpointEvent\n"},"seq":2690}
1: (254572) Send Event AD7BreakpointEvent
--> R (evaluate-15): {"type":"response","request_seq":15,"success":true,"command":"evaluate","body":{"result":"{...}","type":"mlir::MLIRContextImpl &","variablesReference":1000},"seq":2685}
--> E (stopped): {"type":"event","event":"stopped","body":{"reason":"breakpoint","threadId":211063,"allThreadsStopped":true,"source":{"name":"AbstractResult.cpp","path":"/home/d.dudkin/dev/llvm-project/flang/lib/Optimizer/Transforms/AbstractResult.cpp","sources":[],"checksums":[]},"line":213,"column":1},"seq":2693}
<--   C (scopes-16): {"command":"scopes","arguments":{"frameId":1000},"type":"request","seq":16}
--> R (scopes-16): {"type":"response","request_seq":16,"success":true,"command":"scopes","body":{"scopes":[{"presentationHint":"locals","name":"Locals","variablesReference":1001,"expensive":false},{"presentationHint":"registers","name":"Registers","variablesReference":1002,"expensive":true}]},"seq":2696}
<--   C (variables-17): {"command":"variables","arguments":{"variablesReference":1000},"type":"request","seq":17}
Stopping due to fatal error: AggregateException: One or more errors occurred. (Cannot access a disposed object.
Object name: 'Microsoft.MIDebugEngine.VariableInformation'.)
```

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.

**Comment by myhamidgit** [comment]
I am getting same error with
`Version: 1.73.1
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: 2022-11-09T02:08:38.961Z (1 wk ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 21.6.0
Sandboxed: No`

The steps for was
1. Set any breakpoint
2. -exec c     <-- this is where I see the error happen. If I was to use the GUI to click the "Play" button, it is fine.
