### ISSUE TITLE
Debug using Internal Console

### ISSUE THREAD

**Issue by WLLR9505** [microsoft/vscode-cpptools#955]
Please, I use vs code in fullscreen, debug using internal console is very good!! I hate change windows to type.

**Comment by gray-heron** [comment]
Technically there is "externalConsole" launch option, but I have never seen it having effect when set to false.

We have an annotation for this option:
> "Note this option is ignored in some cases for technical reasons."

Please specify these cases and consider not ignoring it - it is sometimes inconvenient to have a useless terminal popping up on every debugging session.

**Comment by pieandcakes** [comment]
This is the same request as #35.

**Comment by ghamelin** [comment]
so has this feature been added or is it still in progress?

**Comment by pieandcakes** [comment]
It is on the backlog of work that still needs to be done.
