### ISSUE TITLE
'__float128' on Windows

### ISSUE THREAD

**Issue by Phantom-Trigger** [microsoft/vscode-cpptools#9558]
My IntelliSense doesn't work with `__float128`. My platform is Windows, compiler is gcc11.2.0 from [winlibs](https://winlibs.com), C/C++ Extension Version is 1.10.8. I've tried all possible options for "IntelliSense Mode" but all still have the same issue as #6574 (i.e. gives an IntelliSense error: identifier “__float128” is undefined). **But it do compiled and run successfully.**
In comparison, when tested on Linux, this code isn't reported to have any error.
![无标题](https://user-images.githubusercontent.com/52826887/177983540-e767af1e-c2f7-48ba-b120-d5120f277e98.png)
![无标题2](https://user-images.githubusercontent.com/52826887/177983550-d721ebe7-1148-4e10-9efc-3944944c241d.png)

_Originally posted by @Phantom-Trigger in https://github.com/microsoft/vscode-cpptools/discussions/9232_

**Comment by sean-mcmanus** [comment]
VS added support for __float128 in linux-gcc-x64 mode, but for some reason they didn't add it for windows-clang-x64 mode or to VS Code.

**Comment by Benzolio** [comment]
I may have the same issue, using `"intelliSenseMode": "windows-gcc-x64"` compiling with ...`msys64\\mingw64\\bin\\g++.exe` when I `#include <stdlib.h>` I get:
```Error while processing C/C++(clang-diagnostics-error) [Ln #, Col #]
std_abs.h[Ln 102, Col 3]: __float128 is not supported on this target.
std_abs.h[Ln 103, Col 7]: __float128 is not supported on this target.
```
Clicking through to std_abs.h shows me:
```
identifier "__float128" is undefined C/C++(20 [Ln 103, Col 2]
identifier "__float128" is undefined C/C++(20 [Ln 103, Col 7]
```
Also, my project builds and links correctly, vscode is just popping these up as "Problems" while editing.

**Comment by sean-mcmanus** [comment]
NOTE: This bug is causing failures with the boost/geometry library: https://github.com/microsoft/vscode-cpptools/issues/9657

**Comment by LitMSCTBB** [comment]
Has there been any updates on this issue? Kind of makes boost development a pain...

**Comment by sean-mcmanus** [comment]
@LitMSCTBB A while back it got fixed in VS, but the fix was not completed for VS Code because of various issues/differences. We would have to complete that work.

**Comment by michelleangela** [comment]
Fix available in pre-release https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.0.

**Comment by michelleangela** [comment]
Fixed in release version https://github.com/microsoft/vscode-cpptools/releases/tag/v1.17.2.
