### ISSUE TITLE
Extension don't recongnize c_cpp_properties.json in they are not in the root .vs_code

### ISSUE THREAD

**Issue by austinh-msft** [microsoft/vscode-cpptools#956]
When you have a nested directory structure the c_cpp_properties.json files in the nested directories doesn't seem to get parsed. This results in all the include paths and such being ignored unless you open up the child directories which is a pain for code navigation.

**Comment by austinh-msft** [comment]
Dupe of: https://github.com/Microsoft/vscode-cpptools/issues/897

**Comment by bobbrow** [comment]
#897 is actually about recursive include paths within a single c_cpp_properties.json file.  What you are asking for is recursive detection and parsing of the c_cpp_properties.json file.  This is not something we intend to support, however, if you can configure your build (do you use CMake?) to output a compile_commands.json file, we do intend to support that in a future release and it will provide correct include paths for all of the source files in your build.
