### ISSUE TITLE
Cannot suppress clang-tidy --header-filter argument

### ISSUE THREAD

**Issue by voltamund** [microsoft/vscode-cpptools#9566]
I use the HeaderFilterRegex option inside the .clang-tidy configuration file. I want to use this option when running clang-tidy from the vscode cpptools extension or outside of vscode. Unfortunately I have not find a way to prevent cpptools from passing --header-filter argument to clang-tidy. If specified it takes precedence over the option in the .clang-tidy configuration. The only way to make it work is to use the same option that is inside .clang-tidy for "C_Cpp.codeAnalysis.clangTidy.headerFilter".
There should be a way to prevent passing --header-filter by cpptools extension.

**Comment by sean-mcmanus** [comment]
The code was written to handle this case, but there was a trivial bug with it.

**Comment by sean-mcmanus** [comment]
With our next release, the --header-filter won't be used if the .clang-tidy file exists (the bug was that the check for .clang-tidy was failing/incorrect).

**Comment by sean-mcmanus** [comment]
Fixed with 1.11.3 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.11.3
