### ISSUE TITLE
Question: Can I define path variables in config file, like ${workspaceRoot}?

### ISSUE THREAD

**Issue by xueyunquan** [microsoft/vscode-cpptools#957]
Hi,

I have a large project that references lots of headers outside the project path, say the headers are under the path /foo/bla/bla/bla/bla/bar . I need to add several include paths into the project config file c_cpp_properties.json , like:

/foo/bla/bla/bla/bla/bar/aaa
/foo/bla/bla/bla/bla/bar/bbb
/foo/bla/bla/bla/bla/bar/ccc
/foo/bla/bla/bla/bla/bar/ccc/ddd  

(The 4th line is needed because the new parsing engine does not support recursive including. It would be nice of it is supported.)

Instead of inserting these paths into the config file,  I feel like to define the root base of the paths "/foo/bla/bla/bla/bla/bar" as a variable, just like the predefined ${workspaceRoot}, such as ${myHeadersRoot}, and so I can write:

${myHeadersRoot}/aaa
${myHeadersRoot}/bbb
${myHeadersRoot}/ccc
${myHeadersRoot}/ccc/ddd

Can I do that in the config file?

**Comment by sean-mcmanus** [comment]
Yes, we support environment variables like ${myEnvVar} for includePath and browse.path. Does that work for you? We eventually want to change this to ${env.Var} to match the syntax used by launch.json.

**Comment by xueyunquan** [comment]
@sean-mcmanus : Thank you for your reply. But I don't know how to do it. Do I define variables in the config file (and what is the schema/syntax to do that?), or should I define&export env variables in Linux?
Could you please elaborate?

**Comment by sean-mcmanus** [comment]
Yeah, you define a Linux environment variable.

**Comment by xueyunquan** [comment]
@sean-mcmanus : Understood. Thank you.

**Comment by eliotstock** [comment]
I see it as a bug that `${env:HOME}` doesn't work in `c_cpp_properties.json`, but does in other config files such as `tasks.json`.

I also think that having to define the OP's `${myHeadersRoot}` in an env var is pretty poor form. I don't want an env var - and env var can't be committed to git and seen by other devs, it's evil. I just want to not have to repeat myself with the same headers path over and over again. Can we not just define a variable earlier in the same `c_cpp_properties.json` file somewhere?

**Comment by xueyunquan** [comment]
I would support @eliotstock 's opinions.

**Comment by SE2Dev** [comment]
Would there be any way to expose environment variables set by another extension to the C/C++ extension? For example: If I had a project management extension (such as vscode-cmake-tools) that sets an environment variable containing the target binary, how would I expose this to the C/C++ extension's launch.json without manually setting the environment variable externally? Are there any alternatives to using?

Edit: It seems that the behavior I was looking for can be achieved using variable substitution for commands in the other extension.

**Comment by bobbrow** [comment]
@eliotstock, we added support for `${env:HOME}` syntax in 0.12.4.

**Comment by sean-mcmanus** [comment]
Seems like this issue is resolved now.

**Comment by sean-mcmanus** [comment]
Ah, re-opening -- misunderstood the request (being able to define variables in the c_cpp_properties.json itself and not just via environment variables).

**Comment by ghost** [comment]
I understand that this issue has been resolved in the latest releases via `env` schema. But I noticed that the initialized variables don't work inside `env` when it is referenced right next to the definition. For example,
```
{
    "env": {
        "envRoot": "apps/tool/buildenv",
        "arm6.include": "${envRoot}/arm6/include",
    },
    "configurations": [
        {
            "name": "Custom",
            "includePath": [
                "${arm6.include}"
            ],
            "browse": {
                "limitSymbolsToIncludedHeaders": false,
                "path": [
                     "${arm6.include}"
                ]
            },
            …
        }
    ],
    "version": 4
}
```
This doesn't seem to work. That would be really useful

**Comment by bobbrow** [comment]
@Gouthamm4G, let me open a new issue for that.  I didn't take that case into consideration when implementing this.  There is only a single lookup per variable right now.
