### ISSUE TITLE
There is no any symbol for c/c++ after i update vscode to 1.14.2

### ISSUE THREAD

**Issue by anhkgg** [microsoft/vscode-cpptools#958]
VSCode Version: 1.14.2
OS Version: windows 10

1. i have installed c/c++ extension for vscode.
2. i can get the symbols by ctrl+shift+o when vscode is 1.12, but it can't work after updating to 1.14.2

Please , how can i solve the problem?

**Comment by sean-mcmanus** [comment]
Go to Symbols should work in general on all VS Code versions, so we need help finding a repro. What sort of failure do you see? Are there just no results? What other features don't work? Does this repro for a simple workspace with a single C/C++ file? What is the Microsoft.VSCode.CPP.Extension.exe process doing?

**Comment by anhkgg** [comment]
1. symbols work right for js/rust in the same environment.
2. it cant list the symbols in all the c/c++ file of the project
3. Microsoft.VSCode.CPP.Extension.exe process is working.
4. i cant see any failture information, just see "cant find symbols"
5. i install the latest vscode in ubuntu16.04, the symbols work right for c/c++

**Comment by sean-mcmanus** [comment]
Our extension never shows the text "cant find symbols". Maybe another extension is causing this? By the "the symbols work right for c/c++" do you mean the feature is working now?

**Comment by anhkgg** [comment]
"cant find symbols" is my  wording.

The problem i  met is that, the same c/c++ project, just right in ubuntu and wrong in windows.
You can test the project , the site is: [https://github.com/01org/linux-sgx-driver](https://github.com/01org/linux-sgx-driver)

today, i test some other c/c++ project again,  vscode can get symbols in some files。

**Comment by sean-mcmanus** [comment]
I can get symbols on Windows. Can you provide a specific symbol that can't be found?

**Comment by bobbrow** [comment]
@anhkgg, please share the contents of your c_cpp_properties.json file so we can see where the extension is trying to pull symbols from.  Are you using a gcc toolchain on Windows?  If so, please set `"intelliSenseMode"` to `"clang-x64"` in the c_cpp_properties.json file.

**Comment by sean-mcmanus** [comment]
@bobbrow Symbol searching is from the Tag Parser so I don't think the intelliSenseMode matters.

**Comment by anhkgg** [comment]
@bobbrow There is no any *.json，so i don't known what to share.
I 'm not using a gcc toolchain .

**Comment by anhkgg** [comment]
@sean-mcmanus 
i'm almost crazy. i can't get the symbols. Could you share your extension list.

**Comment by sean-mcmanus** [comment]
@anhkgg Use "C/C++: Edit Configuration" to generate the default c_cpp_properties.json. You should kill any dangling Microsoft.VSCode.CPP.* processes -- symbol searching would fail if another process is trying to access the same database. After restarting VS Code you may want to wait till that process is done running (no more red flame) so that you can be sure all the symbols have been parsed. Also, let us know the size of your .browse.vc.db file in your workspaceStorage location or set the databaseFilename to something like "${workspaceRoot}/.vscode/vc.db" for easier access. Does hover or Go to Definition show anything? What is your intelliSenseEngine setting?

**Comment by sean-mcmanus** [comment]
@anhkgg Do you have non-ASCII characters in your file paths? Our stat implementation was changed on Windows for 0.12.2, causing the regression. We should have a fix next week.

**Comment by anhkgg** [comment]
@sean-mcmanus yeah，yeah，good！it's work!

Thank you so much！

Good job for your patience!

Expect next version.

**Comment by bobbrow** [comment]
We released 0.12.3 which has a fix for this.
