### ISSUE TITLE
Should it be an error if browse.path does not contain include directory?

### ISSUE THREAD

**Issue by geertj** [microsoft/vscode-cpptools#9582]
### Feature Request

Consider the following workspace:

```
$ cat src/foo.c
#include <foo.h>
int bar()
{
    return foo(1);
}

$ cat include/foo.h 
int foo(int arg);

$ cat .vscode/c_cpp_properties.json 
{
    "configurations": [
        {   "includePath": [ "${workspaceFolder}/include"  ],
            "browse": { "path": [ "${workspaceFolder}/src" ]  }  }
    ],
    "version": 4
}
```

In this configuration, open the containing directory, and then open "foo.c". VS Code will show error squiggles saying that `<foo.h>` is not in `browse.path`:

![error squiggles](https://user-images.githubusercontent.com/796683/178991621-61998b69-daa9-4e60-9242-93472dfaad5c.png)

The include file itself is resolved using `includePath` because IntelliSense information is available for it. Hovering over the function call shows:

![function prototype](https://user-images.githubusercontent.com/796683/178990742-3f8cc19e-95bf-48b5-a1a9-7e3e5b93a66b.png)

Right clicking on the header file, and selecting "Go to definition" works and opens the file. I can also open `foo.h` using Command+P and typing the name. My question therefore is, does it make sense to require `foo.h` to be in `browse.path`? Are there things that break if `foo.h` is not in `browse.path`?

Related question, this is how I think I would configure a project with the current behavior. Would this be correct?

- `includePath`:
  - All directories normally passed with `-I` to the compiler
- `browse.path`
  - All source directories.
  - All include directories suffixed with `/*` to disable recursion.

If the error would not be shown, I would not duplicate the include directories in `browse.path`.

Versions:
* VS code: `Version: 1.69.1 (Universal)
Commit: b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a
Date: 2022-07-12T08:21:51.333Z (2 days ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin arm64 20.6.0`
* C++ extension: `Version 1.10.8: July 7, 2022`

**Comment by sean-mcmanus** [comment]
Yes, you should have the include paths in the browse.path, because features like Find All References won't be able to find the global symbols in those headers otherwise. You could potentially make that browse.path non-recursive and/or add folders to the C_Cpp.files.exclude setting to avoid parsing the symbols in those files. By default, if no browse.path is added we copy the includePath into the browse.path. Does that answer your questions?
