### ISSUE TITLE
CPPTools allocates >8GB RAM when opening specific .h-file

### ISSUE THREAD

**Issue by Chuvi-w** [microsoft/vscode-cpptools#9583]
### Environment

Environment
- Windows 7 (Always avaiable on Windows 10 too)
- VS Code 1.69.1
- C/C++ Extension 1.11.2

### Bug Summary and Steps to Reproduce

Bug Summary:
cpptools 

Steps to reproduce:
1. git clone https://github.com/dtschump/CImg.git
2. open CImg.h with VSCode. 
3. View memory usage in task manager
4. See that cpptools allocated >8GB of RAM

### Expected behavior

cpptools not to allocate so much memory

### Code sample and Logs

```shell
-------- Diagnostics - 14.07.2022, 19:52:10
Version: 1.11.2
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.22000.0",
    "compilerPath": "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe",
    "cStandard": "c17",
    "cppStandard": "c++17",
    "intelliSenseMode": "windows-msvc-x64",
    "intelliSenseModeIsExplicit": false,
    "cStandardIsExplicit": false,
    "cppStandardIsExplicit": false,
    "mergeConfigurations": false,
    "compilerPathIsExplicit": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ D:\VSCode\cimg\examples\captcha.cpp ]:
    D:\VSCode\cimg\CImg.h *
Translation Unit Configurations:
[ D:\VSCode\cimg\examples\captcha.cpp ]:
    Process ID: 704
    Memory Usage: 9078 MB
    Compiler Path: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
    Includes:
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.29.30133\INCLUDE
        C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\VC\TOOLS\MSVC\14.29.30133\ATLMFC\INCLUDE
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\UM
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\UCRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\SHARED
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\WINRT
        C:\PROGRAM FILES (X86)\WINDOWS KITS\10\INCLUDE\10.0.22000.0\CPPWINRT
        D:\VSCODE\CIMG
    Defines:
        _DEBUG
        UNICODE
        _UNICODE
    Standard Version: ms_c++17
    IntelliSense Mode: windows-msvc-x64
Total Memory Usage: 9078 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 5690
Number of files parsed: 378
```

### Screenshots

https://raw.githubusercontent.com/Chuvi-w/chuvi-w.github.io/master/cpptools-8gb.png

**Comment by sean-mcmanus** [comment]
I'm not reproing this -- there is a known issue with Win7 at https://github.com/microsoft/vscode-cpptools/issues/9144 -- the workaround is to set C_Cpp.intelliSenseCacheSize to 0 -- does that fix your issue or do you believe your issue is different? If that doesn't fix your issue, I can check if others on our team are able to repro the issue.

I'm using VS 2022 cl.exe headers, so maybe the repro might require older VS 2019 headers?

**Comment by Chuvi-w** [comment]
I've looked through previous issues, but I've somehow missed #9144. Sorry for that. 
I've rechecked it on Windows 10 with VS 2022 installed, and got only 3526 MB of Total Memory Usage.

But ~4GB of memory usage, caused by CImg.h probably looks like an issue too.
