### ISSUE TITLE
Cannot pass "-target <arch>" to compilerArgs

### ISSUE THREAD

**Issue by c1rcle** [microsoft/vscode-cpptools#9586]
### Environment

- OS and Version: Windows 11 21H2
- VS Code Version: 1.69.1
- C/C++ Extension Version: 1.10.8

### Bug Summary and Steps to Reproduce

Bug Summary:

Adding `-target <arch>` to `compilerArgs` in c_cpp_properties is impossible as of 1.10.5. I'd like to specify a specific target architecture for the compiler query.

Steps to reproduce:
1. Create a sample source folder with `c_cpp_properties.json`.
2. Specify the path to a clang compiler.
3. Add `-target`, `arm-tizen-linux-gnueabi` to `compilerArgs`.
4. Observe C/++ Configuration Warnings.

### Expected behavior

There should be a way to specify target selection options in `compilerArgs` (it was possible in 1.9.8).

### Code sample and Logs

```shell
{
  "configurations": [
    {
      "name": "tizen-5.5-wearable",
      "includePath": [
        "${workspaceFolder}/inc/**",
        "${workspaceFolder}/compiled_libs/**",
        "${env:TIZEN_STUDIO}/tools/llvm-4.0.0/lib/clang/4.0.0/include/**",
        "${env:TIZEN_STUDIO}/platforms/tizen-5.5/wearable/rootstraps/wearable-5.5-device.core/usr/include/**"
      ],
      "compilerPath": "${env:TIZEN_STUDIO}/tools/llvm-4.0.0/bin/clang.exe",
      "compilerArgs": ["-target", "arm-tizen-linux-gnueabi"],
      "cStandard": "c99"
    }
  ],
  "version": 4
}

Compiler query command line: C:\tizen-studio/tools/llvm-4.0.0/bin/clang.exe arm-tizen-linux-gnueabi -std=c99 -fno-blocks -Wp,-v -E -dM -x c nul
clang.exe: error: no such file or directory: 'arm-tizen-linux-gnueabi'
```

**Comment by sean-mcmanus** [comment]
Fixed with 1.11.3 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.11.3
