### ISSUE TITLE
"C_Cpp.AddDebugConfiguration not found" in a remote macOS -> Windows session

### ISSUE THREAD

**Issue by wrobelda** [microsoft/vscode-cpptools#9587]
### Environment

- OS and version: macOS 12.4
- VS Code: 1.69.1
- C/C++ extension: 1.2.0
- OS and version of remote machine (if applicable): Windows 10.0.19044.1766
- GDB / LLDB version: n/a

### Bug Summary and Steps to Reproduce

Bug Summary:
I am trying to set up a debugger (add additional command line arguments to run the executable with). Compilation and running actually work fine, using the VS2019's debugger. 

However, any "C/C++" extension's command from command palette ends up with the "C_Cpp.AddDebugConfiguration not found" error, in particular the "C/C++: Edit Configurations (JSON)" and "C/C++: Edit Configurations (UI)".

I tried reinstalling the extension on the remote node, to no avail. I checked the FAQ/docs and run out of the idea.

**Comment by Colengms** [comment]
Hi @wrobelda .  Could you try enabling the setting `"C_Cpp.loggingLevel": "Debug"` and checking if there is anything logged to the C/C++ output channel related to this issue?

When none of the C/C++ extension commands work from the command palette, that usually indicates VS Code failed to install the extension properly for some reason, causing it to fail to activate properly.  Simple reinstalling the extension is not sufficient to address that, as VS Code preserves the original installation directory for the extension and reuses it.  I'd suggest deleting the cpptools extension directory (under a `.vscode-server` folder in your user directory on the remote machine), and installing again.

**Comment by wrobelda** [comment]
@Colengms removed the `.vscode-server`, reinstalled all extensions from scratch, still getting same errors unfortunately.

**Comment by Colengms** [comment]
Hi @wrobelda .  Can you provide more information about your environment?  When you open a C or C++ file, does the C/C++ extension try to activate and provide IntelliSense?  Does it output anything to the C/C++ output log, with logging set to Debug as I mentioned previously?  If so, the contents of that log could be useful.

We are not currently tracking any general issues preventing the extension from running on macOS.
