### ISSUE TITLE
After version 1.8.4, launch.json cannot be automatically generated when starting debugging

### ISSUE THREAD

**Issue by runewrz** [microsoft/vscode-cpptools#9588]
### Environment

- OS and version:Windows 11 21H2 22000.795
- VS Code:1.69.1
- C/C++ extension:1.11.2
- OS and version of remote machine (if applicable):
- GDB / LLDB version:gdb 12.1

### Bug Summary and Steps to Reproduce

With the plugin of version 1.8.4, when there is no .vscode folder, launch.json and tasks.json will be automatically generated after starting debugging (after pressing F5);
But with plugins after version 1.8.4 (such as 1.11.2), only tasks.json will be generated after debugging is started.

### Debugger Configurations

```shell
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: g++.exe 生成活动文件",
            "command": "C:\\msys64\\mingw64\\bin\\g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe",
                "-Wall",
                "-Wl,--stack=268435456",
                "-D_GLIBCXX_DEBUG",
                "-D_GLIBCXX_DEBUG_PEDANTIC"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "调试器生成的任务。"
        }
    ],
    "version": "2.0.0"
}
```

### Debugger Logs

```shell
//
```

**Comment by sean-mcmanus** [comment]
This is "by design". You can generate the "launch.json" via the gear icon in the top right, if C_Cpp.debugShortcut is set to true. Other potential improvements are being tracked by: https://github.com/microsoft/vscode-cpptools/issues/9382

![image](https://user-images.githubusercontent.com/19859882/179295446-53289288-d031-4307-9e25-0f1dbb4f11de.png)
