### ISSUE TITLE
out-of-order initializers are nonstandard in C++

### ISSUE THREAD

**Issue by dortamiguel** [microsoft/vscode-cpptools#9592]
### Environment

- OS and Version: Windows 11
- VS Code Version: 1.69.1
- C/C++ Extension Version: v1.10.8
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I get this error message only Windows, on Macos is fine.

### Bug Summary and Steps to Reproduce

Bug Summary:
If you initialize a struct with unordered members the linter on vscode will complain, though the compiler works fine.

Steps to reproduce:
1. Write a .cpp file with the following code

```c++
    struct Foo {
        int a, b;
    };

    Foo foo = {
        .b = 1,
        .a = 1,
    };

```

The you will see the error in the line where the variable `a` gets initialized
```
Foo{.b = (int)1, .a = (<error-type>)<error-constant>} out-of-order initializers are nonstandard in C++
```

### Expected behavior

I don't get the error in the editor

### Code sample and Logs

```shell
++
    struct Foo {
        int a, b;
    };

    Foo foo = {
        .b = 1,
        .a = 1,
    };
```

### Additional context

I'm using the following settings for the extension

```json
{
  "C_Cpp.default.cppStandard": "c++20",
}
```

**Comment by ellipticaldoor** [comment]
Okay, I just had to set my compiler to path to clang++

```c++
"C_Cpp.default.compilerPath": "C:\\msys64\\mingw64\\bin\\clang++.exe",
```
