### ISSUE TITLE
[New Feature] Allow bash environment variable to be used in configuration

### ISSUE THREAD

**Issue by gaodingpan** [microsoft/vscode-cpptools#9597]
Currently, when configuring C/C++ include/browse or dotconfig paths, bash environment variables are not allowed, only vscode variables like ${workspaceFolder} can be recognized. This can be a bit troubling when there are multiple dotconfig paths(using bash environment variable to distinguish different options, e.g debug build/release build) in the same workspace. Support of using bash environment variable to configure such paths is much desired.

**Comment by Colengms** [comment]
Hi @gaodingpan .  Thanks for suggesting this.  We will consider this for our backlog.  Upvotes would increase its priority.
