### ISSUE TITLE
Honor *.exclude settings

### ISSUE THREAD

**Issue by csholmq** [microsoft/vscode-cpptools#96]
The indexing doesn't seem to honor the *.exclude settings and simply indexes all files within the project.

```
"search.exclude": {
    "**/out": true
},
"files.exclude": {
    "**/out": true
},
```

It would be nice if one could exclude the build directory (in my case **/out) as it only gives me grief and multiple matches.

**Comment by jgoshi** [comment]
This is now fixed and will appear in the next release (version 0.9.0)
