### ISSUE TITLE
Auto-Completion has some error

### ISSUE THREAD

**Issue by Kurt-Shiwz** [microsoft/vscode-cpptools#960]
Auto-Completion has some error,can't suggest right word
<img width="506" alt="qq20170809-001127 2x" src="https://user-images.githubusercontent.com/7554917/29082470-34885ce8-7c98-11e7-8d02-065ed7f87f21.png">

**Comment by bobbrow** [comment]
Did you set `"intelliSenseEngine": "Default"` in your settings.json file?  You currently have to opt-in to the new IntelliSense engine which does give back the exact results for structs, classes, and namespaces.

**Comment by sean-mcmanus** [comment]
@Kurt-Shiwz Also, the "Tag Parser" (fuzzy) autocomplete is expected to give too many results, although the t should be found after typing t.

**Comment by FMLS** [comment]
I have been set "intelliSenseEngine": "Default", but it appears the same error, show me a large list that content isn't what I expect, I set "C_Cpp.autocomplete": "Default" too

**Comment by bobbrow** [comment]
@FMLS, it is still expected to get a large list if you are typing variable/class names.  The Default intelliSenseEngine provides suggestions for class/struct/namespace members (e.g. after you type `.`, `->`, `::`) everything else is still using the Tag Parser.

**Comment by vscpp** [comment]
Same error happened on my computer. IntelliSense Engine can't identify the structure member, always show a large list.
I have set ""C_Cpp.intelliSenseEngine": "Default",". I deleted the symbols folder in C:\Users\XXX\AppData\Roaming\Code\User\workspaceStorage, and re-parse the code by C/C++ extension tool, but have no effect.
(Windows Server 2012 R2, VS code 1.14.2, C/C++ extension 0.12.2)

**Comment by sean-mcmanus** [comment]
@vscpp It sounds like you are falling back to the "Tag Parser" due to missing includePath paths that can't be found. What does it show in your Problems window?

**Comment by vscpp** [comment]
@sean-mcmanus I checked the error message, seems Intellisense force to switch to "Tag Parser".
I am a UEFI BIOS developer, the UEFI has its own rules of grammar. UEFI define .dec file which include the include path, UEFI build tool will parse all header file by its rule.
So seems it's difficult for VS code.

But Source Insight works, I believe VS code C++ extension will be more better than SI. :)
![image](https://user-images.githubusercontent.com/26138585/29201886-18e76a20-7e95-11e7-9d71-c6891421b2ef.png)

**Comment by sean-mcmanus** [comment]
@vscpp I don't really understand. Are your header files actual files with a path you can add to the c_cpp_properties.json includePath setting? If not, you can turn the intelliSenseEngineFallback setting to "Disabled", although you might get error squiggles about unknown identifiers.

**Comment by Kurt-Shiwz** [comment]
@sean-mcmanus why can't just prompt t?
![2017-08-12 15 28 10](https://user-images.githubusercontent.com/7554917/29238937-f9a8cc06-7f72-11e7-81f5-e2eaf04055d9.jpg)
![2017-08-12 15 29 34](https://user-images.githubusercontent.com/7554917/29238938-f9ab1bb4-7f72-11e7-8e87-c5551caf72ce.jpg)

**Comment by bobbrow** [comment]
@Kurt-Shiwz the Tag Parser can't just prompt "t" because it doesn't know the type of the variable on the left side of the `.`.  It just returns a list of all symbols that have been parsed that could be used as a member of something.  The "default" IntelliSense engine knows the type, so it can suggest just "t".
