### ISSUE TITLE
Use compiler predefined command information from CMake

### ISSUE THREAD

**Issue by go2sh** [microsoft/vscode-cpptools#9615]
### Feature Request

CMake added a variable (CMAKE_\<LANG\>_COMPILER_PREDEFINES_COMMAND), which holds the command to get the compiler predefined values. CMake could provide this to the cpptools extension to use it for the gathering of predefined values.

**Comment by Colengms** [comment]
Hi @go2sh .  Thank you for suggesting this.  We will consider this for our backlog.
