### ISSUE TITLE
Inlay hint parameter match filtering can stop working when a lambda with a for loop is passed to a function

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#9619]
### Environment

- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):  
- If using SSH remote, specify OS of remote machine:  
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

### Bug Summary and Steps to Reproduce

The filtering out of parameters with matching names doesn't work with the repro code (j inlay hint is still shown).

### Code sample and Logs

```shell
#include <functional>

int func(int i, std::function<void()> f, int j)
{
    int i, j;
    func(i,
        []{
        for(int i = 0; i < 10; ++i){}
        },
        j);
}
```

**Comment by bobbrow** [comment]
Closing stale issue with narrow repro steps and no upvotes.
