### ISSUE TITLE
command'c_Cpp.ConfigurationEditUl' not found with win10

### ISSUE THREAD

**Issue by xinmu123456** [microsoft/vscode-cpptools#9623]
### Environment

- OS : Windows10 
- VS Code: version 1.69
- C/C++ extension: v1.11.4

### Bug Summary and Steps to Reproduce

Bug Summary:

**I can't open c_cpp_properties.json using CTRL + Shift + P**

![image](https://user-images.githubusercontent.com/96987156/180354716-5dd5a79f-b5c1-46fc-bcd8-ab2f5b58a4ee.png)
![image](https://user-images.githubusercontent.com/96987156/180354769-bc9b61b7-1910-49c8-ac37-6079584b1c16.png)

**And I discovered the solution and what caused it**

![image](https://user-images.githubusercontent.com/96987156/180355313-cfea53b4-0b28-4755-9422-7c151dd89aff.png)

Like the screenshot above, if I disable it, I can not open c_cpp_properties.json

To open the c_cpp_properties.json file, I have to take this option **Default**

![image](https://user-images.githubusercontent.com/96987156/180355813-24269e21-582d-4a41-9d13-6aa038c8eee3.png)

Now I can open c_cpp_properties.json, but I don't know how it works

**Comment by sean-mcmanus** [comment]
We are already tracking this issue with https://github.com/microsoft/vscode-cpptools/issues/9614
