### ISSUE TITLE
Variadic Macros named __VA_ARGS__ not supported by Default parser

### ISSUE THREAD

**Issue by poseidon4o** [microsoft/vscode-cpptools#9626]
### Environment

- OS and Version: macOS 12.4
- VS Code Version: June 2022 (version 1.69)
- C/C++ Extension Version: 1.11.4: July 21, 2022
- Other extensions you installed (and if the issue persists after disabling them):  repro without any other extensions
- If using SSH remote, specify OS of remote machine:  repro locally, and also on remote linux

### Bug Summary and Steps to Reproduce

Bug Summary:
Default parser does not support named variadic arguments in macros as referenced here https://gcc.gnu.org/onlinedocs/cpp/Variadic-Macros.html

Steps to reproduce:
1. Make source file containing only `#define eprintf(args...) fprintf (stderr, args)`
2. The C/C++ extension logs this:
```
  tag parsing file: /Users/poseidon4o/workspace/main.cpp
    tag parsing error (this can be ignored unless symbols can't be found):
    line 2 (col. 21): error: expected a ')'
```

### Expected behavior

The Default parser should treat the named variadic arguments as if they were __VA_ARGS__

### Code sample and Logs

```shell
tag parsing file: /Users/poseidon4o/workspace/main.cpp
    tag parsing error (this can be ignored unless symbols can't be found):
    line 1 (col. 21): error: expected a ')'
```

**Comment by sean-mcmanus** [comment]
What is the error you're experiencing? I believe the logging message can just be ignored as it mentions, since no symbols are missing. Our "tag parser" mode always executes on a general mode that doesn't take into account specific language extensions such as the one used here, which is a gcc extension.
