### ISSUE TITLE
Files with a .c extension sent "/std:c++17" in compilerFragments incorrectly get interpreted as C instead of C++

### ISSUE THREAD

**Issue by sean-mcmanus** [microsoft/vscode-cpptools#9628]
### Environment

- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):  
- If using SSH remote, specify OS of remote machine:  
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

### Bug Summary and Steps to Reproduce

We have an internal repro using CMake Tools. With cl.exe. It manifested as a result of https://github.com/microsoft/vscode-cmake-tools/pull/1696 .

### Code sample and Logs

```shell
internal repro
```

**Comment by Colengms** [comment]
This applies to compile_commands.json configs and custom configurations from a custom configuration provider (when they include a compilerPath and args/fragments and no language standard version).  In those cases, we have file-specific command lines.

**Comment by sean-mcmanus** [comment]
Fixed with 1.12.0 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.12.0
