### ISSUE TITLE
"C_Cpp.errorSquiggles" option doesn't work

### ISSUE THREAD

**Issue by vscpp** [microsoft/vscode-cpptools#963]
I set C_Cpp.intelliSenseEngine to default, and set C_Cpp.errorSquiggles to Disabled.
But error squiggles still display in my code. seems C_Cpp.errorSquiggles doesn't work.

Because my project include 3 git repo, usually, I only open one folder (repo), so it's expected that intellisense engine can't locate .h head file. I think the C_Cpp.errorSquiggles can control error squiggles, but it's not.

![image](https://user-images.githubusercontent.com/26138585/29158343-3d15645a-7ddd-11e7-9b17-f8357b7bf23e.png)

**Comment by bobbrow** [comment]
This is expected.  We have no other way to tell you that the IntelliSense engine is working with partial information.  If you update your includePath to point to the folder that contains `Library`, then the squiggles will go away, and you will be able to get IntelliSense information about the symbols defined in those includes.

![squiggles](https://user-images.githubusercontent.com/12818240/29178043-3fd74c0e-7da5-11e7-8b21-87d6c399d6bf.png)
