### ISSUE TITLE
C/C++ formatter stuck as #6809

### ISSUE THREAD

**Issue by b05902034** [microsoft/vscode-cpptools#9631]
### Environment

- OS and version: macOS Monterey 12.0.1
- VS Code: 1.69.2
- C/C++ extension: v1.11.4

### Bug Summary and Steps to Reproduce

Bug Summary:

same issue as #6809
and I check that its cpptools using CPU but I can't find C_Cpp.loggingLevel in settings

**Comment by sean-mcmanus** [comment]
The formatting getting stuck is likely due to another system blocking the formatting operation. C_Cpp.loggingLevel is available as a user/workspace setting (not workspace folder). If cpptools is using CPU, can you attach a debugger to get a call stack for the thread that appears to be doing work? https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv

**Comment by b05902034** [comment]
I can't activate the debugger to check if cpptools executed correctly
but I used activity monitor to get sum sample as follow
hope this would be [cpptools call stack sample.txt](https://github.com/microsoft/vscode-cpptools/files/9209635/cpptools.call.stack.sample.txt)

**Comment by sean-mcmanus** [comment]
The call stacks doesn't show any formatting, but it shows IntelliSense process creation. Are you able to wait for IntelliSense to be finished updating before running the format command? It also shows it's trying to use recursive includes, so you may want to remove any paths with "**" from your include path to stop using recursive includes, which could be faster.

**Comment by b05902034** [comment]
I used lldb to get the log
> log while calling lldb
(lldb) process attach --pid 2631
Process 2631 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00007ff806a9a33a libsystem_kernel.dylib`__read_nocancel + 10
libsystem_kernel.dylib`__read_nocancel:
->  0x7ff806a9a33a <+10>: jae    0x7ff806a9a344            ; <+20>
    0x7ff806a9a33c <+12>: movq   %rax, %rdi
    0x7ff806a9a33f <+15>: jmp    0x7ff806a992f1            ; cerror_nocancel
    0x7ff806a9a344 <+20>: retq   
Target 0: (cpptools) stopped.

Executable module set to "/Users/username/.vscode/extensions/ms-vscode.cpptools-1.12.0-darwin-x64/bin/cpptools".
Architecture set to: x86_64h-apple-macosx-.

**Comment by b05902034** [comment]
I used lldb to get the call stack as @lucasaf04 
<img width="562" alt="截圖 2022-08-14 09 12 51" src="https://user-images.githubusercontent.com/43400807/184518437-c428b24f-00a1-41ec-bd24-f5fccfc1f96a.png">
It seems like it's stuck
