### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by susheelv1989** [microsoft/vscode-cpptools#9634]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `1.11.4`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.69.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/91720/AppData/Local/Temp/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment]
The file isn't attached.
