### ISSUE TITLE
problemMatcher in vscode-cpptools fails to open warnings in files while using nested makefiles and gcc

### ISSUE THREAD

**Issue by basiljoseph** [microsoft/vscode-cpptools#964]
- Visual Studio Code 1.14.2
- Extensions:  cpptools
- OS: Windows 10 1607(14393.1358) x64

I have asked this question earlier on stackoverflow.
https://stackoverflow.com/questions/45594118/file-not-found-error-on-visual-studio-code-when-clicking-on-problems-window-usi

When using nested makefiles to compile a binary using gcc, the warnings produced by the makefiles in sub directories are captured in the problem tab.
But clicking on them shows a "File not found error"
VS Code IDE is not considering the sub folders in the path, although Eclipse IDE is properly handling them.

I have tried different combinations on the fileLocation field provided at https://code.visualstudio.com/docs/editor/tasks#_variable-substitution
But they dont work.
My current tasks.json looks like this.

```
{
    "version": "2.0.0",
    "tasks": [
        {
            "taskName": "make",
            "command": "make",
            "type": "shell",
            "problemMatcher": {
                "base": "$gcc",
                "fileLocation": ["relative","${workspaceRoot}"]
            }
        }
    ]
}
```
Is there any workaround available to open the file when clicking the warnings in problem tab?

**Comment by sean-mcmanus** [comment]
The only thing the C++ extension does is define the gcc problem matcher. I'm not aware of a workaround. Can you try filing an issue with VS Code itself? Such as http://stackoverflow.com/questions/tagged/vscode (or https://github.com/Microsoft/vscode/issues if it's a bug or feature request) .

**Comment by basiljoseph** [comment]
It looks like this is a [known issue](https://github.com/Microsoft/vscode/issues/11663) in VS Code itself.
So I will close this, hoping the original issue will get fixed soon.
