### ISSUE TITLE
Cann't find rename symbol menu item, F2 is not working

### ISSUE THREAD

**Issue by elxxnpn** [microsoft/vscode-cpptools#965]
When I write C++ code, I select the functions that need to be renamed, press F2, do not pop up the renamed small form, right-click menu, nor rename the options. But when I write Python code, select the need to rename the function name, press F2, small form will pop up rename, right-click menu can see rename symbols after the rename option, press Enter all refer to this function file will be updated.

**Comment by sean-mcmanus** [comment]
We haven't implemented rename yet. See https://github.com/Microsoft/vscode-cpptools/issues/296 .

**Comment by elxxnpn** [comment]
I got it, Thank you very much! Hope to provide this function as soon as possible.
