### ISSUE TITLE
Anonymous unions and structs don't display while debugging [MacOS - LLDB]

### ISSUE THREAD

**Issue by dirondin** [microsoft/vscode-cpptools#966]
Example of struct:
```cpp
struct AnonUnion
{
    union {
        int x;
        int y;
    };
} au;
```
Reproduce steps:
1. Build code with example struct under MacOS (Xcode).
2. Debug it by LLDB.
3. Watch `au` variable while debugging and try to display it's content in Variable/Watch/Debug console windows.

Expected result:
Display fields in anonymous union/struct as fields of parent struct or display they as child node with name '<anonymous union/struct>'.

Example of code and screenshot available on: https://github.com/dirondin/anon-union-test.

PS. If you use MI for watching variable maybe this Issue will be interesting for you: [Correctly identify anonymous-union variable](https://github.com/Microsoft/MIEngine/pull/642).

**Comment by pieandcakes** [comment]
@dirondin I can take the change you linked above and see if it still occurs.

**Comment by dirondin** [comment]
@pieandcakes, hello.
I saw this fix is included in version 0.12.4.
After update I checked case from my repo (https://github.com/dirondin/anon-union-test) under MacOS (lldb) and problem reproduced unfortunately 😞 
![image](https://user-images.githubusercontent.com/8371890/30417207-9e4e69f4-9937-11e7-9621-6a60eebdef55.png)

**Comment by pieandcakes** [comment]
I'll reopen it. Will have to step into the lldb path when I have some time to investigate this but it probably won't be right away.

**Comment by pieandcakes** [comment]
This should be fixed. please reopen if it isn't . I tried with the code in your screenshot and it works for me.
