### ISSUE TITLE
command 'C_Cpp.ConfigurationEditJSON' not found

### ISSUE THREAD

**Issue by zgxgoo** [microsoft/vscode-cpptools#9668]
### Environment

- OS and version: mac os Big Sur
- VS Code:
- C/C++ extension:
- OS and version of remote machine (if applicable):
- GDB / LLDB version:

OS and version: mac os Big Sur
VS Code:1 .69.2
C/C++ extension: v1.11.4
OS and version of remote machine (if applicable):local

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. In this environment...
2. With this config...
3. Do ' c/c++: edit configurations(ui/jason)'
4. See error 命令"C/C++: 编辑配置(UI)"导致错误 (command 'C_Cpp.ConfigurationEditUI' not found)
命令"C/C++: 编辑配置(JSON)"导致错误 (command 'C_Cpp.ConfigurationEditJSON' not found)

### Debugger Configurations

```shell
no task.json and launch.json
```

### Debugger Logs

```shell
none
```

**Comment by Colengms** [comment]
Hi @zgxgoo .  Could you try upgrading to the 1.12.0 prerelease version and let us know if the issue still exists?  If the issue is because IntelliSense has been disabled via a setting, 1.12.0 should indicate that correctly instead of using the generic 'command not found' error message.
