### ISSUE TITLE
vscode squiggles all includes and claims that it can't find <list>, <cstddef> or other file

### ISSUE THREAD

**Issue by ineffective** [microsoft/vscode-cpptools#9669]
### Environment

- OS and Version: Windows 10
- VS Code Version: 1.69.2
- C/C++ Extension Version:
  Name: C/C++
  Id: ms-vscode.cpptools
  Description: C/C++ IntelliSense, debugging, and code browsing.
  Version: 1.11.4
  Publisher: Microsoft
  VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools
- Other extensions you installed (and if the issue persists after disabling them):

Below is listing of ~/.vscode/extensions directory:
ms-vscode.cmake-tools-1.4.0
ms-vscode.cpptools-0.28.1
vscodevim.vim-1.14.5

- If using SSH remote, specify OS of remote machine:  Debian 9.13
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

I use custom installation of g++ (x86_64-linux-gnu-g++-9.2.0), boost (1.71.0 and some other libraries installed in non-standard location (/opt/ZS/deps/). File c_cpp_properties.json points compileCommands to proper (vscode finds it) compile_commands.json file. "C/C++" output shows that custom directory /opt/ZS/deps/include is scanned and a number of files is read. At the same time VSCode can't find most of includes, not even <string> or <list> (depending on which *.cpp file is opened).

### Bug Summary and Steps to Reproduce

Bug Summary:

I use custom installation of g++ (x86_64-linux-gnu-g++-9.2.0), boost (1.71.0 and some other libraries installed in non-standard location. IntelliSense (at least I assume it is IntelliSense) claims to be unable to find headers (e.g. <list>, <cstddef>), but at the same time shows that these files were parsed (part of C/C++ debug output, ):

  tag parsing file: /opt/ZS/deps/include/c++/9.2.0/memory
  tag parsing file: /opt/ZS/deps/include/c++/9.2.0/tr1/memory
  tag parsing file: /opt/ZS/deps/include/c++/9.2.0/ext/memory
  tag parsing file: /opt/ZS/deps/include/c++/9.2.0/experimental/memory
  tag parsing file: /opt/ZS/deps/include/c++/9.2.0/list <<=== NOTE: vscode can't find this file (or "memory" above, does not matter)
  tag parsing file: /opt/ZS/deps/include/c++/9.2.0/profile/list
  tag parsing file: /opt/ZS/deps/include/c++/9.2.0/experimental/list
  tag parsing file: /opt/ZS/deps/include/c++/9.2.0/debug/list
  tag parsing file: /opt/ZS/deps/include/c++/9.2.0/utility

File that is purposely missing is different depending on which source file I open. I understand that some files (e.g. header only libraries) do not compile on their own (there are other bug reports regarding it), but as attached screenshot show it happens even if `#include <iostream>` is first line in file - it can't be found. (NOTE: C/C++ Log Diagnostics and Language Server Loggin below are for different files, but whatever I do it ends the same).

Steps to reproduce:

I can't think of doing it in any other setup that one that we use in our company, sorry.

### Expected behavior

I expect intelliSense not to claim that it can't find files that were reported as scanned 30 seconds ago.

### Code sample and Logs

```shell
c_cpp_properties.json:

{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "compilerPath": "",
            "cStandard": "c11",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64",
            "configurationProvider": "ms-vscode.cmake-tools",
            "compileCommands": "${workspaceFolder}/.build-x86_64/compile_commands.json"
        }
    ],
    "version": 4
}
----------------------------
TOOLCHAIN FILE THAT I USE:

set(CMAKE_C_COMPILER x86_64-linux-gnu-gcc-9.2.0 CACHE INTERNAL "Path to C compiler")
set(CMAKE_CXX_COMPILER x86_64-linux-gnu-g++-9.2.0 CACHE INTERNAL "Path to C++ compiler")
set(PKG_CONFIG_EXECUTABLE pkg-config)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED YES)

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR amd64)

set(CMAKE_SYSTEM_VERSION 1)

set(THREADS_PTHREAD_ARG -pthread)
set(BOOST_ROOT "/opt/ZS/deps/include")
set(BOOST_INCLUDEDIR "/opt/ZS/deps/include")
set(BOOST_LIBRARYDIR "/opt/ZS/deps/x86_64-linux-gnu/lib/")
set(CMAKE_SKIP_BUILD_RPATH FALSE)
set(CMAKE_SKIP_RPATH OFF)
set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
set(CMAKE_INSTALL_RPATH_USE_LINK_PATH ON)
set(CMAKE_BUILD_RPATH "/opt/ZS/deps/x86_64-linux-gnu/lib/:/opt/ZS/deps/lib64:/opt/ZS/deps/lib")
set(CMAKE_INSTALL_RPATH "/opt/ZS/deps/x86_64-linux-gnu/lib/:/opt/ZS/deps/lib64:/opt/ZS/deps/lib")


---------------------------
"C/C++: Log Diagnostics":

-------- Diagnostics - 8/2/2022, 1:55:53 PM
Version: 1.11.4
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "compilerPath": "",
    "cStandard": "c11",
    "cppStandard": "gnu++17",
    "intelliSenseMode": "linux-gcc-x64",
    "configurationProvider": "ms-vscode.cmake-tools",
    "compileCommands": "${workspaceFolder}/.build-x86_64/compile_commands.json",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "/home/jd/code/masters-thesis/code/.build-x86_64/CMakeFiles",
        "/home/jd/code/masters-thesis/code/lang-spec",
        "/home/jd/code/masters-thesis/code",
        "/home/jd/code/masters-thesis/code/inc",
        "/opt/ZS/deps/include",
        "/home/jd/code/masters-thesis/code/src",
        "/home/jd/code/masters-thesis/code/src/passes"
    ],
    "compilerPath": "/usr/local/bin/x86_64-linux-gnu-g++-9.2.0",
    "compilerArgs": [],
    "compilerFragments": [
        "-g",
        "-Wall",
        "-Wextra",
        "-pedantic",
        "-g3",
        "-ggdb",
        "-DQUEX_OPTION_ASSERTS_WARNING_MESSAGE_DISABLED_EXT",
        "-std=gnu++17"
    ]
}
Custom configurations:
[ /home/jd/code/masters-thesis/code/src/main.cpp ]
{
    "includePath": [
        "/home/jd/code/masters-thesis/code",
        "/home/jd/code/masters-thesis/code/lang-spec",
        "/home/jd/code/masters-thesis/code/inc",
        "/opt/ZS/deps/include"
    ],
    "defines": [],
    "compilerPath": "/usr/local/bin/x86_64-linux-gnu-g++-9.2.0",
    "compilerArgs": [],
    "compilerFragments": [
        "-g",
        "-Wall",
        "-Wextra",
        "-pedantic",
        "-g3",
        "-ggdb",
        "-DQUEX_OPTION_ASSERTS_WARNING_MESSAGE_DISABLED_EXT",
        "-std=gnu++17"
    ]
}
[ /home/jd/code/masters-thesis/code/src/symbol_info.cpp ]
{
    "includePath": [
        "/home/jd/code/masters-thesis/code",
        "/home/jd/code/masters-thesis/code/lang-spec",
        "/home/jd/code/masters-thesis/code/inc",
        "/opt/ZS/deps/include"
    ],
    "defines": [],
    "compilerPath": "/usr/local/bin/x86_64-linux-gnu-g++-9.2.0",
    "compilerArgs": [],
    "compilerFragments": [
        "-g",
        "-Wall",
        "-Wextra",
        "-pedantic",
        "-g3",
        "-ggdb",
        "-DQUEX_OPTION_ASSERTS_WARNING_MESSAGE_DISABLED_EXT",
        "-std=gnu++17"
    ]
}
Translation Unit Mappings:
[ /home/jd/code/masters-thesis/code/src/main.cpp ]:
    /home/jd/code/masters-thesis/code/src/main.cpp
    /opt/ZS/deps/include/boost/filesystem/string_file.hpp *
    /opt/ZS/deps/include/boost/filesystem/fstream.hpp *
    /opt/ZS/deps/include/boost/config.hpp *
[ /home/jd/code/masters-thesis/code/src/symbol_info.cpp ]:
    /home/jd/code/masters-thesis/code/src/symbol_info.cpp
    /home/jd/code/masters-thesis/code/inc/scope_context.hpp *
Translation Unit Configurations:
[ /home/jd/code/masters-thesis/code/src/main.cpp ]:
    Process ID: 20910
    Memory Usage: 330 MB
    Includes:
        /home/jd/code/masters-thesis/code
        /home/jd/code/masters-thesis/code/lang-spec
        /home/jd/code/masters-thesis/code/inc
        /opt/ZS/deps/include
    Defines:
        QUEX_OPTION_ASSERTS_WARNING_MESSAGE_DISABLED_EXT
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=103000
[ /home/jd/code/masters-thesis/code/src/symbol_info.cpp ]:
    Process ID: 20978
    Memory Usage: 330 MB
    Includes:
        /home/jd/code/masters-thesis/code
        /home/jd/code/masters-thesis/code/lang-spec
        /home/jd/code/masters-thesis/code/inc
        /opt/ZS/deps/include
    Defines:
        QUEX_OPTION_ASSERTS_WARNING_MESSAGE_DISABLED_EXT
    Standard Version: c++17
    IntelliSense Mode: linux-gcc-x64
    Other Flags:
        --g++
        --gnu_version=103000
Total Memory Usage: 660 MB
Browse Paths from compile_commands.json, from workspace folder: /home/jd/code/masters-thesis/code
    /home/jd/code/masters-thesis/code
    /home/jd/code/masters-thesis/code/.build-x86_64/CMakeFiles
    /home/jd/code/masters-thesis/code/inc
    /home/jd/code/masters-thesis/code/lang-spec
    /home/jd/code/masters-thesis/code/src
    /home/jd/code/masters-thesis/code/src/passes
    /opt/ZS/deps/include

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 15387
Number of files parsed: 2120
```

### Screenshots

![image](https://user-images.githubusercontent.com/8870983/182371217-e49c64fd-735b-4908-aa55-8727425e7838.png)

**Comment by ineffective** [comment]
Attached is language server log, as it was too big for literal inclusion and I couldn't for some reason attach it.

[language-server-log-2022-08-02.txt](https://github.com/microsoft/vscode-cpptools/files/9242088/language-server-log-2022-08-02.txt)

**Comment by sean-mcmanus** [comment]
Hmm, the logging shows "Skipping query of compiler due to explicitly empty compilerPath" -- that appears to be what is causing the issue. Can you try removing `"compilerPath": "",` from your c_cpp_properties.json?

**Comment by ineffective** [comment]
> Hmm, the logging shows "Skipping query of compiler due to explicitly empty compilerPath" -- that appears to be what is causing the issue. Can you try removing `"compilerPath": "",` from your c_cpp_properties.json?

I removed it and it works like a charm. Also reading about `compilerPath` settings makes it _nearly_ obvious what was happening. Thank you for help and sorry for the noise.

I suppose on one hand setting empty `compilerPath` is a good candidate for a warning as it leads to aforementioned situation, but on the other hand most people how do have it empty put it there on purpose and warning would be confusing as it is absolutely valid configuration, so there is no great solution I guess.

Anyway, thank you once again and thanks for extremely useful tool.
