### ISSUE TITLE
lldb debugger crashes on MacOS when hover over member variable in C++ code

### ISSUE THREAD

**Issue by greylight61** [microsoft/vscode-cpptools#967]
MacOS Sierra 10.12.6,  VS Code v1.15.0,  C/C++ Extension v 0.12.2

For a particular class in my app, the debugger will crash when I attempt to hover over a variable to see its value. Examining variables in other classes appears to work fine.

Steps to reproduce:
- Place a breakpoint in a C++ instance function for a particular class (MyWindow).
- Launch the debugger from VS Code (F5).
- When the breakpoint hits, move the mouse to hover over a member variable (e.g. m_bCreatedCalled) that is a member of "this" (an instance of MyWindow).
- Debugger crashes with the error/output in the DEBUG CONSOLE (see below):

The variables in the "VARIABLES" pane are shown correctly, and you can expand "this" to see the correct value for the member variable the mouse was hovering over.  Additionally, you can step through code without it crashing.

The "this" pointer is an instance of MyWindow, but the error refers to an instance of Session, and the MyWindow class has references to Session, but Session not used in the member function where the breakpoint is located.

If I have a breakpoint in other classes and hover over a member variable, it does *not* crash.

DEBUG CONSOLE OUTPUT:
-------
1: (25457) <-1037-var-create - - "m_bCreateCalled" --thread 1 --frame 0
1: (25572) STDERR: error: Session.o Parsing a die that is being parsed die: 0x00020604: DW_TAG_class_type __deque_iterator<void (Session::*)(), void (Session::**)(), void (Session::*&)(), void (Session::***)(), long, 256>
1: (25573) STDERR: error: Session.o Parsing a die that is being parsed die: 0x00020604: DW_TAG_class_type __deque_iterator<void (Session::*)(), void (Session::**)(), void (Session::*&)(), void (Session::***)(), long, 256>
1: (25574) STDERR: error: Session.o Parsing a die that is being parsed die: 0x00020604: DW_TAG_class_type __deque_iterator<void (Session::*)(), void (Session::**)(), void (Session::*&)(), void (Session::***)(), long, 256>

... ~ 20 similar lines ...

1: (25579) STDERR: error: Session.o Parsing a die that is being parsed die: 0x00020604: DW_TAG_class_type __deque_iterator<void (Session::*)(), void (Session::**)(), void (Session::*&)(), void (Session::***)(), long, 256>
1: (25579) STDERR: error: Session.o Parsing a die that is being parsed die: 0x00020604: DW_TAG_class_type __deque_iterator<void (Session::*)(), void (Session::**)(), void (Session::*&)(), void (Session::***)(), long, 256>
1: (25961) "/Users/username/.vscode/extensions/ms-vscode.cpptools-0.12.2/debugAdapters/lldb/bin/lldb-mi" exited with code 139 (0x8B).
1: (25965) <-logout
ERROR: LLDB exited unexpectedly with exit code 139 (0x8B). Debugging will now abort.
The program '/Users/username/MyApp/MyApp.app/Contents/MacOS/MyApp' has exited with code -1 (0xffffffff).
--------

I'm using the following task in launch.json:
{
    "name": "(lldb) Launch MyApp",
    "type": "cppdbg",
    "request": "launch",
    "program": "${workspaceRoot}/MyApp/MyApp.app/Contents/MacOS/MyApp",
    "args": [],
    "stopAtEntry": false,
    "cwd": "${workspaceRoot}",
    "environment": [],
    "externalConsole": true,
    "MIMode": "lldb",
    "logging": { "engineLogging": true }
}

Workspace settings:
{
    "files.associations": {
        "ios": "cpp",
        "cstddef": "cpp"
    },
    "debug.allowBreakpointsEverywhere": true
}

**Comment by pieandcakes** [comment]
@greylight61 Do you by chance have a good repro that I can do for this? I can't seem to reproduce it.

**Comment by pieandcakes** [comment]
Thank you for reporting an issue. We do not have enough information at this time to act upon this issue. Please try our latest version and if it is still occuring, provide more information including configurations, logs and version information and reopen this issue.
