### ISSUE TITLE
Enable the extension will make minimap selectionOccurrenceHighlight not working

### ISSUE THREAD

**Issue by reubenzh** [microsoft/vscode-cpptools#9674]
### Environment

- OS and Version:
- VS Code Version:
- C/C++ Extension Version:
- Other extensions you installed (and if the issue persists after disabling them):  
- If using SSH remote, specify OS of remote machine:  
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

### Bug Summary and Steps to Reproduce

Bug Summary:
Double click a variable will trigger highlighting for all the same name variables in the default vs code minimap.
However, after enabling the extension, this highlighting will lose effect.

Steps to reproduce:
1. Go to Settings.json without enable the extension
2. Enable minimap highlighting by the following settings: 
```
workbench.colorCustomizations": {
        "minimap.selectionOccurrenceHighlight": "#00bbd0",
}
```
3. Open a C++ file, double click any variable in the text editor, note that all the same name variable will be highlighted with blue color
4. Enable the extension
5. Repeat 3, notice no highlighting any more.

### Expected behavior

Variables are still able to highlight after enable the extension.

### Code sample and Logs

```shell
workbench.colorCustomizations": {
        "minimap.selectionOccurrenceHighlight": "#00bbd0",
}
```

**Comment by michelleangela** [comment]
@reubenzh 
I couldn't reproduce the issue described. Here is my repro using extension version 1.12.0 on Windows:

Setting used
```
    "workbench.colorCustomizations": {
        "minimap.selectionOccurrenceHighlight": "#d00068",
    }
```
![image](https://user-images.githubusercontent.com/38734287/182717334-2bd1ed9c-dfbf-4a37-999d-86abb5da3fac.png)


The C/C++ extension has no feature that modify the minimap, so the highlighting on the minimap should not get disabled by the extension. Do you have any other extensions enabled/installed? Are there other settings configured? Could you try reloading the window and see if that fixes the issue?
