### ISSUE TITLE
Linter support for CppCoreGuidelines

### ISSUE THREAD

**Issue by agauniyal** [microsoft/vscode-cpptools#968]
New VS version (not code) has some support for these [guidelines](https://github.com/isocpp/CppCoreGuidelines) and clang-tidy does have them too. So it would be great to see a linter based on cpp core guidelines that'll mark/report relevant warnings/errors inside code. I'll be fine with something that runs explicitly, rather than on typing (to reduce the workload on plugin).

Thanks 😸

**Comment by florian-jackisch** [comment]
I would love to see some clang-tidy integration. Are there plans to integrate clang-tidy or other linters? (BTW: Issue #531 and this one are quite similar).

**Comment by sean-mcmanus** [comment]
There are no immediate plans to add clang-tidy integration.

**Comment by tristan957** [comment]
@sean-mcmanus I will be leaving this comment in order for people to +1 support for clang-tidy support
