### ISSUE TITLE
Formatting document problems

### ISSUE THREAD

**Issue by felix-0701** [microsoft/vscode-cpptools#9685]
### Environment

- OS and Version:WIN10
- VS Code Version:1.69.2(user setup)
- C/C++ Extension Version:v1.11.4
- Other extensions you installed (and if the issue persists after disabling them):  
- If using SSH remote, specify OS of remote machine:  
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

### Bug Summary and Steps to Reproduce

Bug Summary:
Formatting document problems
Steps to reproduce:
1.#define uint8 UINT8
2.typedef struct tst
{
UINT8 (*tst_vscode)(void);
}TST_T;
3.shift+Alt+F or ctrl+K ctrl+f
4.typedef struct tst
{
UINT8 (*tst_vscode)
(void);
} TST_T;

### Expected behavior

1.#define uint8 UINT8
2.typedef struct tst
{
UINT8 (*tst_vscode)(void);
}TST_T;
3.shift+Alt+F or ctrl+K ctrl+f
4.typedef struct tst
{
UINT8 (*tst_vscode)(void);
} TST_T;

### Code sample and Logs

```shell
1.#define uint8 UINT8
2.typedef struct tst
{
UINT8 (*tst_vscode)(void);
}TST_T;
3.shift+Alt+F or ctrl+K ctrl+f
4.typedef struct tst
{
UINT8 (*tst_vscode)(void);
} TST_T;
```

### Screenshots

![123](https://user-images.githubusercontent.com/67326167/182885344-ffb75b4f-26b0-4927-9ae5-6fe80b53273d.PNG)

**Comment by sean-mcmanus** [comment]
I don't understand what the bug is. Can you explain more? The behavior I'm seeing is that is it formatting as expected for both vcFormant and clangFormat formatters.
