### ISSUE TITLE
Cpptools doesn't show the constuctor's parameter info of a class when initialization its object in a array

### ISSUE THREAD

**Issue by RuoXian233** [microsoft/vscode-cpptools#9691]
### Environment

- OS and Version: Win10 x64
- VS Code Version: 1.70.0
- C/C++ Extension Version: v1.12.0
- Other extensions you installed (and if the issue persists after disabling them):  C/C++ Extention Pack, error lens, error gutters, path intellisense
- If using SSH remote, specify OS of remote machine:  None
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc). 

### Bug Summary and Steps to Reproduce

- Bug Summary:
A simple file within 300 lines, I use a syntax similar to the following example, but it has no hints when I typed 
"Object("

``` C++
class Object {
public:
    Object(int x, int y);
}

int main() {
    Object arr[] = {
        Object(0, 0),
        Object(1, 1) // No parameter hints when calling constructor like this syntax
    }
}
```

Steps to reproduce:
- Try to enter code snippet above in visual studio code

### Expected behavior

- Add parameter hints when using inlined initialization in an array for class
- Similar to constructor called outside a "{ }"

### Code sample and Logs

```shell
C++
class Object {
public:
    Object(int x, int y);
}

int main() {
    Object arr[] = {
        Object(0, 0),
        Object(1, 1) // No parameter hints when calling constructor like this syntax
    }
}
```
No language server error reported
c_cpp_properties: I haven't changed any of settings in it, it didn't appear in my .vscode folder
```


### Screenshots

```
And here's a screenshot:
You can see the cursor is in the bracket and no hint triggered
![屏幕截图 2022-08-06 195541](https://user-images.githubusercontent.com/88079598/183248941-ca8ddd65-71b5-4c72-b78e-e7de66e45136.png)

### Additional context

Nope, everything worked properly except this

**Comment by RuoXian233** [comment]
Is the code snippet showed a new attribute of C++ which the version I've specified to cpptools doesn't support? It works well with my clion IDE and pass the compilation

**Comment by michelleangela** [comment]
@RuoXian233 Please upvote this issue at Visual Studio feedback ticket https://developercommunity.visualstudio.com/t/cc-intellisense-error-with-initialization-of-neste/883249. It will also help to include your sample code in that feedback ticket to demonstrate issue in other cases.
