### ISSUE TITLE
M1 Mac intellisense not work when working with eigen

### ISSUE THREAD

**Issue by a1mersnow** [microsoft/vscode-cpptools#9692]
### Environment

- OS and Version: OSX 12.5
- VS Code Version: 1.70.0
- C/C++ Extension Version: v1.12.0

### Bug Summary and Steps to Reproduce

Bug Summary:
<img width="981" alt="image" src="https://user-images.githubusercontent.com/13799160/183268624-48d90e70-137e-4329-8d84-d1690ea49831.png">

- I installed eigen by brew.
- I'm using a M1 macbook pro 14-inch
- I'm using vscode-cpptools with cmake-tools
- I config the `include_directories(/opt/homebrew/include)` in `CMakeList.txt`
- I can `cmd+click` into `eigen/Eigen/Eigen`:

<img width="486" alt="image" src="https://user-images.githubusercontent.com/13799160/183268683-c5f32531-f344-4e96-89a4-17da56a98094.png">

### Code sample and Logs

```shell
c_cpp_properties.json:


{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [],
            "compilerPath": "/usr/bin/clang++",
            "cStandard": "gnu17",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "macos-clang-arm64",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```

**Comment by aimergenge** [comment]
resolved in issue [#7413](https://github.com/microsoft/vscode-cpptools/issues/7413#issuecomment-827172897)
