### ISSUE TITLE
how to use "Go to Declaration" feature?

### ISSUE THREAD

**Issue by abc100m** [microsoft/vscode-cpptools#97]
"Go to Definition" , press  F12  works well

now I want "Go to Declaration", how to jump to declaration?  I can't find any way to do this

**Comment by Seg0r** [comment]
I got similar problem/question. I got code in C, when i use F12 (Go to Definition) on function name it goes to declaration in header file and not to definition in other source file... Please fix it as it is a most important feature in every IDE.
Peek definition also shows declaration. Both ways does not suggest other competing declarations/definitions.

**Comment by jgoshi** [comment]
Which version of the C++ extension are you using? From version 0.8.0 on Windows you may have a slightly improved experience for this since we added a global cpp.hint file (handles common macros on Windows).

**Comment by Seg0r** [comment]
Problem still existed on 0.8.0. 
I have just updated to 0.8.1 and nothing have changed. "Go to definition" jumps to declaration in header file :( 
I found another bug: I tried to rename this header file, and now all old names shows in window with possible match...
![image](https://cloud.githubusercontent.com/assets/20472869/17249405/20e7ff10-55a0-11e6-9052-4ca98569460b.png)
after clicking in any it shows 0: 
![image](https://cloud.githubusercontent.com/assets/20472869/17249436/37ca0f16-55a0-11e6-8822-2d58f1d98290.png)

**Comment by Seg0r** [comment]
Update: I am not sure, but I guess that the problem with jumping to definition can be connected with non-standard files  extensions (*.sqc and *.ec). I got one *.c file, and it works well on functions from this file.

**Comment by jgoshi** [comment]
In the next release of cpptools (version 0.10.0) the rename issue should be fixed. We don't currently support Go to Declaration, could you open an issue for that feature request? Regarding go to definition not working properly (going to a header file) this should also be fixed in version 0.10.0. If it still repros could you open a new issue with details (and a small sample if possible).
