### ISSUE TITLE
Auto include header files

### ISSUE THREAD

**Issue by yvvt0379** [microsoft/vscode-cpptools#9702]
### Feature Request

When I input a name that is not defined, IntelliSense should speculate which header file where the name exists and show a suggestion to include the header file. If there are multiple header files in which the name is defined, show multiple choices and let me choose which header file to include.
Here's a case I described above. Item "Include \<vector\>" should be included in the drop down menu, and when I choose it, a line `#include <vector>` should be added to the top of file.
![屏幕截图 2022-08-06 112753](https://user-images.githubusercontent.com/62426149/183362486-778a9518-769e-4008-a3d3-5791f4473dee.jpg)

**Comment by Colengms** [comment]
Hi @CodeCrazy-ywt .  Thanks for suggesting this. We are currently tracking this feature request with this issue: https://github.com/microsoft/vscode-cpptools/issues/4776

I'd suggest up-voting that issue.
