### ISSUE TITLE
Debugger hits breakpoint but sporadically it does not show the associated source

### ISSUE THREAD

**Issue by daniel-brosche** [microsoft/vscode-cpptools#9703]
### Environment

- OS and version: Debian Buster
- VS Code: 1.70
- C/C++ extension: 1.11.4
- GDB version: 12.1 (also with 9.2 reproduced)

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. having an project structure like that
  /srv/git/cxxx/imports/opc_ua/opc_ua_cxxx_workspace/app.cpp
  /srv/git/cxxx/imports/opc_ua/opc_ua_cxxx_workspace/src_dir_a/src/src_a.h
  /srv/git/cxxx/imports/opc_ua/opc_ua_cxxx_workspace/src_dir_a/src/src_a.cpp
  /srv/git/cxxx/imports/opc_ua/opc_ua_cxxx_workspace/src_dir_b/src/src_b.h
  /srv/git/cxxx/imports/opc_ua/opc_ua_cxxx_workspace/src_dir_b/src/src_b.cpp
  
  Each of the src dirs results in seprate shared objects that will be loaded dynamicaly by the application.

3. With the provided config (see debugger configurations)...
     
5. Do '...'
- set breakpoint in the different src-dir header-file e.g. src_a.h (shared objects)
- start debugger / application

7. See error...

- gdb hits the breakpoint

- sporadically vscode show not the associated source file (33-50% reproducible).
  - all debug symbols are loaded correctly
  - the fullname in the log is correct (e.g. /srv/git/cxxx/imports/opc_ua/opc_ua_cxxx_workspace/build/../../src_dir_a/src/src_a.h exists)  

- when I click on the printed path of the debug console then following appears:

![image](https://user-images.githubusercontent.com/23653928/183373149-702589ac-2063-4245-af78-91b6b4875262.png)

with the absolute path of /srv/git/cxxx/imports/opc_ua_cxxx_workspace/src_dir_a/src/src.h

workaround / possible error reasons:
- this error seems especially happen with breakpoints in header files (e.g. src_a.h, src_b.h), but also happens from time to time in cpp files
- sometimes it seems to help to deactivate / activate all breakpoints and or set more breakpoints in the corresponding cpp files
- when I set two breakpoints one in der header and one in cpp-file and the debugger hits the breakpoint in the cpp first (src_a.cpp), then following hit in src_a.h works and the file gets opened in the editor. So I guess it has something to do with the activated breakpoint order and this may affects the path resolution
- the log output is always the same:

NOT WORKING
1: (27748) ->*stopped,reason="breakpoint-hit",disp="keep",bkptno="3",frame={addr="0x00007fffb7d8be7c",func="lenze::opc_ua::OpcUaEngBpmServerProviderT<lenze::opc_ua::EngBpmDataProvider>::Initialize",args=[{name="this",value="0x7fffc414daf0"},{name="ctx",value="0x7ffff02e6580 <g_providers+448>"}],file="../../opc_ua_eng_bpm_server_provider/src/opc_ua_eng_bpm_server_provider.h",fullname="/srv/git/cxxx/imports/opc_ua/opc_ua_cxxx_workspace/build/../../opc_ua_eng_bpm_server_provider/src/opc_ua_eng_bpm_server_provider.h",line="871",arch="i386:x86-64"},thread-id="33",stopped-threads="all",core="0"

WORKING
1: (35171) ->*stopped,reason="breakpoint-hit",disp="keep",bkptno="4",frame={addr="0x00007fffd7d8be7c",func="lenze::opc_ua::OpcUaEngBpmServerProviderT<lenze::opc_ua::EngBpmDataProvider>::Initialize",args=[{name="this",value="0x7fffbc14daf0"},{name="ctx",value="0x7ffff02e6580 <g_providers+448>"}],file="../../opc_ua_eng_bpm_server_provider/src/opc_ua_eng_bpm_server_provider.h",fullname="/srv/git/cxxx/imports/opc_ua/opc_ua_cxxx_workspace/build/../../opc_ua_eng_bpm_server_provider/src/opc_ua_eng_bpm_server_provider.h",line="871",arch="i386:x86-64"},thread-id="33",stopped-threads="all",core="0"

### Debugger Configurations

```shell
{
        "name": "[TARGET:CPP] GDB SSH",
        "type": "cppdbg",
        "request": "launch",
        "program": "/opt/lenze/bin/runtime",
        "stopAtEntry": false,
        "cwd": "/opt/lib/",
        "environment": [],
        "externalConsole": true,
        "filterStderr": true,
        "filterStdout": true,
        "pipeTransport": {    
            "pipeCwd": "/usr/bin", 
            "pipeProgram": "${workspaceFolder}/ssh.py",
            "debuggerPath": "/usr/bin/gdb" 
        },
        "MIMode": "gdb",
        "setupCommands": [
            {
                "description": "Skip library files",
                "text": "-interpreter-exec console \"skip -gfi **/bits/*.h\""
            }, 
        ]
    },
```

### Debugger Logs

```shell
1: (28066) ->*stopped,reason="breakpoint-hit",disp="keep",bkptno="3",frame={addr="0x00007fffb3d8beb6",func="ServerProviderT>::Initialize",args=[{name="this",value="0x7fffbc14d6d0"},{name="ctx",value="0x7ffff02e6580 <g_providers+448>"}],file="../../src_dir_a/src/src.h",fullname="/srv/git/cxxx/imports/opc_ua/opc_ua_cxxx_workspace/build/../../src_dir_a/src/src.h",line="874",arch="i386:x86-64"},thread-id="33",stopped-threads="all",core="0"
```

**Comment by WardenGnaw** [comment]
This would be on VS Code not properly finding the file to open. 

The debugger seems to be returning the correct path.
> /srv/git/cxxx/imports/opc_ua/opc_ua_cxxx_workspace/build/../../src_dir_a/src/src_a.h

I would reopen this ticket at https://github.com/microsoft/vscode/issues
