### ISSUE TITLE
Version 1.11.5 is available for update but there's no changelog or even tag in this repo

### ISSUE THREAD

**Issue by mikedld** [microsoft/vscode-cpptools#9709]
### Environment

- OS and version: macOS 12.4
- VS Code: 1.71.0-insider (5cf4a848f9d297f6708e6dbd27b2a48f03ac6595)
- C/C++ extension: 1.11.4
- OS and version of remote machine (if applicable): Gentoo Linux

### Bug Summary and Steps to Reproduce

Bug Summary:
New version is available for download/update but I'm not sure it's safe to use it.

Steps to reproduce:
1. Check for extension updates
2. See new [suspicious] version...

<img width="748" alt="image" src="https://user-images.githubusercontent.com/298203/183954989-182df545-cf7d-474d-a779-6b335249b07e.png">

<img width="757" alt="image" src="https://user-images.githubusercontent.com/298203/183955121-81942584-9f68-432f-b375-cb2e84b8672c.png">

**Comment by Colengms** [comment]
Hi @mikedld .  1.11.5 is a hot-fix for a crash.  We decided to forgo the changelog update for expediency, and because the issue is not yet fully addressed.
