### ISSUE TITLE
Add IntelliSense for C library includes

### ISSUE THREAD

**Issue by sajibsrs** [microsoft/vscode-cpptools#9718]
### Feature Request

Current tool doesn't suggests or auto includes file that is required but not included in the file.

Example: `free(memory);` should trigger include suggestion for `<stdlib.h>`.
Inclusion scope: Configured directory and standard header files (probably).

OS: Pop_OS!
Tool chain: gcc 11.2.0

**Comment by michelleangela** [comment]
@sajibsrs 
Thank you for the feature request. We are currently tracking this feature request with this issue: https://github.com/microsoft/vscode-cpptools/issues/4776
. Please up-vote that issue to increase its priority.

**Comment by sajibsrs** [comment]
Thank you.
