### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Aeidle** [microsoft/vscode-cpptools#9719]
- Issue Type: `Bug`
- Extension Name: `cpptools`
- Extension Version: `1.10.8`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.69.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 1240,
		"activateCallTime": 61,
		"activateResolvedTime": 1131,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "ms-vscode.cpptools",
				"_lower": "ms-vscode.cpptools"
			},
			"activationEvent": "workspaceContains:/.vscode/c_cpp_properties.json"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by michelleangela** [comment]
@Aeidle 
Could you provide more info about the issue? For example, does the extension fail to start? Is there an issue with IntelliSense or configuration?

**Comment by Aeidle** [comment]
It's fixed now, at first it kept showing me an error message that something
is messing, I tried to reinstall the plugging, but it didn't let me.
I opened the plugging manager, disabled the plagging, uninstalled it, then
installed it once again and it worked.
I guess it has something to do with a service that couldn't run or
something.  Anyway thank you for the reply.
