### ISSUE TITLE
The downloading progress of C# dependencies stucked in China

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-cpptools#972]
_From @IcyPoint on August 13, 2017 2:8_

- VSCode Version: 1.15.0
- OS Version: win7 sp1

Steps to Reproduce:

1.Update to 1.15.0
2.Restart VS Code and check output window

Reproduces without extensions: No

_Copied from original issue: Microsoft/vscode#32399_

**Comment by sean-mcmanus** [comment]
We're not responsible for the C# extension. Can you find the correct team?
