### ISSUE TITLE
Static inline functions in header - go to definition doesn't work

### ISSUE THREAD

**Issue by MaJerle** [microsoft/vscode-cpptools#9720]
### Environment

Version: 1.69.2 (user setup)
Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a
Date: 2022-07-18T16:12:52.460Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

### Bug Summary and Steps to Reproduce

1. create header file
2. create static inline function
3. include file to source file
4. try to write function name - intelisense completer wont find it.
5. if you manage to write it, CTRL+Click won't jump to definition

**Comment by sean-mcmanus** [comment]
I don't repro the issue and I don't remember a previous report of this. Can you provide more info?

**Comment by sean-mcmanus** [comment]
In your video, I see uint32_t being treated as "<error type>", so there is some pre-existing parsing problem in your TU regarding that. Are you able to fix that somehow? Are you able to repro the __STATIC_INLINE issue in a standalone TU that has no error squiggles or uint32_t references?

I'm still not reproing the issue. When you run C/C++: Log Diagnostics does it show any compilerPath being used? You're settings show compilerPath is set to "", so you won't have any system defines set, which may be required for some headers to parse uint32_t correctly.

**Comment by sean-mcmanus** [comment]
TU is the translation unit (.cpp plus all the included headers).

What compiler are you using? It sounds like your includePath is not set up correctly to be used with a "" compilerPath -- usually you should set the compilerPath if possible, otherwise you need to provide the system include paths and defines yourself.

**Comment by sean-mcmanus** [comment]
No, you shouldn't set includePath to a system include. It normally wouldn't be used anyway though because you have a configurationProvider set. You should try removing the compilerPath and configure CMake Tools to use the gcc compiler (Cmake: select a kit) or set the compilerPath yourself.

**Comment by sean-mcmanus** [comment]
It looks like "IntelliSense Mode: windows-msvc-x64" is incorrect.

**Comment by sean-mcmanus** [comment]
Well, you could try setting "intelliSenseMode": "windows-gcc-x64" but it seems like there may be a bug with our intelliSenseMode detection logic based on looking at the compiler defines.

**Comment by sean-mcmanus** [comment]
Do you get any "C/C++ Configuration Warnings" output pane to appear with a message about changing the intelliSenseMode?

**Comment by sean-mcmanus** [comment]
This could be https://github.com/microsoft/vscode-cpptools/issues/6677 .

**Comment by Colengms** [comment]
Hi @MaJerle .  Could you set `"C_Cpp.loggingLevel": "Debug"` and provide the log output from the C/C++ output channel, from launch until after the repro?

Also, did you intentionally set `compilerPath` to `""`?  When using a custom configuration provider, that is a special value indicating the compiler specified by the custom configuration should not be used.  That would result in not querying the compiler for system includes.  It's possible you are seeing IntelliSense issues in code following failures for IntelliSense to include system headers (and then failures to parse code that relies on the contents of those headers).
