### ISSUE TITLE
Clang-Tidy warnings still in Problems view when editor is closed

### ISSUE THREAD

**Issue by dfarley1** [microsoft/vscode-cpptools#9721]
### Environment

- OS and version: Gentoo Linux
- VS Code: 1.70.1
- C/C++ extension: 1.11.5
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

I have clang-tidy configured:
```
        "C_Cpp.codeAnalysis.clangTidy.enabled": true,
        "C_Cpp.codeAnalysis.clangTidy.path": "/usr/lib/llvm/13/bin/clang-tidy",
        "C_Cpp.codeAnalysis.clangTidy.useBuildPath": true,
```
and I happily get its warnings in the Problems tab when I interact with a source file.

However, when I close the file's editor window/tab, the warnings stick around without any way to clear them except for reloading the window. It's especially annoying when I "Go to Definition" into a system header for a quick second and end up with the hundreds of warnings coming out of that file without a way to clear them.

**Comment by sean-mcmanus** [comment]
It is intentional that the code analysis squiggles don't clear when the file is closed because we support operations like Run Code Analysis on All Files which gives warnings for workspace files that aren't open.

There is a code action and command to Clear All Code Analysis problems.

clang-tidy isn't normally supposed to run when opening a file that external to the workspace folder -- do you know how you're able to get that to happen?

**Comment by dfarley1** [comment]
> It is intentional that the code analysis squiggles don't clear when the file is closed because we support operations like Run Code Analysis on All Files which gives warnings for workspace files that aren't open.

That's a slight bummer for my workflow but good to know there's a command to clear them at least!

> clang-tidy isn't normally supposed to run when opening a file that external to the workspace folder -- do you know how you're able to get that to happen?

It's shown up inconsistently, but then again I only dive into system headers inconsistently...

1. Open file in our workspace
2. Ctrl+Click on `IPPROTO_TCP` which takes us to `/usr/include/netinet/in.h`

I can't appear to repro it off the cuff, but that's definitely the file/variable I was looking at when I last noticed it happen. I'll open a new ticket if/when I can repro.
