### ISSUE TITLE
The file `.clang-format` can not be found if its a symbolic link on Windows

### ISSUE THREAD

**Issue by emmenlau** [microsoft/vscode-cpptools#9726]
### Feature Request

We use a symbolic link to point to the file `.clang-format` from a directory higher in the folder tree. This works nicely on Linux and MacOS, but does not work on Windows. The clang format integration does not see the file and uses standard formatting rules instead. The link was created in Cygwin as a normal user (not the kind of link that requires Administrator privileges). When I remove the link and instead place the file, everything works and clang-format detects the file.

This is our folder layout:
```
root/
root/.clang-format -> Scripts/formatting/.clang-format
root/Project/
root/Project/Project.code-workspace
Scripts/
Scripts/formatting/
Scripts/formatting/.clang-format
```
When I edit `Project`, then clang format does not find the corresponding format file on Windows if it is a symbolic link.

**Comment by sean-mcmanus** [comment]
This appears to be an issue with the Cygwin symlinks and not our handling, which works correctly with normal symlinks created in Windows/Linux, see https://stackoverflow.com/questions/3343988/accessing-a-cygwin-symlink-from-windows .

**Comment by Colengms** [comment]
Closing external issue.
