### ISSUE TITLE
How to debug .dylib library with attached process

### ISSUE THREAD

**Issue by shigomany** [microsoft/vscode-cpptools#9728]
### Environment

- OS and version: Mac OS Mneterey 12.0.1 (21A559)
- VS Code: 1.70.1 (Universal)
- C/C++ extension: v1.11.5

### Bug Summary and Steps to Reproduce

Bug Summary:

How to debug **.dylib** library with attached process?

I created `launch.json` in this form:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach to Proccess C++",
            "request": "attach",
            "type": "cppdbg",
            "processId": "${command:pickProcess}",
            "program": "${workspaceRoot}/build/src/libNeoML.dylib",
            "showDisplayString": true,
            "logging": {
                "engineLogging": true,
                "trace": true,
                "traceResponse": true,
                "programOutput": true
            },
            "osx": {
                "MIMode": "lldb",
                "miDebuggerPath": "${extensionInstallFolder:ms-vscode.cpptools}/debugAdapters/lldb-mi/bin/lldb-mi",
            },
        }
    ]
}
```

Steps to reproduce:
I opened the CMake project in VSCode, built it. And I'm trying to join the dart process (with ffi).

### Additional Information

I did the same thing on Windows and through Visual Studio I managed to attach the process.

**Comment by WardenGnaw** [comment]
Can you attach to the main process that calls into the dylib?

**Comment by shigomany** [comment]
> Can you attach to the main process that calls into the dylib?

On Windows I can use Visual Studio, but on macOS I can't use VSCode.

**Comment by shigomany** [comment]
I get information about such an error (with this `launch.json`):

<img width="294" alt="image" src="https://user-images.githubusercontent.com/43740557/184447144-189a15bc-8fba-4d3c-8be3-7231040603a8.png">

**Comment by shigomany** [comment]
If I specify the path to the `dart` process being started, I get a similar error.

```json
{
   "program": "/Users/***/fvm/versions/stable/bin/cache/dart-sdk/bin/dart"
}
```

> I get information about such an error (with this `launch.json`):
> 
> <img alt="image" width="294" src="https://user-images.githubusercontent.com/43740557/184447144-189a15bc-8fba-4d3c-8be3-7231040603a8.png">

If I specify the path to the `dart` process being started, I get a similar error.

```json
{
   "program": "/Users/***/fvm/versions/stable/bin/cache/dart-sdk/bin/dart"
}
```

**Comment by shigomany** [comment]
Dart proccess info:

```
cwd
/Users/***/Documents/workingprojects/dart-neoml
txt
/Users/***/fvm/versions/stable/bin/cache/dart-sdk/bin/dart
txt
/Library/Preferences/Logging/.plist-cache.I4U9d1iR
txt
/System/Library/CoreServices/Encodings/libCyrillicConverter.dylib
txt
/usr/lib/dyld
txt
/usr/share/icu/icudt68l.dat
txt
/private/var/db/timezone/tz/2022a.1.0/icutz/icutz44l.dat
txt
/Users/***/Documents/workingprojects/dart-neoml/assets/macOS/libNeoMathEngine.dylib
txt
/Users/***/Documents/workingprojects/dart-neoml/assets/macOS/libNeoML.dylib <--- LOADED
0
->0xd80a243142eea9a9
1
->0xd80a243142eeab39
2
->0xd80a243142eeacc9
3
->0x24ea0e11d814aa75
4
->0x7fd387dc7ca4a3ed
5
count=0, state=0xa
6
[ctl com.apple.netsrc id 6 unit 32]
7
localhost:50667
8
->0xd80a243142ee6809
9
10
->0xf73d07bf6fe61be6
11
->0xcc0999d3555a8d6f
13
```

**Comment by shigomany** [comment]
Why specify program at all when I'm attaching by processid?

**Comment by shigomany** [comment]
Update
