### ISSUE TITLE
the code is not debugged and runned

### ISSUE THREAD

**Issue by Karthikmanjunath18** [microsoft/vscode-cpptools#9735]
![Screenshot (214)](https://user-images.githubusercontent.com/111171283/184472362-f5b87426-eaa4-4261-ae51-9e5786c983c6.png)
![Screenshot (214)](https://user-images.githubusercontent.com/111171283/184472366-7a27612b-c966-4a6a-a817-af48ee20b73d.png)
![Screenshot (214)](https://user-images.githubusercontent.com/111171283/184472378-bc9812e5-968f-4cb2-bd4f-2e9978a8a4e3.png)
Type: <b>Feature Request</b>

if i run the programme its not running its showing some issue like gcc is not installed and some extensions are not there like that

Extension version: 1.2.0
VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.25151
Modes:

**Comment by michelleangela** [comment]
@Karthikmanjunath18 
The C++ extension does not include a C++ compiler nor a C++ debugger like GCC. You will need to install a compiler (used for IntelliSense) and a debugger for debugging.

For help in setting up the extension and downloading the required compiler and debugger, please follow our tutorials at https://code.visualstudio.com/docs/languages/cpp#_tutorials based on the platform you're using.
