### ISSUE TITLE
left hanging installation in wsl:ubuntu

### ISSUE THREAD

**Issue by aizzaf** [microsoft/vscode-cpptools#9738]
### Environment

- OS and version: wsl:ubuntu-22.04
- VS Code:
- C/C++ extension:
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. In this environment...
2. With this config...
3. Do '...'
4. See error...

**Comment by michelleangela** [comment]
@aizzaf 
Could you try re-installing the extension and see if it still hangs? Could you also provide information on how you installed the extension?

**Comment by aizzaf** [comment]
oh sorry, it  is not left hanging anymore, but takes time too long too install about hours
and it works now

**Comment by michelleangela** [comment]
It should not take a long time to install the extension. It could be taking a while to download the VSIX package. For future installs, you could try downloading the VSIX package manually from https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools and then install it.

I'll close this issue as resolved.
