### ISSUE TITLE
multiple issues on linux

### ISSUE THREAD

**Issue by yamcenutzer** [microsoft/vscode-cpptools#974]
OS: Fedora 20
vscode :  1.15.0
cpp extension: 12.2
other extensions: cmake, cmake-tools, cmake-tools-helper, git history, git-lens, gitignore, Trailing-spaces, vscode-icons

open a folder for a non-trivial hierarchy of make files, with nested symlinks.
- intellisense can't find the simplest things and complains about missing includes, verify they point to correct folders
- After a while it seems to work
- after ca. 20. mins the few things it could find go away and hovering over a symbol that used to work just a moment ago shows 'Loading..'
- I thought the recursive symlink issue was resolved quite a while ago, but propbably not, or only for small projects, or it is something else altogether.

OS: Centos 7, RHEL 7
same as above,
additionally:
- dependancy on glibc 2.18 still exists, the workaround posted in the appropriate issue breaks with every new release of the extension.
- IIRC vscode itself used to have a dependancy on glibc 2.18, but that got resolved. At least I can install vscode on Centos/RHEL 7 now.
- note that centos/rhel 7 use glibc 2.17 as default.

**Comment by sean-mcmanus** [comment]
What is your intelliSenseEngine settting? "Loading..." generally means the main thread is stuck doing some processing.

**Comment by yamcenutzer** [comment]
intellisense engine is set to default with fallback to tagparser enabled

**Comment by igor-borovkov** [comment]
Didn't install any updates for 6 months until yesterday, the extension worked perfectly fine. Now intellisense is regularly broken, "Extension host terminated unexpectedly. Please reload the window to recover."  pops  up every hour. (Ubuntu)

my settings were default, never modified

code base:  webkit.org

**Comment by cmazakas** [comment]
I've been having many issues myself on OS X.

Maybe it's because I'm also using CMake? But on Windows, VS Code seems to work properly when I link my target against interface libraries, for example.

I know I can't ask anything of people who work for free but integrating the C++ tools with CMake would make VS Code probably the best IDE out there.

**Comment by yamcenutzer** [comment]
TBH I don't see a real use case for vscode on windows, where you can use the real thing (VS).
I was hoping for something useful on Linux, something definitely better than atom or eclipse.
But I'm not sure that cyclic symlinks and arbitary hierarchies can be solved at all to give a proper intellisense without actually compiling the code.

**Comment by bobbrow** [comment]
I'm closing old issues marked "more info needed".  If you are still having issues with the extension, please ensure you have installed the latest version and open a new issue with the issue details.
