### ISSUE TITLE
#include<iostream> after updating the MacOS

### ISSUE THREAD

**Issue by chenjunyi1999** [microsoft/vscode-cpptools#9740]
### Environment

- OS and Version: MacOS Monterey12.5
- VS Code Version: 1.70.1
- C/C++ Extension Version: 1.12.0
- Other extensions you installed (and if the issue persists after disabling them):  Code Runner, CodeLLDB

### Bug Summary and Steps to Reproduce

Bug Summary:

Before I update to Monterey12.5 from Catalina, I can create a .cpp file and run it directly with the help of cpptools/ Code Runner/ CodeLLDB. However, When I update to Monterey12.5. The error message has been shown below:
```
"#include errors detected. Please update your includePath. Squiggles are disabled for this translation unitC/C++(1696)"
"cannot open source file "wchar.h"(dependency of "iostream")C/C++(1696)"
```
### **I have reinstalled the 'xcode-select' after the updating ! ! !**
I need to excute `g++ -v -E -x c++ - ` and add the path manually to `c_cpp_properties.json` for every project. I want to know how can i deal with this problem and run the code as before( without configuring `c_cpp_properties.json` for each project)

### Code sample and Logs

```shell
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${default}",
                "/usr/local/include",
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/v1",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/13.1.6/include",
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks"
            ],
            "defines": [],
            "macFrameworkPath": [],
            "compilerPath": "/usr/local/bin/gcc-9",
            "cStandard": "gnu17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "macos-gcc-x64"
        }
    ],
    "version": 4
}
```

**Comment by sean-mcmanus** [comment]
Can you remove the system includes from you includePath so you just have "${default}"?

Your compilerPath should be picking up the updated system include paths.

**Comment by chenjunyi1999** [comment]
Thank you for your reply, sir.
Before i update to macos12.5, the includePath is like what you say( just have "${default}") which i think is the default config of cpptools. But in macos12.5, I can run cpp code successfully only if i add these system includes manually. Otherwise, there will be a #include error.

**Comment by chenjunyi1999** [comment]
> Can you remove the system includes from you includePath so you just have "${default}"?
> 
> Your compilerPath should be picking up the updated system include paths.

Thank you for your reply, sir.
Before i update to macos12.5, the includePath is like what you say( just have "${default}") which i think is the default config of cpptools. But in macos12.5, I can run cpp code successfully only if i add these system includes manually. Otherwise, there will be a #include error.

**Comment by sean-mcmanus** [comment]
Can you instead update your compilerPath? Maybe the gcc-9 one is too old. Updating just the includes won't update the system defines correctly.

**Comment by chenjunyi1999** [comment]
Thank you so much, sir. After I **switch the compilerPath from 'default' to '/usr/bin/clang'** ,  I can run any project without  modify `c_cpp_properties.json` for each project manually. 
The `c_cpp_properties.json` for each project are changed to
```
{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "macFrameworkPath": [],
            "cStandard": "gnu17",
            "cppStandard": "gnu++14",
            "intelliSenseMode": "macos-gcc-x64"
        }
    ],
    "version": 4
}
```
So, do I need further change the "intelliSenseMode" into "clang-x64" ?
In addition, I  am also curious abut whats the possible reason that the original configuration is invalid in Monterey.

**Comment by sean-mcmanus** [comment]
The setting for intelliSenseMode probably won't matter, because if it's set incorrectly we will attempt to fix it and you'll see a configuration warning like "or C++ source files, IntelliSenseMode was changed from "macos-gcc-x64" to "macos-clang-x64" based on compiler args and querying compilerPath".

I'm not sure what is wrong with the initial /usr/local/bin/gcc-9 compilerPath -- it might just be a broken install without the necessary system headers installed. If you set C_Cpp.loggingLevel to "Debug", you could check the C/C++ logging to see what we get when we query the compiler, i.e. it might be failing or getting incomplete/incorrect results.

**Comment by chenjunyi1999** [comment]
Thanks for the analysis and advice! 
Best regards.
