### ISSUE TITLE
The position of inlay hint parameter is wrong when using `at` or `operator[]` to access a container's element

### ISSUE THREAD

**Issue by zhiyiYo** [microsoft/vscode-cpptools#9741]
### Environment

- OS and version: Windows 11 22621.382
- VS Code: 1.70.1
- C/C++ extension: v1.12.1 pre-released

### Bug Summary and Steps to Reproduce

Bug Summary:
The position of inlay hints is wrong.
![image](https://user-images.githubusercontent.com/65096819/184787832-0259f76a-46c8-4ffa-a227-ea41a0d32911.png)

### Expected behavior

`c:` should be in front of `s_[0]`

### Code sample and Logs

```cpp
#include <iostream>
#include <string>
using namespace std;

int main(int argc, char const *argv[])
{
    string s = "hello";
    string s_ = "world";
    s.push_back(s_[0]);
    return 0;
}
```

**Comment by michelleangela** [comment]
Other repro cases:

```
#include <iostream>
#include <string>
#include <vector>

using namespace std;

int main(int argc, char const* argv[])
{
    string resultString = "";
    string myString = "abc";
    vector<char> charsVector = { 'a', 'b' };
    char charsArray[] = { 'a', 'b' };

    vector<int> numVector = { 0, 1 };
    int numArray[] = { 0, 1 };
    vector<int> resultNum = {};

    // Parameter hint "Ch" should be displayed in front of "charsVector"
    // instead of in front of the container's accessor.
    resultString.push_back(charsVector.at(0));
    resultString.push_back(charsVector[0]);
    
    // Parameter hint "Ch" should be displayed in front of "myString"
    // instead of in front of the container's accessor.
    resultString.push_back(myString.at(0));
    resultString.push_back(myString[0]);

    // Parameter hint is displayed as expected for these examples
    resultString.push_back(charsArray[0]);
    resultNum.push_back(numArray[0]);
    resultNum.push_back(numVector[0]);
    resultNum.push_back(numVector.at(0));

    return 0;
}
```

![image](https://user-images.githubusercontent.com/38734287/184961146-c29f344f-d1d5-458e-be96-2fdf2e420aff.png)

**Comment by michelleangela** [comment]
@zhiyiYo 
Thank you for reporting this issue. Our extension's IntelliSense code base which has this bug is shared with Visual Studio, so I created a feedback ticket against Visual Studio.

Please upvote the issue at https://developercommunity.visualstudio.com/t/C-inline-hint-parameter----position-of/10122247?port=1026&fsid=c4e872fe-0e2c-4bdf-aa14-c26fe321ff59&entry=problem

**Comment by zhiyiYo** [comment]
@michelleangela 
I have voted for this issue🙂

**Comment by michelleangela** [comment]
Verified fixed for 1.13.2

**Comment by sean-mcmanus** [comment]
@michelleangela What? I don't believe the fix made it in yet. The plan was for 1.13.3.

**Comment by sean-mcmanus** [comment]
@michelleangela Ah, I see now -- it is fixed. I was looking at the follow up PR which is related.

**Comment by sean-mcmanus** [comment]
@zhiyiYo Fixed with https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.2
