### ISSUE TITLE
Setting "C_Cpp.vcFormat.indent.namespaceContents" to false has no effect

### ISSUE THREAD

**Issue by lunar-natalie** [microsoft/vscode-cpptools#9743]
### Environment

- OS and version: Arch Linux, Kernel 5.19.1, Display protocol: Wayland (VS Code running on XWayland), Compositor: Sway 1.7
- VS Code version: 1.70.1 (Official binary)
- C/C++ extension version: 1.11.5
- Other enabled extensions: Better C++ Syntax (`jeff-hykin.better-cpp-syntax`), CMake (`twxs.cmake`), Docker (`ms-azuretools.vscode-docker`), Doxygen Documentation Generator (`cschlosser.doxdocgen`), GitLens — Git supercharged (`eamodio.gitlens`), Go (`golang.go`), Jupyter (`ms-toolsai.jupyter`), Jupyter Keymap (`ms-toolsai.jupyter-keymap`), Jupyter Notebook Renderers (`ms-toolsai.jupyter-renderers`), Markdown All in One (`yzhang.markdown-all-in-one`), Material Icon Theme (`PKief.material-icon-theme`), Material Product Icons (`PKief.material-product-icons`), One Dark Pro (`zhuangtongfa.material-theme`), Pylance (`ms-python.vscode-pylance`), Python (`ms-python.python`), Remote - Containers (`ms-vscode-remote.remote-containers`), Remote - SSH (`ms-vscode-remote.remote-ssh`), Remote - SSH: Editing Configuration Files (`ms-vscode-remote.remote-ssh-edit`)
- Not using SSH remote
- Relatively small, single project workspace with ~20 C++ source/header files in total with sizes varying from ~30 to ~200 lines (including comments) each, using the CMake build system

### Bug summary

After setting `C_Cpp.vcFormat.indent.namespaceContents` to `false` in either the user or the workspace `settings.json`, the contents of namespaces are still automatically indented when writing C++ source code when the `editor.autoIndent` preference is set to `full`.

### Steps to reproduce

1. Go to the VS Code user preferences
2. Search for `editor.autoIndent` and ensure the option is set to `full`
3. Search for `C_Cpp.vcFormat.indent.namespaceContents` and disable the option
4. Open a C++ source or header file
5. Type `namespace test {` and press return
6. The following line is indented by the editor's tab size

### Expected behavior

Namespace contents are **not** automatically indented if the `C_Cpp.vcFormat.indent.namespaceContents` preference is set to `false`.

Example: in the C++ source code sample below, the typedef of `B` should be aligned with `namespace a` to the left margin without having to delete an inserted indent before writing the typedef.

### Notes

Attempting to override this with `NamespaceIndentation: None` in a `.clang-format` file or with surrounding braces in the `C_Cpp.clang_format_style` preference has no effect.

### Samples and logs

Code sample:

```cc
namespace a
{

    typedef class B
    {
    } B;

}
```

`c_cpp_properties.json` (Workspace):

```json
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [],
            "cStandard": "c17",
            "cppStandard": "c++17"
        }
    ],
    "version": 4
}
```

C/C++ Diagnostics log:

```
-------- Diagnostics - 16/08/2022, 23:46:35
Version: 1.11.5
Current Configuration:
{
    "name": "Linux",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [],
    "cStandard": "c17",
    "cppStandard": "c++17",
    "compilerPathIsExplicit": false,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": false,
    "macFrameworkPath": [],
    "intelliSenseMode": "linux-clang-x64",
    "mergeConfigurations": false,
    "compilerPath": "/usr/bin/clang",
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Translation Unit Mappings:
[ /home/natalie/dev/gelatinous-cube/src/signal.cc ]:
    /home/natalie/dev/gelatinous-cube/src/signal.cc
[ /home/natalie/dev/gelatinous-cube/src/tui/main_loop.cc ]:
    /home/natalie/dev/gelatinous-cube/src/tui/main_loop.cc
    /home/natalie/dev/gelatinous-cube/src/tui/main_loop.hh *
    /home/natalie/dev/gelatinous-cube/src/tui/panel_manager.hh *
    /home/natalie/dev/gelatinous-cube/src/tui.hh *
[ /home/natalie/dev/gelatinous-cube/src/options.cc ]:
    /home/natalie/dev/gelatinous-cube/src/options.cc
    /home/natalie/dev/gelatinous-cube/src/tui.hh
[ /home/natalie/dev/gelatinous-cube/src/tui/start.cc ]:
    /home/natalie/dev/gelatinous-cube/src/tui/start.cc
    /home/natalie/dev/gelatinous-cube/src/tui.hh
    /home/natalie/dev/gelatinous-cube/src/tui/main_loop.hh
    /home/natalie/dev/gelatinous-cube/src/tui/panel_manager.hh
Translation Unit Configurations:
[ /home/natalie/dev/gelatinous-cube/src/signal.cc ]:
    Process ID: 139601
    Memory Usage: 833 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/12.1.1
        /usr/include/c++/12.1.1/x86_64-pc-linux-gnu
        /usr/include/c++/12.1.1/backward
        /usr/lib/clang/14.0.6/include
        /usr/local/include
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=140006
[ /home/natalie/dev/gelatinous-cube/src/tui/main_loop.cc ]:
    Process ID: 139630
    Memory Usage: 833 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/12.1.1
        /usr/include/c++/12.1.1/x86_64-pc-linux-gnu
        /usr/include/c++/12.1.1/backward
        /usr/lib/clang/14.0.6/include
        /usr/local/include
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=140006
[ /home/natalie/dev/gelatinous-cube/src/options.cc ]:
    Process ID: 139664
    Memory Usage: 833 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/12.1.1
        /usr/include/c++/12.1.1/x86_64-pc-linux-gnu
        /usr/include/c++/12.1.1/backward
        /usr/lib/clang/14.0.6/include
        /usr/local/include
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=140006
[ /home/natalie/dev/gelatinous-cube/src/tui/start.cc ]:
    Process ID: 139789
    Memory Usage: 833 MB
    Compiler Path: /usr/bin/clang
    Includes:
        /usr/include/c++/12.1.1
        /usr/include/c++/12.1.1/x86_64-pc-linux-gnu
        /usr/include/c++/12.1.1/backward
        /usr/lib/clang/14.0.6/include
        /usr/local/include
        /usr/include
    Standard Version: c++17
    IntelliSense Mode: linux-clang-x64
    Other Flags:
        --clang
        --clang_version=140006
Total Memory Usage: 3332 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 61186
```

**Comment by sean-mcmanus** [comment]
We only invoke the formatting when "editor.formatOnType": true -- is that sufficient?

**Comment by lunar-natalie** [comment]
@sean-mcmanus Unfortunately it appears that that preference has no effect for me either, the result is still the same.

**Comment by sean-mcmanus** [comment]
Okay, let me double check -- my repro steps may have been insufficient...

**Comment by sean-mcmanus** [comment]
What is your C_Cpp.formatting setting? The vcFormat.* settings are only applied when it's set to "vcFormat" and not "clangFormat".

I could look into the repro steps involving clang-format if you want.

**Comment by lunar-natalie** [comment]
Ah, thank you. After setting `C_Cpp.formatting` to `vcFormat` all is working, apologies - I didn't know about that option.
