### ISSUE TITLE
vscode configuration c/c++ development and debugging environment (with mingw) unsuccessful

### ISSUE THREAD

**Issue by pedoc** [microsoft/vscode-cpptools#9756]
### Environment

- OS and version:
```
Win 11 22H2 (22622.575)
```
- VS Code:
```
Version: 1.70.2 (system setup)
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:35:13.448Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22622
```
- C/C++ extension:
```
C/C++ Themes v1.0.0
C/C++ Extension Pack v1.2.0
C/C++ v1.11.5
```
- OS and version of remote machine (if applicable):
```
local mingw64
MINGW64_NT-10.0-22622 DESKTOP-HOME 3.3.5-341.x86_64 2022-07-04 21:33 UTC x86_64 Msys
```
- GDB / LLDB version:
```
gdb:GNU gdb (GDB) 12.1
g++: (Rev3, Built by MSYS2 project) 12.1.0
gcc: (Rev3, Built by MSYS2 project) 12.1.0
```

### Bug Summary and Steps to Reproduce

Bug Summary:
Unable to start F5 debug and run from VSCode

Steps to reproduce:
1. Environment configuration according to https://code.visualstudio.com/docs/cpp/config-mingw
2. Example code
#### helloworld.cpp
```
#include <iostream>
#include <vector>
#include <string>
using namespace std;
int main()
{
    vector<string> msg{"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};
    for (const string &word : msg)
    {
        cout << word << " ";
    }
    cout << endl;
}
```
3. Press F5 to start debugging,will be failed
![image](https://user-images.githubusercontent.com/6604230/185632268-42cb39e3-d00d-47e2-9131-29972839bb12.png)

4. Copy the build command from the output and execute it directly without any errors and it can be executed successfully.
```
g++.exe -fdiagnostics-color=always -g K:\code\sample\helloworld.cpp -o K:\code\sample\helloworld.exe
```
![image](https://user-images.githubusercontent.com/6604230/185633387-b71ddd14-4504-4905-b8ce-179ccea34f29.png)

### Debugger Configurations

```shell
#### launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "gcc.exe - Build and debug active file",
            "type": "cppdbg",
            "request": "launch",
            "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
            "args": [],
            "stopAtEntry": false,
            "cwd": "${fileDirname}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "gdb.exe",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                }
            ],
            "preLaunchTask": "C/C++: gcc.exe build active file"
        }
    ],
    "logging": {
        "engineLogging": true,
        "trace": true,
        "traceResponse": true
    }
}


#### tasks.json
{
    "tasks": [
        {
            "type": "cppbuild",
            "label": "C/C++: gcc.exe build active file",
            "command": "g++.exe",
            "args": [
                "-fdiagnostics-color=always",
                "-g",
                "${file}",
                "-o",
                "${fileDirname}\\${fileBasenameNoExtension}.exe"
            ],
            "options": {
                "cwd": "${fileDirname}"
            },
            "problemMatcher": [
                "$gcc"
            ],
            "group": {
                "kind": "build",
                "isDefault": true
            },
            "detail": "Task generated by Debugger."
        }
    ],
    "version": "2.0.0"
}
```

### Debugger Logs

```shell
debug console does not output any logs
```

### Other Extensions

I have other extensions installed, but all are currently disabled, only C/C++ extensions remain, the problem still exists.
![image](https://user-images.githubusercontent.com/6604230/185633052-4a0226a4-14ed-41fc-9c05-400828099e61.png)

### Additional Information

[Original issue link](https://github.com/microsoft/vscode/issues/158578)

@weinand thought it was a C/C++ extension issue and suggested I migrate the issue here

**Comment by sean-mcmanus** [comment]
We haven't seen a report like this yet. Is there something "unusual" about your setup? Do you have a particular language pack installed in VS or in your OS settings?

**Comment by pedoc** [comment]
@sean-mcmanus  Hi,thank you for your reply

I verified this issue by installing a fresh win10 and mingw environment in a virtual machine and the conclusion is
1. The mingw environment must be added to the global system PATH, and the environment variable configured by VSCode is invalid (the above phenomenon occurs)
I had previously enabled the mingw environment by tweaking the VSCode settings to avoid interfering with the system global PATH.
The configuration is as follows:

#### settings.json
```
{
    "workbench.iconTheme": "vscode-icons",
    "vsicons.dontShowNewVersionMessage": true,
    "editor.unicodeHighlight.nonBasicASCII": false,
    "editor.accessibilitySupport": "off",
    "editor.wordWrap": "on",
    "security.workspace.trust.untrustedFiles": "open",
    "[json]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "terminal.integrated.profiles.windows": {
        "nushell": {
            "path": "C:\\Users\\pedoc\\.cargo\\bin\\nu.exe",
        },
        "cmd": {
            "path": "cmd.exe",
        },
        "pwsh":{
            "path":"C:\\Program Files\\PowerShell\\7\\pwsh.exe"
        }
    },
    "editor.foldingMaximumRegions": 50000,
    "workbench.sideBar.location": "right",
    "editor.inlineSuggest.enabled": true,

    "terminal.integrated.defaultProfile.windows": "pwsh",
    "security.workspace.trust.banner": "never",
    "security.workspace.trust.enabled": false,
    "security.workspace.trust.startupPrompt": "never",
    "security.workspace.trust.emptyWindow": false,
    "redhat.telemetry.enabled": true,
    "editor.unicodeHighlight.ambiguousCharacters": false,
    "cmake.configureOnOpen": true,
    "explorer.confirmDelete": false,
    "terminal.integrated.env.windows": {
        "PATH": "D:\\Env\\msys64\\usr\\bin;D:\\Env\\msys64\\mingw64\\bin;${env:PATH}"
    },
    "terminal.integrated.inheritEnv": true,
    "debug.onTaskErrors": "showErrors",
    "workbench.colorTheme": "Github Light Theme"
}
```

2. This problem has nothing to do with other extensions, because after I do 1, enabling other extensions can also debug normally

So, one question is
Do C/C++ extensions not respect VSCode's PATH environment variable?

**Comment by sean-mcmanus** [comment]
Thanks for the info -- we'll look into it.

I'm not sure what is going on with the PATH. The cppbuild task may be creating it's own terminal and not inheriting the PATH.

Changing the task's type to "shell" or something other than "cppbuild" may be a workaround.

**Comment by pedoc** [comment]
Changing the task type to ``shell`` doesn't help and gives a new error.
![image](https://user-images.githubusercontent.com/6604230/185730766-ee0ae03c-7346-4d87-addb-f64f2f725421.png)
![image](https://user-images.githubusercontent.com/6604230/185730802-64ffba28-3cd5-4dc7-be8e-a038466abad7.png)

Currently the only solution is to set the system PATH

**Comment by sean-mcmanus** [comment]
You may need to set the full path to the miDebuggerPath in your launch.json (but I haven't tried if that works yet).

Also, your previous screenshot shows launch.json being the active file, so make sure you start debugging with the .cpp file active instead.

**Comment by pedoc** [comment]
>You may need to set the full path to the miDebuggerPath in your launch.json (but I haven't tried if that works yet).

I have tried setting miDebuggerPath to the full path, but it doesn't work

>Also, your previous screenshot shows launch.json being the active file, so make sure you start debugging with the .cpp file active instead.

Yes, what I did on the .cpp file, the screenshot was a mistake.

I believe this problem exists, but I don't have any more ideas to verify or rule it out.
Please let me know if there is, thanks

**Comment by sean-mcmanus** [comment]
So is this a feature request to read/handle the `terminal.integrated.env.windows` setting when running our build tasks? It sounds like you didn't follow the tutorial step of adding the mingw path to the Windows PATH environment variable.

**Comment by pedoc** [comment]
It depends on how you look at the problem.
I can fix this by adding the ``mingw`` environment to the system ``PATH``, but I mean, since this extension also executes commands in the terminal, why doesn't he respect the ``terminal.integrated.env.windows`` setting in ``VSCode``?

Personally I don't think this is a new feature request, at best it's a refinement or addition.

**Comment by sean-mcmanus** [comment]
@pedoc @elahehrashedi This is looking to me like it might be a VS Code issue (or "by design"?), because the resolvedDefinition we're getting back doesn't have the environment variable set or the `${env:MYVAR}` resolved using the terminal.integrated.env.windows: https://github.com/microsoft/vscode-cpptools/blob/main/Extension/src/LanguageServer/cppBuildTaskProvider.ts#L209 , i.e. it doesn't seem like our extension should need to read the terminal.integrated.env.windows setting ourselves, and even if we did we wouldn't be able to correctly resolve the `${env:MYVAR}` because we receive them resolved already from VS Code.

**Comment by pedoc** [comment]
Sorry I'm not familiar with the interaction between extension and the VSCode host, and at the same time I don't think this is an urgent/important issue.
I'd be happy about support for ``terminal.integrated.env.windows`` configuration, but in the end it's up to you guys, thanks for your hard work.

So, if there is no support plan for this at the moment, should I close this issue?

**Comment by sean-mcmanus** [comment]
@pedoc From what I can tell, this is a VS Code issue that our extension isn't able to resolve on our own, because I'm seeing environment variables that resolves for us by the vscode.CustomExecution not use the `terminal.integrated.env.windows` so you may want to file an issue at https://github.com/microsoft/vscode/issues .

**Comment by elahehrashedi** [comment]
@pedoc  can you modify the `"cwd"` in your `tasks.json` and `launch.json` file from `"${fileDirname}"` to the binary directory of your compiler, e.g. `"D:\\Env\\msys64\\mingw64\\bin"`?

**Comment by pedoc** [comment]
@elahehrashedi Hi, thanks for your suggestion, I tried it but it doesn't work.

**Comment by pedoc** [comment]
Ok, then I will close this issue first.
