### ISSUE TITLE
it repeat quickSuggestions  with other plug-in

### ISSUE THREAD

**Issue by Marvin-WX** [microsoft/vscode-cpptools#976]
Because vsCode is not better in quickSuggestions, like Custom variables. It cannot complete the Custom variables, so I download the other plug-in C/C++ Clang Command Adapter. But it will repeat quickSuggestions  with this.

**Comment by Marvin-WX** [comment]
C/C++ Clang Command Adapter performs code analysis as code is typed, highlighting errors but this plug-in is not.

**Comment by Marvin-WX** [comment]
so please do something

**Comment by bobbrow** [comment]
You can disable our extension's auto-complete suggestions by adding `"C_Cpp.autocomplete": "Disabled"` to your settings.json file.
