### ISSUE TITLE
Emscripten is cleaning cache on every VScode startup

### ISSUE THREAD

**Issue by galoko** [microsoft/vscode-cpptools#9770]
### Brief Issue Summary

On startup this extention does `em++ -x c++ -E -dM nul` which triggers clearing cache on Windows. Cache takes about 5 minutes to rebuild so it's a deal breaker to use VSCode. Is there any workaround at least?

**Comment by sean-mcmanus** [comment]
@galoko Did you locate the line of code in the CMake Tools extension that is calling the compiler? Our C/C++ extension just queries the compiler with whatever file casing we're sent -- are you able to use a capital drive letter somehow? I'm seeing CMake Tools use an upper case driver letter with the compilers I have installed.
