### ISSUE TITLE
Failed to open /dev/tty with vscode debugger

### ISSUE THREAD

**Issue by FuckerRin** [microsoft/vscode-cpptools#9772]
### Environment

- OS and version: 

> Ubuntu 22.04.1 LTS

- VS Code: 

> 1.70.1

- C/C++ extension:  

> v1.11.5   

- OS and version of remote machine (if applicable):

> local

- GDB / LLDB version: 

> GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90

### Bug Summary and Steps to Reproduce

> Bug Summary:

In my program, I tried to read(or open,et al.) **/dev/tty** in vscode debugger. The program cannot open the file with vscode debugger, but the file is successfully opened with vscode internal command line or linux command line  `./cp1 cp1.c /dev/tty`
I also tried to [debug programs with "sudo" in VSCODE](https://stackoverflow.com/questions/40033311/how-to-debug-programs-with-sudo-in-vscode). It doesn't work either,seemd to have nothing to do with it.

> my code is:

```
#include<stdio.h>
#include<unistd.h>
#include<fcntl.h>
#include<stdlib.h>
#define BUFFERSIZE 4096
#define COPYMODE 0644

void oops(char*,char*);
int main(int ac,char *av[])
{
    int in_fd,out_fd,n_chars;
    char buf[BUFFERSIZE];
    //check args
    if(ac!=3)
    {
        fprintf(stderr,"usage:%s sourcr destination\n",*av);
        exit(1);
    }
    if((in_fd=open(av[1],O_RDONLY))==-1)
    {
        oops("Cannot open",av[1]);
    }
    if((out_fd=open(av[2],O_CREAT|O_WRONLY|O_TRUNC))==-1)
    {
        //when debug in VScode,it always get here
        oops("Cannot creat",av[2]);
    }
    while((n_chars = read(in_fd,buf,BUFFERSIZE))>0)
    {
        if(write(out_fd,buf,n_chars)!=n_chars)
        {
            oops("Write error to",av[2]);
        }
    }
    if(n_chars==-1) 
    {
        oops("Read error form",av[1]);
    }
    if(close(in_fd)==-1 || close(out_fd)==-1)
    {
        oops("Error closing files","");
    }
    return 0;
}
void oops(char* s1,char* s2)
{
    fprintf(stderr,"Error: %s",s1);
    perror(s2);
    exit(1);
}
```

> console result:

```
Error: Cannot creat/dev/tty: No such device or address
in 3[1] + Done                       "/usr/bin/gdb" --interpreter=mi --tty=${DbgTerm} 0<"/tmp/Microsoft-MIEngine-In-blbvypap.jt4" 1>"/tmp/Microsoft-MIEngine-Out-xlbca4ay.0tc"
```

### Debugger Configurations

```shell
launch.json:
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "(gdb) Launch",
            "type": "cppdbg",
            "request": "launch",
            "program": "${workspaceFolder}/${fileBasenameNoExtension}.out",
            "args": ["cp1.c","/dev/tty"],     (cp1.c is source code file)
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            "environment": [],
            "externalConsole": false,
            "MIMode": "gdb",
            "preLaunchTask": "build",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true,
                    
                }
            ]
        }
    ]
}




task.json:
{
    "version": "2.0.0",
    "tasks": [
        {
            "label": "build",
            "type": "shell",
            "command": "g++",
            "args": ["-g", "${file}", "-std=c17", "-o", "${fileBasenameNoExtension}.out"]
        }
        ]
}
```

### Debugger Logs

```shell
In Additional Information
```

### Other Extensions

Better C++ Syntax
Bracket Select
C++ Helper
Doxygen Documentation Generator
indent-rainbow
Rainbow Brackets
C/C++ Extension Pack v1.2.0

### Additional Information

it works well in internal console by `./cp1 cp1.c /dev/tty`
![image](https://user-images.githubusercontent.com/102639335/186095958-c35b75cf-74c5-4eb6-9d0a-62bd00e542d4.png)

when I press `ctrl + F5`   , same as debug press `F5`
![image](https://user-images.githubusercontent.com/102639335/186096558-e86944c0-6b46-42ea-9aee-5ab1d05d5a98.png)

**I also saw the Issue [Failed to open /dev/tty with vscode debugger](https://github.com/microsoft/vscode-cpptools/issues/3351), the last comment didn't work on mine**,attribute "console" have discarded (vscode:**Property console is not allowed**)? whatever "externalConsole" is true or false ,it didn't work either

**here is Debugger Log :**
[log.txt](https://github.com/microsoft/vscode-cpptools/files/9400459/log.txt)

**Comment by WardenGnaw** [comment]
Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.

**Comment by FuckerRin** [comment]
> Thank you for reporting this issue. We’ll let you know if we need more information to investigate it.

Thank you! Wait for your need!
