### ISSUE TITLE
/bin/sh: g++: not found - FreeBSD 13.1

### ISSUE THREAD

**Issue by rajhlinux** [microsoft/vscode-cpptools#9787]
### Environment

VS Code-OSS Version: 1.68.1
Commit: 30d9c6cd9483b2cc586687151bcbcd635f373630
Date: 2022-08-16T16:31:30.846Z
Electron: 17.4.8
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: FreeBSD x64 13.1-RELEASE-p1

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
clicking on the "play" button to compile "C" code, i get the following error:

`"/bin/sh: g++: not found"
`
I have installed both GCC11 and clang/llvm on FreeBSD 13.1.
I can not find any documentation to solve the issue.

I have the following task written on "task.json":

```
{
  "version": "2.0.0",
  "tasks": [
    {
      "type": "shell",
      "label": "C/C++: g++ build active file",
      "command": "/usr/bin/g++11",
      "args": ["-g", "${file}", "-o", "${fileDirname}/${fileBasenameNoExtension}"],
      "options": {
        "cwd": "/usr/bin"
      },
      "problemMatcher": ["$gcc11"],
      "group": {
        "kind": "build",
        "isDefault": true
      },
      "detail": "Task generated by Debugger."
    }
  ]
}
```

Thanks. 

### Other Extensions

I have install this extension: https://marketplace.visualstudio.com/items?itemName=Kr4is.cpptools-extension-pack

**Comment by sean-mcmanus** [comment]
Does running `/usr/bin/g++11` work? I don't think this our bug because the "shell" type is from VS Code.
