### ISSUE TITLE
 The debug configurations viewlet doesn’t appear or show any configurations

### ISSUE THREAD

**Issue by ghost** [microsoft/vscode-cpptools#9790]
### Environment

- OS and version: Windows 11 Home (build 22000.832)
- VS Code: 1.70.2 (user)
- C/C++ extension: 1.11.5
- OS and version of remote machine (if applicable): No
- GDB / LLDB version: GDB `v7.6.1`

### Bug Summary and Steps to Reproduce

**BUG SUMMARY**: _“Select a configuration”_ viewlet doesn’t appear or show any configurations

**STEPS TO REPRODUCE**:
1. Click on the **“Configure Default Build Task…”** in the _“Terminal”_ tab and then select **“C/C++: gcc.exe active build file”** in the _“Select the task to be used as the default build task”_ viewlet.
It’ll create a `tasks.json`, as usual.

https://user-images.githubusercontent.com/111590440/186884853-6e16f915-b7f9-4604-a536-ae0a8df22e19.MOV

![43FC000B-A7AA-45AF-83C0-CDAF54367E49](https://user-images.githubusercontent.com/111590440/186884873-393b4e38-802b-43a7-8578-1ec5070173cd.png)
(The `tasks.json` file)

2. Click on **“Add Configuration…”** in the _“Run”_ tab, then select **“C++ (GBD/LLDB)”** in the _“Select Environment”_ viewlet.

**ERROR**: It’ll open this `launch.json` file with no configurations, without showing the _“Select a configuration”_ viewlet first (the same happens also with **”C++ (Windows)”**).

https://user-images.githubusercontent.com/111590440/186886200-5b700e53-5bb9-4027-bd52-dac10a72bb41.MOV

![EC88FF25-E02F-456C-8C25-B8294B42B702](https://user-images.githubusercontent.com/111590440/186886218-aa60e6b1-8950-4f96-907b-76a0a0612d0b.png)
(the `launch.json` file)

**HOW IT SHOULD WORK**: After choosing the Environment, it should first open the _“Select a configuration”_ viewlet with the predefined debugging configurations 
![57B2EBF5-3795-4072-A267-56A97E55E157](https://user-images.githubusercontent.com/111590440/186888063-8e28737b-21ae-4634-bb98-4f0b8c711ddc.jpeg)
and then create a `launch.json` file with the user’s selected configuration.
![0C0A102F-C641-44ED-8B05-24262054078E](https://user-images.githubusercontent.com/111590440/186888105-44c4aa25-a6e2-4224-a70b-3aee48a57759.jpeg)
(Source: _Debugging a C++ project in VSCode_ - Visual Studio Code’s YouTube channel)

Thanks for your help.

### Other Extensions

- C/C++ Extension Pack `v1.2.0`
- C/C++ Themes  `v1.0.0`
- CMake  `v0.0.17`
- CMake Tools  `v1.11.26`
- Doxygen documentation Generator  `v1.4.0`
- Better C++ Syntax  `v1.15.19`

- Code Runner  `v0.11.8`

### Additional Information

P.S. As you can see, my example is done with C, but can you also check it the same issue is present with C++?

**Comment by sean-mcmanus** [comment]
I believe this was a "by design" change. The new way to generate the launch.json is to run the C/C++: Add Debug Configuration command from the Command Palette or use the corresponding icon in the top right of a C/C++ file if C_Cpp.debugShortcut is true.

**Comment by Nuho-ZubaedSalam** [comment]
> I believe this was a "by design" change (after 1.8.4). The new way to generate the launch.json is to run the C/C++: Add Debug Configuration command from the Command Palette or use the corresponding icon in the top right of a C/C++ file if C_Cpp.debugShortcut is true.

Can you explain me how to do it, step by step

**Comment by sean-mcmanus** [comment]
Just open a C/C++ and use the C/C++: Add Debug Configuration command from the View->Command Palette -- is that not working for you?

**Comment by sean-mcmanus** [comment]
Or click the gear icon:
![image](https://user-images.githubusercontent.com/19859882/186968468-342be90e-9f23-4dd7-9858-d846374dd2bf.png)

**Comment by Nuho-ZubaedSalam** [comment]
> Just open a C/C++ file and use the C/C++: Add Debug Configuration command from the View->Command Palette -- is that not working for you?

Ok, here I opened my file. 
![Immagine 2022-08-26 203302](https://user-images.githubusercontent.com/111590440/186969573-702fa0ae-9e9d-4182-a12e-d4ed6457d5c2.png)
and now (can you guide me step by step, please... I'm new here and I need to learn to use VSCode better)?

**Comment by Nuho-ZubaedSalam** [comment]
> Just open a C/C++ file and use the C/C++: Add Debug Configuration command from the View->Command Palette -- is that not working for you?

Oh, it’s finally working :D 
Thank you very much. ;)
