### ISSUE TITLE
Option to disable hover for just this plugin

### ISSUE THREAD

**Issue by tbfleming** [microsoft/vscode-cpptools#9793]
### Feature Request

When hover is enabled globally via `editor.hover.enabled`, vscode often freezes on C++ code. I have to disable it, but I really want hover enabled for other plugins, e.g. GitLens. I don't find the C++ plugin's hovers useful, and they tend to get in the way, so I'd prefer to disable them even if they weren't freezing vscode.

**Comment by tbfleming** [comment]
e.g. of why I don't like the C++ hovers:

![image](https://user-images.githubusercontent.com/418464/186934613-58afe7a5-d414-4461-be9f-de5c38068890.png)

I don't need it to pester me with definitions except when I explicitly ask for one

**Comment by sean-mcmanus** [comment]
Is using
```json
    "[cpp]": {
        "editor.hover.enabled": false
    }
```
sufficient?

**Comment by sean-mcmanus** [comment]
Also, the bad/incorrect hover result is caused by usage of C_Cpp.intelliSenseEngine "Tag Parser" or a configuration error that is causing it to fall back to the "Tag Parser" hover. If the IntelliSense is working correctly the hover should return a single result. However, it's possible it may still trigger delays due to code that attempts to retrieve documentation comments.

**Comment by tbfleming** [comment]
> Is using
> 
> ```json
>     "[cpp]": {
>         "editor.hover.enabled": false
>     }
> ```
> 
> sufficient?

Unfortunately that disables all plugins' hovers in cpp files, not just the C/C++ extension.

**Comment by sean-mcmanus** [comment]
Setting "C_Cpp.intelliSenseEngine" to "Disabled" will work, but it would disable "all" language service features.

The implementation of a new "C_Cpp.hover" setting might follow the example of the existing "C_Cpp.autocomplete" setting.

**Comment by sean-mcmanus** [comment]
The fix is available with 1.13.3 (pre-release): https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.3

**Comment by tbfleming** [comment]
Thanks!
