### ISSUE TITLE
Generate Doxygen comment doesn’t work via typing the preset Doxygen style `/**` & `/*!`

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#9799]
1. Set the `C_Cpp.doxygen.generatedStyle` to either  `/**` or `/*!` and set `C_Cpp.doxygen.generateOnType` to true.
2. Type the Doxygen style over a function. 

Actual result: Doxygen comment stub is not generated.

Expected result: Doxygen comment stub gets generated.

**Comment by sean-mcmanus** [comment]
I believe we wanted https://github.com/microsoft/vscode/issues/154994 to be fixed first and then enable the auto */ closing for [c], [cpp].
