### ISSUE TITLE
Debugging using WSL. Launch failed

### ISSUE THREAD

**Issue by xLobito** [microsoft/vscode-cpptools#980]
Hi there. 

I guess the issue has been reported before (Even I tried to get an answer but none was given). I hardly tried to get debugger works in VS Code for my C projects but throws an "unknown error":

"Starting: "c:\windows\sysnative\bash.exe" -c "/usr/bin/gdb --interpreter=mi"
Error: 0x80070057

"c:\windows\sysnative\bash.exe" exited with code -1 (0xFFFFFFFF)."

I used the method based on its documentation but didn't work either. 

 #![report](https://user-images.githubusercontent.com/16466974/29490501-cde69448-8514-11e7-8a59-ce535d98648f.png)

I'd appreciate a way to solve this out. Thanks in advance.

**Comment by pieandcakes** [comment]
@xLobito If you run `"c:\windows\sysnative\bash.exe" -c "/usr/bin/gdb --interpreter=mi"`  from the command line what do you see? 

>I guess the issue has been reported before (Even I tried to get an answer but none was given). 

I don't see another issue that was reported for this.

**Comment by pieandcakes** [comment]
I see its a duplicate of #877. Closing this one as its a duplicate.
