### ISSUE TITLE
PCH warning: header stop cannot be in a linkage block.  An IntelliSense PCH file was not generated.C/C++(2925)

### ISSUE THREAD

**Issue by listenha** [microsoft/vscode-cpptools#9804]
### Environment

- OS and Version: Mac OS 10.13.6 High Sierra
- VS Code Version: 1.70.2
- C/C++ Extension Version: v1.11.5
- Other extensions you installed (and if the issue persists after disabling them):  

- If using SSH remote, specify OS of remote machine:  
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
- 
[helloworld.zip](https://github.com/microsoft/vscode-cpptools/files/9441104/helloworld.zip)

### Bug Summary and Steps to Reproduce

Bug Summary: when include the header <string>, vscode gave the warning "PCH warning: header stop cannot be in a linkage block.  An IntelliSense PCH file was not generated.C/C++(2925)". and when compile helloworld.cpp, the compilation fail because that it doesn't seem to recognize the class <string>.  All concerning file is attached by the zip file above, it's a rather simple test program given by the vscode documentation itself for setting up clang compilation for mac.

By the way my mac is having trouble updating the os system, it can only stay on version 10.13.6. Any solution suggesting to update the operating system is not viable. Thanks very much if u could  provide any clue to solve this problem

Steps to reproduce:
1. Go to 'helloworld.cpp'
2. move the cursor on #include <string> to see the PCH warning
3. Click on 'run' to compile

### Code sample and Logs

```shell
====code sample:====
#include <iostream>
#include <vector>
#include <string>

using namespace std;

int main()
{
    vector<string> msg;
    msg={"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};
    
    for (const string &word : msg)
    {
        cout << word << " ";
    }
    cout << endl;
}


====c_cpp_properties.json====
{
  "configurations": [
    {
      "name": "macos-clang-x64",
      "includePath": [
        "${workspaceFolder}/**"
      ],
      "defines": [],
      "macFrameworkPath": [
        "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks"
      ],
      "compilerPath": "/usr/bin/clang",
      "cStandard": "${default}",
      "cppStandard": "${default}",
      "intelliSenseMode": "clang-x64",
      "compilerArgs": [
        ""
      ]
    }
  ],
  "version": 4
}
```

**Comment by michelleangela** [comment]
@listenha 
This warning is part of the IntelliSense cache. If the IntelliSense engine is able to, it will try to generate a precompiled headers (PCH) to improve parsing performance. You can ignore this warning or disable IntelliSense cache by setting `C_Cpp.intelliSenseCacheSize` to `0`.

**Comment by sean-mcmanus** [comment]
That error is not normally supposed to occur. Can you provide the output of running C/C++: Log Diagnostics with the repro file open?

I'm not reproing the issue with clang 13 and the macOS 11 SDK.

**Comment by sean-mcmanus** [comment]
This error can occur when our IntelliSense parser encounters code like
```cpp
extern "C"
{
<end of file>
```
in a header file. My assumption is that code like that doesn't exist, which leads me to believe there is either some configuration problem leading to invalid system headers/defines being used or there is some other IntelliSense error being hit, i.e. this could be a symptom of a larger problem, but trying the workaround at https://github.com/microsoft/vscode-cpptools/issues/9804#issuecomment-1230736168 may also be sufficient.

**Comment by sean-mcmanus** [comment]
I don't repro this with the old Sierra OS (our oldest supported OS). I'm not sure if we have a High Sierra OS available.

**Comment by listenha** [comment]
> ```shell
> c_cpp_properties.json
> ```

I'm actually not sure how to "set C_Cpp.intelliSenseCacheSize to 0". And as a matter of fact, this bug dramatically disappear after i've deleted the whole .vscode folder and regenerate them. This time the c_cpp_properties.json file didn't automatically show up in the .vscode folder

**Comment by sean-mcmanus** [comment]
C_Cpp.intelliSenseCacheSize is a setting you can set the same way as any other VS Code setting. But if deleting the c_cpp_properties.json fixes the issue then that sounds fine as well.
