### ISSUE TITLE
jump wrong line , Intellisense mouse hover display error

### ISSUE THREAD

**Issue by cjr163** [microsoft/vscode-cpptools#9806]
Hi,My english is bad, I use translation software,Thank you for checking my question, I will add pictures and instructions after the work is finished tomorrow.
Jump wrong line in .h or .hpp file  ,  Intellisense mouse hover display error,  and new feature "editor.experimental.stickyScroll.enabled": true, Error line displayed.
When the number of lines exceeds 600, Maybe 512 lines ,Usually I don't have more than 500 lines per file,Even  jump the wrong line, Usually within 30 lines up or down, So there's not too much trouble. 
I remember having this problem since 2019, Whether it's Keil, IAR, GCC project.
I looked at some of the Issues, Tomorrow I'll try **C/C++: Reset IntelliSense Database,** But I don't think it will work,Because this problem always arises when you have too many rows,Copying the project to another folder does not work either.

If you understand the problem, please give me some hints, or how can I better describe the problem

**Comment by sean-mcmanus** [comment]
Yeah, we need more info. I'm not able to repo the issue or understand what is going wrong (there could be multiple issues).

**Comment by cjr163** [comment]
![g111](https://user-images.githubusercontent.com/41551741/187384930-c3676e1c-9769-4dd8-8bd2-24308c9dbcf0.png)
![g222](https://user-images.githubusercontent.com/41551741/187384957-a71897f4-3761-44dd-b3b2-e9c95cdb96b4.png)
![g333](https://user-images.githubusercontent.com/41551741/187384973-c65be127-4b52-4a56-8bc3-cf11a0d474b7.png)

**Comment by cjr163** [comment]
Later I put the project on Github

**Comment by cjr163** [comment]
![g444](https://user-images.githubusercontent.com/41551741/187390701-29bec35b-5bb4-4241-a47e-72ba4367be73.png)
![g555](https://user-images.githubusercontent.com/41551741/187390713-db405783-4a8a-4544-a543-f4894e2cf2d7.png)
![g666](https://user-images.githubusercontent.com/41551741/187390731-8bab5a80-1f7f-4910-8a82-7c823f1b4561.png)

**Comment by cjr163** [comment]
![g777](https://user-images.githubusercontent.com/41551741/187395144-ef5c5eb8-5a84-426d-9b11-8941dac36a9f.png)


Even do not change the number of lines, 
Only the number of char in the string is changed,
the jump to the wrong line will change.

So I think it's the number of char that's wrong, not the number of lines

**Comment by cjr163** [comment]
https://github.com/cjr163/bug_issues
This is the project when the picture was taken, no changes were made

**Comment by cjr163** [comment]
![g888](https://user-images.githubusercontent.com/41551741/187412647-8c5df5d2-e35c-4bf1-8537-86421dafb0e0.png)
Try this directive after you push it to Github **C/C++: Reset IntelliSense Database**  ,it's work ,But I don't know if it's gonna happen again

**Comment by sean-mcmanus** [comment]
Does this bug still repro after the database was reset?
