### ISSUE TITLE
vscode Debugger not working

### ISSUE THREAD

**Issue by RehanKhan14** [microsoft/vscode-cpptools#9817]
Getting Errors while trying to Debug Please Help me out
![Screenshot (62)](https://user-images.githubusercontent.com/101788037/187566128-096d0dd3-61b4-4ebc-be5b-8f548671d271.png)
![Screenshot (63)](https://user-images.githubusercontent.com/101788037/187566134-d4831688-69d9-44a6-add5-4dfdf928d764.png)
![Screenshot (64)](https://user-images.githubusercontent.com/101788037/187566135-2915d0b4-421e-4ff1-bede-efb8438bce00.png)

**Comment by RehanKhan14** [comment]
Launch.json
{
    "version": "0.2.0",
    "configurations": [
    
      {
        "name": "g++.exe build and debug active file",
        "type": "cppdbg",
        "request": "launch",
        "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": false, //set to true to see output in cmd instead
        "MIMode": "gdb",
        "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
        "setupCommands": [
          {
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
          }
        ],
        "preLaunchTask": "g++.exe build active file"
      },
      {
        "name": "g++ build & run active file",
        "type": "cppdbg",
        "request": "launch",
        "program": "${fileDirname}\\${fileBasenameNoExtension}.exe",
        "args": [],
        "stopAtEntry": false,
        "cwd": "${workspaceFolder}",
        "environment": [],
        "externalConsole": false, //set to true to see output in cmd instead
        "MIMode": "gdb",
        "miDebuggerPath": "C:\\MinGW\\bin\\gdb.exe",
        "setupCommands": [
          {
            "description": "Enable pretty-printing for gdb",
            "text": "-enable-pretty-printing",
            "ignoreFailures": true
          }
        ],
        "preLaunchTask": "g++ build & run active file"
      }
      ]
  }
task.json
{
    "tasks": [
      {
        "type": "shell",
        "label": "g++.exe build active file",
        "command": "C:\\MinGW\\bin\\g++.exe",
        "args": [
          "-g",
          "${file}",
          "-o",
          "${fileDirname}\\${fileBasenameNoExtension}.exe"
        ],
        "options": {
          "cwd": "C:\\MinGW\\bin"
        }
      },
      {
        "type": "shell",
        "label": "g++ build & run active file",
        "command": "C:\\MinGW\\bin\\g++.exe",
        "args": [
          "${file}",
          "-o",
          "${fileDirname}\\${fileBasenameNoExtension}.exe"
        ],
        "options": {
          "cwd": "C:\\MinGW\\bin"
        }
      }
    ],
    "version":"2.0.0"
  }

**Comment by WardenGnaw** [comment]
Can you add the following to your `launch.json` and share the output of the DebugConsole when you enable logging with:
```json
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```
