### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by Tarun-Bavra** [microsoft/vscode-cpptools#9820]
- Issue Type: `Bug`
- Extension Name: `cpptools`
- Extension Version: `1.12.3`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.70.2````json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 3199,
		"activateCallTime": 495,
		"activateResolvedTime": 7259,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "ms-vscode.cpptools",
				"_lower": "ms-vscode.cpptools"
			},
			"activationEvent": "onLanguage:c"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by michelleangela** [comment]
@Tarun-Bavra 
Could you provide more info about the issue you encountered with the C/C++ extension? For example, was the issue about a specific IntelliSense feature or a debugging feature?
