### ISSUE TITLE
Can't update this extension. Please help.

### ISSUE THREAD

**Issue by Dhanashri22-6** [microsoft/vscode-cpptools#9825]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Type: <b>Bug</b>

Can't update c/c++ extension. Tried 2 to 3 times. Still nothing is happening.

Extension version: 1.12.3
VS Code version: Code 1.70.2 (e4503b30fc78200f846c62cf8091b76ff5547662, 2022-08-16T05:35:13.448Z)
OS version: Windows_NT x64 10.0.19044
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU  N3710  @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.83GB (0.57GB free)|
|Process Argv|--crash-reporter-id e9a45b05-89bc-4ebb-abce-d61dbc6a17b3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdf:30486550
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

**Comment by michelleangela** [comment]
@Dhanashri22-6 
Have you tried uninstalling the extension and doing a fresh install? If that doesn't work, could you try downloading the VSIX package from the [marketplace](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools) and manually installing it?

**Comment by sean-mcmanus** [comment]
You may also want to consider filing a bug with VS Code at https://github.com/microsoft/vscode/issues, since our extension doesn't install itself, so it's likely a VS Code issue.
