### ISSUE TITLE
[gdb] -exec is broken in 1.12.4/1.12.3

### ISSUE THREAD

**Issue by sbobko** [microsoft/vscode-cpptools#9827]
### Environment

- OS and version: Ubuntu 20.04.4 LTS
- VS Code: 1.70.2
- C/C++ extension: 1.12.4 / 1.12.3

### Bug Summary and Steps to Reproduce

Bug Summary:
Trying to use -exec results in nothing and crashes.

v1.12.4
![image](https://user-images.githubusercontent.com/46919374/187901915-4860cca3-bac3-4052-b3b9-fffc6edd0ee1.png)
v1.12.3
![image](https://user-images.githubusercontent.com/46919374/187902164-4795151b-1e9d-4b97-96d8-90fa9f45d99a.png)

When rolling back two versions, the problem disappears:
v1.11.5
![image](https://user-images.githubusercontent.com/46919374/187901653-0b490cde-2a64-4698-bdbd-7cd2c7f15164.png)

Steps to reproduce:
1. Start debugging using gdb
2. run -exec any_command in debug consol
expected: ![image](https://user-images.githubusercontent.com/46919374/187901653-0b490cde-2a64-4698-bdbd-7cd2c7f15164.png)
Actual:
![image](https://user-images.githubusercontent.com/46919374/187902164-4795151b-1e9d-4b97-96d8-90fa9f45d99a.png)

### Debugger Configurations

```shell
"description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
```

### Debugger Logs

```shell
Nothing
```

**Comment by WardenGnaw** [comment]
This is most likely due to Fix "The result of GDB -exec evaluate request in all contexts is printed in debug console." https://github.com/microsoft/MIEngine/issues/1236

VS Code should be outputting the result of the evaluate request into the console. 

Investigating....

**Comment by WardenGnaw** [comment]
I'm unable to reproduce this on v1.12.4 Ubuntu 20.04 with VS Code v1.71.0.
![image](https://user-images.githubusercontent.com/3953714/188028877-8a02d465-1cc9-45b2-8bad-e36b1767307a.png)

Can you share your `launch.json` and share the output of the DebugConsole when you enable logging with:
```json
"logging": {
   "engineLogging": true,
   "traceResponse": true
}
```

**Comment by sbobko** [comment]
Hello @WardenGnaw 
launch.json :
{
    "configurations": [
        {
            "comments": [
                "Full launch.json configuration details can be found here:",
                "https://code.visualstudio.com/docs/cpp/launch-json-reference"
            ],
            "name": "(gdb-oneapi) array-transform Launch",
            "type": "cppdbg",
            "request": "launch",
            "preLaunchTask": "",
            "postDebugTask": "",
            "program": "/home/sergey/samples/array-transform/src/array-transform",
            "args": [
                "gpu"
            ],
            "stopAtEntry": false,
            "cwd": "${workspaceFolder}",
            // "environment": [{ "name": "SYCL_DEVICE_FILTER", "value": "opencl" }],
            "externalConsole": false,
            "MIMode": "gdb",
            "miDebuggerPath": "gdb-oneapi",
            "setupCommands": [
                {
                    "description": "Enable pretty-printing for gdb",
                    "text": "-enable-pretty-printing",
                    "ignoreFailures": true
                },
                {
                    "description": "Disable target async",
                    "text": "set target-async off",
                    "ignoreFailures": true
                }
            ],
            "logging": {
                "engineLogging": true,
                "traceResponse": true
             }
        }
    ]
}

info threads log:
-exec info threads
<--   C (evaluate-23): {"command":"evaluate","arguments":{"expression":"-exec info threads","frameId":1000,"context":"repl"},"type":"request","seq":23}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (26336) <-1066-gdb-set output-radix 10\n"},"seq":1003}
1: (26336) <-1066-gdb-set output-radix 10
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (26336) ->1066^done\n"},"seq":1005}
1: (26336) ->1066^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (26336) ->(gdb)\n"},"seq":1007}
1: (26336) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (26336) 1066: elapsed time 0\n"},"seq":1009}
1: (26336) 1066: elapsed time 0
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (26337) <-1067-interpreter-exec console \"info threads\"\n"},"seq":1011}
1: (26337) <-1067-interpreter-exec console "info threads"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (26337) ->~\"  Id   Target Id                                            Frame \\n\"\n"},"seq":1013}
1: (26337) ->~"  Id   Target Id                                            Frame \n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (26337) ->~\"* 1    Thread 0x7ffff7689bc0 (LWP 177825) \\\"array-transform\\\" 0x00007ffff7e7f672 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6\\n\"\n"},"seq":1015}
1: (26337) ->~"* 1    Thread 0x7ffff7689bc0 (LWP 177825) \"array-transform\" 0x00007ffff7e7f672 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6\n"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (26337) ->1067^done\n"},"seq":1017}
1: (26337) ->1067^done
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (26337) ->(gdb)\n"},"seq":1019}
1: (26337) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (26337) 1067: elapsed time 0\n"},"seq":1021}
1: (26337) 1067: elapsed time 0
--> R (evaluate-23): {"type":"response","request_seq":23,"success":true,"command":"evaluate","body":{"result":"  Id   Target Id                                            Frame \n* 1    Thread 0x7ffff7689bc0 (LWP 177825) \"array-transform\" 0x00007ffff7e7f672 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6\n","variablesReference":0},"seq":1023}

Upd:
Commands that start with - work, the example in the screenshot. Perhaps this will tell you more than it tells me.
![image](https://user-images.githubusercontent.com/46919374/188149175-2e4d3775-130b-45ee-b4d9-dd1f24b35bd6.png)
 
-exec -thread-info log:

-exec -thread-info
<--   C (evaluate-26): {"command":"evaluate","arguments":{"expression":"-exec -thread-info","frameId":1000,"context":"repl"},"type":"request","seq":26}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (275510) <-1069-thread-info\n"},"seq":1040}
1: (275510) <-1069-thread-info
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (275511) ->1069^done,threads=[{id=\"1\",target-id=\"Thread 0x7ffff7689bc0 (LWP 177825)\",name=\"array-transform\",frame={level=\"0\",addr=\"0x00007ffff7e7f672\",func=\"__cxa_throw\",args=[],from=\"/lib/x86_64-linux-gnu/libstdc++.so.6\",arch=\"i386:x86-64\"},state=\"stopped\",core=\"2\"}],current-thread-id=\"1\"\n"},"seq":1042}
1: (275511) ->1069^done,threads=[{id="1",target-id="Thread 0x7ffff7689bc0 (LWP 177825)",name="array-transform",frame={level="0",addr="0x00007ffff7e7f672",func="__cxa_throw",args=[],from="/lib/x86_64-linux-gnu/libstdc++.so.6",arch="i386:x86-64"},state="stopped",core="2"}],current-thread-id="1"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (275511) ->(gdb)\n"},"seq":1044}
1: (275511) ->(gdb)
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (275511) 1069: elapsed time 0\n"},"seq":1046}
1: (275511) 1069: elapsed time 0
--> R (evaluate-26): {"type":"response","request_seq":26,"success":true,"command":"evaluate","body":{"result":"result-class: done\r\nthreads: [{id=1,target-id=Thread 0x7ffff7689bc0 (LWP 177825),name=array-transform,frame={level=0,addr=0x00007ffff7e7f672,func=__cxa_throw,args=[],from=/lib/x86_64-linux-gnu/libstdc++.so.6,arch=i386:x86-64},state=stopped,core=2}]\r\ncurrent-thread-id: 1\r\n","variablesReference":0},"seq":1048}
result-class: done
threads: [{id=1,target-id=Thread 0x7ffff7689bc0 (LWP 177825),name=array-transform,frame={level=0,addr=0x00007ffff7e7f672,func=__cxa_throw,args=[],from=/lib/x86_64-linux-gnu/libstdc++.so.6,arch=i386:x86-64},state=stopped,core=2}]
current-thread-id: 1

**Comment by WardenGnaw** [comment]
We may need to bring this to VS Code issues.
I logged it at https://github.com/microsoft/vscode/issues/159960

Between the two requests, they are similar, but only one of them seems to print to the debug console. 

```
-exec info threads
<-- C (evaluate-23): {"command":"evaluate","arguments":{"expression":"-exec info threads","frameId":1000,"context":"repl"},"type":"request","seq":23}
--> R (evaluate-23): {"type":"response","request_seq":23,"success":true,"command":"evaluate","body":{"result":" Id Target Id Frame \n* 1 Thread 0x7ffff7689bc0 (LWP 177825) "array-transform" 0x00007ffff7e7f672 in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6\n","variablesReference":0},"seq":1023}
```

```
-exec -thread-info
<-- C (evaluate-26): {"command":"evaluate","arguments":{"expression":"-exec -thread-info","frameId":1000,"context":"repl"},"type":"request","seq":26}
--> R (evaluate-26): {"type":"response","request_seq":26,"success":true,"command":"evaluate","body":{"result":"result-class: done\r\nthreads: [{id=1,target-id=Thread 0x7ffff7689bc0 (LWP 177825),name=array-transform,frame={level=0,addr=0x00007ffff7e7f672,func=__cxa_throw,args=[],from=/lib/x86_64-linux-gnu/libstdc++.so.6,arch=i386:x86-64},state=stopped,core=2}]\r\ncurrent-thread-id: 1\r\n","variablesReference":0},"seq":1048}
```
