### ISSUE TITLE
is there a configuration that make parser do not parse some path?

### ISSUE THREAD

**Issue by liuyuxun** [microsoft/vscode-cpptools#983]
big project need about 3 hours to parse.

if there is the configuration, it will be helpful

**Comment by bobbrow** [comment]
There are a few settings that control what is included in the parsing.

1. By default, we recursively search your `${workspaceRoot}` for code files.  You can edit this setting by opening your c_cpp_properties.json file (use the "C/Cpp: Edit Configurations..." command) and updating the value of `"browse.path"` to use fewer folders, or only include the subfolders of `${workspaceRoot}` that you need.
2. If it is easier to *exclude* just a few folders than to manually list out all the folders you want to *include*, you can update the `"files.exclude"` setting in your settings.json file.
