### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by mr27t** [microsoft/vscode-cpptools#9834]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `1.12.4`
- OS Version: `Windows_NT x64 10.0.19043`
- VS Code version: `1.71.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/mr27t/AppData/Local/Temp/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment]
No file is attached.
