### ISSUE TITLE
Interferes with 'Developer: Inspect Editor Tokens and Scopes'

### ISSUE THREAD

**Issue by smarpug** [microsoft/vscode-cpptools#9835]
Type: <b>Bug</b>

Install extension C/C++ for Visual Studio Code by Microsoft.
Open command 'Developer: Inspect Editor Tokens and Scopes' from command palette on any text in editor.
A pop-up text block "Loading..." appears and never changes.

Extension version: 1.12.4
VS Code version: Code 1.71.0 (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:36:10.600Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.03GB free)|
|Process Argv|--crash-reporter-id 01b459bc-0404-4f2c-ae55-603fd82973ac|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
2144e591:30553903

```

</details>

**Comment by smarpug** [comment]
![image](https://user-images.githubusercontent.com/13921750/188024276-4bd8fdf5-bbfa-460f-b229-0c9ba340f487.png)

**Comment by smarpug** [comment]
Disabling installed extension C/C++ for Visual Studio Code causes this problem to go away and the Developer command works as expected:
![image](https://user-images.githubusercontent.com/13921750/188024445-55bca57e-0752-4217-92ec-6c01697e6d62.png)

**Comment by smarpug** [comment]
Running on Microsoft Windows 10 Pro 10.0.19044.
Installed extensions:
danielroedl.meld-diff@1.3.3
eamodio.gitlens@12.2.0
fabiospampinato.vscode-diff@1.4.2
GitHub.github-vscode-theme@6.3.2 
GitHub.vscode-pull-request-github@0.50.0
jebbs.plantuml@2.17.3
jeff-hykin.better-cpp-syntax@1.15.19
josetr.cmake-language-support-vscode@0.0.4
ms-dotnettools.vscode-dotnet-runtime@1.5.0
ms-vscode-remote.remote-containers@0.251.0
ms-vscode-remote.remote-ssh@0.84.0
ms-vscode-remote.remote-ssh-edit@0.80.0
ms-vscode-remote.remote-wsl@0.66.3
ms-vscode.cmake-tools@1.12.26
ms-vscode.cpptools@1.12.4
ms-vscode.cpptools-extension-pack@1.3.0
ms-vscode.cpptools-themes@1.0.0
ms-vscode.makefile-tools@0.6.0
ms-vsliveshare.vsliveshare@1.0.5705
ms-vsliveshare.vsliveshare-audio@0.1.91
redhat.vscode-xml@0.21.2022062916
twxs.cmake@0.0.17

**Comment by sean-mcmanus** [comment]
You should be able to set C_Cpp.enhancedColorization to "Disabled" as a workaround.

Something may be causing our semantic token provider to not provided the info it needs or it could not be ready yet.

In order to fix the root cause we'd need more info to repro the issue.
