### ISSUE TITLE
Don't always show SSH Targets View

### ISSUE THREAD

**Issue by xisui-MSFT** [microsoft/vscode-cpptools#9836]
### Feature Request

#9760 Always shows an SSH Targets View in the debug panel, which may be annoying for users who are not using this feature. 

It's hard to determine if users use or don't use it. We can probably show it when a related command is invoked, but not being able to see a list of devices before invoking commands seems pretty awkward and confusing...

Andrew suggests that we can check 'host' in launch.json. It's a good idea, with the only drawback being it requires listening to configuration change event, which fires on all settings changes.

Also open to other suggestions.

**Comment by sean-mcmanus** [comment]
Available in 1.13.1: https://github.com/microsoft/vscode-cpptools/releases/tag/v1.13.1
