### ISSUE TITLE
Browse database (.BROWSE.VC.DB) goes big unexpectedly | Find All Reference slow

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [microsoft/vscode-cpptools#9837]
# Update
Temporary solution and cause of problem found, see this reply:  
https://github.com/microsoft/vscode-cpptools/issues/9837#issuecomment-1247146528

### Environment

- OS and Version: Windows 10 Pro 21H1 19043.1889 Experience Pack 120.2212.4180.0
- VS Code Version: 1.71.0 (user setup) Commit:`784b0177c56c607789f9638da7b6bf3230d47a8c`
- C/C++ Extension Version: v1.12.4
- Other extensions you installed (and if the issue persists after disabling them):  `ms-vscode.cpptools-extension-pack`, `ms-python.python`, `TabNine.tabnine-vscode`, `shardulm94.trailing-spaces`
- If using SSH remote, specify OS of remote machine:  No
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

Hey guys, I know the days of carefully optimizing software are over,  
but I did surprised how "by design" can effect my PC.  
I wrote a VSCode cpptools performance guide for my friend and wish to share to you,  
so you may identify some problem in current design.

The original document is [here](https://github.com/mhtvsSFrpHdE/prefetch/tree/master/qpp/prefetch#warning-vscode-cpptools), but you don't need to open it at all.

### Bugged `.BROWSE.VC.DB`

The one contains include information, VSCode will parse include path to this database,  
then use them to analysis C++ source file.

However, when using giant library like `Qt` and `boost`, VSCode can take a century to iterate through file system,  
and save 70000+ file information to `.BROWSE.VC.DB`.  
Until it was finished, CPU and hard disk never gets a rest.

This is not the worst, everytime a VSCode close/open, cpptools may drop entire database and create from zero.  
I collect some information about when the database can lost:

- Close VSCode during "Parsing workspase files"  
   This can happen if you added new library to include path recently.
- You did a database backup and restore  
   But when backup, `.BROWSE.VC.DB-shm` and `.BROWSE.VC.DB-wal` exist on disk.  
   Even if VSCode is safe shutdown(not parsing), sometimes the two file can still exist.  
   Do not restore these two small files, and delete the two exist before start VSCode,  
   or cpptools can refuse to accept the restore.
- Start VSCode, however there is `.BROWSE.VC.DB-shm` and `.BROWSE.VC.DB-wal` exist:  
   Although you have did nothing wrong, but you're running out of luck.

Therefore, open VSCode and wait the parse to complete,  
close VSCode and backup the `.BROWSE.VC.DB` is necessary.  
You will find it very useful one day.

### IPCH cache

Let's just accept these files are important for new IntelliSense to work.  
They are also means everytime do Ctrl+S save edited source code,  
390 MB will write to disk. There is no "reuse exist file".

The file is default save to operating system drive maybe %appdata%,  
So I move them to ramdisk partition.

If these file are moved to hard disk by using `C_Cpp.intelliSenseCachePath`,  
You can witness very funny things that is a cache is much slower than disable cache.  
Compress these file using `7z lzma2 fastest`, can reduce total size from `2.19GB` to `190MB`.  
I'm pretty sure my SSD nand lifespan were abused.

Enable NTFS compress on ipch folder can also reduce size from `2.19GB` to `615MB`.  
The performance should be improved in this approach.

### Feature request cpptools

In conclusion, I hope cpptools devs could take care of that `.BROWSE.VC.DB` more seriously.  
Recreate the one can be easily for developers who own SSD,  
but it's very important to HDD developers to have the database prevent from recreate.

For ipch cache files, do 7z lzma2 fastest compress to them,  
you can see vast performance gain on HDD, and sure can hold more cache in default 5000 MB limit.  
At lease to set a NTFS compress attribute on that folder if you don't wish to coding that compress.  
But `2.19GB` to `190MB` certainly better utilize limited SSD nand life isn't it?

### Bug Summary and Steps to Reproduce

Bug Summary: `.BROWSE.VC.DB` is easy to lost in daily use

Steps to reproduce:
1. Open VSCode
2. Close VSCode before "Parsing workspace folder" complete
3. Re-open VSCode
4. See very possible VSCode deleted entire db and recreate from zero
5. If delete `.BROWSE.VC.DB-shm` and `.BROWSE.VC.DB-wal`, VSCode always successfully reused the database.  
 I mean, the database did have possible to corroupt, but VSCode often actively drop it without any try.

### Expected behavior

VSCode will recover the database if it's not corrupt.

VSCode will compress the ipch cache before write to disk,  
this can be an optional setting and may allow to choose compress level.

### Code sample and Logs

```shell
`start_vscode.bat` to reuse `.BROWSE.VC.DB` as much as possible.


del /q cpptools\browse.databaseFile\.BROWSE.VC.DB-shm
del /q cpptools\browse.databaseFile\.BROWSE.VC.DB-wal
start "" "%vsCodePath%" "%vsCodeWorkspace%"
```
```


### Screenshots

_No response_

### Additional context

_No response_

**Comment by mhtvsSFrpHdE** [comment]
In my investigation process, I saw these interesting issues:

[Huge .cache folder (4.8G) - ipch](https://github.com/microsoft/vscode-cpptools/issues/6594)  
[Limit size of .browse.VC.db to avoid filling up disk](https://github.com/microsoft/vscode-cpptools/issues/3470)  
[issue 26: .browse.VC.db file deleted and recreated on each restart of code.](https://github.com/Microsoft/vscode-cpptools/issues/26)  
[Issue 26 is still happening](https://github.com/microsoft/vscode-cpptools/issues/133)  
[Discovering files stuck](https://github.com/microsoft/vscode-cpptools/issues/2633)  
[Intellisense is finding a ridiculous number of files in the workspace](https://github.com/microsoft/vscode-cpptools/issues/9037)

**Comment by sean-mcmanus** [comment]
Yes, you can use C_Cpp.files.exclude to exclude large libraries like QT or boost from the global symbol parsing. The database will get reset if the cpptools process is closed before the database safety check has been written in order to prevent a database corruption. The safety check gets written 5 seconds or so after the last database write. It's possible there could be more we could do to prevent the database resetting (I'm not sure exactly what though...I believe our database handling is equivalent to what VS does).

The ipch cache is not essential for IntelliSense to work. If you're using an HDD or are concerned about the SSD usage, you should set the C_Cpp.intelliSenseCacheSize to 0. As you have observed, the usage of the cache may decrease performance in some cases such as with a slower disk drive or when a header file is edited a lot. The ipch file isn't supposed to get re-written very time a source file changes, only if a header file changes (if it is, that sounds like a bug). I'm not sure how you're getting ipch files to be usable after compressing them (or how we'd get them to be usable), because we load them via memory mapping, so compression would save disk space storage when not in use, but increase the loading time.

**Comment by mhtvsSFrpHdE** [comment]
And this screenshot shows why add things to `C_Cpp.files.exclude` is not a decent solution:
```
"files.exclude": {
  "**/ThirdParty/boost/**": true,
  "**/ThirdParty/qt/**": true
}
```
you can see intellisense putting error red wavy line everywhere.  
I try the solution before post issue, that's the reason why I end up with dealing the databse problem.
![image](https://user-images.githubusercontent.com/10773245/188239900-49ab2f91-5bf4-4dc7-a433-e81777365dcf.png)

# ==========

For ipch cache, I find it best to have one to get speed.  
0 is slow for me.

With NTFS compress, I can store 10240 MB ipch into my ramdisk, which is 3300 MB only.  
If user use SSD, they should be capable to handle more cache with less NAND consume:  
that's why I say compress can be an optional setting. Or, maybe put a small note in setting page,  
to tell SSD users to enable NTFS compress for the folder manually.

Modern processor is always waiting for disk I/O, so exchange disk space by more CPU cycle is acceptable.  
Unless user use mobile platform, compress do consume battery which is more sensitive.

However, due to how NTFS compress work (when write, divide into small 4K block),  
HDD, rotational media will never handle NTFS compress (extremely slow without do defragment).  
That's why I mention alternative compress algorithm, lzma2, lz4, etc,  
to keep final ipch cache file continuously on disk.

You talked about `memory mapping`, indeed, change current design must be a hard work.  
I already adapt myself in current situation, so I no necessary to have a patch.  

These investigation results on my page [HDD ultimate performance guide](https://github.com/mhtvsSFrpHdE/prefetch/wiki/Frequently-asked-questions#hdd-ultimate-performance-guide)

# ==========

Consider what I do to VSCode:
```
del /q cpptools\browse.databaseFile\.BROWSE.VC.DB-shm
del /q cpptools\browse.databaseFile\.BROWSE.VC.DB-wal
start "" "%vsCodePath%" "%vsCodeWorkspace%"
```
I believe there is a potential unstable can cause database lost when it shouldn't be.

Is there a method I can grab VSCode log after VSCode exit?  
If I find I close VSCode, but the two file exist (oops, database is going to lose),  
I can upload log for you to investigate in the future.

**Comment by mhtvsSFrpHdE** [comment]
Off-topic, I use a Western Digital Black 7200 RPM CMR "gaming" hard drive.  
Sure it's slower than, 10000 RPM enterprise, but's far more good than other customers  
like the popular recetly 5400 RPM SMR, etc.

Even though, I have performance issue with cpptools ipch,  
lucky I have 32GB RAM installed so I go ramdisk. But others don't.

If one have 4GB+ graphics card, [GpuRamDrive](https://github.com/abesada/GpuRamDrive) go brrrrrrr

**Comment by sean-mcmanus** [comment]
Yeah, using files.exclude won't work for QT headers if they require recursive includes to generate the includePath for IntelliSense. You could potentially work around that adding the includePaths for QT explicitly (instead of with the ** at the end).

Which VS Code log are you referring to? The C_Cpp.loggingLevel "Debug" C/C++ logging? I don't think the logging would be useful for diagnosing database reset issues.

Actually, we're supposed to be writing the database safety check on shutdown, so if you're seeing the database get reset that implies there's some bug in which we're not shutting down cleanly. We can use this issue to track investigating that.

**Comment by mhtvsSFrpHdE** [comment]
Today I captured a bad database, I click on "X" in the top right corner of the Window to close VSCode.  
After VSCode gone,

![image](https://user-images.githubusercontent.com/10773245/189507015-2da7912f-0069-4742-bd92-729f891c9c28.png)

Currently, I have no knowledge to find evidence or dump the environment for debug...

**Comment by mhtvsSFrpHdE** [comment]
@sean-mcmanus I discovered **unusual config** in my rig. I see this issue:  
[#4102 Add ability to limit Find All References to scopes: current file, open files, workspace files](https://github.com/microsoft/vscode-cpptools/issues/4102)

The thing is every time I do `find all reference`, cpptools always go iterate through entire `Qt` and `boost`  
to find a small function named `init()` I have written, and only called 3 times in my project.

I already use ramdisk for `ipch` and `.BROWSE.VC.DB`, there's no I/O bottleneck.  
So my CPU go to 99% usage, and takes 15+ minutes to `find all reference`.

Then I look at the issue 4102 and noticed a config called `browse.path`:
```
// settings.json
		"C_Cpp.default.browse.path": [
			"${workspaceFolder}"
		]
```
```
// https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference
      "browse": {
        "path": ["${workspaceFolder}"],    // <-- This one
        "limitSymbolsToIncludedHeaders": true,
        "databaseFilename": ""
      }
```
When I go to my `c_cpp_properties.json`, it looks like:
```
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/../ThirdParty/qt/include/**",
                "${workspaceFolder}/../ThirdParty/boost"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "C:\\mingw-w64\\bin\\g++.exe",
            "cStandard": "c99",
            "cppStandard": "c++11",
            "intelliSenseMode": "windows-gcc-x86"
        }
    ],
    "version": 4
}
```

There is no `browse` related setting at all. Then I add these value to my `c_cpp_properties.json`:
```
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": "${workspaceFolder}\\cpptools\\browse.databaseFile\\.BROWSE.VC.DB"
            }
```

After close, delete database, start VSCode,  
this time, the cpptools complete workspace parse in very short time,  
left a 17.9 MB database on disk. Which is greatly small compare to 1.05 GB in the beginning of this issue.  
I can't recall why the two value are not there and not interested in create blank project for more test.

With the new config, cpptools run smooth, most operation complete in a second.  
So I can share the latest idea:

### `.BROWSE.VC.DB`

There is nothing to do with `includePath` or `files.exclude`.  
Third party library can just normally put there as usual, even if they are big.

I assume there is no database shutdown bug at all. When a database goes big unexpectedly,  
any operation can't complete in a reasonable time.

The reason that database go big is when no value provided in `c_cpp_properties.json`,  
`cpptools` not use default value suggested on [VSCode document](https://code.visualstudio.com/docs/cpp/c-cpp-properties-schema-reference) (`["${workspaceFolder}"]`).  
Instead, cpptools use `includePath` as the default `browse.path` value,  
and, `limitSymbolsToIncludedHeaders` is ignored.

To fix this, the simplest solution I can found is  
always "install" default value to `c_cpp_properties.json` if they are not already there when the extension loads.  
Hand over the config to workspace parser after config is modified correct.

The other is you can fix the default value in workspace parser,  
or to figure out why `C_Cpp.default.browse.path` default value not work.  
I have not touched the config (not listed in modified filter).

**Comment by mhtvsSFrpHdE** [comment]
By the way, I still think there should be an optimization on `ipch` cache file size.  
Look at the compress ratio!

Well, it's fine, maybe the only impact of smaller file size is   
to let me feel I'm not wasting resource, more earth environmentally friendly, less carbon footprint,  
****! I can't even tell use more CPU or use more disk, which one consume less energy. ********.

Smaller file size is good for SSD NAND life, though.  
Modern SSD may be capable for 300 TB write. Why I'm always keep reducing writes in my mind.

**Comment by sean-mcmanus** [comment]
So can we close this issue?

**Comment by mhtvsSFrpHdE** [comment]
> So can we close this issue?

As my suggest, if you made some change to current config init logic, then close it,  
more user can benefit from it, how about that?  
For example, when they open the `c_cpp_properties.json`,  
and realized there are two different folder related option.

Or even if the config is missing, the default value will correct, so workspace parser don't go to `includePath`.

Assume these default value is work at the beginning, `cpptools` won't have noticeable performance problem.  
And this issue won't even be posted.

**Comment by mhtvsSFrpHdE** [comment]
I look at the source code, it was at here

https://github.com/microsoft/vscode-cpptools/blob/3243e39c4f7599815805972755095b1f9c6639d8/Extension/src/LanguageServer/configurations.ts

line 909
```
// 909      if (!configuration.browse.path) {
                if (settings.defaultBrowsePath) {
                    configuration.browse.path = settings.defaultBrowsePath;
                } else if (configuration.includePath) {
// 913              // If the user doesn't set browse.path, copy the includePath over. Make sure ${workspaceFolder} is in there though...
                    configuration.browse.path = configuration.includePath.slice(0);
                    if (configuration.includePath.findIndex((value: string, index: number) =>
                        !!value.match(/^\$\{(workspaceRoot|workspaceFolder)\}(\\\*{0,2}|\/\*{0,2})?$/g)) === -1
                    ) {
                        configuration.browse.path.push("${workspaceFolder}");
                    }
                }
            } else {
                configuration.browse.path = this.updateConfigurationPathsArray(configuration.browse.path, settings.defaultBrowsePath, env);
            }
```

Line 913, no, do not copy `includePath`, just use `${workspaceFolder}`.  
In my experience, no `includePath` in `browse.path` will not cause the kind of side effect,  
at least in current release version.

**Comment by mhtvsSFrpHdE** [comment]
Line 913 design have an immediate consequence: workspace parser treat `includePath` as part of user source code.

This should not happen, an [Intel® Xeon® Processor E3-1231 v3](https://www.intel.com/content/www/us/en/products/sku/80910/intel-xeon-processor-e31231-v3-8m-cache-3-40-ghz/specifications.html) processor  
takse 15+ minutes to do `Find All Reference` if a function named `init()`,  
when user use `Qt` and `boost` at the same time.

**Comment by mhtvsSFrpHdE** [comment]
Here is an example about how can I think a fix should be:

https://github.com/microsoft/vscode-cpptools/pull/9881

**Comment by mhtvsSFrpHdE** [comment]
If create a new win32 configuration
- Open new project, click on `C/C++ Configuration` button (icon text: Win32)
- Edit Configurations (JSON)

Then this file shows:
![image](https://user-images.githubusercontent.com/10773245/190527966-6c008d42-c7b6-4f6e-9bf4-e0cbc89d55b4.png)

You can see there is no default value of `folder` config group:
```
            "browse": {
                "path": [
                    "${workspaceFolder}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
```

Therefore, if a user add any library to `includePath`,  
the `browse.databaseFile` sure to grow and cause low performance.  
Which is can reproducible now.

**Comment by mhtvsSFrpHdE** [comment]
We have collect enough information on this.  
The conclusion is at https://github.com/microsoft/vscode-cpptools/pull/9881#issuecomment-1248807815
