### ISSUE TITLE
Clang-tidy flame icon disappears after clicking "Pause clang-tidy" (Linux only)

### ISSUE THREAD

**Issue by michelleangela** [microsoft/vscode-cpptools#9840]
### Environment

- OS and Version: Linux platforms
- VS Code Version: 1.70
- C/C++ Extension Version: 1.12.4

### Bug Summary and Steps to Reproduce

1. Run code analysis
2. Pause code analysis by clicking on "flame icon" from status bar and then click "Pause clang-tidy".
3. Result: flame icon disappears.

### Expected behavior

Flame icon should not disappear.

### Code sample and Logs

```shell
n/a
```

**Comment by sean-mcmanus** [comment]
Hmm...I don't repro the bug using WSL2 on our vc folder. Do you know their repro details and/or have you reproed this and/or any ideas why I'm not reproing it?

**Comment by michelleangela** [comment]
I used sample code from tutorial:

```cpp
#include <iostream>
#include <vector>
#include <string>

using namespace std;

int main()
{
   vector<string> msg {"Hello", "C++", "World", "from", "VS Code", "and the C++ extension!"};

   for (const string& word : msg)
   {
      cout << word << " ";
   }
   cout << endl;
}
```

**Comment by sean-mcmanus** [comment]
Yeah, I still don't repro the issue -- if you only launched code analysis on 1 file, it's possible that it was already in progress and not pausable and so it just finished. The pausing is typically for the scenario when multiple files are being analyzed in a long-running operation.

**Comment by sean-mcmanus** [comment]
Do you get any logging message? I just see "cpptools/pauseCodeAnalysis".

**Comment by michelleangela** [comment]
I see "cpptools/pauseCodeAnalysis" in the logging. I think it is a race condition too where it just finished when it was paused for a small file size. If you quickly do a pause on a small file, then the flame icon does not disappear. 

I will close this is as not a bug. I also agree that the pausing feature is meant for long-running operations.
