### ISSUE TITLE
How to break the debugger with a single exception type?

### ISSUE THREAD

**Issue by evandrocoan** [microsoft/vscode-cpptools#9849]
### Feature Request

I see https://github.com/Microsoft/vscode-cpptools/issues/1800 was closed when https://github.com/microsoft/vscode-cpptools/issues/8728 was merged, but I do not see how to add a single exception type to stop gdb.

I would not like to break on all exceptions, but on a specific exception as `std::runtime_error`: 
![image](https://user-images.githubusercontent.com/5332158/188438582-450ae9d6-d3a7-48f0-8a26-e9516c214bf4.png)

**Comment by WardenGnaw** [comment]
If you right, click and select `Edit Condition` you can specify which exception type to only stop on.

Steps:
Go to Breakpoints window:
![image](https://user-images.githubusercontent.com/3953714/188726432-cdaf94df-a449-4bcc-ba36-ac9bfa5dc00f.png)

After selecting `Edit Condition...`
![image](https://user-images.githubusercontent.com/3953714/188726450-a7581c71-535d-40aa-9481-8afcb0f811a0.png)

**Comment by evandrocoan** [comment]
Thanks. I did not try it yet, but when I use the debugger again I will check it out.
