### ISSUE TITLE
C/C++ Clang_Format, prompts no plugin is installed

### ISSUE THREAD

**Issue by AllanWang0507** [microsoft/vscode-cpptools#9854]
Unable to use shift+alt+F for code formatting, it prompts that no plugin is installed
[image](https://user-images.githubusercontent.com/48042184/188622449-d98a50b7-adf1-4013-9688-ccf4234b3f6e.png)

**Comment by michelleangela** [comment]
@AllanWang0507 
If the error prompt says no plugin is installed, could you try uninstalling and reinstalling the extension? If there are installing issues, please file a bug on VS Code https://github.com/Microsoft/vscode as the VS Code client manages installation procress.
