### ISSUE TITLE
C++20 module imports not detected (using G++ as compiler)

### ISSUE THREAD

**Issue by MangoDev1** [microsoft/vscode-cpptools#9855]
### Environment

- OS and Version: Windows 10 Home x64 (v10.0.19044)
- VS Code Version: 1.71.0
- C/C++ Extension Version: 1.12.4
- Other extensions you installed (and if the issue persists after disabling them): ms-vscode.makefile-tools (Yes)
- If using SSH remote, specify OS of remote machine:  N/A
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc):

`export`ing modules gives no errors, but trying to `import` them (even if the source file for that module is in the same folder) always gives the error: `"could not find module file for module "[insert module name here]"C/C++(3275)"`. Below are screenshots of the `export module` statement (no errors), and the `import` statement (always gives error). I am using GCC through MSYS2, and it supports modules for the most part. I am not using any private module sections, so there shouldn't be any errors. In both the makefile and `c_cpp_properties.json` file, I have the `-fmodules-ts` and `-std=c++20` compiler flags passed.

`export module` statement:
![image](https://user-images.githubusercontent.com/94928669/188705351-6e182677-99c6-481c-b437-d88947744566.png)

`import` statement:
![image](https://user-images.githubusercontent.com/94928669/188705462-eeab59c7-22bf-4986-99d7-cf6f28528479.png)

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. Create project
2. Create main file
3. Create module file
4. Add `export module [module name]` to the module file
5. Add `import [module name]` to main file
6. See error

### Expected behavior

The module should be imported successfully, including all of its *(exported)* functions, variables, structs, classes, etc.

### Code sample and Logs

```shell
main.cpp, module.cpp, and Makefile are all in the root directory of the project.

/* main.cpp */
import testmodule;

int main() {
    f();
    return 0;
}

/* module.cpp */
module;

#include <iostream>

export module testmodule;

export void f() {
    std::cout << "Hello world!\n";
}

# Makefile
default:
	g++ *.cpp -o program.exe -std=c++20 -fmodules-ts

// c_cpp_properties.json
{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.20348.0",
            "compilerPath": "C:/msys64/mingw64/bin/g++.exe",
            "cStandard": "c17",
            "cppStandard": "c++20",
            "intelliSenseMode": "windows-gcc-x64",
            "configurationProvider": "ms-vscode.makefile-tools"
        }
    ],
    "version": 4
}

-------- Diagnostics - 9/6/2022, 1:16:38 PM
Version: 1.12.4
Current Configuration:
{
    "name": "Win32",
    "includePath": [
        "${workspaceFolder}/**"
    ],
    "defines": [
        "_DEBUG",
        "UNICODE",
        "_UNICODE"
    ],
    "windowsSdkVersion": "10.0.20348.0",
    "compilerPath": "C:/msys64/mingw64/bin/g++.exe",
    "cStandard": "c17",
    "cppStandard": "c++20",
    "intelliSenseMode": "windows-gcc-x64",
    "configurationProvider": "ms-vscode.makefile-tools",
    "compilerPathIsExplicit": true,
    "cStandardIsExplicit": true,
    "cppStandardIsExplicit": true,
    "intelliSenseModeIsExplicit": true,
    "mergeConfigurations": false,
    "browse": {
        "path": [
            "${workspaceFolder}/**"
        ],
        "limitSymbolsToIncludedHeaders": true
    }
}
Custom browse configuration: 
{
    "browsePath": [
        "c:\\Users\\INSERT_USER_HERE\\projects\\modules"
    ],
    "compilerPath": "C:\\msys64\\mingw64\\bin\\g++.exe",
    "standard": "c++20",
    "compilerArgsLegacy": [
        "-o",
        "program.exe",
        "-fmodules-ts"
    ]
}
Translation Unit Mappings:
[ C:\Users\INSERT_USER_HERE\projects\modules\main.cpp ]:
    C:\Users\INSERT_USER_HERE\projects\modules\main.cpp
Translation Unit Configurations:
[ C:\Users\INSERT_USER_HERE\projects\modules\main.cpp ]:
    Process ID: 14916
    Memory Usage: 12 MB
    Compiler Path: C:\msys64\mingw64\bin\g++.exe
    Includes:
        C:\MSYS64\MINGW64\INCLUDE\C++\12.2.0
        C:\MSYS64\MINGW64\INCLUDE\C++\12.2.0\X86_64-W64-MINGW32
        C:\MSYS64\MINGW64\INCLUDE\C++\12.2.0\BACKWARD
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\12.2.0\INCLUDE
        C:\MSYS64\MINGW64\INCLUDE
        C:\MSYS64\MINGW64\LIB\GCC\X86_64-W64-MINGW32\12.2.0\INCLUDE-FIXED
    Standard Version: c++20
    IntelliSense Mode: windows-gcc-x64
    Other Flags:
        --g++
        --gnu_version=120200
Total Memory Usage: 12 MB

------- Workspace parsing diagnostics -------
Number of files discovered (not excluded): 3381

Terminal:
PS C:\Users\INSERT_USER_HERE\projects\modules> mingw32-make
g++ *.cpp -o program.exe -std=c++20 -fmodules-ts
PS C:\Users\INSERT_USER_HERE\projects\modules> ./program.exe
Hello world!
PS C:\Users\INSERT_USER_HERE\projects\modules>
```

### Screenshots

![image](https://user-images.githubusercontent.com/94928669/188709925-55f30976-4dfa-4973-ab47-d72fe77ca969.png)
![image](https://user-images.githubusercontent.com/94928669/188709961-bf849e9d-e554-4edb-b612-4d1907f60768.png)
![image](https://user-images.githubusercontent.com/94928669/188710000-cb06d7e4-a798-40d9-b155-e2111b6d3967.png)
![image](https://user-images.githubusercontent.com/94928669/188710036-51d3da66-3f9b-4095-b897-bdd20136c0cb.png)

Intellisense gave errors, yet the program compiled successfully
![image](https://user-images.githubusercontent.com/94928669/188710589-e46a31ce-fab3-499c-bb6c-35692c5d5383.png)

**Comment by sean-mcmanus** [comment]
We're already tracking module importing with https://github.com/microsoft/vscode-cpptools/issues/6302 .
