### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by knabd** [microsoft/vscode-cpptools#9857]
- Issue Type: `Performance`
- Extension Name: `cpptools`
- Extension Version: `1.12.4`
- OS Version: `Darwin arm64 21.6.0`
- VS Code version: `1.70.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/qh/795hqxt165n5wtnm0kdn3qvc0000gn/T/ms-vscode.cpptools-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by sean-mcmanus** [comment]
No attachment data.
