### ISSUE TITLE
Datetime formatted wrongly

### ISSUE THREAD

**Issue by AquaDrome** [microsoft/vscode-cpptools#9858]
I would like to keep...

`D'2022.09.07 15:50:10'`

...as is, but the extension's formatting changes it to...

`D '2022.09.07 15:50:10'`

Please note the inserted whitespace after _D_. I have to use this C/C++ extension for another, C-derived language. More than a mere cosmetics issue, this causes a compilation error!

I've scanned the [documentation ](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) for a  solution but I can't find one for the life of me.

Can you please help me with this hopefully simple problem?

**Comment by sean-mcmanus** [comment]
How are you getting `D'2022.09.07 15:50:10'` to compile?

**Comment by AquaDrome** [comment]
Short of a more specific alternative, I'm using this extension for a C-derived language and it works well except for this one formatting issue here. I compile in VS Code via a VS Code Task → Powershell Script → Bash Script. The Bash Script runs the derived language's compiler on the code in VS Code.

This just as additional information as requested.

Please just tell me how I can avoid the extension's formatting inserting that space in `D '2022.09.07 15:50:10'` — can I exclude letter D somehow (seems to be treated the same like e.g. a data type) in the extension's configuration? Or would this be a new feature?

**Comment by sean-mcmanus** [comment]
Which formatting engines are you running: clang-format or vcFormat (i.e. C_Cpp.formatting setting)?

The formatters are designed to format a specific language, so I'm not sure if either formatter would be able to handle this. We're unlikely to implement it for vcFormat (closed source), but you may be able to implement it in clang-format, which is open source -- clang-format supports different language configurations.

**Comment by AquaDrome** [comment]
So this issue will not be addressed?

Then can you please share a workaround for this formatting issue? Can I twist the Extensions' settings somehow so that it doesn't insert a space after keywords (?) like "D" or whatever the extension thinks "D" to be (D seems to be treated the same way like e.g. data types like int, double etc.)? 

How is the setting called that I need to change, please?

**Comment by sean-mcmanus** [comment]
@AquaDrome What is your C_Cpp.formatting setting? Do you want to format with vcFormat or clang-format?

**Comment by AquaDrome** [comment]
I think I want to format with clang. Actually I have [this other extension](https://marketplace.visualstudio.com/items?itemName=nicholishen.mql-extension-pack) installed which should do the formatting, but I think the author mentioned he had to drop code formatting. Anyway, the code is formatted with your extension now by VSC and apart from the datetime issue we have been discussing above it works fine.

Can you please help me with my datetime formatting issue somehow?

**Comment by sean-mcmanus** [comment]
You should file an issue at https://github.com/llvm/llvm-project/issues on clang-format. It's open source so you could potentially contribute a fix.
