### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by UgoBen3** [microsoft/vscode-cpptools#9863]
- Issue Type: `Bug`
- Extension Name: `cpptools`
- Extension Version: `1.12.4`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.0`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by Colengms** [comment]
Hi @UgoBen3 .  This issue does not contain information about the problem you encountered.  Could you please provide details about the problem you are seeing, as well as the other information requested in the 'new issue' form?
