### ISSUE TITLE
Bug in the blackout specification by the preprocessor part

### ISSUE THREAD

**Issue by welch-s** [microsoft/vscode-cpptools#9864]
### Environment

- OS and version: Windows10
- VS Code: 1.71.0
- C/C++ extension: v1.12.4
- OS and version of remote machine (if applicable):not remote

## Bug Summary:
If you put a comment in an area that is disabled by the preprocessor, the process of darkening the source code works incorrectly.

### No problem description
Areas that were invalidated by the preprocessor are darkened as intended.

#if 0				
static int test;	
#endif

void main(void)
{
	char aaa;
	aaa++;
}
![image](https://user-images.githubusercontent.com/4651390/189321810-8c8f8276-6263-4982-a3eb-e28d0ca4e991.png)

--- 

### Description that does not work well
If you insert a half-width space or a tab and a slash x2 in the invalidation area, the blackout specification will be applied to the code after the endif.

#if 0 //
static int test; //
#endif

void main(void)
{
	char aaa;
	aaa++;
}

![image](https://user-images.githubusercontent.com/4651390/189321683-1ace05aa-8691-43fc-b28b-219c34b002c4.png)
--- 

### Other Extensions

・C/C++ Themes
・C# for Visual Studio Code
・Community Material Theme
・Dracula Official
・Draw.io Integration
・Git Graph
・GitHub Theme
・GitLens
・Hex Editor
・Japanese Language Pack for Visual Studio Code
・jumpy
・Material Theme
・Material Theme Icons
・One Monokai Theme
・Todo Tree
・Zenkaku-Hankaku

**Comment by Colengms** [comment]
Hi @welch-s .  I believe the issue you are seeing here may actually be a bug in VS Code, and not the C/C++ extension.  

There are 2 types of 'blackout' occurring.  The C/C++ extension is responsible for providing the 'dimmed out' look for content within a disabled processor (`#if`) block.  VS Code provides colorization for comments.  It's not obvious from your theme, but perhaps with another theme, you should see that there are two styles involved here.  You can also confirm this by using the `Developer: Inspect Editor Tokes and Scopes` command and clicking on the colored text.  This should indicate the incorrectly colored text is being considered a comment, although it clearly is not a comment.

I see that this only occurs in C files and not C++ files.  There issue would seem to be with VS Code's 'TextMate colorization`, which involves identifying regions to color based on regular expressions.  It would seem that use of single-line comment is somehow causing all subsequent text to be colored as a comment.

I'd suggest opening an issue against VS Code here: https://github.com/microsoft/vscode/issues

I was not able to reproduce an issue specific to "half-width space" characters.  However, a "half-width space" is not consider white space by C++, so will be treated as a literal character.  https://en.cppreference.com/w/cpp/string/byte/isspace

**Comment by welch-s** [comment]
@Colengms 
Thank you for your answer.
Since it was reproduced with all extensions including c/cpp extensions removed, it was determined to be a problem with VisalStudioCode.
This issue will be closed and will be reported again in the VisualStudioCode project.
