### ISSUE TITLE
Rendering issue: Text greyed out after outside of `#if #endif`.

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#9868]
Type: <b>Bug</b>

Rendering issue: Text greyed out after outside of `#if #endif`.

On the screenshot the effect is visible even after I deleted the `#if #endif`

Extension version: 1.12.4
VS Code version: Code 1.71.0 (Universal) (784b0177c56c607789f9638da7b6bf3230d47a8c, 2022-09-01T07:25:38.437Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.28GB free)|
|Process Argv|--crash-reporter-id a7eaff19-94ae-4653-b917-d9aaab19da5d|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
pylanb8912:30545647
vsclangdc:30486549
c4g48928:30535728
hb751961:30553087
dsvsc012cf:30540253
azure-dev_surveyone:30548225
i497e931:30553904

```

</details>

![Screenshot 2022-09-09 at 14 10 49](https://user-images.githubusercontent.com/47526411/189337970-f3393a4f-3ced-4d0c-9977-d86931ac6d54.png)

**Comment by Colengms** [comment]
Hi @H-G-Hristov .  Can you provide a repro, so we can investigate further?

Is it possible this may be simply a delay, due to complex and time-consuming processing necessary to provide an updated analysis of the file after you've changed/removed the preprocessor conditional?

**Comment by H-G-Hristov** [comment]
Can the above issue be related to: https://github.com/microsoft/vscode-cpptools/issues/9870

**Comment by sean-mcmanus** [comment]
@H-G-Hristov It seems unlikely. In that case, semantic highlighting was broken due to IntelliSense crashing, but in your case a region is being reported as inactive. You could confirm by checking for IntelliSense crash messages in your logging or when we release 1.13.1 next week.

**Comment by H-G-Hristov** [comment]
> Hi @H-G-Hristov . Can you provide a repro, so we can investigate further?
> 
> Is it possible this may be simply a delay, due to complex and time-consuming processing necessary to provide an updated analysis of the file after you've changed/removed the preprocessor conditional?

I haven't been able to reproduce it again yet.
