### ISSUE TITLE
No syntax highlighting for typedeffed types.

### ISSUE THREAD

**Issue by Srekel** [microsoft/vscode-cpptools#987]
This is what it looks like for me. I've included the TM scope inspection.

![image](https://user-images.githubusercontent.com/1578924/29603610-0fe2e7de-87e5-11e7-9ecd-07d38bccde9d.png)

Seems like the whole type + variable name gets parsed as the same token? I'm not sure if this is a bug in the C++ extension or in VS Code's standard C++ language definition but I thought it made sense to post here first.

**Comment by bobbrow** [comment]
The current colorizer doesn't have any knowledge of user-defined types or typedefs, so they won't get the colors you expect.  We are tracking colorization with issue #230.
