### ISSUE TITLE
IntelliSense/Editor C++23 support

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#9878]
### Feature Request

C++23 syntax is not supported, e.g. https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p0330r8.html

![Screenshot 2022-09-14 at 13 51 47](https://user-images.githubusercontent.com/47526411/190135267-bbd7cd41-27cd-4a46-9750-8776c4b38ec2.png)
![Screenshot 2022-09-14 at 13 52 32](https://user-images.githubusercontent.com/47526411/190135418-af2e77c6-d130-496d-a738-3b5451803007.png)
![Screenshot 2022-09-14 at 13 53 32](https://user-images.githubusercontent.com/47526411/190135587-58ee66f6-8e64-450c-9405-5dea5198e980.png)

**Comment by sean-mcmanus** [comment]
C++23 support is actively being developed...I'm checking if we're supposed to file a bug or just wait for them to finish implementing it...

**Comment by sean-mcmanus** [comment]
It's not implemented by the cl.exe or EDG compilers yet: see https://en.cppreference.com/w/cpp/23 . We're closing this issue since there's no value in tracking it as a bug or feature request since that's already being tracked for C++23 in general.
