### ISSUE TITLE
IntelliSense does not prompt class members sometimes

### ISSUE THREAD

**Issue by lh123** [microsoft/vscode-cpptools#988]
Operating System and version：win10
VS Code version: 1.15.1
C/C++ extension version:0.12.3

1.In the template class, IntelliSense can not prompt for the type that is typedef defined

![image](https://user-images.githubusercontent.com/10697249/29702973-25211bbc-89a6-11e7-9b61-c47c49969cb0.png)

2.In non-template classes, IntelliSense can prompt for types that are typedef defined

![image](https://user-images.githubusercontent.com/10697249/29703141-de13749e-89a6-11e7-9bfc-e15723f57566.png)

**Comment by bobbrow** [comment]
Thanks for reporting this.  I have a fix for it which will be in the next update.

**Comment by bobbrow** [comment]
The fix for this is in 0.12.4
