### ISSUE TITLE
![image](https://user-images.githubusercontent.com/8823157/93025684-96a37280-f61d-11ea-888f-8754ead59d26.png)

### ISSUE THREAD

**Issue by govind0107** [microsoft/vscode-cpptools#9885]
![image](https://user-images.githubusercontent.com/8823157/93025684-96a37280-f61d-11ea-888f-8754ead59d26.png)

Even I'm facing the same issue

_Originally posted by @FazeelUsmani in https://github.com/microsoft/vscode-cpptools/issues/5664#issuecomment-691707307_

**Comment by sean-mcmanus** [comment]
We need more info, such as what is provided by running the C/C++: Log Diagnostics command.

**Comment by govind0107** [comment]
The issue got resolved.
Thank you
