### ISSUE TITLE
Trying to debug a C++ program for the first time in WSL with gdb in Ubuntu 20.04 but getting 'the value of miDebuggerPath is invalid.' What is launch.json file and how to set it up?

### ISSUE THREAD

**Issue by shahjacobb** [microsoft/vscode-cpptools#9892]
### Environment

- OS and version: Ubuntu 20.04 on Windows 10
- VS Code: 1.71 
- C/C++ extension: Regular VScode store C++ extension pack....
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

I am trying to debug a simple program with gdb for the first time in C++ and am totally lost and overwhelmed by this json stuff. I'm running Ubuntu 20.04 on Windows 10 and installed g++ using `sudo apt install build-essential`. When I compile and execute with `g++` the programs execute just fine in the terminal. I don't want to debug via the terminal whatsoever. I **get this error** while debugging: 'the value of miDebuggerPath is invalid.' 

It then tells me to set up a configuration file or something Idk what any of this stuff means man, 
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": []
}
```
Idk what a `launch.json` or `task.json` file is or what all the confusing keys/commands in the file mean and what value to set the 20 or keys/commands to in the `launch.json` file. It just spits out this empty confusing file above with no context. There's no good beginner-friendly tutorials online either. Can someone help me? 

```

### Other Extensions

_No response_

### Additional Information

_No response_

**Comment by sean-mcmanus** [comment]
We have a walkthrough at https://code.visualstudio.com/docs/cpp/config-linux .

Normally, all you have to do is press the debug button in the top right of the file.

**Comment by DaPiePiece** [comment]
Hello, I have the exact same issue and can't find a single solution online. Currently debugging by hand.

Working on WSL2, Ubuntu 20.08. 

I've specified my debugger path inside of launch.json, and it still tells me "the value of miDebuggerPath is invalid".

What's odd is that specifying the include and compiler paths inside of c_cpp_properties.json is the exact same process, and vscode has no issue resolving those two.

Here's my launch.json file.

`{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "C/C++ Runner: Debug Session",
      "type": "cppdbg",
      "request": "launch",
      "args": [],
      "stopAtEntry": false,
      "externalConsole": false,
      "cwd": "/mnt/c/Users/berej/OneDrive/Documents/'Masters Suffering'/Code/cpp",
      "program": "/mnt/c/Users/berej/OneDrive/Documents/'Masters Suffering'/Code/cpp/build/Debug/outDebug",
      "MIMode": "gdb",
      "miDebuggerPath": "gdb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        }
      ]
    }
  ]
}`

**Comment by johngco** [comment]
Hey not sure if im allowed to do this but this still might be issue. I can compile the using this command in Ubuntu 22.04 
 # g++ -o hello HelloWorld.cc
 #./hello 
Hello C++ World from VS Code and the C++ extension!

But in VS it errors. 

and here are the VS terminal logs... literally says report it to github. lol 

`[2023-02-27 22:00:37.968] Server bound to 127.0.0.1:46097 (IPv4)
[2023-02-27 22:00:37.968] Extension host agent listening on 46097
[2023-02-27 22:00:37.968] 
[2023-02-27 22:00:37.977] Started local proxy server on 64252.
[2023-02-27 22:00:37.977] WSL resolver response: 127.0.0.1:64252
[2023-02-27 22:00:37.977] To debug connection issues, open a local browser on http://127.0.0.1:64252/version
[2023-02-27 22:00:37.977] Using 'wslExeProxy' to connect to the VS Code server as configured by setting 'remote.WSL2.connectionMethod'
[2023-02-27 22:00:37.977] 'wslExeProxy' should fix reconnection issues after sleep and network adapter changes.
[2023-02-27 22:00:37.977] Please report issues related with the new setting to https://github.com/microsoft/vscode-remote-release/issues/5894
[2023-02-27 22:00:37.977] To revert back to the old way of connecting, change setting 'remote.WSL2.connectionMethod' to 'wsl2VMAddress'.`

**Comment by bobbrow** [comment]
Hi @johngco, your issue appears to be different and the message you shared says to report problems with the `wslExeProxy` setting to https://github.com/microsoft/vscode-remote-release/issues/5894 which is in another repository.  It looks like you are getting disconnected and the maintainers at that repository might be able to help you out.

**Comment by johngco** [comment]
Bob
Thank you for the direction

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
