### ISSUE TITLE
issue with package.json

### ISSUE THREAD

**Issue by weinand** [microsoft/vscode-cpptools#99]
_From @nate2009 on July 13, 2016 6:15_
- VSCode Version:
- OS Version:

Steps to Reproduce:
1. Cannot read file /home/iga/.vscode/extensions/ms-vscode.cpptools-0.7.1/package.json: ENOENT: no such file or directory, open '/home/iga/.vscode/extensions/ms-vscode.cpptools-0.7.1/package.json'.
2. 

_Copied from original issue: Microsoft/vscode#9171_

**Comment by weinand** [comment]
@nate2009 in what situation does this occur? Please provide **steps** not just an error message.

**Comment by pieandcakes** [comment]
@nate2009 Can you also try and reinstall the extension?

**Comment by sridmad** [comment]
@nate2009. Please try installing the latest version of the extension. If you continue to see the issue please add a comment and we can reopen the issue.

**Comment by Com-Mean** [comment]
after upgrade this plugin，this issues come back again
无法读取文件 C:/Users/xxx/.vscode/extensions/ms-vscode.cpptools-0.8.1/package.json: ENOENT: no such file or directory, open 'C:\Users\xxx.vscode\extensions\ms-vscode.cpptools-0.8.1\package.json'。

**Comment by sean-mcmanus** [comment]
The new extension is 0.9.2, so it's expected that 0.8.1 wouldn't be found, but it shouldn't be looking it. Does this block you from using the extension?
