### ISSUE TITLE
Compiler exited with error. How do I diagnose?

### ISSUE THREAD

**Issue by bobbrow** [microsoft/vscode-cpptools#990]
From @semihalf-kardach-stanislaw:  (moved from #846)

I have a question related to this topic. I am having a similar issue when I'm working on my MIPS C project on an x86 host. I have all my include paths set and I don't get any errors reported in my C file in the problems window. However when I hover over a symbol I get:
![image](https://user-images.githubusercontent.com/10021343/29719406-320abb5c-89b6-11e7-988e-e38eaaa78e1d.png)

Is there any way to read the output of clang to figure out what is the compiler error produced?

**Comment by bobbrow** [comment]
A few questions for you:

Which OS are you using?  Is VS Code running on the x86 host?
Is this a .c file or a .h file? The most common reason for this error is when you open a header file and we can't find the matching source file. The simple solution to work around bugs in source file detection is to open a source file that references this header, and then open the header file.

**Comment by semihalf-kardach-stanislaw** [comment]
My bad, should have mentioned it in the first place. VS Code is running on Linux on a x86 host:
```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID:	LinuxMint
Description:	Linux Mint 18 Sarah
Release:	18
Codename:	sarah
$ uname -rvpi
4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64
```

This happens when I open a .c file.

It's not really that I would like to find the solution right away, rather I would like to know if it would be helpful to me if I look at the clang output that caused the "Compiler exited with error".

**Comment by bobbrow** [comment]
This leaves me a bit confused.  We only compile 64-bit binaries for linux.  I'm not sure how you were able to get this error message in the first place.  The extension shouldn't even be running!

**Comment by semihalf-kardach-stanislaw** [comment]
To be exact it's `amd64` or `x86_64` host (as shown in `uname` output) so it is a 64-bit linux system.
I'm not sure if I understood your question correctly.

**Comment by bobbrow** [comment]
Ok.  I'll need to add more logging to the extension then to help diagnose this.  Our IntelliSense engine is not running an actual instance of Clang.  It is just a front end that has a clang "mode".

**Comment by hensz** [comment]
Hi!
I also get this error message after reinstalling the OS. I'm running
SUSE Linux Enterprise Desktop 12 SP2
```
> uname -rvpi
4.4.74-92.35-default #1 SMP Mon Aug 7 18:24:48 UTC 2017 (c0fdc47) x86_64 x86_64
```

Any update on this so far? Any new version with extended logging available?
Thanks!
Torsten

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
