### ISSUE TITLE
can't generate any output. any solution?

### ISSUE THREAD

**Issue by luigivendetta** [microsoft/vscode-cpptools#991]
file: 'file:///c%3A/Users/lenovo/Documents/Basic.cpp'
severity: 'Info'
message: 'Include file not found in browse.path.'
at: '1,1'
source: ''
![cpp](https://user-images.githubusercontent.com/10692823/29723169-319355aa-89e1-11e7-94ec-b45b29419ef9.jpg)

**Comment by bobbrow** [comment]
Where is the iostream header located on your PC?  On Windows, the extension will look for those headers in your Visual Studio 2015 or 2017 installation folders.  If you have not installed either of those, then we don't know where else to look.

**Comment by michelleangela** [comment]
Closing this issue due to long inactivity. If you update to the latest version of the C/C++ extension and your issue still persists, please re-open the issue and reply with additional information that can help us investigate the issue.
