### ISSUE TITLE
This extension generates a lot of .pch files

### ISSUE THREAD

**Issue by YOYO-UIAT** [microsoft/vscode-cpptools#9915]
### Environment

- OS and version: Windows 10
- VS Code: 1.71.2
- C/C++ extension: 1.12.4

### Bug Summary and Steps to Reproduce

Bug Summary:

When I create a C++ file using VSCode, this extension generates some very big .pch files in `C:\Users\Alan\AppData\Local\Microsoft\vscode-cpptools\ipch`, they are all over 200MB. Can I stop it from generating these files?

### Other Extensions

Code Runner

### Additional Information

These files are all generated after 2022.9.24. Before 9.24, I didn't see such files.

**Comment by YOYO-UIAT** [comment]
It seems that when I type `g++ test3.cpp -o test3.exe` in CMD, it still produces .pch files in `C:\Users\Alan\AppData\Local\Microsoft\vscode-cpptools\ipch`. I use msys2 MinGW64 as my compiler, is this compiler modified by the C++ extension?

**Comment by YOYO-UIAT** [comment]
When I close the VSCode window, and edit the C++ file with another editor, and compile the file, it didn't produce the .pch file.

**Comment by michelleangela** [comment]
@YOYO-UIAT 
The files in the [ipch folder are pre-compiled headers ](https://code.visualstudio.com/docs/cpp/faq-cpp#_what-is-the-ipch-folder )that the IntelliSense engine creates and uses to improve processing performance. This feature can be disabled by setting [C_Cpp.intelliSenseCacheSize](https://code.visualstudio.com/docs/cpp/faq-cpp#_how-do-i-disable-the-intellisense-cache-ipch) to 0.
