### ISSUE TITLE
the C/C++ Extension took up 950M memory

### ISSUE THREAD

**Issue by linzhongzi** [microsoft/vscode-cpptools#9916]
### Environment

- OS and version: Windows_NT x64 10.0.19041
- VS Code: Code 1.71.2 (https://github.com/microsoft/vscode/commit/74b1f979648cc44d385a2286793c226e611f59e7, 2022-09-14T21:03:37.738Z)
- C/C++ extension:  ms-1.12.4
- OS and version of remote machine (if applicable):

### Bug Summary and Steps to Reproduce

Bug Summary:
Today(2022.9.22) updating make the memory occupied too much.
I only use vscode to run a "hello world" program. It took off 1.5G memory.
Then the C/C++ Extension took up 950M.
Then if I use the option: "console": "externalTerminal".
It wil increase the memory all the time even if I had close the shell windows.
I think the reason is coming from the "cpptools-extension-pack".
It is out of my computer's performance.

Steps to reproduce:
1. In this environment...
2. With this config...
3. Do '...'
4. See error...

### Other Extensions

<html>
<body>
<summary style="box-sizing: border-box; display: list-item; cursor: pointer;"><br class="Apple-interchange-newline">Extensions (6)</summary><slot id="details-content" style="color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Extension | Author (truncated) | Version
-- | -- | --
clang-format | mjo | 1.10.0
vscode-language-pack-zh-hans | MS- | 1.71.9140930
cpptools | ms- | 1.12.4
cpptools-extension-pack | ms- | 1.3.0
notepadplusplus-keybindings | ms- | 1.0.7
vetur | oct | 0.36.0

<p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px;">(1 theme extensions excluded)</p></slot>
</body>
</html>

<html>
<body>
<summary style="box-sizing: border-box; display: list-item; cursor: pointer;"><br class="Apple-interchange-newline">System Info</summary><slot id="details-content" style="color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Item | Value
-- | --
CPUs | Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)
GPU Status | 2d_canvas: enabledcanvas_oop_rasterization: disabled_offdirect_rendering_display_compositor: disabled_off_okgpu_compositing: enabledmultiple_raster_threads: enabled_onopengl: enabled_onrasterization: enabledraw_draw: disabled_off_okskia_renderer: enabled_onvideo_decode: enabledvideo_encode: enabledvulkan: disabled_offwebgl: enabledwebgl2: enabledwebgpu: disabled_off
Load (avg) | undefined
Memory (System) | 7.92GB (3.22GB free)
Process Argv | --user-data-dir D:\Program Files\.vscode --extensions-dir D:\Program Files\.vscode\extensions --crash-reporter-id 8f616df8-be42-4758-8472-2f22c6283036
Screen Reader | no
VM | 0%

</slot>
</body>
</html>

**Comment by sean-mcmanus** [comment]
Can you open 1 C/C++ file, and then run the C/C++: Log Diagnostics command from the View->Command Palette and look for what "Total Memory Usage:" shows in the logging?

**Comment by SapitoSucio** [comment]
I second this, I use VSCode in my RPi4 (4gb) and the extension can take up to 1gb of ram, the thing is, I have disabled it several times already because it messes up with my RPi (which doesnt happen with the extension uninstalled/OFF), sometimes I have to end up rebooting the unit.

I tried running the  C/C++: Log Diagnostics command but it doesn't appear on my options

**Comment by AaboutL** [comment]
> @SapitoSucio Yeah, 4 GB might be too low memory (Raspberry Pi's OS doesn't handle low memory conditions well). Certain TUs might cause cpptools-srv to use a lot of memory. If you don't see Log Diagnostics in the command palette, then you may not have the C/C++ extension installed/enabled.

You guys never really solved the problem. The vscode-cpptools create three or more cpptools-srv processes. Each of them takes up almost 900MB memory.
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/27000386/198860893-920fa201-f8a1-4a22-b3b9-9df39c85d145.png">

**Comment by bobbrow** [comment]
@AaboutL, @SapitoSucio, 
Have you tried using the `C_Cpp.intelliSense.maxCachedProcesses` and `C_Cpp.intelliSense.maxMemory` settings to limit the total number of processes and memory that the extension uses?  If the defaults don't work for your situation, you should be able to tweak the values and find a configuration that works better for you.

**Comment by m-radfar** [comment]
I had same issue and seems it is over know 
try like this: (attached image)
![CCpp vscode IntelliS](https://user-images.githubusercontent.com/19426236/213710105-76f4c587-db0d-4949-b2d6-8df2c7393b9e.png)

**Comment by m-radfar** [comment]
I had the same problem and it seems to be over now
try like this:
![CCpp vscode IntelliS](https://user-images.githubusercontent.com/19426236/213711458-cdeffac9-458d-418c-a950-6af39b81e0ae.png)
