### ISSUE TITLE
This is already being tracked by https://github.com/microsoft/vscode-cpptools/issues/6290 .

### ISSUE THREAD

**Issue by Mirandatz** [microsoft/vscode-cpptools#9920]
This is already being tracked by https://github.com/microsoft/vscode-cpptools/issues/6290 .

_Originally posted by @sean-mcmanus in https://github.com/microsoft/vscode-cpptools/issues/6616#issuecomment-739093148_
      
The link is broken :(

**Comment by sean-mcmanus** [comment]
I've updated that comment. It's https://github.com/microsoft/vscode-cpptools/issues/6302 .
