### ISSUE TITLE
Change the language to English.

### ISSUE THREAD

**Issue by Jason7158** [microsoft/vscode-cpptools#9929]
### Feature Request

![image](https://user-images.githubusercontent.com/26430685/192914313-2fecc8a4-bf21-4b5c-bb39-4cfacc96ba10.png)

![image](https://user-images.githubusercontent.com/26430685/192914378-14558a8f-b91f-4a38-986b-66e0c57615c4.png)

**Comment by Colengms** [comment]
Hi @Jason7158 .  The C/C++ Extension uses libraries provided by VS Code for selecting localized strings.  It does not directly have a concept of what the current language is set to.  Rather, those libraries  ([`vscode-nls`](https://github.com/microsoft/vscode-nls) and [`vscode-nls-dev`](https://github.com/microsoft/vscode-nls-dev)) select the appropriate strings for us.  There are some known issues with this that have come up before, such as: https://github.com/microsoft/vscode/issues/82791

The issue you are seeing would seem to be an issue in VS Code itself.  I'd suggest opening an issue in that repo, here: https://github.com/microsoft/vscode/issues

Closing this issue as external.
