### ISSUE TITLE
compile_commands.json + cross compilation - some headers not found

### ISSUE THREAD

**Issue by ineffective** [microsoft/vscode-cpptools#9931]
### Environment

- OS and Version: **Windows 10 x64**
- VS Code Version:
**Version: 1.71.2 (user setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z (2 wks ago)
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19043
Sandboxed: No**

- C/C++ Extension Version: **1.12.4**
- Other extensions you installed (and if the issue persists after disabling them):
  **Remote system (below) has only the following Microsoft's extensions installed: ".Net Install Tool for Extension Authors", "C/C++" (this one), "C/C++ Extension Pack" and "CMake Tools". I believe I can disable only ".Net Install Tool...", but disabling it does not change anything.** 
- If using SSH remote, specify OS of remote machine:  **Debian Linux 9.2.0**
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).
**Single, small project ~10 files, uses cmake (creates compile_commands.json and points c_cpp_properties.json to it) and custom toolchain file. Some headers (specifically boost/asio/io_context.hpp  in example below) are not recognized from time to time.**

### Bug Summary and Steps to Reproduce

Bug Summary:

Intellisense doesn't seem to see `#include <boost/asio/io_context.hpp>`, even though for other files it has no problems with finding files even deeper in the hierarchy. Note, that this line is in a header file that is NOT included in any file in the project, for now let's call it `issue.hpp`. This is a library that has some `.cpp` files and many `.hpp` files which are not included by any of `.cpp` files, because they are meant for inclusion by library consumers.

The problem can stem from the following fragment in the logs:

```
cpptools/getCodeActions: /opt/ZS/deps/include/boost/asio/io_context.hpp (id: 1268)
cpptools/queryTranslationUnitSource: /opt/ZS/deps/include/boost/asio/io_context.hpp (id: 1269)
textDocument/didOpen: /opt/ZS/deps/include/boost/asio/io_context.hpp
Attempting to get defaults from compiler found on the machine: '/usr/bin/gcc'
Checking for syntax errors: /opt/ZS/deps/include/boost/asio/io_context.hpp
Queueing IntelliSense update for files in translation unit of: /home/jd/repos/pac/tools-common/src/main.cpp
cpptools/textEditorSelectionChange
cpptools/getDocumentSymbols: /opt/ZS/deps/include/boost/asio/io_context.hpp (id: 1270)
cpptools/getDocumentSymbols
cpptools/activeDocumentChange: /opt/ZS/deps/include/boost/asio/io_context.hpp
Attempting to get defaults from compiler found on the machine: '/usr/bin/gcc'
cpptools/getSemanticTokens: /opt/ZS/deps/include/boost/asio/io_context.hpp (id: 1271)
cpptools/getInlayHints: /opt/ZS/deps/include/boost/asio/io_context.hpp (id: 1272)
cpptools/getFoldingRanges: /opt/ZS/deps/include/boost/asio/io_context.hpp (id: 1273)
textDocument/didClose: /opt/ZS/deps/include/boost/asio/io_context.hpp
```

As you can ses there is this part: `Attempting to get defaults from compiler found on the machine: '/usr/bin/gcc'`. This is clearly wrong, as I am using custom gcc/g++ 9.2.0. It is declared in the toolchain file. My `c_cpp_properties.json` is as simple as possible:

```json
{
    "configurations": [
        {
            "name": "Linux",
            "cStandard": "c11",
            "cppStandard": "gnu++17",
            "intelliSenseMode": "linux-gcc-x64",
            "compileCommands": "${workspaceFolder}/.builddir-arm/compile_commands.json"
        }
    ],
    "version": 4
}
```

I tried adding to this file the following:

```json
"configurationProvider": "ms-vscode.cmake-tools",
```
but it barely changed anything.

Also if I add this `issue.hpp` file to any of .cpp files in the library, this very problem goes away, but now IntelliSense says that it can't find `<sys/select.h>` and `<sys/cdefs.h>`. They are in `/usr/include/x86_64-linux-gnu/sys/select.h` and `/usr/include/x86_64-linux-gnu/sys/cdefs.h` (but also other paths, see below) respectively. Compiler should know these paths, as they are reported as system directories, as per `echo | x86_64-linux-gnu-g++-9.2.0 -E -Wp,-v -`:

```
ignoring nonexistent directory "/usr/local/include/x86_64-linux-gnu"
ignoring nonexistent directory "/opt/ZS/deps/lib/gcc/x86_64-linux-gnu/9.2.0/../../../../x86_64-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/ZS/deps/lib/gcc/x86_64-linux-gnu/9.2.0/include
 /usr/local/include
 /opt/ZS/deps/lib/gcc/x86_64-linux-gnu/9.2.0/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.
# 1 "<stdin>"
# 1 "<built-in>"
# 1 "<command-line>"
# 31 "<command-line>"
# 1 "/usr/include/stdc-predef.h" 1 3 4
# 32 "<command-line>" 2
# 1 "<stdin>"

```

I am completely dumbfound as some .cpp files use `<sys/types.h>` and there are no problems with finding it whatsoever, even though it is present in several directories.

As a side note, I can't for the life of me figure out how IntelliSense discovers paths it considers when searching for files. On one hand it shouldn't know about path where `cdefs.h`, `select.h` or `types.h` is, but on other hand it suggests that I add one of `/usr/include/x86_64-linux-gnu`, `/usr/include/bsd` or `/usr/include/arm-linux-gnueabihf` to `includePath` so that <sys/select.h> is found. Again "of course" it could be a problem with this file existing in multiple directories, but simple compiler query would quickly solve all problems. In addition even there there should be no problems, since file `<sys/types.h>` exists in multiple directories and is easily found (also, see below).

One thing to note: if `configurationProviders` is set in `c_cpp_properties.json` file, toolchain for `arm-linux-gnueabihf` works without issues, not a single error is shown. Two files are identical except that `x86_64-linux-gnu` part is changed to `arm-linux-gnueabihf`.

Also note, that output from "C/C++" output window shows:

```
  Folder: /opt/ZS/deps/lib/gcc/x86_64-linux-gnu/9.2.0/include/ will be indexed
  Folder: /usr/local/include/ will be indexed
  Folder: /opt/ZS/deps/lib/gcc/x86_64-linux-gnu/9.2.0/include-fixed/ will be indexed
  Folder: /usr/include/ will be indexed
  Folder: /home/jd/repos/pac/tools-common/inc/ will be indexed
  Folder: /opt/ZS/deps/include/ will be indexed
  Folder: /home/jd/repos/pac/tools-common/config/inc/ will be indexed
  Folder: /home/jd/repos/pac/tools-common/logger/inc/ will be indexed
  Folder: /home/jd/repos/pac/tools-common/src/ will be indexed
  Folder: /home/jd/repos/pac/tools-common/config/src/ will be indexed
  Folder: /home/jd/repos/pac/tools-common/logger/src/ will be indexed
```

This is clearly lacking `/usr/include/x86_64-linux-gnu/` directory, but at the same time includes (no pun intended) ALL other directories reported by aforementioned compiler command showing include paths, EXCEPT for this one. This makes me think that even though I remember reading that some include paths are not searched recursively, these clearly are, especially since most probably shortest common prefix is used as a path for paths that share it.

In the end it seems that my problems are caused by two facts:
1. Header file not included in any .cpp files has squiggles because it is assumed that it will be, without it it is not clear what settings should be used and default /usr/bin/gcc is used, which is clearly pointless in my case (and probably very useful in other cases)
2. System files that can be found in multiple directories (e.g. /usr/include/arm-linux-gnueabihf and /usr/include/x86_64-linux-gnu) are treated equally, even though querying the compiler would reveal which one is correct, but as I wrote earlier most probably since /usr/include is a prefix of /usr/include/x86_64-linux-gnu the latter is dropped and the former is used, which is clearly not a great solution in this case - but since it works this way it is most probably required on some systems in some configurations. Maybe even in 90% of other cases except for mine. 

Steps to reproduce:
Can't really be reproduced without full setup I can't create another machine to create smallest possible example.

### Expected behavior

I expect that there would be no problems with at least system includes, since rest of the problems most probably stems from the fact that I expect everything to heavily rely on CMake Tools. But system includes can be found by querying the compiler directly, and I assume it is known to the vscode-cpptools extension if "configurationProvider" is included.

### Code sample and Logs

```shell
Everything was provided earlier I believe.
```

**Comment by ineffective** [comment]
Note, that of course I could add path `/usr/include/x86_64-linux-gcc`, but when I want to compile using different toolchain I simply change active kit. And this is not the only project where I have this problem, there are ~20 more, so I want to keep things as simple as possible, especially since it is obvious that it is possible if not for aforementioned issue with path being removed.

**Comment by sean-mcmanus** [comment]
Setting the configurationProvider is preferable over compileCommands. Can you run the C/C++: Log Diagnostics command from the command palette? That should show which configuration info we're getting from CMake Tools or compile commands or if they being treated as stand alone headers.

It sounds like you're hitting an issue with standalone headers, can you set the compilerPath and compilerArgs settings? Otherwise, the correct values won't be provided by the configurationProvider or compileCommands since the headers aren't built.

**Comment by ineffective** [comment]
Sean, thanks for your reply. I was under impression that in fact `compile_commands.json` is better than `configurationProvider`. After leaving only `configurationProvider` and adding all header files to single dummy .cpp file I have zero (yay, zero!) error squiggles. Never the less I have attached output of the command that you requested - maybe you will find there something interesting and someone else will some day find it useful.

Is there any documentation how this file should be read? I see for example that first is `Current Configuration`, but it includes `"compilerPath": "/usr/bin/gcc"`. This sounds bad, but it looks like it is an unused default - right after that (I have only `main.cpp` file opened) there are saner values in `Translation Unit Mappings` - I see correct compiler being used and also `Translation Units Configurations` contains `/usr/include/x86_64-linux-gnu` directory which was previously missing. Is `Current Configuration` (one with `/usr/bin/gcc`) used only for standalone files that are not configured by CMake? This would mean that I can work around it by providing compiler and args, but at the same time it seems far better to simply create dummy file, as it will be always picked, no matter what toolchain file will be used. Is that correct?

[vscode-c-cpp-log-diagnostics-2022-09-29.txt](https://github.com/microsoft/vscode-cpptools/files/9678515/vscode-c-cpp-log-diagnostics-2022-09-29.txt)

**Comment by sean-mcmanus** [comment]
I don't think we have documentation on the C/C++: Logging.

Current Configuration are the settings from c_cpp_properties.json or settings, but the settings from Custom configurations will usually take precedence. The Translation Unit Configurations section shows what is being used for the particular TU.

So yeah, /usr/bin/gcc is not used. It's possible it could be used if you opened a header that wasn't included by any source file. If you run Log Diagnostics again after opening the header you can check. Creating a dummy source file that includes the header should work too as long as it's picked up by CMake.

**Comment by ineffective** [comment]
Thanks for an answer. In the end **THE** configuration that works best for me is, surprisingly:

```json
{
    "configurations": [
        {
            "name": "Linux",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}
```
It dictates nothing and achieves everything - no problems with any `#include` directives for about 3 hours of work.
