### ISSUE TITLE
C_Cpp.vcFormat.space.withinInitializerListBraces setting ignored?

### ISSUE THREAD

**Issue by akubly** [microsoft/vscode-cpptools#9932]
Type: <b>Bug</b>

Though I have unchecked the C_Cpp.vcFormat.space.withinInitializerListBraces setting, I still get the following automatic spacing in my .cpp files:

int foo{ 0 };

I can't seem to find any other setting that appears to be relevant.

Extension version: 1.13.1
VS Code version: Code - Insiders 1.72.0-insider (1a55beb2aaee64eb8d0cbe5b61b10088bbc6c895, 2022-09-13T05:18:15.280Z)
OS version: Windows_NT x64 10.0.25213
Modes:
Sandboxed: Yes

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.78GB (29.45GB free)|
|Process Argv|--no-sandbox d:\\git\\cu\\src --crash-reporter-id 8df2cbf3-5adc-46a7-8b08-99645e4fc359|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv695:30137379
vsins829:30139715
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492:30256197
vslsvsres303:30308271
pythonvspyl392:30422396
pythontb:30258533
pythonptprofiler:30281269
vsdfh931:30280409
vshan820:30294714
pythondataviewer:30285072
vscod805cf:30301675
bridge0708:30335490
bridge0723:30353136
cmake_vspar411cf:30557515
vsaa593:30376534
pythonvs932:30404738
cppdebug:30492333
vsclangdf:30492506
c4g48928:30535728
dsvsc012cf:30540253
pylantcb52:30568093
vscccc:30564267
pyindex848cf:30577859

```

</details>

**Comment by sean-mcmanus** [comment]
The setting works for me with C_Cpp.formatting set to "vcFormat" -- I'm guessing you have that set to something else. Let me know if you're still having an issue with this.
