### ISSUE TITLE
Move to vscode l10n

### ISSUE THREAD

**Issue by ChaseKnowlden** [microsoft/vscode-cpptools#9947]
### Feature Request

The gulpfile still uses vscode-nls. But see if they can change it to use the new npm package.

**Comment by sean-mcmanus** [comment]
Could you explain what this means?

**Comment by Colengms** [comment]
This appears to be a new library in development that might replace `vscode-nls`/`vscode-nls-dev`.  https://github.com/microsoft/vscode-l10n

However, I'd not heard anything about it yet.  The repo README indicates: `This repo is still under early development. API may be changed`

Given the complexity of our localization pipeline, I'm not eager to make changes to it unless/until necessary.

**Comment by Colengms** [comment]
I'm going to close this for now.  We'll add a new issue to track this, once we have official guidance from the VS Code team.
