### ISSUE TITLE
include errors detected Mac OS X / endian.h

### ISSUE THREAD

**Issue by wAuner** [microsoft/vscode-cpptools#995]
Mac OS X 10.12.6
VS Code 1.15.1
C/C++ extension 0.12.3

I updated the extension today to 0.12.3 and now I get "#include errors detected". It also says "cannot open source file endian.h (dependency of "iostream").
Never had any issues before. How can I fix this?

**Comment by bobbrow** [comment]
Just add `/usr/include/machine` to your `"includePath"` in **c_cpp_properties.json**.  We now add this path by default in 0.12.3 if the c_cpp_properties.json file has not been created yet.

**Comment by wAuner** [comment]
@bobbrow thanks for your answer, but this doesn't solve the problem, I still get the error message. I don't have the directory /usr/include.
My c_cpp_properties.json now contains the following:

```{
    "configurations": [
        {
            "name": "Mac",
            "includePath": [
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                "/usr/local/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include",
                "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                "/usr/include",
                "/usr/include/machine",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1",
                    "/usr/local/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/8.1.0/include",
                    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include",
                    "/usr/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        },
        ...
    ],
    "version": 2
}```

**Comment by bobbrow** [comment]
You're on a Mac and you don't have a `/usr/include` folder?  Did you delete it?

**Comment by wAuner** [comment]
That's correct. I didn't delete it neither did I do anything crazy. Before the update I hadn't had any problems with VS Code or Xcode. I still can compile everything without problems, I just get this annoying error message all the time.

**Comment by bobbrow** [comment]
what does your compiler print out when you do `<compiler> -v -E -x c++ - < /dev/null`?

**Comment by wAuner** [comment]
Thanks for your help. This is the ouput:

```
>>g++ -v -E -x c++ - < /dev/null
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang" -cc1 -triple x86_64-apple-macosx10.12.0 -Wdeprecated-objc-isa-usage -Werror=deprecated-objc-isa-usage -E -disable-free -disable-llvm-verifier -discard-value-names -main-file-name - -mrelocation-model pic -pic-level 2 -mthread-model posix -mdisable-fp-elim -masm-verbose -munwind-tables -target-cpu penryn -target-linker-version 278.4 -v -dwarf-column-info -debugger-tuning=lldb -resource-dir /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.1.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -stdlib=libc++ -fdeprecated-macro -fdebug-compilation-dir /Users/air -ferror-limit 19 -fmessage-length 80 -stack-protector 1 -fblocks -fobjc-runtime=macosx-10.12.0 -fencode-extended-block-signature -fcxx-exceptions -fexceptions -fmax-type-align=16 -fdiagnostics-show-option -fcolor-diagnostics -o - -x c++ -
clang -cc1 version 8.1.0 (clang-802.0.42) default target x86_64-apple-darwin16.7.0
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include/c++/v1"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/local/include"
ignoring nonexistent directory "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/Library/Frameworks"
#include "..." search starts here:
#include <...> search starts here:
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.1.0/include
 /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/usr/include
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks (framework directory)
End of search list.
# 1 "<stdin>"
# 1 "<built-in>" 1
# 1 "<built-in>" 3
# 340 "<built-in>" 3
# 1 "<command line>" 1
# 1 "<built-in>" 2
# 1 "<stdin>" 2
```

**Comment by wAuner** [comment]
Btw this is my /usr dir:
```
>>ls /usr
bin        lib        libexec    local      sbin       share      standalone

**Comment by bobbrow** [comment]
Thanks.  Now that I think about it, I don't think `/usr/include` gets added on Mac unless you run `xcode-select --install`

Try doing `find /Applications/Xcode.app -name "endian.h"`.  You should find at least one candidate path that matches the include path you shared above.

**Comment by bobbrow** [comment]
(and BTW, I would recommend updating your include path to match the output of your compiler)

**Comment by wAuner** [comment]
Thanks a lot, I was finally able to get rid of this annoying error message by adding `/Applications/Xcode.app//Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/i386/`as include path to `c_cpp_properties.json`.
Would you be so kind to help me understand what and why this happened? I'm new to c++. 
I was surprised to find that the `c_cpp_properties.json` was created in my project folder and not somewhere in `~/.vscode` or anything like that. On my linux machine I couldn't find that config at all.
In any case, thanks for your patience.

**Comment by bobbrow** [comment]
We haven't gotten to the root cause for the "endian.h" missing error yet. The folder you need to add to get it isn't reported by the compiler.

Where was c_cpp_properties.json created?  We always create it in `${workspaceRoot}/.vscode/c_cpp_properties.json`.  We don't create the file until you use the "C/Cpp: Edit Configurations..." command.  When the file is not present we use a set of default values based on your operating system.

**Comment by bobbrow** [comment]
The root cause for this is being tracked by new issue: #1005.  Add `"__LITTLE_ENDIAN__"` to your `"defines"` array in c_cpp_properties.json and you won't need to add a path to "endian.h".
