### ISSUE TITLE
IntelliSense making nonsensical errors

### ISSUE THREAD

**Issue by HasanMdArik** [microsoft/vscode-cpptools#9951]
### Environment

- OS and Version: Ubuntu 22.04
- VS Code Version: 1.71.2
- C/C++ Extension Version: v1.13.1
- Other extensions you installed (and if the issue persists after disabling them):  not necessary
- If using SSH remote, specify OS of remote machine:  not using ssh

### Bug Summary and Steps to Reproduce

Bug Summary:
So I was developing an HTTP API with C++ and everything was fine until I came back to the project yesterday. The IntelliSense was showing unnecessary errors. I tried with an example code from the docs assuming I had done any mistake but IntelliSense is making unnecessary error claims. See the picture below...
![image](https://user-images.githubusercontent.com/67511967/193714267-d3b889e5-cd81-4f2f-9ad0-99181f3cebb4.png)

Though it compiles fine and runs. I tried re-installing the extension and then the whole code editor but nothing was fixed. I tested the same project on JetBrains's CLion and everything works there(photo given below)...
![image](https://user-images.githubusercontent.com/67511967/193714517-d705b8c1-e486-4ea5-8321-08e4ccee15c5.png)

Then I went inside the problematic header file(HttpResponse.h can be found in https://github.com/an-tao/drogon) and look what I got...
![image](https://user-images.githubusercontent.com/67511967/193715114-40ab5580-f6ee-443e-a312-aae1a777d701.png)
![image](https://user-images.githubusercontent.com/67511967/193715167-fe30a436-90d7-4386-af2f-4db04300b89d.png)
(though they were inside the class declaration)

Again they were alright in the CLion IDE.

I think it is something related to the 'jsoncpp' library, it's 'Json' namespace is taken invalid by the editor though it has found definitions for it...
![image](https://user-images.githubusercontent.com/67511967/193720330-f0ff0d2d-ff10-41df-8829-270f8485ea73.png)

Please help me out with this...

Steps to reproduce:
It happened to me for the first time and I don't know how and why...

### Expected behavior

There should have been no errors like screenshots from the CLion page

### Code sample and Logs

```shell
The demonstration was taken from https://drogon.docsforge.com/master/quick-start/ & https://drogon.docsforge.com/master/controller-introduction/controller-httpsimplecontroller/
```

### Screenshots

Already given above

**Comment by MohammadArik** [comment]
I traced the thing and it's actually a problem with the JSON library the framework used. Fixed by
`sudo ln -s /usr/include/jsoncpp/json/ /usr/include/json`

**Comment by leo-frank** [comment]
I met the same problem but in a different library - Eigen.  Eigen installs it's include_files into /usr/local/include/eigen3/Eigen.
When I  open a single file (not a directory)  who has one line "#include<Eigen/Core>", this line squiggle unexpectedly.
Since it's a single file opened by VScode, so I can't configure c_cpp_properties.json to let IntelliSense sense the include_dir /usr/local/include/eigen3/Eigen. 
The way I solved this problem is as same as you, 
`
sudo ln -s /usr/local/include/eigen3/Eigen /usr/local/include/Eigen
`
It makes sense, but i have to say it's not elegant as expected.
