### ISSUE TITLE
Visual Studio's GDB client does not attach to a J-Link GDB Server connected to an ARM7 target.

### ISSUE THREAD

**Issue by gtrevi** [microsoft/vscode-cpptools#9956]
### Environment

- OS and version: Windows 11 21H2
- VS Code: on latest 1.71.2, but same issues on all previous versions
- C/C++ extension: latest 1.12.4
- OS and version of remote machine (if applicable): N.A. - target is a bare metal NXP LPC2294 ARM7 with JTAG interface.
- GDB / LLDB version: GNU Arm Embedded Toolchain v10 2021.10, J-Link GDB Server v6.12f
- Hardware setup: Windows PC (details above) attached to an ARM7 target device through a [SEGGER J-Link JTAG USB interface](https://www.segger.com/products/debug-probes/j-link/models/j-link-base/). Firmware code is bare metal C.

### Bug Summary and Steps to Reproduce

I'm attempting to switch my embedded projects from [emIDE](https://www.emide.org/) to Visual Studio Code (VSC).

When attempting to start a debug session on VSC, the VSC GDB client fails attaching to the J-Link GDB Server, whilst in the *same exact setup*, emIDE always successfully connects and starts the debug session (btw, no issue even using [SEGGER's Embedded Studio](https://www.segger.com/products/development-tools/embedded-studio/)).

emIDE uses the following command line to successfully connect, which I attempted to replicate in the attached `launch.json`:

```cmd
C:\Program Files (x86)\SEGGER\JLink\JLinkGDBServer.exe -device LPC2294 -endian little -if JTAG -speed Adaptive -port 2331 -swoport 2332 -telnetport 2333 -singlerun
```

Here below is a side-by-side comparison of the J-Link GDB Server window, when launching a debug session on both emIDE (left window) and VSC (right window). As observable, the logs are identical, up to the point in which VSC's GDB client is supposed to connect (but times-out):

![image](https://user-images.githubusercontent.com/22826130/193983723-69f3ec49-3e60-435e-867c-1775915c8e61.png)

After the 5-second timeout (configured in `launch.json`), VSC quits the debug session with the following error:

![image](https://user-images.githubusercontent.com/22826130/193991671-6c0729ae-cbcc-4e79-b6f2-31ab8129e6a2.png)

Any suggestions on why VSC is not connecting to the J-Link GDB Server?

### Debugger Configurations

```shell
Launch configuration:
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug J-Link",
            "type": "cppdbg",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "program": "X:\\work\\projects\\gt_automation\\Hardware\\GT_MB01\\Firmware\\gta_server\\bin\\Debug\\GTA_Server.elf",
            "stopAtEntry": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\10 2021.10\\bin\\arm-none-eabi-gdb.exe",
            "debugServerPath": "C:/Program Files (x86)/SEGGER/JLink_V612f/JLinkGDBServer.exe",
            "debugServerArgs": "-select USB -device LPC2294 -endian little -if JTAG -speed Adaptive -port 2331 -swoport 2332 -telnetport 2333 -singlerun",
            "serverStarted": "Connected\\ to\\ target",
            "serverLaunchTimeout": 5000,
            "filterStderr": false,
            "filterStdout": true,
            "setupCommands": [
                {"text": "target remote localhost:2333"},
                {"text": "monitor flash breakpoints = 1"},
                {"text": "monitor flash download = 1"},
                {"text": "monitor reset"},
                {"text": "load X:/work/projects/gt_automation/Hardware/GT_MB01/Firmware/gta_server/bin/Debug/GTA_Server.elf"},
                {"text": "monitor reset"},
                {"text": "continue"}
              ],

              "logging": {
                "exceptions": true,
                "moduleLoad": true,
                "programOutput": true,
                "engineLogging": true,
                "trace": true,
                "traceResponse": true
            },            
        }
    ]
}
```

### Debugger Logs

```shell
Nothing relevant (\Code\logs\20221004T180329\exthost3\output_logging_20221004T214831\14-remote-attach.log is empty)
```

**Comment by WardenGnaw** [comment]
@xisui-MSFT Would you know why the JLink setup is not working?

**Comment by xisui-MSFT** [comment]
@gtrevi The log shows that GDB listens to 2331, but you are trying to connect to 2333. Is this intended?

@WardenGnaw I never used JLink before.

**Comment by gtrevi** [comment]
@xisui-MSFT  thanks for following up.
Actually, the command line specifies port 2331, i.e. mimicking *exactly* what emIDE does (port 2333 is specified as the additional telnet port):
```
debugServerArgs": "-select USB -device LPC2294 -endian little -if JTAG -speed Adaptive -port 2331 -swoport 2332 -telnetport 2333 -singlerun",
```

If you are instead referring to the "setupCommands" group, those seem not to be even considered (they should be executed after the connection has been established, i.e. to upload the binary to the device, reset, break, etc.); in fact, changing `target remote localhost` to 2331 is ineffective.

If you have in mind any configuration changes you'd like me to test, please let me know.
Thanks!

**Comment by xisui-MSFT** [comment]
Ah I see what you mean. So the debug server is able to connect to the device, but MIEngine thinks it's not connected. Not sure if "connected to target" is printed to stdout and can be picked up by MIEngine? @WardenGnaw Sounds like an MIEngine issue.

Just wondering, can you try if `deploySteps` help? Syntax would be similar to (typing using phone so may not be accurate):
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug J-Link",
            "type": "cppdbg",
            "request": "launch",
            "cwd": "${workspaceRoot}",
            "program": "X:\\work\\projects\\gt_automation\\Hardware\\GT_MB01\\Firmware\\gta_server\\bin\\Debug\\GTA_Server.elf",
            "stopAtEntry": true,
            "MIMode": "gdb",
            "miDebuggerPath": "C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\10 2021.10\\bin\\arm-none-eabi-gdb.exe",
            "miDebuggerServerAddress": "localhost:2331",
            "deploySteps": [
                {
                    "type": "shell",
                    "command": "C:\\Program Files (x86)\\SEGGER\\JLink\\JLinkGDBServer.exe -device LPC2294 -endian little -if JTAG -speed Adaptive -port 2331 -swoport 2332 -telnetport 2333 -singlerun",
                   "continueOn": "Connected\\ to\\ target"
                }
            ],
            "setupCommands": [
                {"text": "monitor flash breakpoints = 1"},
                {"text": "monitor flash download = 1"},
                {"text": "monitor reset"},
                {"text": "load X:/work/projects/gt_automation/Hardware/GT_MB01/Firmware/gta_server/bin/Debug/GTA_Server.elf"},
                {"text": "monitor reset"},
                {"text": "continue"}
              ],

              "logging": {
                "exceptions": true,
                "moduleLoad": true,
                "programOutput": true,
                "engineLogging": true,
                "trace": true,
                "traceResponse": true
            },            
        }
    ]
}

```

**Comment by benmcmorran** [comment]
If it helps, you can also try looking at this [J-Link launch configuration](https://github.com/azure-rtos/getting-started/blob/7ffb25fb3afeec6db7af49aae1c3bc6e726973f1/NXP/MIMXRT1060-EVK/.vscode/launch.json#L25-L52) from the Azure RTOS Getting Started Guide. Additionally, you might want to try using [`postRemoteConnectCommands`](https://github.com/microsoft/MIEngine/blob/b20b747a715a6b07aafc3a2429609d5e7449b3f1/src/MIDebugPackage/OpenFolderSchema.json#L127-L130) instead of `setupCommands` to run raw GDB commands _after_ connecting to JLinkGDBServer.

FYI @microsoft/embedded-dev

**Comment by gtrevi** [comment]
@xisui-MSFT thanks for the suggestion. With the configuration  you posted, results are the same, except for the fact that the session stays stuck until I manually close the J-Link GDB server, on "`Running deploy steps`".

![image](https://user-images.githubusercontent.com/22826130/195501021-50250542-ff34-493c-bff5-9b2d8a1a0558.png)

I enabled Information logging on the c/c++ extension, and here's the output (not much I guess):

```
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
IntelliSense Engine = Default.
Enhanced Colorization is enabled.
Error squiggles are enabled if all header dependencies are resolved.
Autocomplete is enabled.
Launch configuration:
{
  "name": "Debug J-Link",
  "type": "cppdbg",
  "request": "launch",
  "cwd": "X:\\work\\projects\\gt_automation\\Hardware\\GT_MB01\\Firmware\\gta_server",
  "program": "X:\\work\\projects\\gt_automation\\Hardware\\GT_MB01\\Firmware\\gta_server\\bin\\Debug\\GTA_Server.elf",
  "stopAtEntry": true,
  "MIMode": "gdb",
  "miDebuggerPath": "C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\10 2021.10\\bin\\arm-none-eabi-gdb.exe",
  "miDebuggerServerAddress": "localhost:2331",
  "deploySteps": [
    {
      "type": "shell",
      "command": "\"C:/Program Files (x86)/SEGGER/JLink_V612f/JLinkGDBServer.exe\" -device LPC2294 -endian little -if JTAG -speed Adaptive -port 2331 -swoport 2332 -telnetport 2333 -singlerun",
      "continueOn": "Connected to target"
    }
  ],
  "setupCommands": [
    {"text": "monitor flash breakpoints = 1"},
    {"text": "monitor flash download = 1"},
    {"text": "monitor reset"},
    {"text": "load X:/work/projects/gt_automation/Hardware/GT_MB01/Firmware/gta_server/bin/Debug/GTA_Server.elf"},
    {"text": "monitor reset"},
    {"text": "continue"}
  ],
  "logging": {
    "exceptions": true,
    "moduleLoad": true,
    "programOutput": true,
    "engineLogging": true,
    "trace": true,
    "traceResponse": true
  },
  "__configurationTarget": 6
}

----> Hangs here, until I close the GDB Server, and then:

$ "C:/Program Files (x86)/SEGGER/JLink_V612f/JLinkGDBServer.exe" -device LPC2294 -endian little -if JTAG -speed Adaptive -port 2331 -swoport 2332 -telnetport 2333 -singlerun 


Process executed successfully.
```


@benmcmorran thanks for pointing that out! It seems they are doing the same, except that they make use of an SVD file.
Using `postRemoteConnectCommands` instead of `setupCommands` isn't changing anything, but I guess this because the connection is still not yet established (and eventually getting to that next step to try).

**Comment by xisui-MSFT** [comment]
@gtrevi To me, looks like the issue is what I thought - nothing prints out to cmd, and yet both method in VS Code depend on this.

Did a quick search online, and in https://forum.segger.com/index.php/Thread/6323-SOLVED-J-Link-Results-Output/, I found:

>cmd /c JLink -device %s -CommanderScript "%s" | more
>The first %s is the target device number, the second is the complete filename of the .jlink CommanderScript file. This returns everything that you see on the screen to the standard output pin on the CMD vi.

Can you try this? Or do you know if there's any other way to print out everything in JLink to cmd?

**Comment by gtrevi** [comment]
@xisui-MSFT sorry but I'm unsure to have understood: the link you pointed out is using another tool, JLink.exe, within LabVIEW. Shouldn't the J-link GDB server's output come through the exposed ports?

As benmcmorran pointed out [here](https://github.com/azure-rtos/getting-started/blob/7ffb25fb3afeec6db7af49aae1c3bc6e726973f1/NXP/MIMXRT1060-EVK/.vscode/launch.json#L25-L52), for Azure RTOS a very similar approach is used to connect to the J-link GDB server (just using the CL instead of the GUI, but the result is the same).
This configuration should be pretty identical to the one used for Azure RTOS (in the link above), therefore, before anything happens, shouldn't the GDB client just connect to the jlink GDB server that is already up and listening on port 2331? 

```json
{
  "name": "Debug J-Link",
  "type": "cppdbg",
  "request": "launch",
  "cwd": "${workspaceFolder}",
  "program": "${workspaceFolder}/bin/Debug/GTA_Server.elf",
  "stopAtEntry": true,
  "MIMode": "gdb",
  "miDebuggerPath": "C:/Program Files (x86)/GNU Arm Embedded Toolchain/10 2021.10/bin/arm-none-eabi-gdb.exe",
  "miDebuggerServerAddress": "localhost:2331",
  "debugServerPath": "C:/Program Files (x86)/SEGGER/JLink_V612f/JLinkGDBServer.exe",
  "debugServerArgs": "-select USB -device LPC2294 -endian little -if JTAG -speed Adaptive -port 2331 -swoport 2332 -telnetport 2333 -singlerun",
  "serverStarted": "Connected to target",
  "serverLaunchTimeout": 5000,
  "filterStdout": true,
  "stopAtConnect": true,
  "logging": {
    "exceptions": true,
    "moduleLoad": true,
    "programOutput": true,
    "engineLogging": true,
    "trace": true,
    "traceResponse": true
  },
}
```

**Comment by benmcmorran** [comment]
If you run this command in a terminal, can you verify that the text "Connected to target" appears on a line from standard out of the `JLinkGDBServer.exe` process within 5 seconds? The error message you're getting looks like the C++ debugger never sees the magic string (`serverStarted`) from the gdbserver process.

```cmd
C:/Program Files (x86)/SEGGER/JLink_V612f/JLinkGDBServer.exe -select USB -device LPC2294 -endian little -if JTAG -speed Adaptive -port 2331 -swoport 2332 -telnetport 2333 -singlerun
```

**Comment by gtrevi** [comment]
@benmcmorran  thanks for clarifying. You're right, the UI server does not output on stdout, but the CLI version does, so I switched to `JLinkGDBServerCL`, which does indeed output to stdout. 
Unfortunately, the GDB connection still does not happen:

New config
```json
{
  "name": "Debug J-Link",
  "type": "cppdbg",
  "request": "launch",
  "cwd": "${workspaceFolder}",
  "program": "${workspaceFolder}/bin/Debug/GTA_Server.elf",
  "stopAtEntry": true,
  "MIMode": "gdb",
  "miDebuggerPath": "C:/Program Files (x86)/GNU Arm Embedded Toolchain/10 2021.10/bin/arm-none-eabi-gdb.exe",
  "miDebuggerServerAddress": "localhost:2331",
  "debugServerPath": "C:/Program Files (x86)/SEGGER/JLink_V612f/JLinkGDBServerCL.exe",
  "debugServerArgs": "-select USB -device LPC2294 -endian little -if JTAG -speed Adaptive -port 2331 -swoport 2332 -telnetport 2333 -singlerun",
  "serverStarted": "Waiting for GDB connection...",
  "serverLaunchTimeout": 5000,
  "filterStdout": true,
  "stopAtConnect": true,
  "logging": {
    "exceptions": true,
    "moduleLoad": true,
    "programOutput": true,
    "engineLogging": true,
    "trace": true,
    "traceResponse": true
  },
}
```

Command prompt test:

```cmd
PS C:\Program Files (x86)\SEGGER\JLink_V612f> .\JLinkGDBServerCL.exe -select USB -device LPC2294 -endian little -if JTAG -speed Adaptive -port 2331 -swoport 2332 -telnetport 2333 -singlerun
SEGGER J-Link GDB Server V6.12f Command Line Version

JLinkARM.dll V6.12f (DLL compiled Jan 13 2017 16:37:50)

-----GDB Server start settings-----
GDBInit file:                  none
GDB Server Listening port:     2331
SWO raw output listening port: 2332
Terminal I/O port:             2333
Accept remote connection:      localhost only
Generate logfile:              off
Verify download:               off
Init regs on start:            off
Silent mode:                   off
Single run mode:               on
Target connection timeout:     0 ms
------J-Link related settings------
J-Link Host interface:         USB
J-Link script:                 none
J-Link settings file:          none
------Target related settings------
Target device:                 LPC2294
Target interface:              JTAG
Target interface speed:        adaptive
Target endian:                 little

Connecting to J-Link...
J-Link is connected.
Firmware: J-Link ARM V8 compiled Nov 28 2014 13:44:46
Hardware: V8.00
S/N: ***********
Feature(s): RDI,FlashDL,FlashBP,JFlash,GDB
Checking target voltage...
Target voltage: 3.29 V
Listening on TCP/IP port 2331
Connecting to target...
J-Link found 1 JTAG device, Total IRLen = 4
JTAG ID: 0x4F1F0F0F (ARM7)
Connected to target
Waiting for GDB connection...

>>>Interrupting with ^C

Restoring target state and closing J-Link connection...
Shutting down...
PS C:\Program Files (x86)\SEGGER\JLink_V612f>
```

**Comment by xisui-MSFT** [comment]
@gtrevi Again just wondering - what if you use deploySteps with JLinkGDBServerCL?

**Comment by gtrevi** [comment]
@xisui-MSFT yes, to regards of the VSC gdb connectivity, I've always tried both in my tests above, with the same results.

The deploy steps, they shouldn't be relevant to establishing at a debug session, in fact I would not need them at all, if I don't need to redeploy the image.

What needs to happen before anything is that the GDB client connects to the GDB server.

That said, now that we understand that the best option for visual studio code is to use the command line GDB server (in order to get the std output), I would expect the extension to capture that output and react to the magic string that is indeed being sent.

Any idea why the extension isn't capturing any output, after it does launch the GDB CL server?

Thanks!

**Comment by gtrevi** [comment]
@xisui-MSFT good catch! By executing JLinkGDBServerCL in the deploySteps (and deleting the other approach) moved us forward, as the debugger seems to connect!

The only odd thing is that the debugger randomly stops within the source code, despite having breakpoints already set, or even setting them as new ones.

Here's the progressed configuration, within the extensions "Information"-level output, wher the debugger this time stopped on "configuration_loader_json.c" (also, notice the truncated "*SEGGER J-Link GDB Server V6.12f Comman*" towards the end):

```cmd
Launch configuration:
{
  "name": "Debug J-Link",
  "type": "cppdbg",
  "request": "launch",
  "cwd": "X:\\work\\projects\\gt_automation\\Hardware\\GT_MB01\\Firmware\\gta_server",
  "program": "X:\\work\\projects\\gt_automation\\Hardware\\GT_MB01\\Firmware\\gta_server/bin/Debug/GTA_Server.elf",
  "stopAtEntry": true,
  "MIMode": "gdb",
  "miDebuggerServerAddress": "localhost:2331",
  "miDebuggerPath": "C:/Program Files (x86)/GNU Arm Embedded Toolchain/10 2021.10/bin/arm-none-eabi-gdb.exe",
  "serverLaunchTimeout": 5000,
  "filterStderr": false,
  "filterStdout": true,
  "stopAtConnect": true,
  "deploySteps": [
    {
      "type": "shell",
      "command": "\"C:/Program Files (x86)/SEGGER/JLink_V612f/JLinkGDBServerCL.exe\" -device LPC2294 -endian little -if JTAG -speed Adaptive -port 2331 -swoport 2332 -telnetport 2333 -singlerun",
      "continueOn": "Waiting for GDB connection..."
    }
  ],
  "logging": {
    "exceptions": true,
    "moduleLoad": true,
    "programOutput": true,
    "engineLogging": true,
    "trace": true,
    "traceResponse": true
  },
  "__configurationTarget": 6
}
$ "C:/Program Files (x86)/SEGGER/JLink_V612f/JLinkGDBServerCL.exe" -device LPC2294 -endian little -if JTAG -speed Adaptive -port 2331 -swoport 2332 -telnetport 2333 -singlerun 
SEGGER J-Link GDB Server V6.12f Comman

Checking for syntax errors: X:\work\projects\gt_automation\Hardware\GT_MB01\Firmware\gta_server\src\configuration_loader_json.c
```

Any idea why the extension isn't responding to any existing or new breakpoints, once connected to the GDB server?

>Note: I can ensure the binary is built on the latest source code, so a symbol/source mismatch is not the case here. Moreover on this, if I close VSC and launch the debug session on emIDE with the same binary, all works without any recompiling or linking being triggered.

Thanks!

**Comment by xisui-MSFT** [comment]
@gtrevi
Message truncated - likely a bug. Need to move logging to [on('data')](https://github.com/microsoft/vscode-cpptools/blob/591242ab5f5c14c06328f10a48a11de1b2ae0943/Extension/src/common.ts#L759) otherwise message would be incomplete if `continueOn` is specified. Created bug #10063 

If debugger connects, there should be something printed out in `debug console`? Can you share the contents?

**Comment by gtrevi** [comment]
@xisui-MSFT thanks for filing the bug, let me know how I can eventually help on that.

When I launch the debug session, as mentioned, VSC stops highlighting a random line in the source code (typically in my scheduler) and 
halts (although, the step-by-step execution is not reliable).

I attached all the output I was able to capture, hope this rings a bell. Thanks!

[Debug Console.log](https://github.com/microsoft/vscode-cpptools/files/9866868/Debug.Console.log)

**Comment by xisui-MSFT** [comment]
@WardenGnaw Can you take a look at this engine log?

**Comment by WardenGnaw** [comment]
I'm seeing one stopped event via a breakpoint.
> --> E (stopped): {"type":"event","event":"stopped","body":{"reason":"breakpoint","threadId":57005,"allThreadsStopped":true,"source":{"name":"scheduler.c","path":"x:\\work\\projects\\gt_automation\\Hardware\\GT_MB01\\Firmware\\_rtos\\scheduler.c","sources":[],"checksums":[]},"line":125,"column":1},"seq":420}

It looks like GDB is having issue creating variables:
> 1: (3181) <-1022-var-create - * "_tx_thread_created_ptr"
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (3195) ->1022^error,msg=\"-var-create: unable to create variable object\"\r\n"},"seq":468}
1: (3195) ->1022^error,msg="-var-create: unable to create variable object"

We would need to find out why GDB is not allowing variable creations.

**Comment by gtrevi** [comment]
@xisui-MSFT @WardenGnaw is there anything I can do to help troubleshoot this?

**Comment by xisui-MSFT** [comment]
@gtrevi As Andrew asked in his comment, do you know why this GDB doesn't allow variable creations?

**Comment by gtrevi** [comment]
@xisui-MSFT not actually. The J-Link GDB server just works with emIDE and SEGGER's Embedded Studio.
Is the client assuming APIs that are not implemented? What I'm looking to archive is just a basic debug session w/breakpoints and variable evaluation, which I can do with emIDE and SEGGER's Embedded Studio.

@WardenGnaw jfyi, the "*stopped event via a breakpoint*" you mention is not an actual breakpoint I set, it's just where the debugger randomly stopped.

**Comment by WardenGnaw** [comment]
The launch config has `stopAtEntry` set to `true` so it will stop at the entry point of your program. 

There is also a breakpoint set from the UI and gets sent to the debug adapter:

> <--   C (setBreakpoints-3): {"command":"setBreakpoints","arguments":{"source":{"name":"command_manager_json.c","path":"x:\\work\\projects\\gt_automation\\Hardware\\GT_MB01\\Firmware\\gta_server\\src\\command_manager_json.c"},"lines":[132],"breakpoints":[{"line":132}],"sourceModified":false},"type":"request","seq":3}
--> E (output): {"type":"event","event":"output","body":{"category":"console","output":"1: (2475) <-1013-break-insert -f command_manager_json.c:132\r\n"},"seq":275}

**Comment by gtrevi** [comment]
@WardenGnaw That is correct, although, the UI is not stopping either on entry (i.e. the first line in main()), nor at my set breakpoint

**Comment by gtrevi** [comment]
@xisui-MSFT @WardenGnaw, just following up, any suggestions for why VSC's gdb client does hook up, but does not `stopAtConnect`, or even at a given breakpoint I set at the beginning of main?

One thing I noticed from my device logs (through a com port), is that it is not being reset, and that may explain why the gdb client stops at a random line of code (i.e. the likeliest of which is in my task scheduler).

I reattached a new Debug Console capture, with just one breakpoint set at the first line of code in main().

Thanks

[Debug Console.log](https://github.com/microsoft/vscode-cpptools/files/9977500/Debug.Console.log)

**Comment by xisui-MSFT** [comment]
I'm still seeing error message "-var-create: unable to create variable object" in this log. But based on my experience, if your target doesn't forbid -var-create, switching to some other versions of gdb client / server probably can solve this issue.

Just guessing, Andrew probably knows more about this.

**Comment by benmcmorran** [comment]
> Is there another way to force the device reset, after the gdb client connects?

Does it work if you issue GDB command to reset in `postRemoteConnectCommands`? [Something like this](https://github.com/azure-rtos/getting-started/blob/ce7c9e04d37ad7c480eb73eb9899797a9654612c/STMicroelectronics/B-L4S5I-IOT01A/.vs/launch.vs.json#L29-L32). Note that that example is targeting OpenOCD, but it looks like there's [similar support for `reset` from J-Link](https://wiki.segger.com/J-Link_GDB_Server#Supported_remote_.28monitor.29_commands).

**Comment by gtrevi** [comment]
Thanks @benmcmorran!! Looks like `postRemoteConnectCommands` was the last missing puzzle piece: I got to reset the target, load the elf file and then halt.

The only nit is that it now halts on the reset handler, rather than on my first breakpoint in main, but at least it's 100% reliable and just hitting F5 will get to that breakpoint!
I tried a number of ways to automate the "hit F5"... but haven't found anything that would work.
If anyone have any hint that'd be great!
Thanks!

Just sharing for all what worked for me:

```json
"postRemoteConnectCommands": [
                {
                    "text": "monitor flash breakpoints = 1",
                    "ignoreFailures": false
                },
                {
                    "text": "monitor flash download = 1",
                    "ignoreFailures": false
                },
                {
                    "text": "monitor reset",
                    "ignoreFailures": false
                },
                {
                    "text": "load",
                    "ignoreFailures": false
                },
                {
                    "text": "monitor reset",
                    "ignoreFailures": false
                },
                {
                    "text": "monitor halt",
                    "ignoreFailures": false
                }
            ],
```

**Comment by gtrevi** [comment]
I think this issue can be closed, thanks again to all for your prompt support!
@benmcmorran 
@WardenGnaw 
@xisui-MSFT
