### ISSUE TITLE
override not highlighted when followed by =0;

### ISSUE THREAD

**Issue by stanczyk4** [microsoft/vscode-cpptools#9957]
### Environment

- OS and Version:
Windows
- VS Code Version:
1.71.2
- C/C++ Extension Version:
v1.12.4
- Other extensions you installed (and if the issue persists after disabling them):  
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

override keyword isnt colored when followed by a =0;
Example usecase:
https://godbolt.org/z/eMqoae9G7
![image](https://user-images.githubusercontent.com/5186634/194085868-a9db3cfe-5c45-4658-ba43-5d2da3b2cdc5.png)

### Bug Summary and Steps to Reproduce

Bug Summary:

Steps to reproduce:
1. Go to https://godbolt.org/z/eMqoae9G7
2. Copy code into vscode .h/cpp
3. See error

### Expected behavior

override will be colored when used

### Code sample and Logs

```shell
#include <cstddef>
#include <cstdint>
#include <functional>

class A {
    virtual void dothing() = 0;
};

class B : virtual public A {
   public:
    void dothing() override = 0;
};

class BImpl : public B {
    void dothing() override {}
};

int main() { BImpl b; }
```

### Screenshots

![image](https://user-images.githubusercontent.com/5186634/194086171-73f19944-c235-4260-b690-b5f3129216bf.png)

**Comment by sean-mcmanus** [comment]
It's not a bug with our extension. It's a bug with VS itself, which gets its syntax colorization from the Better C++ extension, see the existing issue at https://github.com/jeff-hykin/better-cpp-syntax/issues/587 .
