### ISSUE TITLE
Clicking on the `View Problem` in a hover scrolls the code editor view

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cpptools#9969]
### Environment

ubuntu 22.04
cpptools 1.13.2
vscode 1.72

### Bug Summary and Steps to Reproduce

Bug Summary:

When I click on `View Problem` as seen on the screenshot the text is scrolled. It's not a big deal but it is still somewhat annoying.

Steps to reproduce:
1. Point to a `~` to view a hover
2. Click on `View Problem`

### Expected behavior

The view shouldn't scroll if there is no reason.

### Code sample and Logs

```shell
-
```

### Screenshots

Before 

![image](https://user-images.githubusercontent.com/3337419/194603348-c19357a2-4d2e-4d6f-b1b6-c947e5176e8b.png)

After

![image](https://user-images.githubusercontent.com/3337419/194603657-de826331-a919-4874-8d58-02318a1c3aeb.png)

**Comment by sean-mcmanus** [comment]
This is a VS Code issue. Our extension doesn't control this behavior. You should report it at https://github.com/microsoft/vscode/issues
