### ISSUE TITLE
#include errors not showing

### ISSUE THREAD

**Issue by aahaselgrove** [microsoft/vscode-cpptools#997]
OS: Windows 10 Pro Version 1703
VS Code version 1.15.1
C/C++ extension version 0.12.3

After selecting a configuration, the warnings on my #include statements disappear, and do not show again until after a file save or swap.

**Comment by sean-mcmanus** [comment]
I can repro this. Looks like we don't queue an IntelliSense squiggle request for open files after a configuration switch.

**Comment by bobbrow** [comment]
This was fixed in 0.13.0
