### ISSUE TITLE
IntelliSense pop-up taking over 1s to show up

### ISSUE THREAD

**Issue by KaeLL** [microsoft/vscode-cpptools#9970]
### Environment

- OS and version: Clear Linux 37410
- VS Code: 1.72.0
- C/C++ extension: 1.13.2

### Bug Summary and Steps to Reproduce

IntelliSense suggestions pop-up started taking a little over 1 second to show up in a small ESP-IDF project. For a standalone hello-world, it's faster, but delay is easily noticeable.
The extension profile and perf runs below are me typing 3 letters to trigger the popup, the last one included me deleting and retyping a couple of characters.

### Additional Information

[Extension host profile](https://github.com/microsoft/vscode-cpptools/files/9735497/CPU-20221007T160538.524Z.cpuprofile.txt)

![Screenshot from 2022-10-07 13-30-48](https://user-images.githubusercontent.com/4423144/194604430-065f66d1-1a68-456e-92ab-cc382006e346.png)
![Screenshot from 2022-10-07 13-36-05](https://user-images.githubusercontent.com/4423144/194604554-16495a34-6ea7-4992-a132-12b273448354.png)
![Screenshot from 2022-10-07 13-39-59](https://user-images.githubusercontent.com/4423144/194604584-b916a6a9-9593-4b8c-8904-eafa75b07a7e.png)

**Comment by Zingam** [comment]
This sound similar to some of mine complaints here: https://github.com/microsoft/vscode-cpptools/issues/9937

**Comment by sean-mcmanus** [comment]
Is this mostly for autocomplete popup or hover? Is it autocomplete of a global variable or a scoped/member variable?

**Comment by KaeLL** [comment]
popup; global (external), I tested writing the name of a function.

**Comment by KaeLL** [comment]
Somehow, it's working as it should now. I have no idea why or what caused this. Only major changes from one week ago are vscode's update to 1.72.1 and kernel update to 6.0, so it may not be related to the extension, and I'll close the issue for now.
