### ISSUE TITLE
macOS: cmd+click on Core Foundation types doesn't work

### ISSUE THREAD

**Issue by H-G-Hristov** [microsoft/vscode-cpptools#9974]
### Environment

- OS and Version: macOS
- VS Code Version: 1.72.9
- C/C++ Extension Version: 1.13.2
- Other extensions you installed (and if the issue persists after disabling them):  
- If using SSH remote, specify OS of remote machine:  
- A clear and concise description of what the bug is, including information about the workspace (i.e. is the workspace a single project or multiple projects, size of the project, etc).

### Bug Summary and Steps to Reproduce

Bug Summary:

I'm reporting to track:

https://github.com/microsoft/vscode-cpptools/issues/9688#issuecomment-1271518495

>> With 1.13.2 I still happened that I was unable to cmd+click to a definition of a Core Foundation type (Apple SDK header).
>There was no stuck flame.
>>
>> After I restarted VSCode the issue fixed itself.
>>
>> Is cmd+click issue related to the wordexp issue?
>
>  @H-G-Hristov That sounds like a different issue. If wordexp is stuck then all IntelliSense operations would be stuck and wordexp would be on a call stack. If only Go to Definition doesn't work that could be caused by something else. Are you able to provide more repro info or logging or a call stack? It sounds like it's random?

I have been experiencing this previously and I have expected that it will be fixed by: 
https://github.com/microsoft/vscode-cpptools/issues/9894
yet I have experienced it once with the latest extension preview. So I'll be observing and will try to give more details.

Steps to reproduce:
1. Open file
2. Attempt cmd+click on a Core Foundation type to inspect the declaration in the source file (maybe any other type)
3. Nothing happens (the text is not clickable)

### Expected behavior

VSCode will open the system header and display the declaration.

### Code sample and Logs

```shell
- none
```

**Comment by michelleangela** [comment]
@H-G-Hristov 
Could you provide additional info and logs to help with determining the cause of the issue?

- Logs from running` C/C++: Log Diagnostics` from the VS Code command palette
- Logs from [the language server logging](https://code.visualstudio.com/docs/cpp/enable-logging-cpp#_enable-logging-for-the-language-server)


If the language server is crashing, here is how to provide call stack logs.

Providing call stacks:
For bugs like crashes, deadlocks, infinite loops, etc. that we are not able to repro and for which the call stack may be useful, please attach a debugger and/or create a dmp and provide the call stacks. Windows binaries have symbols available in VS Code by setting your "symbolSearchPath" to "https://msdl.microsoft.com/download/symbols".

Instructions for attaching debugger to language service process:
https://github.com/microsoft/vscode-cpptools/wiki/Attaching-debugger-to-cpptools-or-cpptools%E2%80%90srv.
