### ISSUE TITLE
IntelliSense: `expression must have a constant value returned` for a constexpr expression 

### ISSUE THREAD

**Issue by Zingam** [microsoft/vscode-cpptools#9977]
Type: <b>Feature Request</b>

In C++23 mode the code snipped compiles GCC 12.2 but cpptools displays an error:

```c++
  constexpr auto intOpt = std::optional<int>{ 7 };
  constexpr auto value = intOpt.transform([](auto value) { return value * 2; }).value();
```

Extension version: 1.13.2
VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:47.539Z)
OS version: Linux x64 5.15.0-48-generic snap
Modes:
Sandboxed: No

![image](https://user-images.githubusercontent.com/3337419/194743524-da2dfe53-68f1-45ab-b033-4e34a8786317.png)

**Comment by michelleangela** [comment]
IntelliSense mode bug. Works for msvc and clang IntelliSense modes.

**Comment by michelleangela** [comment]
This issue also reproduces on VS which the VS Code C++ extension shares the IntelliSense engine with. Created an internal feedback ticket on VS for this issue.

**Comment by Colengms** [comment]
It looks like this has since been addressed.  (I believe this predated full C++23 support).
