### ISSUE TITLE
C++11/C++14 Error Squiggles!

### ISSUE THREAD

**Issue by 7kemZmani** [microsoft/vscode-cpptools#998]
I'm using the latest version of VSCode, and the C/C++ extension on Debian 9.
How can I disable "Error Squiggles" from correct C++11/C++14 code? 
For example the code in the picture works fine, yet the extension still shows an error!

<a href="https://ibb.co/jENMRk"><img src="https://preview.ibb.co/kkECXQ/screenshot.png" alt="screenshot" border="0"></a><br />

**Comment by bobbrow** [comment]
Can you share your `"includePath"` from c_cpp_properties.json and also the output of `gcc -v -E -x c++ - < /dev/null`?  If they don't match, that is likely the source of the problem.  The extension may have pulled in the wrong default include paths for you.

**Comment by 7kemZmani** [comment]
`includePath` in `c_cpp_properties.json` looks like this:
```
            "includePath": [
                "/usr/include/c++/6",
                "/usr/include/x86_64-linux-gnu/c++/6",
                "/usr/include/newlib/c++/5.4.1",
                "/usr/local/include",
                "/usr/lib/clang/4.0.1/include",
                "/usr/include",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include/newlib",
                "${workspaceRoot}"
            ],
```

and `gcc -xc++ -E -v - < /dev/null` returned: 
```
...
#include "..." search starts here:
#include <...> search starts here:
 /home/linuxbrew/.linuxbrew/include
 /home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0
 /home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/x86_64-unknown-linux-gnu
 /home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/../../../../include/c++/5.3.0/backward
 /home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include
 /usr/local/include
 /home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/include
 /home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include-fixed
 /usr/include/x86_64-linux-gnu
 /usr/include
End of search list.

...
```

**Comment by 7kemZmani** [comment]
okay, so now I fixed the ~/.vscode/c_cpp_properties.json to make `intialPath` use the same paths gcc uses, and in the same order.

```
{
    "configurations": [
        {
            "name": "Linux",
            "includePath": [
                "/home/linuxbrew/.linuxbrew/include",
                "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/include/c++/5.3.0",
                "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/include/c++/5.3.0/x86_64-unknown-linux-gnu",
                "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/include/c++/5.3.0/backward",
                "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include",
                "/usr/local/include",
                "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/include",
                "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include-fixed",
                "/usr/include/x86_64-linux-gnu",
                "/usr/include",
                "${workspaceRoot}"
            ],
            "defines": [],
            "intelliSenseMode": "clang-x64",
            "browse": {
                "path": [
                    "/home/linuxbrew/.linuxbrew/include",
                    "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/include/c++/5.3.0",
                    "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/include/c++/5.3.0/x86_64-unknown-linux-gnu",
                    "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/include/c++/5.3.0/backward",
                    "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include",
                    "/usr/local/include",
                    "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/include",
                    "/home/linuxbrew/.linuxbrew/Cellar/gcc/5.3.0/lib/gcc/x86_64-unknown-linux-gnu/5.3.0/include-fixed",
                    "/usr/include/x86_64-linux-gnu",
                    "/usr/include",
                    "${workspaceRoot}"
                ],
                "limitSymbolsToIncludedHeaders": true,
                "databaseFilename": ""
            }
        }
    ],
    "version": 2
}
```
restarted vscode, and the same red squiggle line is there :(
it correctly detects C++98 error; but this is a valid C++11, C++14 (and C++17!) code.

**Comment by bobbrow** [comment]
We might need to dig into your header file for this.  The extension compiles your code with c++14 (and partial c++17) support, but if the version of vector you are compiling against doesn't have the support for initializer_list enabled (i.e. it is excluded because of a missing preprocessor define), it will show up as a squiggle.

I haven't used linuxbrew before so if you could share some instructions, I can try to get a setup similar to yours.

**Comment by 7kemZmani** [comment]
Linuxbrew is a simple package manger (a fork of the popular macOS Homebrew project that runs on linux). To install it, you'll need first the dependencies:
`sudo apt-get install build-essential curl file git python-setuptools ruby`
and then install linuxbrew with:
`ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)"`
you should see it now installed in `/home/linuxbrew/.linuxbrew`
update your PATH variable
PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
and you'll be all set. 
Now run:
`brew install gcc`
and it will take care of installing the latest version of gcc along with the necessity dependencies.

**Comment by 7kemZmani** [comment]
This is actually no longer an issue in `vscode: 1.21.0` with `ms-vscode.cpptools: 0.15.0`
thank you guys for the awesome extension.

**Comment by ShuminY** [comment]
I have this issue now with vs code 1.25.0 and the cpptools 0.17.6. 
gcc compiling didn't report this error. could it be something with the intelliSene?

![image](https://user-images.githubusercontent.com/20390609/42680951-0043fc7c-86b9-11e8-8d47-802df6306e8f.png)
