### ISSUE TITLE
Questions about licenses and transitive closure of dependencies

### ISSUE THREAD

**Issue by dariomx** [microsoft/vscode-cpptools#9980]
### Feature Request

Hello there,

I have some questions regarding dependencies and licenses.

1. Could you clarify if this file contains the transitive closure of dependencies for this extension? https://github.com/microsoft/vscode-cpptools/blob/main/Extension/ThirdPartyNotices.txt

Meaning that it lists not only dependencies used directly by the extension, but dependencies used by dependencies and so on. 

2. Could you clarify what components are associated to the runtime licenses listed at https://github.com/microsoft/vscode-cpptools/tree/main/RuntimeLicenses? Can these components opted-out or are mandatory?

Thanks in advance, great extension by the way.

**Comment by sean-mcmanus** [comment]
Yes, it includes the dependencies used by dependencies. It's generated by an internal Microsoft tool by processing the dependencies in our package.json (with one edit to cut off garbage and one edit to add other dependency licenses at the bottom).

The runtime licenses apply to the cpptools, cpptools-srv, and vsdbg binaries. The cpptools binaries are required to run the language service. Setting C_Cpp.intelliSenseMode to "disabled" would avoid running those, so in that sense they're optional. The vsdbg binary is only for debugging on Windows with cl.exe.

**Comment by dariomx** [comment]
Thanks a lot, Sean; for your quick response.

Could you clarify what features cpptools-srv offer and whether it can be opted-out?

Kind regards.

**Comment by sean-mcmanus** [comment]
The cpptools process launches the cpptools-srv process, so usually you'd want both, but you can set C_Cpp.intelliSenseEngine to "tag parser" to avoid launching cpptools-srv.

**Comment by dariomx** [comment]
Thank you, Sean. 

Just to double check I understood: if I disable intellisense, and if I do not use cl.exe for debugging, then I will not use any component whose license is listed in https://github.com/microsoft/vscode-cpptools/tree/main/RuntimeLicenses, right?

**Comment by sean-mcmanus** [comment]
@dariomx Yes, you can verify this via deleting the `bin/cpptools` and `bin/cpptools-srv` processes from the extensions folder and `debugAdapters/vsdbg/bin/vsdbg.exe` (if it exists). Those processes won't get launched.

**Comment by dariomx** [comment]
Got it, thank you Sean.
