### ISSUE TITLE
Out-of-the-box file nesting

### ISSUE THREAD

**Issue by xiaoxi-david** [microsoft/vscode-cpptools#9982]
### Feature Request

Could the extension provide file nesting for cases like this?

![nesting-file](https://user-images.githubusercontent.com/24303680/195083582-671dd91c-afff-4bd3-b019-8a0887b0a6f6.png)

I know I can set it up, but I'm hoping this extension can provide it out of the box.

**Comment by michelleangela** [comment]
@xiaoxi-david 
The file nesting feature is managed by the VS Code client and not by the extension. A quick way to verify this is by disabling the extension and see that the settings `explorer.fileNesting.* still exist.

If you'd like for VS Code to improve this feature, create an issue at their repository at [explorer.fileNesting.enabled](https://github.com/microsoft/vscode/issues)
