### ISSUE TITLE
[Highlighting] Distinguish between system include path and user include path (like Xcode)

### ISSUE THREAD

**Issue by zhouzq-thu** [microsoft/vscode-cpptools#9991]
### Feature Request

**Xcode** allows user to define **System Header Search Paths** and **User Header Search Paths** as following:

![Screen Shot 2022-10-13 at 09 20 54](https://user-images.githubusercontent.com/9458157/195477068-c5b88818-2a79-4c11-ad08-f215750bada3.png)

After configuration:
- the functions and variables in system header paths are purple colored.
- the functions and variables in user header paths are green colored.
- the macros are brown colored.

e.g

![Screen Shot 2022-10-13 at 09 20 29](https://user-images.githubusercontent.com/9458157/195477354-fe7c2450-28d1-456b-bd9e-d806f5e55a47.png)

**Comment by sean-mcmanus** [comment]
We already support special/theme colors for macros, see https://code.visualstudio.com/docs/cpp/colorization-cpp#_intellisense-tokens-and-scopes .

@Colengms The system vs. user distinction seems like it might first require VS Code support and/or the themes would have to support it, which they don't currently?
