### ISSUE TITLE
Add support for configuring include path when open a single file

### ISSUE THREAD

**Issue by leo-frank** [microsoft/vscode-cpptools#9992]
### Feature Request

* Say ahead: Issue #9951 showed same demand as me, but the issue has been closed by author.

* Feature request: Eigen is a famous library written in C++ and it installs it's include_files into "/usr/local/include/eigen3/Eigen". There are several files under the dir "/usr/local/include/eigen3/Eigen", Core, Sparse and so on. Programmers can include Eigen files by add "#include<Eigen/Core>" in their project directory after configuring include path in c_cpp_properties.json provided by IntelliSense.  However, when open a single file (not a directory) which has one line "#include<Eigen/Core>", this line squiggles unexpectedly. Since it's a single file opened by VScode, so I can't configure c_cpp_properties.json to let IntelliSense sense the include_dir "/usr/local/include/eigen3/Eigen". The way I solved this problem is by:
`sudo ln -s /usr/local/include/eigen3/Eigen /usr/local/include/Eigen`
It makes sense, but i have to say it's not elegant as expected.  New feature should help add include path when coding a single file. 

Thanks for your reading.

**Comment by leo-frank** [comment]
#6091 should be what I mean. 
But, actually, error squiggles appears when I open a single file, picture below. This is awkward with issue #6091.

Again, thanks for your reply.

![image](https://user-images.githubusercontent.com/47302141/195752187-a0e32833-bf4c-4a79-9935-5b0c92665c6b.png)

**Comment by leo-frank** [comment]
More precisely, I am now not clear with this problem:
* "Since cpptools doesn't provide squiggles for Open File scenario , how include errors(as shown red in screenshot) was detected?" 

Thanks for your work and reply.

**Comment by sean-mcmanus** [comment]
I believe that's how we designed it. We just show the include file errors and not the other errors.

**Comment by Colengms** [comment]
@leo-frank  Would https://github.com/microsoft/vscode-cpptools/issues/3171 address this?

**Comment by leo-frank** [comment]
yes, thanks to your help!
