### ISSUE TITLE
provide some default `explorer.fileNesting.patterns` for c++

### ISSUE THREAD

**Issue by cjwijtmans** [microsoft/vscode-cpptools#9998]
### Feature Request

Provide default `explorer.fileNesting.patterns` configs for C++.

```json
    "explorer.fileNesting.patterns": {
        "*.c": "${capture}.h, inc/${capture}.h, ${capture}.*.c, ${capture}.*.h, inc/${capture}.*.h",
        "*.cpp": "${capture}.hpp, inc/${capture}.hpp, ${capture}.*.cpp, ${capture}.*.hpp, inc/${capture}.*.hpp",
        "*.h": "${capture}.*.h",
        "*.ixx": "${capture}.cpp, ${capture}.*.ixx, ${capture}.*.cpp"
    },
```

I would also like to have a feature that i can specify directories as in.

```json
    "explorer.fileNesting.patterns": {
        "*.cpp": "inc/${capture}.hpp, ../inc/${capture}.hpp",
    },
```

But this does not seem to be supported in vscode(yet). https://github.com/microsoft/vscode/pull/149970 (ondeck)

**Comment by sean-mcmanus** [comment]
Can you provide a screenshot/example of how this is supposed to work?

Did you want us to add that setting to our package.json defaults, i.e. https://github.com/microsoft/vscode-cpptools/blob/main/Extension/package.json#L5260 .

**Comment by sean-mcmanus** [comment]
@AlexandraKemperMS I assigned this to in case you wanted to look into if this would be a good thing to add or not. The implementation would just involve setting that default setting in our package.json, i.e. https://github.com/microsoft/vscode-cpptools/blob/main/Extension/package.json#L5452 .
